Repository pylint-dev/pylint, pull requests merged in 2021-02, with the labels that each got.

#4073 Add pytest-benchmark info in the readme
  README.rst
Labels: documentation

#4059 Add support for pep585 with postponed evaluation
  CONTRIBUTORS.txt
  ChangeLog
  pylint/checkers/typecheck.py
  pylint/checkers/utils.py
  tests/functional/p/postponed_evaluation_pep585.py
  tests/functional/p/postponed_evaluation_pep585.rc
  tests/functional/p/postponed_evaluation_pep585.txt
  tests/functional/p/postponed_evaluation_pep585_error.py
  tests/functional/p/postponed_evaluation_pep585_error.rc
  tests/functional/p/postponed_evaluation_pep585_error.txt
  tests/functional/p/postponed_evaluation_pep585_py39.py
  tests/functional/p/postponed_evaluation_pep585_py39.rc
Labels: enhancement, python 3.9

#4075 Add check for alternative union syntax - PEP 604
  ChangeLog
  pylint/checkers/typecheck.py
  pylint/checkers/utils.py
  tests/functional/a/alternative_union_syntax.py
  tests/functional/a/alternative_union_syntax.rc
  tests/functional/a/alternative_union_syntax_error.py
  tests/functional/a/alternative_union_syntax_error.rc
  tests/functional/a/alternative_union_syntax_error.txt
  tests/functional/a/alternative_union_syntax_py37.py
  tests/functional/a/alternative_union_syntax_py37.rc
  tests/functional/a/alternative_union_syntax_py37.txt
Labels: enhancement, python 3.10, python 3.9

#4064 Fix multiple false positives with assignment expressions
  ChangeLog
  pylint/checkers/variables.py
  tests/functional/a/assignment_expression.py
  tests/functional/a/assignment_expression.rc
  tests/functional/a/assignment_expression.txt
Labels: bug, false-positive, python 3.8

#4072 Fix TypedDict inherit-non-class false-positive Python 3.9+
  ChangeLog
  pylint/checkers/classes.py
  tests/functional/t/typedDict.py
  tests/functional/t/typedDict.rc
Labels: bug, python 3.9

#4076 Add a warning in the .gitignore
  .gitignore
Labels: documentation

#4077 Update hooks in pre commit
  .pre-commit-config.yaml
Labels: task

#4092 Graingert add generated members match against the qualified name
  CONTRIBUTORS.txt
  ChangeLog
  pylint/checkers/typecheck.py
  tests/functional/g/generated_members.py
  tests/functional/g/generated_members.rc
  tests/functional/g/generated_members.txt
Labels: bug, false negative

#4095 Fix the changelog and whatsnew retroactively
  ChangeLog
  doc/whatsnew/2.6.rst
  doc/whatsnew/2.7.rst
  doc/whatsnew/index.rst
Labels: documentation, task

#3966 Add nan-comparison checker for NaN values
  ChangeLog
  doc/whatsnew/2.7.rst
  pylint/checkers/base.py
  tests/checkers/unittest_base.py
  tests/functional/n/nan_comparison_check.py
  tests/functional/n/nan_comparison_check.txt
Labels: checkers, enhancement

#4105 Fix false positive when zip() receives iterable
  ChangeLog
  doc/whatsnew/2.7.rst
  pylint/checkers/python3.py
  tests/checkers/unittest_python3.py
Labels: false-positive

#4104 Fix false positive when map() receives iterable
  CONTRIBUTORS.txt
  ChangeLog
  doc/whatsnew/2.7.rst
  pylint/checkers/python3.py
  tests/checkers/unittest_python3.py
Labels: false-positive

#3309 Add new `consider-using-generator` checker Issue #3165
  CONTRIBUTORS.txt
  ChangeLog
  doc/whatsnew/2.7.rst
  pylint/checkers/refactoring/refactoring_checker.py
  tests/functional/c/consider_using_generator.py
  tests/functional/c/consider_using_generator.txt
  tests/functional/u/use_a_generator.py
  tests/functional/u/use_a_generator.txt
Labels: checkers, enhancement

#4113 Add 2.8.0 in the Changelog and WhatsNew
  ChangeLog
  doc/release.md
  doc/whatsnew/2.8.rst
  doc/whatsnew/index.rst
  pylint/__pkginfo__.py
Labels: documentation, task

#4153 Properly strip dangerous sys.path entries (not just the first one)
  CONTRIBUTORS.txt
  ChangeLog
  pylint/__main__.py
  tests/test_self.py
Labels: bug

#4160 Upgrade the changelog following release of 2.7.2
  ChangeLog
  pylint/__pkginfo__.py
Labels: task
