Repository pylint-dev/pylint, pull requests merged in 2021-06, with the labels that each got.

#4537 Add new checker `invalid-all-format`
  ChangeLog
  doc/whatsnew/2.9.rst
  pylint/checkers/variables.py
  tests/functional/i/invalid/invalid_all_format.py
  tests/functional/i/invalid/invalid_all_format.txt
  tests/functional/i/invalid/invalid_all_format_valid_1.py
  tests/functional/i/invalid/invalid_all_format_valid_2.py
Labels: checkers, enhancement

#4547 Bump pyupgrade to v2.19.1
  .pre-commit-config.yaml
Labels: dependency

#4548 Improve traceback for pytest runs
  pylint/testutils/lint_module_test.py
  tests/test_functional.py
Labels: task

#4550 Add regression test for Pattern Matching 3.10
  ChangeLog
  tests/functional/p/pattern_matching.py
  tests/functional/p/pattern_matching.rc
Labels: false-positive, python 3.10

#4514 Implemented new checker ``await-outside-async``
  ChangeLog
  doc/whatsnew/2.9.rst
  pylint/checkers/typecheck.py
  tests/functional/a/await_outside_async.py
  tests/functional/a/await_outside_async.rc
  tests/functional/a/await_outside_async.txt
Labels: checkers, enhancement

#4559 Add additional documenation for typing extension
  pylint/extensions/typing.rst
Labels: documentation

#4566 Add exclude_lines coverage
  .coveragerc
Labels: task

#4569 Fix error with slice as subscript for dict
  ChangeLog
  pylint/checkers/typecheck.py
  tests/functional/u/unhashable_dict_key.py
  tests/functional/u/unhashable_dict_key.txt
Labels: crash

#4573 Add test case from issue #119 for easier resolution
  pylint/checkers/base.py
  tests/functional/i/invalid/invalid_name.py
  tests/functional/i/invalid/invalid_name.txt
Labels: task

#4579 Remove appveyor.yml replaced by github actions
  ChangeLog
  MANIFEST.in
  appveyor.yml
Labels: task

#4581 Upgrade astroid to 2.6.0-dev0
  requirements_test_min.txt
  setup.cfg
Labels: task

#4567 Remove deprecated `astroid.Ellipsis` node
  pylint/checkers/base.py
  pylint/checkers/format.py
Labels: requires astroid update

#4568 Remove deprecated `astroid.Index` and `astroid.ExtSlice` nodes
  pylint/checkers/refactoring/recommendation_checker.py
  pylint/checkers/refactoring/refactoring_checker.py
  pylint/checkers/typecheck.py
  pylint/checkers/utils.py
Labels: requires astroid update

#4558 Add regression tests for Enum.name and .value inference
  ChangeLog
  tests/functional/e/enum_subclasses.py
Labels: bug, requires astroid update

#4570 Add regression test from #2306
  tests/functional/r/regression/regression_2306_enum_value.py
Labels: regression, requires astroid update

#4589 Add a test for ``max-statement`` option of ``too-many-statements`` check
  tests/functional/t/too/too_many_statements.py
  tests/functional/t/too/too_many_statements.rc
  tests/functional/t/too/too_many_statements.txt
Labels: documentation, enhancement, minor

#4594 Better recognize property decorators
  ChangeLog
  pylint/checkers/utils.py
  tests/functional/c/cached_property.py
  tests/functional/c/cached_property.rc
  tests/functional/c/cached_property.txt
Labels: false-positive

#4543 Remove docs and code associated with the removed W0623 (redefine-in-handler) checker
  CONTRIBUTORS.txt
  pylint/checkers/base.py
  pylint/checkers/utils.py
  pylint/checkers/variables.py
  tests/functional/r/redefined_argument_from_local.py
Labels: documentation, maintenance, task

#4602 Upgrade astroid to 2.6.0
  ChangeLog
  requirements_test_min.txt
  setup.cfg
Labels: task

#4605 Add code analysis provided by GitHub
  .github/workflows/codeql-analysis.yml
Labels: task

#4613 Fix a crash when a test function is decorated with ``@pytest.fixture``
  ChangeLog
  pylint/checkers/utils.py
  tests/functional/r/regression/regression_4612_crash_pytest_fixture.py
Labels: blocker, crash

#4539 Rebase of issue/2913-unicode-defs
  tests/functional/r/regression/regression_2913.py
  tests/functional/r/regression/regression_2913.txt
Labels: task

#4551 Add type annotations to pyreverse
  ChangeLog
  doc/whatsnew/2.9.rst
  pylint/pyreverse/diagrams.py
  pylint/pyreverse/inspector.py
  pylint/pyreverse/utils.py
  pylint/pyreverse/writer.py
  tests/unittest_pyreverse_writer.py
Labels: enhancement, topic-pyreverse

#4604 VariableChecker now accounts for attribute lookups in type comments
  CONTRIBUTORS.txt
  ChangeLog
  pylint/checkers/variables.py
  pylint/constants.py
  tests/checkers/unittest_variables.py
Labels: enhancement, false-positive

#4626 Move back to a dev version and upgrade documentation
  doc/whatsnew/2.10.rst
  doc/whatsnew/2.9.rst
  pylint/__pkginfo__.py
  tbump.toml
Labels: maintenance, task

#4628 Fix deprecated methods from #4620
  pylint/checkers/stdlib.py
Labels: enhancement, minor

#4632 Fix a crash with ``StopIteration`` when using ``limit-inference-results=0``
  tests/functional/r/regression/regression_issue_4631.py
  tests/functional/r/regression/regression_issue_4631.rc
  tests/functional/r/regression/regression_issue_4631.txt
Labels: blocker, crash, requires astroid update

#4636 Bump pylint to 2.9.1, update changelog
  ChangeLog
  pylint/__pkginfo__.py
  pylint/extensions/confusing_elif.py
  tbump.toml
Labels: maintenance, task

#4637 Move back to a dev version following 2.9.1 release
  pylint/__pkginfo__.py
  tbump.toml
Labels: maintenance, task

#4641 Add ``rstcheck`` to pre-commit configuration
  .pre-commit-config.yaml
  ChangeLog
  doc/how_tos/transform_plugins.rst
  doc/tutorial.rst
  doc/whatsnew/2.9.rst
Labels: documentation, maintenance
