Repository pylint-dev/pylint, pull requests merged in 2021-07, with the labels that each got.

#4645 Fix false positive ``unused-private-member`` if class member is accessed via ``self``
  ChangeLog
  pylint/checkers/classes.py
  tests/functional/u/unused/unused_private_member.py
Labels: false-positive

#4663 Fix false positive `unused-private-member` if class member is assigned/mutated with `cls`
  ChangeLog
  pylint/checkers/classes.py
  tests/functional/u/unused/unused_private_member.py
  tests/functional/u/unused/unused_private_member.txt
Labels: false-positive

#4665 Fix false-positive ``consider-using-with`` when using ``contextlib.ExitStack``
  ChangeLog
  doc/whatsnew/2.9.rst
  pylint/checkers/refactoring/refactoring_checker.py
  tests/functional/c/consider/consider_using_with.py
Labels: false-positive

#4669 [duplicate-code] Fix ignored empty functions by similarities checker with ignore-signatures option enabled
  CONTRIBUTORS.txt
  ChangeLog
  pylint/checkers/similar.py
  tests/checkers/unittest_similar.py
  tests/input/similar_empty_func_1.py
  tests/input/similar_empty_func_2.py
Labels: bug, false-positive

#4675 [test utils] No output with an expected output now fail properly
  pylint/testutils/lint_module_test.py
  pylint/testutils/reporter_for_tests.py
  tests/functional/r/regression/regression_issue_4631.txt
Labels: bug, maintenance, task

#4678 Use absolute import qualified module name for deprecated module check
  ChangeLog
  pylint/checkers/deprecated.py
  pylint/checkers/imports.py
  pylint/checkers/utils.py
  tests/checkers/unittest_deprecated.py
  tests/functional/d/deprecated/deprecated_relative_import/__init__.py
  tests/functional/d/deprecated/deprecated_relative_import/dot_relative_import.py
  tests/functional/d/deprecated/deprecated_relative_import/dot_relative_import.rc
  tests/functional/d/deprecated/deprecated_relative_import/dot_relative_import.txt
  tests/functional/d/deprecated/deprecated_relative_import/subpackage/__init__.py
  tests/functional/d/deprecated/deprecated_relative_import/subpackage/dot_dot_relative_import.py
  tests/functional/d/deprecated/deprecated_relative_import/subpackage/dot_dot_relative_import.rc
  tests/functional/d/deprecated/deprecated_relative_import/subpackage/dot_dot_relative_import.txt
Labels: bug, false-positive

#4679 Fix false-positive ``consider-using-with`` for ternary conditionals in ``with`` items
  ChangeLog
  doc/whatsnew/2.9.rst
  pylint/checkers/refactoring/refactoring_checker.py
  tests/functional/c/consider/consider_using_with_open.py
Labels: false-positive

#4666 Fix false-positive of `use-maxsplit-arg` when index is incremented inside a loop
  ChangeLog
  pylint/checkers/refactoring/recommendation_checker.py
  tests/functional/u/use/use_maxsplit_arg.py
Labels: false-positive

#4688 Catch MRO error when applying missing hints feature.
  CONTRIBUTORS.txt
  ChangeLog
  pylint/checkers/typecheck.py
  tests/functional/r/regression/regression_4688_duplicated_bases_member_hints.py
  tests/functional/r/regression/regression_4688_duplicated_bases_member_hints.txt
Labels: blocker, crash

#4695 Clarify documentation for consider-using-from-import
  CONTRIBUTORS.txt
  ChangeLog
  pylint/checkers/imports.py
Labels: documentation

#4651 Document the release process
  doc/release.md
Labels: documentation, maintenance

#4710 Fix invalid-overridden-method with nested property
  ChangeLog
  pylint/checkers/utils.py
  tests/functional/i/invalid/invalid_overridden_method.py
  tests/functional/i/invalid/invalid_overridden_method.txt
Labels: false-positive

#4708 [unused-private-member] add logic to check for obj attributes when using ``__new__``
  ChangeLog
  pylint/checkers/classes.py
  tests/functional/u/unused/unused_private_member.py
Labels: false-positive

#4686 Add a functional tests for 4685
  ChangeLog
  tests/functional/p/pattern_matching.py
Labels: crash, python 3.10, requires astroid update

#4703 Fix cyclic import with TYPE_CHECKING
  ChangeLog
  pylint/checkers/imports.py
  tests/input/func_noerror_cycle/__init__.py
  tests/input/func_noerror_cycle/a.py
  tests/input/func_noerror_cycle/b.py
  tests/messages/func_noerror_cycle.txt
  tests/test_func.py
Labels: false-positive, requires astroid update

#4702 Ignore import errors if in guarded import block
  ChangeLog
  pylint/checkers/imports.py
  pylint/checkers/utils.py
  pylint/checkers/variables.py
  tests/functional/i/import_error.py
  tests/functional/i/import_error.txt
  tests/functional/u/ungrouped_imports.py
Labels: false-positive, requires astroid update

#4717 Add regression test TypedDict not-callable
  ChangeLog
  tests/functional/t/typedDict.py
Labels: false-positive, requires astroid update

#4721 Fix 4689 Exclude ``ThreadPoolExecutor`` and ``ProcessPoolExecutor`` from ``consider-using-with``
  ChangeLog
  doc/whatsnew/2.9.rst
  pylint/checkers/refactoring/refactoring_checker.py
  tests/functional/c/consider/consider_using_with.py
  tests/functional/c/consider/consider_using_with.txt
Labels: false-positive

#4728 Bump pylint to 2.9.4, update changelog
  ChangeLog
  pylint/__pkginfo__.py
  pylint/checkers/classes.py
  pylint/checkers/imports.py
  pylint/checkers/mapreduce_checker.py
  pylint/checkers/similar.py
  pylint/checkers/stdlib.py
  pylint/checkers/typecheck.py
  pylint/checkers/utils.py
  pylint/exceptions.py
  pylint/extensions/_check_docs_utils.py
  pylint/extensions/broad_try_clause.py
  pylint/extensions/check_docs.py
  pylint/extensions/confusing_elif.py
  pylint/reporters/ureports/nodes.py
  tbump.toml
  tests/checkers/unittest_similar.py
  tests/extensions/test_confusing_elif.py
  tests/test_self.py
Labels: maintenance, task

#4729 Move back to a dev version following 2.9.4 release
  ChangeLog
  pylint/__pkginfo__.py
  tbump.toml
Labels: maintenance, task

#4733 Fix crash if a callable returning a context manager was assigned to a list or dict item
  ChangeLog
  doc/whatsnew/2.9.rst
  pylint/checkers/refactoring/refactoring_checker.py
  tests/functional/c/consider/consider_using_with.py
  tests/functional/c/consider/consider_using_with.txt
Labels: crash

#4737 [#3791] propose a fix
  CONTRIBUTORS.txt
  pylint/checkers/variables.py
  tests/functional/u/undefined/undefined_variable.py
  tests/functional/u/undefined/undefined_variable.txt
Labels: bug, false-positive

#4742 Add Github issue forms and densify some templates
  .github/ISSUE_TEMPLATE/1_Bug_report.md
  .github/ISSUE_TEMPLATE/2_Feature_request.md
  .github/ISSUE_TEMPLATE/3_Question.md
  .github/ISSUE_TEMPLATE/BUG-REPORT.yml
  .github/ISSUE_TEMPLATE/FEATURE-REQUEST.yml
  .github/ISSUE_TEMPLATE/QUESTION.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/PULL_REQUEST_TEMPLATE.md
  ChangeLog
Labels: documentation, enhancement, maintenance

#4749 Improve Issue forms
  .github/ISSUE_TEMPLATE/BUG-REPORT.yml
  .github/ISSUE_TEMPLATE/FEATURE-REQUEST.yml
  .github/ISSUE_TEMPLATE/QUESTION.yml
Labels: maintenance, task

#4765 2.9.6 release branch
  ChangeLog
  pylint/__pkginfo__.py
  pylint/checkers/variables.py
  tbump.toml
Labels: maintenance, task

#4565 Performance improvment of the Similarity checker
  ChangeLog
  doc/whatsnew/2.10.rst
  pylint/checkers/similar.py
  tests/checkers/unittest_similar.py
  tests/input/similar1
  tests/input/similar2
  tests/messages/func_w0801.txt
Labels: enhancement, topic-duplication, topic-performance

#4767 Remove classes.dot after testing #4762
  tests/test_pylint_runners.py
Labels: maintenance, task

#4758 Add ignored-parents option to design checker
  CONTRIBUTORS.txt
  ChangeLog
  doc/whatsnew/2.10.rst
  pylint/checkers/design_analysis.py
  pylintrc
  tests/checkers/unittest_design.py
  tests/functional/t/too/too_many_ancestors_ignored_parents.py
  tests/functional/t/too/too_many_ancestors_ignored_parents.rc
  tests/functional/t/too/too_many_ancestors_ignored_parents.txt
Labels: checkers, enhancement

#4661 Use `XDG_CACHE_HOME` for `PYLINTHOME`
  CONTRIBUTORS.txt
  ChangeLog
  doc/faq.rst
  pylint/config/__init__.py
  setup.cfg
  tests/lint/unittest_lint.py
Labels: enhancement, task

#4764 Omit no-member error if guarded behind if stmt
  ChangeLog
  doc/whatsnew/2.10.rst
  pylint/checkers/typecheck.py
  tests/functional/n/no/no_member_if_statements.py
  tests/functional/n/no/no_member_if_statements.txt
Labels: false-positive

#4175 Similar check: Passe min_lines to recombined.
  ChangeLog
  pylint/lint/parallel.py
  tests/test_check_parallel.py
Labels: bug, checkers

#4770 Fix style issues Changelog + What's New
  ChangeLog
  doc/release.md
  doc/whatsnew/2.10.rst
  doc/whatsnew/index.rst
Labels: documentation

#4768 Extended `consider-using-tuple` check to cover `in` comparisons
  ChangeLog
  doc/whatsnew/2.10.rst
  pylint/checkers/classes.py
  pylint/checkers/python3.py
  pylint/checkers/refactoring/refactoring_checker.py
  pylint/checkers/stdlib.py
  pylint/checkers/typecheck.py
  pylint/extensions/code_style.py
  pylint/lint/pylinter.py
  script/bump_changelog.py
  tests/functional/ext/code_style/code_style_consider_using_tuple.py
  tests/functional/ext/code_style/code_style_consider_using_tuple.txt
Labels: enhancement

#4769 Add new checkers ``use-list-literal`` and ``use-dict-literal``
  ChangeLog
  doc/whatsnew/2.10.rst
  pylint/checkers/refactoring/refactoring_checker.py
  pylint/checkers/stdlib.py
  pylint/checkers/utils.py
  pylint/utils/pragma_parser.py
  tests/functional/c/consider/consider_using_dict_comprehension.py
  tests/functional/c/consider/consider_using_dict_items.py
  tests/functional/c/consider/consider_using_get.py
  tests/functional/d/dangerous_default_value_py30.py
  tests/functional/g/generic_alias/generic_alias_side_effects.py
  tests/functional/i/invalid/e/invalid_exceptions_caught.py
  tests/functional/i/invalid/g/invalid_getnewargs_ex_returned.py
  tests/functional/i/invalid/invalid_unary_operand_type.py
  tests/functional/n/not_callable.py
  tests/functional/s/statement_without_effect.py
  tests/functional/u/unnecessary/unnecessary_comprehension.py
  tests/functional/u/unnecessary/unnecessary_dict_index_lookup.py
  tests/functional/u/unnecessary/unnecessary_lambda.py
  tests/functional/u/use/use_literal_dict.py
  tests/functional/u/use/use_literal_dict.txt
  tests/functional/u/use/use_literal_list.py
  tests/functional/u/use/use_literal_list.txt
  tests/functional/u/use/using_constant_test.py
Labels: enhancement

#4771 Add ``forgotten-debug-statement`` checker
  ChangeLog
  doc/whatsnew/2.10.rst
  pylint/checkers/stdlib.py
  tests/functional/f/forgotten_debug_statement_py37.py
  tests/functional/f/forgotten_debug_statement_py37.rc
  tests/functional/f/forgotten_debug_statement_py37.txt
Labels: enhancement

#4745 Handle has-a relationships for type-hinted arguments in class diagrams
  ChangeLog
  doc/whatsnew/2.10.rst
  pylint/pyreverse/utils.py
  tests/data/classes_No_Name.dot
  tests/data/clientmodule_test.py
  tests/data/suppliermodule_test.py
  tests/unittest_pyreverse_diadefs.py
  tests/unittest_pyreverse_inspector.py
  tests/unittest_pyreverse_writer.py
Labels: enhancement

#4779 Add documentation for useless-suppression
  doc/user_guide/message-control.rst
Labels: documentation
