Repository pylint-dev/pylint, pull requests merged in 2021-05, with the labels that each got.

#4425 Add support for checking deprecated class arguments.
  pylint/checkers/deprecated.py
  pylint/checkers/stdlib.py
  tests/checkers/unittest_deprecated.py
Labels: enhancement

#4424 Add deprecated methods, classes and arguments to stdlib checker
  pylint/checkers/stdlib.py
Labels: enhancement, false negative

#4398 Add --fail-on option (#4227)
  CONTRIBUTORS.txt
  ChangeLog
  doc/whatsnew/2.9.rst
  pylint/lint/pylinter.py
  pylint/lint/run.py
  tests/test_self.py
Labels: needs review

#4435 warn deprecated x argument of int(), bool(), float() in all python versions
  pylint/checkers/stdlib.py
Labels: enhancement

#4450 Fix broken tests
  tests/test_self.py
Labels: task

#4453 Issue 4430 false positive consider-using-with R1732
  ChangeLog
  pylint/checkers/refactoring/refactoring_checker.py
  tests/functional/c/consider/consider_using_with.py
  tests/functional/c/consider/consider_using_with.txt
  tests/functional/c/consider/consider_using_with_open.py
  tests/functional/c/consider/consider_using_with_open.txt
Labels: enhancement, false-positive

#4442 Fix changelog
  ChangeLog
Labels: documentation

#4454 Moved stdlib module deprecation from imports checker to stdlib checker
  ChangeLog
  pylint/checkers/imports.py
  pylint/checkers/stdlib.py
  pylint/config/man_help_formatter.py
  pylint/config/option.py
  pylint/config/option_manager_mixin.py
  pylint/config/option_parser.py
  pylint/config/options_provider_mixin.py
Labels: enhancement

#4462 Change rebase-strategy dependabot
  .github/dependabot.yml
Labels: task

#4463 Tox - update pre-commit version
  tox.ini
Labels: task

#4445 Implemented new check `consider-using-dict-items`
  CONTRIBUTORS.txt
  ChangeLog
  doc/whatsnew/2.9.rst
  pylint/checkers/refactoring/recommendation_checker.py
  pylint/checkers/typecheck.py
  pylint/checkers/utils.py
  tests/functional/c/consider/consider_using_dict_items.py
  tests/functional/c/consider/consider_using_dict_items.txt
Labels: checkers, enhancement

#4446 Fix issues with Python 3.6.0
  ChangeLog
  doc/whatsnew/2.9.rst
  pylint/checkers/strings.py
  requirements_test.txt
  requirements_test_pre_commit.txt
  tests/functional/i/inconsistent/inconsistent_returns.py
  tests/functional/i/inconsistent/inconsistent_returns.txt
  tests/functional/i/inconsistent/inconsistent_returns_noreturn.py
  tests/functional/i/inconsistent/inconsistent_returns_noreturn.rc
  tests/functional/i/inconsistent/inconsistent_returns_noreturn.txt
Labels: blocker, crash

#4476 Consider using with no assign
  ChangeLog
  pylint/checkers/refactoring/refactoring_checker.py
  pylint/pyreverse/utils.py
  tests/functional/b/bad_open_mode_py3.py
  tests/functional/b/bad_open_mode_py3.txt
  tests/functional/c/consider/consider_using_with.txt
  tests/functional/c/consider/consider_using_with_open.py
  tests/functional/c/consider/consider_using_with_open.txt
  tests/functional/s/subprocess_popen_preexec_fn.py
  tests/lint/unittest_lint.py
Labels: checkers, enhancement

#4474 Add ignore_signatures to similarity checker
  CONTRIBUTORS.txt
  ChangeLog
  doc/whatsnew/2.9.rst
  pylint/checkers/similar.py
  tests/checkers/unittest_similar.py
  tests/input/similar5
  tests/input/similar6
Labels: checkers, enhancement

#4469 Implemented new check ``use-maxsplit-arg``
  ChangeLog
  doc/whatsnew/2.9.rst
  pylint/checkers/refactoring/recommendation_checker.py
  pylint/checkers/utils.py
  pylint/testutils/lint_module_test.py
  tests/functional/u/use/use_maxsplit_arg.py
  tests/functional/u/use/use_maxsplit_arg.txt
Labels: checkers, enhancement

#4493 Add security.md for Tidelift coordinated disclosure plan
  .github/SECURITY.md
Labels: task

#4485 Implemented new check ``unnecessary-dict-index-lookup``
  ChangeLog
  doc/whatsnew/2.9.rst
  pylint/checkers/refactoring/refactoring_checker.py
  tests/functional/u/unnecessary/unnecessary_dict_index_lookup.py
  tests/functional/u/unnecessary/unnecessary_dict_index_lookup.txt
Labels: checkers, enhancement

#4491 Implemented new check ``consider-using-from-import``
  ChangeLog
  doc/whatsnew/2.9.rst
  pylint/checkers/imports.py
  tests/extensions/test_empty_comment.py
  tests/functional/i/import_aliasing.py
  tests/functional/i/import_aliasing.txt
  tests/functional/u/useless/useless-import-alias.txt
Labels: checkers, enhancement

#4492 Multiple `output-format` support
  CONTRIBUTORS.txt
  ChangeLog
  doc/user_guide/output.rst
  doc/whatsnew/2.9.rst
  pylint/lint/pylinter.py
  pylint/reporters/__init__.py
  pylint/reporters/multi_reporter.py
  tests/unittest_reporting.py
Labels: enhancement

#4502 Add list literal check to using-constant-test.
  CONTRIBUTORS.txt
  ChangeLog
  doc/whatsnew/2.9.rst
  pylint/checkers/base.py
  tests/functional/u/use/using_constant_test.py
  tests/functional/u/use/using_constant_test.txt
Labels: enhancement, false negative

#4500 Added suggestion in helptext for ``unnecessary-comprehension`` checker
  ChangeLog
  pylint/checkers/refactoring/refactoring_checker.py
  tests/functional/u/unnecessary/unnecessary_comprehension.py
  tests/functional/u/unnecessary/unnecessary_comprehension.txt
Labels: enhancement

#4512 Improve build config
  MANIFEST.in
  setup.cfg
Labels: task

#4508 Fixed false negative of ``consider-using-enumerate`` on attributes
  ChangeLog
  pylint/checkers/design_analysis.py
  pylint/checkers/refactoring/recommendation_checker.py
  pylint/config/option_manager_mixin.py
  tests/functional/c/consider/consider_using_enumerate.py
  tests/functional/c/consider/consider_using_enumerate.txt
Labels: false negative

#4510 Implemented new checker ``invalid-class-object``
  ChangeLog
  doc/whatsnew/2.9.rst
  pylint/checkers/classes.py
  tests/functional/i/invalid/b/invalid_bool_returned.py
  tests/functional/i/invalid/b/invalid_bool_returned.txt
  tests/functional/i/invalid/b/invalid_bytes_returned.py
  tests/functional/i/invalid/b/invalid_bytes_returned.txt
  tests/functional/i/invalid/e/invalid_envvar_value.py
  tests/functional/i/invalid/e/invalid_envvar_value.txt
  tests/functional/i/invalid/e/invalid_exceptions_caught.py
  tests/functional/i/invalid/e/invalid_exceptions_caught.rc
  tests/functional/i/invalid/e/invalid_exceptions_caught.txt
  tests/functional/i/invalid/e/invalid_exceptions_raised.py
  tests/functional/i/invalid/e/invalid_exceptions_raised.txt
  tests/functional/i/invalid/g/invalid_getnewargs_ex_returned.py
  tests/functional/i/invalid/g/invalid_getnewargs_ex_returned.txt
  tests/functional/i/invalid/g/invalid_getnewargs_returned.py
  tests/functional/i/invalid/g/invalid_getnewargs_returned.txt
  tests/functional/i/invalid/invalid_class_object.py
  tests/functional/i/invalid/invalid_class_object.txt
  tests/functional/i/invalid/l/invalid_length_hint_returned.py
  tests/functional/i/invalid/l/invalid_length_hint_returned.txt
  tests/functional/i/invalid/l/invalid_length_returned.py
  tests/functional/i/invalid/l/invalid_length_returned.txt
  tests/functional/i/invalid/m/invalid_metaclass.py
  tests/functional/i/invalid/m/invalid_metaclass_py3.py
  tests/functional/i/invalid/m/invalid_metaclass_py3.rc
  tests/functional/i/invalid/s/invalid_sequence_index.py
  tests/functional/i/invalid/s/invalid_sequence_index.txt
  tests/functional/i/invalid/s/invalid_slice_index.py
  tests/functional/i/invalid/s/invalid_slice_index.txt
  tests/functional/i/invalid/s/invalid_star_assignment_target.py
  tests/functional/i/invalid/s/invalid_star_assignment_target.rc
  tests/functional/i/invalid/s/invalid_star_assignment_target.txt
  tests/functional/i/invalid/s/invalid_str_returned.py
  tests/functional/i/invalid/s/invalid_str_returned.txt
Labels: checkers, enhancement

#4516 Add `ignore-paths` to match against the full path.
  CONTRIBUTORS.txt
  ChangeLog
  doc/whatsnew/2.9.rst
  pylint/lint/expand_modules.py
  pylint/lint/pylinter.py
  tests/lint/unittest_expand_modules.py
Labels: enhancement

#4513 Added deprecated decorators check
  ChangeLog
  doc/whatsnew/2.9.rst
  pylint/checkers/deprecated.py
  pylint/checkers/stdlib.py
  tests/checkers/unittest_deprecated.py
  tests/functional/d/deprecated/deprecated_decorators.py
  tests/functional/d/deprecated/deprecated_decorators.rc
  tests/functional/d/deprecated/deprecated_decorators.txt
  tests/functional/i/invalid/invalid_overridden_method.py
  tests/functional/n/name/name_styles.py
  tests/functional/n/name/name_styles.txt
  tests/functional/p/property_with_parameters.py
Labels: checkers, enhancement

#4471 Add regression test for no-member with generic base class
  ChangeLog
  tests/functional/t/typing_generic.py
Labels: bug, requires astroid update

#4348 Add regression tests of instance attribute inference on builtins.object
  tests/functional/r/regression/regression_3595_notcallable_collections.py
  tests/functional/r/regression/regression_4221_object_instanceattr.py
Labels: bug, requires astroid update

#4428 Add regression tests of inference of implicit None return
  tests/functional/a/abstract/abstract_class_instantiated_py3.py
  tests/functional/a/abstract/abstract_method_py3.py
  tests/functional/r/regression/regression_implicit_none_with_no_return.py
  tests/functional/r/regression/regression_implicit_none_with_no_return.txt
Labels: enhancement, requires astroid update

#4473 Additional regression tests for PyCQA/astroid#940
  tests/functional/r/regression/regression_3535_double_enum_inherit.py
  tests/functional/r/regression/regression_4358_unsubscriptable_enum.py
  tests/functional/r/regression/regression_properties_in_class_context.py
  tests/functional/r/regression/regression_properties_in_class_context.txt
Labels: bug, requires astroid update

#4522 Fix false-positive assigning-non-slot with typing.Generic base
  ChangeLog
  pylint/checkers/classes.py
  tests/functional/a/assign/assigning_non_slot_4509.py
  tests/functional/a/assign/assigning_non_slot_4509.rc
  tests/functional/a/assign/assigning_non_slot_4509.txt
Labels: false-positive

#4517 Add new checker ``consider-using-namedtuple``
  ChangeLog
  doc/whatsnew/2.9.rst
  pylint/checkers/classes.py
  pylint/checkers/design_analysis.py
  pylint/checkers/exceptions.py
  pylint/checkers/logging.py
  pylint/checkers/refactoring/refactoring_checker.py
  pylint/checkers/strings.py
  tests/functional/c/consider/consider_using_namedtuple.py
  tests/functional/c/consider/consider_using_namedtuple.txt
Labels: checkers, enhancement

#4533 Upgrade release.md following the decision to pin astroid
  doc/release.md
Labels: documentation, task
