Repository pylint-dev/pylint, pull requests merged in 2021-04, with the labels that each got.

#4279 Fix class-const naming style
  ChangeLog
  pylint/checkers/base.py
  pylint/checkers/utils.py
  tests/functional/n/name/name_final.py
  tests/functional/n/name/name_final.rc
  tests/functional/n/name/name_final.txt
  tests/functional/n/name/name_final_snake_case.py
  tests/functional/n/name/name_final_snake_case.rc
  tests/functional/n/name/name_final_snake_case.txt
  tests/functional/n/name/name_styles.py
  tests/functional/n/name/name_styles.txt
Labels: false-positive, regression

#4267 Allow protected-access in class methods
  CONTRIBUTORS.txt
  ChangeLog
  doc/whatsnew/2.7.rst
  pylint/checkers/classes.py
  tests/functional/a/access/access_to_protected_members.py
  tests/functional/a/access/access_to_protected_members.txt
Labels: enhancement, false-positive

#4288 Extend documentation for issue #4282
  CONTRIBUTORS.txt
  doc/user_guide/output.rst
  doc/user_guide/run.rst
Labels: documentation

#4280 Apply const-naming-style to module const annotated with Final
  ChangeLog
  pylint/checkers/base.py
  tests/functional/n/name/name_final.py
  tests/functional/n/name/name_final.txt
  tests/functional/n/name/name_final_snake_case.py
  tests/functional/n/name/name_final_snake_case.rc
  tests/functional/n/name/name_final_snake_case.txt
Labels: enhancement

#4287 Add a test for epylint for issue 4286
  tests/test_epylint.py
Labels: enhancement

#4298 Add continuous integration with read the doc
  .github/workflows/ci.yaml
  ChangeLog
Labels: maintenance, task

#4305 Use prescriptve description for unidiomatic-typecheck
  ChangeLog
  pylint/checkers/base.py
  tests/functional/u/unidiomatic_typecheck.txt
Labels: enhancement

#4312 Add editable install in requirements_test_min.txt
  .github/workflows/ci.yaml
  requirements_test_min.txt
Labels: bug, task

#4314 Add prettier to the pre-commit configuration
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/1_Bug_report.md
  .github/ISSUE_TEMPLATE/2_Feature_request.md
  .github/ISSUE_TEMPLATE/3_Question.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/ci.yaml
  .pre-commit-config.yaml
  .pre-commit-hooks.yaml
  .readthedocs.yaml
  .travis.yml
  appveyor.yml
  doc/release.md
Labels: maintenance

#4317 Don't show ``astroid.DuplicateBasesError`` for attribute access
  ChangeLog
  pylint/checkers/typecheck.py
  tests/functional/d/duplicate_bases.py
Labels: crash

#4332 Enable loading of plugins in functional tests (Fix 4331)
  pylint/testutils/lint_module_test.py
  tests/functional/b/bad_builtins.py
  tests/functional/b/bad_builtins.rc
  tests/functional/b/bad_builtins.txt
  tests/functional/f/fixture_docparams_missing.py
  tests/functional/f/fixture_docparams_missing.txt
Labels: bug

#4329 Force encoding in reading of setup.cfg to utf-8
  CONTRIBUTORS.txt
  ChangeLog
  pylint/config/find_default_config_files.py
Labels: bug

#4334 Update ``astroid`` to 2.5.3
  ChangeLog
  doc/whatsnew/2.8.rst
  requirements_test_min.txt
  setup.cfg
  tests/functional/n/name/name_styles.py
  tests/functional/t/typing_generic.py
  tests/functional/t/typing_generic.rc
Labels: astroid, bug, requires astroid update, topic-typing

#4239 Add generic alias test cases
  tests/functional/g/generic_alias/__init__.py
  tests/functional/g/generic_alias/generic_alias_collections.py
  tests/functional/g/generic_alias/generic_alias_collections.rc
  tests/functional/g/generic_alias/generic_alias_collections.txt
  tests/functional/g/generic_alias/generic_alias_collections_py37.py
  tests/functional/g/generic_alias/generic_alias_collections_py37.rc
  tests/functional/g/generic_alias/generic_alias_collections_py37.txt
  tests/functional/g/generic_alias/generic_alias_collections_py37_with_typing.py
  tests/functional/g/generic_alias/generic_alias_collections_py37_with_typing.rc
  tests/functional/g/generic_alias/generic_alias_collections_py37_with_typing.txt
  tests/functional/g/generic_alias/generic_alias_mixed_py37.py
  tests/functional/g/generic_alias/generic_alias_mixed_py37.rc
  tests/functional/g/generic_alias/generic_alias_mixed_py37.txt
  tests/functional/g/generic_alias/generic_alias_mixed_py39.py
  tests/functional/g/generic_alias/generic_alias_mixed_py39.rc
  tests/functional/g/generic_alias/generic_alias_mixed_py39.txt
  tests/functional/g/generic_alias/generic_alias_postponed_evaluation_py37.py
  tests/functional/g/generic_alias/generic_alias_postponed_evaluation_py37.rc
  tests/functional/g/generic_alias/generic_alias_postponed_evaluation_py37.txt
  tests/functional/g/generic_alias/generic_alias_related.py
  tests/functional/g/generic_alias/generic_alias_related.rc
  tests/functional/g/generic_alias/generic_alias_related.txt
  tests/functional/g/generic_alias/generic_alias_related_py39.py
  tests/functional/g/generic_alias/generic_alias_related_py39.rc
  tests/functional/g/generic_alias/generic_alias_related_py39.txt
  tests/functional/g/generic_alias/generic_alias_side_effects.py
  tests/functional/g/generic_alias/generic_alias_side_effects.rc
  tests/functional/g/generic_alias/generic_alias_side_effects.txt
  tests/functional/g/generic_alias/generic_alias_typing.py
  tests/functional/g/generic_alias/generic_alias_typing.rc
  tests/functional/g/generic_alias/generic_alias_typing.txt
Labels: enhancement, high effort

#4337 Add a regression test for #2605
  tests/functional/d/dataclass_with_default_factory.py
  tests/functional/d/dataclass_with_default_factory.rc
Labels: regression

#4318 New ConfusingConsecutiveElifCheckr (for: #3920)
  ChangeLog
  doc/whatsnew/2.8.rst
  pylint/extensions/confusing_elif.py
  tests/extensions/test_confusing_elif.py
  tests/functional/c/confusing_consecutive_elif.py
  tests/functional/c/confusing_consecutive_elif.rc
  tests/functional/c/confusing_consecutive_elif.txt
Labels: checkers, enhancement

#4340 Improve check for invalid PEP 585 syntax inside functions
  ChangeLog
  pylint/checkers/utils.py
  tests/functional/p/postponed_evaluation_pep585.py
  tests/functional/p/postponed_evaluation_pep585.txt
  tests/functional/p/postponed_evaluation_pep585_error.py
  tests/functional/p/postponed_evaluation_pep585_error.txt
  tests/functional/p/postponed_evaluation_pep585_py39.py
Labels: bug, topic-typing

#4345 Fix - Improve check for invalid PEP 585 syntax
  pylint/checkers/utils.py
  tests/functional/p/postponed_evaluation_pep585.py
  tests/functional/p/postponed_evaluation_pep585_error.py
  tests/functional/p/postponed_evaluation_pep585_error.txt
  tests/functional/p/postponed_evaluation_pep585_py39.py
Labels: bug, false negative, topic-typing

#4373 resolved false positive on unused variables in decorator functions
  CONTRIBUTORS.txt
  ChangeLog
  pylint/checkers/variables.py
  tests/functional/d/decorator_unused.py
  tests/functional/d/decorator_unused.txt
Labels: false-positive

#4374 Added test case for issue #4163
  tests/functional/r/redefine_loop.py
  tests/functional/r/redefine_loop.txt
Labels: enhancement

#4381 Improve exception debugging
  pylint/utils/ast_walker.py
Labels: enhancement

#4339 Enhancement 1070 file output
  ChangeLog
  doc/user_guide/run.rst
  doc/whatsnew/2.8.rst
  pylint/lint/run.py
  tests/test_self.py
Labels: enhancement

#4396 Prepare for 2.8.0 release
  .copyrite_aliases
  ChangeLog
  doc/whatsnew/2.8.rst
  pylint/__init__.py
  pylint/__pkginfo__.py
  pylint/checkers/__init__.py
  pylint/checkers/base.py
  pylint/checkers/classes.py
  pylint/checkers/format.py
  pylint/checkers/misc.py
  pylint/checkers/raw_metrics.py
  pylint/checkers/similar.py
  pylint/checkers/spelling.py
  pylint/checkers/stdlib.py
  pylint/checkers/variables.py
  pylint/epylint.py
  pylint/extensions/comparetozero.py
  pylint/extensions/confusing_elif.py
  pylint/graph.py
  pylint/pyreverse/writer.py
  pylint/utils/__init__.py
  tests/checkers/unittest_format.py
  tests/checkers/unittest_similar.py
  tests/checkers/unittest_spelling.py
  tests/extensions/test_confusing_elif.py
  tests/test_self.py
Labels: task

#4400 Remove 2.8.0 breaking changes in ``__pkginfo__``
  ChangeLog
  doc/whatsnew/2.8.rst
  pylint/__init__.py
  pylint/__pkginfo__.py
Labels: documentation

#4403 Prepare 2.8.1 release
  pylint/__pkginfo__.py
  requirements_test_min.txt
  setup.cfg
Labels: task

#4418 tests: Sort for comparison in test_expand_modules
  tests/lint/unittest_expand_modules.py
Labels: bug

#4416 Fix too-many-ancestors
  ChangeLog
  doc/whatsnew/2.9.rst
  pylint/checkers/design_analysis.py
  tests/functional/t/too/too_many_ancestors.py
  tests/functional/t/too/too_many_ancestors.txt
Labels: false-positive

#4419 Add new warning ``deprecated-class`` #4388
  .pre-commit-config.yaml
  CONTRIBUTORS.txt
  ChangeLog
  doc/whatsnew/2.8.rst
  pylint/checkers/deprecated.py
  pylint/checkers/stdlib.py
  tests/functional/d/deprecated/deprecated_class_py33.py
  tests/functional/d/deprecated/deprecated_class_py33.rc
  tests/functional/d/deprecated/deprecated_class_py33.txt
Labels: enhancement

#4423 Add pre-commit CI in continuous integration
  .github/workflows/ci.yaml
  README.rst
Labels: task
