Repository pylint-dev/pylint, pull requests merged in 2021-10, with the labels that each got.

#5098 Move ``merge_stats`` to ``checkerstats.py``
  pylint/lint/parallel.py
  pylint/utils/__init__.py
  pylint/utils/checkerstats.py
Labels: maintenance

#5110 Improve and flatten ``unused-wildcard-import`` message
  ChangeLog
  doc/whatsnew/2.12.rst
  pylint/checkers/variables.py
  tests/functional/u/unused/unused_name_from_wilcard_import.py
  tests/functional/u/unused/unused_name_from_wilcard_import.txt
Labels: enhancement, blocked

#5118 Fix crash with AssignAttr in TYPE_CHECKING blocks
  ChangeLog
  pylint/checkers/variables.py
  tests/functional/u/undefined/undefined_variable.py
Labels: crash

#5094 Improve node info for invalid-name
  ChangeLog
  pylint/checkers/base.py
  tests/functional/i/invalid/invalid_name.py
  tests/functional/i/invalid/invalid_name.txt
  tests/functional/n/name/name_styles.txt
Labels: enhancement

#5121 Use 3.10 for Github actions
  .github/workflows/ci.yaml
Labels: maintenance

#5109 Fix a crash if ``str.format`` is referenced without being called
  CONTRIBUTORS.txt
  ChangeLog
  pylint/checkers/refactoring/recommendation_checker.py
  tests/functional/c/consider/consider_using_f_string.py
Labels: bug, regression, crash

#5227 Fix incorrect ``consider-using-ternary`` when condition is inferable as False
  ChangeLog
  doc/whatsnew/2.12.rst
  pylint/checkers/refactoring/refactoring_checker.py
  tests/functional/t/ternary.py
  tests/functional/t/ternary.txt
Labels: enhancement

#5229 Unify all `<y or n>` metavars
  CONTRIBUTORS.txt
  doc/how_tos/custom_checkers.rst
  doc/tutorial.rst
  pylint/checkers/base.py
  pylint/checkers/format.py
  pylint/checkers/imports.py
  pylint/checkers/spelling.py
  pylint/checkers/strings.py
  pylint/checkers/typecheck.py
  pylint/checkers/variables.py
  pylint/extensions/typing.py
  pylint/lint/pylinter.py
  pylint/pyreverse/main.py
Labels: documentation

#5231 Allow no type in Numpy param docstrings for ``mising-param-doc``
  ChangeLog
  doc/whatsnew/2.12.rst
  pylint/extensions/_check_docs_utils.py
  tests/extensions/test_check_docs.py
Labels: false-positive

#5232 Fix ``protected-access`` for attributes and methods of nested classes
  CONTRIBUTORS.txt
  ChangeLog
  doc/whatsnew/2.12.rst
  pylint/checkers/classes.py
  pylint/checkers/utils.py
  tests/functional/a/access/access_to_protected_members.py
  tests/functional/a/access/access_to_protected_members.txt
Labels: false-positive

#5236 Remove accidental print statement
  pylint/extensions/_check_docs_utils.py
Labels: maintenance

#5233 Nographviz fix
  CONTRIBUTORS.txt
  ChangeLog
  doc/whatsnew/2.12.rst
  pylint/pyreverse/main.py
Labels: topic-pyreverse, documentation
