Repository pylint-dev/pylint, pull requests merged in 2021-08, with the labels that each got.

#4709 [unused-private-member] add logic for checking nested functions
  ChangeLog
  pylint/checkers/classes.py
  tests/functional/u/unused/unused_private_member.py
  tests/functional/u/unused/unused_private_member.txt
Labels: false-positive

#4782 Fix false-positive of `unused-private-member` with class name
  ChangeLog
  pylint/checkers/classes.py
  tests/functional/u/unused/unused_private_member.py
  tests/functional/u/unused/unused_private_member.txt
Labels: false-positive

#4783 Fix crash for `unused-private-member` when there are nested attributes
  ChangeLog
  pylint/checkers/classes.py
  tests/functional/u/unused/unused_private_member.py
  tests/functional/u/unused/unused_private_member.txt
Labels: bug, crash

#4731 Create common ``Printer`` base class for ``pyreverse`` and improve typing.
  pylint/pyreverse/diagrams.py
  pylint/pyreverse/dot_printer.py
  pylint/pyreverse/main.py
  pylint/pyreverse/printer.py
  pylint/pyreverse/utils.py
  pylint/pyreverse/vcg_printer.py
  pylint/pyreverse/writer.py
  tests/data/classes_No_Name.dot
  tests/data/classes_No_Name.vcg
  tests/data/packages_No_Name.dot
  tests/data/packages_No_Name.vcg
  tests/unittest_pyreverse_writer.py
Labels: enhancement, maintenance

#4784 Fix false positives for ``superfluous-parens``
  ChangeLog
  doc/whatsnew/2.10.rst
  pylint/checkers/format.py
  tests/checkers/unittest_format.py
  tests/functional/s/super/superfluous_parens.py
  tests/functional/s/super/superfluous_parens.txt
  tests/functional/s/super/superfluous_parens_walrus_py38.py
  tests/functional/s/super/superfluous_parens_walrus_py38.rc
  tests/functional/s/super/superfluous_parens_walrus_py38.txt
  tests/functional/s/superfluous_parens.py
  tests/functional/s/superfluous_parens.txt
Labels: bug, false-positive, walrus operator

#4791 Fix false negative for used-before-assignment (ExceptHandler)
  ChangeLog
  doc/whatsnew/2.10.rst
  pylint/checkers/variables.py
  tests/functional/u/unused/unused_variable.py
  tests/functional/u/unused/unused_variable.txt
  tests/functional/u/use/used_before_assignment_issue626.py
  tests/functional/u/use/used_before_assignment_issue626.txt
Labels: bug, topic-control-flow

#4793 Refactor ``--list-msgs`` & ``--list-msgs-enabled``
  ChangeLog
  doc/whatsnew/2.10.rst
  pylint/lint/pylinter.py
  pylint/lint/run.py
  pylint/message/message_definition_store.py
Labels: bug, documentation

#4801 Hot-fix master following release of python 3.10-rc's new version
  tests/functional/r/regression/regression_4439.rc
Labels: bug, maintenance

#4794 Add ``format-string-without-interpolation`` checker
  ChangeLog
  doc/whatsnew/2.10.rst
  pylint/checkers/strings.py
  pylint/config/__init__.py
  tests/functional/s/string/string_formatting.py
  tests/functional/s/string/string_formatting.txt
  tests/functional/s/string/string_formatting_error.py
  tests/functional/s/string/string_formatting_error.txt
Labels: enhancement

#4800 Documentation for what blocks are and FAQ clean up
  doc/faq.rst
Labels: documentation

#4797 Add ``disable-next`` option
  ChangeLog
  doc/faq.rst
  doc/user_guide/message-control.rst
  doc/whatsnew/2.10.rst
  pylint/exceptions.py
  pylint/lint/pylinter.py
  pylint/message/message_handler_mix_in.py
  pylint/utils/pragma_parser.py
  tests/functional/d/disable_msg_next_line.py
  tests/functional/d/disable_msg_next_line.txt
Labels: enhancement

#4804 Add ``redundant-u-string-prefix`` checker
  ChangeLog
  doc/whatsnew/2.10.rst
  pylint/checkers/strings.py
  tests/functional/a/anomalous_unicode_escape_py3.py
  tests/functional/a/assign/assigning_non_slot.py
  tests/functional/d/duplicate_dict_literal_key.py
  tests/functional/e/excess_escapes.py
  tests/functional/e/excess_escapes.txt
  tests/functional/i/implicit/implicit_str_concat.py
  tests/functional/i/iterable_context.py
  tests/functional/m/member/membership_protocol.py
  tests/functional/r/raise/raising_format_tuple.py
  tests/functional/r/raise/raising_format_tuple.txt
  tests/functional/r/redundant_u_string_prefix.py
  tests/functional/r/redundant_u_string_prefix.rc
  tests/functional/r/redundant_u_string_prefix.txt
  tests/functional/s/suspicious_str_strip_call_py3.py
  tests/functional/s/suspicious_str_strip_call_py3.txt
  tests/functional/u/unsubscriptable_value.py
Labels: enhancement, checkers

#4829 Fix false positives for invalid-all-format (#4711)
  CONTRIBUTORS.txt
  ChangeLog
  pylint/checkers/variables.py
  tests/functional/i/invalid/invalid_all_format_valid_3.py
  tests/functional/i/invalid/invalid_all_format_valid_4.py
Labels: false-positive

#4830 Fix the link to the discord server in the doc
  doc/development_guide/contribute.rst
Labels: task, maintenance

#4812 Update option_manager_mixin.py - issue 3839
  CONTRIBUTORS.txt
  ChangeLog
  pylint/config/option_manager_mixin.py
  tests/test_config.py
Labels: enhancement

#4827 Fix bugs in W0640 cell-var-from-loop checker
  ChangeLog
  doc/whatsnew/2.10.rst
  pylint/checkers/utils.py
  pylint/checkers/variables.py
  tests/functional/c/cellvar_escaping_loop.py
  tests/functional/c/cellvar_escaping_loop.txt
  tests/functional/c/consider/consider_using_enumerate.py
Labels: bug, enhancement

#4824 Add a regression test for #4823
  tests/functional/c/class_attributes.py
Labels: maintenance

#4831 Fix false-positive used-before-assignment with := in Return node
  ChangeLog
  pylint/checkers/variables.py
  tests/functional/a/assign/assignment_expression.py
Labels: false-positive, walrus operator

#4810 Permit to lint to the end in case of crash on a file
  ChangeLog
  doc/tutorial.rst
  doc/whatsnew/2.10.rst
  pylint/lint/pylinter.py
  pylint/lint/utils.py
  pylint/utils/ast_walker.py
  tests/lint/test_pylinter.py
  tests/lint/test_utils.py
  tests/lint/unittest_expand_modules.py
Labels: enhancement

#4834 Simplification in error handling inside Pylinter
  pylint/lint/pylinter.py
Labels: enhancement

#4835 Add `use-sequence-for-iteration` checker
  ChangeLog
  doc/whatsnew/2.10.rst
  pylint/checkers/refactoring/recommendation_checker.py
  tests/functional/ext/code_style/code_style_consider_using_tuple.py
  tests/functional/ext/code_style/code_style_consider_using_tuple.txt
  tests/functional/u/undefined/undefined_loop_variable.py
  tests/functional/u/use/use_sequence_for_iteration.py
  tests/functional/u/use/use_sequence_for_iteration.txt
Labels: enhancement

#4838 Improvements `consider-using-tuple`
  ChangeLog
  doc/whatsnew/2.10.rst
  pylint/extensions/code_style.py
  tests/functional/ext/code_style/code_style_consider_using_tuple.py
  tests/functional/ext/code_style/code_style_consider_using_tuple.txt
Labels: enhancement, checker-CodeStyle

#4840 [duplicate-code] Ignore decorators lines by similarities checker when ignore signatures flag enabled
  CONTRIBUTORS.txt
  ChangeLog
  pylint/checkers/similar.py
  tests/checkers/unittest_similar.py
  tests/input/similar5
Labels: enhancement, topic-duplication

#4843 Add pylintrc config for typing extension
  pylintrc
Labels: maintenance

#4844 Allow true / false in pylintrc
  ChangeLog
  pylint/config/option.py
Labels: enhancement, topic-configuration

#4846 ``pyreverse``: add PlantUML output
  ChangeLog
  doc/whatsnew/2.10.rst
  pylint/pyreverse/dot_printer.py
  pylint/pyreverse/main.py
  pylint/pyreverse/plantuml_printer.py
  pylint/pyreverse/printer.py
  pylint/pyreverse/printer_factory.py
  pylint/pyreverse/writer.py
  tests/data/suppliermodule_test.py
  tests/pyreverse/conftest.py
  tests/pyreverse/data/classes_No_Name.dot
  tests/pyreverse/data/classes_No_Name.puml
  tests/pyreverse/data/classes_No_Name.vcg
  tests/pyreverse/data/packages_No_Name.puml
  tests/pyreverse/test_diadefs.py
  tests/pyreverse/test_printer.py
  tests/pyreverse/test_printer_factory.py
  tests/pyreverse/test_writer.py
Labels: enhancement, topic-pyreverse

#4847 Add a regression test for #4837
  tests/functional/u/unused/unused_private_member.py
  tests/functional/u/unused/unused_private_member.txt
Labels: crash

#4851 Suppress ``consider-using-with`` on return statements
  ChangeLog
  doc/whatsnew/2.10.rst
  pylint/checkers/refactoring/refactoring_checker.py
  tests/functional/c/consider/consider_using_with_open.py
Labels: false-positive

#4848 Fix crash on relative import beyond top-level package
  ChangeLog
  pylint/checkers/utils.py
  tests/functional/i/import_aliasing.py
  tests/functional/i/import_aliasing.txt
Labels: bug, blocker, crash

#4858 [duplicate-code] Parse functions and class methods recursively when gathering signature lines
  CONTRIBUTORS.txt
  ChangeLog
  doc/whatsnew/2.10.rst
  pylint/checkers/similar.py
  tests/checkers/unittest_similar.py
  tests/input/similar_cls_a.py
  tests/input/similar_cls_b.py
Labels: enhancement, topic-duplication

#4855 Use alias for astroid.nodes 01
  examples/custom.py
  pylint/checkers/async.py
  pylint/checkers/base.py
  pylint/checkers/classes.py
  pylint/checkers/deprecated.py
Labels: task

#4863 Use alias for astroid.nodes 02
  pylint/checkers/exceptions.py
  pylint/checkers/imports.py
  pylint/checkers/logging.py
  pylint/checkers/newstyle.py
  pylint/checkers/python3.py
  pylint/checkers/similar.py
  pylint/checkers/stdlib.py
  pylint/checkers/strings.py
  pylint/checkers/typecheck.py
Labels: task

#4860 Add extension check against use of while loops
  ChangeLog
  doc/whatsnew/2.10.rst
  pylint/checkers/utils.py
  pylint/config/option_manager_mixin.py
  pylint/extensions/typing.py
  pylint/extensions/while_used.py
  pylint/lint/utils.py
  pylint/reporters/ureports/__init__.py
  pylint/utils/utils.py
  tests/extensions/test_while_used.py
  tests/functional/ext/while_used.py
  tests/functional/ext/while_used.rc
  tests/functional/ext/while_used.txt
  tests/functional/i/import_outside_toplevel.py
  tests/functional/i/import_outside_toplevel.txt
Labels: enhancement

#4859 pyreverse - Handle a regression with typehints of type astroid.Subscript
  pylint/pyreverse/utils.py
  tests/data/suppliermodule_test.py
  tests/pyreverse/data/classes_No_Name.dot
  tests/pyreverse/data/classes_No_Name.puml
  tests/pyreverse/data/classes_No_Name.vcg
  tests/pyreverse/data/classes_colorized.dot
  tests/pyreverse/data/classes_colorized.puml
  tests/pyreverse/test_utils.py
Labels: bug, regression

#4867 Prevent crashing when it's impossible to create the issue template
  pylint/lint/utils.py
Labels: blocker, crash

#4866 Use alias for astroid.nodes 03
  pylint/checkers/refactoring/len_checker.py
  pylint/checkers/refactoring/not_checker.py
  pylint/checkers/refactoring/recommendation_checker.py
  pylint/checkers/utils.py
  pylint/checkers/variables.py
  pylint/extensions/_check_docs_utils.py
Labels: task

#4869 Use alias for astroid.nodes 04
  pylint/checkers/refactoring/refactoring_checker.py
  pylint/extensions/bad_builtin.py
  pylint/extensions/check_elif.py
  pylint/extensions/code_style.py
  pylint/extensions/confusing_elif.py
  pylint/extensions/emptystring.py
  pylint/extensions/redefined_variable_type.py
  pylint/extensions/typing.py
  pylint/pyreverse/diadefslib.py
  pylint/pyreverse/diagrams.py
  pylint/pyreverse/dot_printer.py
  pylint/pyreverse/inspector.py
  pylint/pyreverse/printer.py
  pylint/pyreverse/utils.py
  pylint/pyreverse/writer.py
  tests/checkers/unittest_stdlib.py
  tests/extensions/test_check_docs.py
  tests/pyreverse/test_diadefs.py
  tests/pyreverse/test_inspector.py
  tests/pyreverse/test_utils.py
Labels: task

#4868 ``astroid.const.BUILTINS`` use removed for clarity and so astroid can also removes it later
  pylint/checkers/base.py
  pylint/checkers/classes.py
  pylint/checkers/python3.py
  pylint/checkers/refactoring/not_checker.py
  pylint/checkers/strings.py
  pylint/checkers/typecheck.py
  pylint/checkers/utils.py
  pylint/constants.py
  pylint/extensions/redefined_variable_type.py
  pylint/pyreverse/diadefslib.py
Labels: task

#4872 Refactor existing code - code_style extension
  pylint/extensions/code_style.py
Labels: task

#4875 Improve invalid-metaclass error message for Instances
  ChangeLog
  pylint/checkers/typecheck.py
  tests/checkers/unittest_typecheck.py
Labels: enhancement

#4878 Add a test for false positive no-member in subclassed dataclasses
  tests/functional/n/no/no_member_subclassed_dataclasses.py
  tests/functional/n/no/no_member_subclassed_dataclasses.rc
Labels: maintenance

#4887 Migrate from ``appdirs`` to ``platformdirs``
  ChangeLog
  pylint/config/__init__.py
  setup.cfg
  tests/lint/unittest_lint.py
Labels: enhancement, maintenance

#4890 Require platformdirs 2.2.0
  setup.cfg
Labels: dependency

#4889 Updated mypy checks
  .pre-commit-config.yaml
  setup.cfg
Labels: task

#4892 Fix a crash from astroid.InferenceError raised on copy.copy
  ChangeLog
  pylint/checkers/stdlib.py
  tests/functional/r/regression/regression_4891.py
Labels: crash

#4905 Add main maintainers to funding.yml
  .github/FUNDING.yml
Labels: maintenance

#4926 Upgrade ignored-parents help description
  CONTRIBUTORS.txt
  pylint/checkers/design_analysis.py
Labels: documentation

#4929 Implement basic control flow checks for ``consider-using-with``
  ChangeLog
  doc/whatsnew/2.10.rst
  pylint/checkers/refactoring/refactoring_checker.py
  tests/functional/c/consider/consider_using_with_open.py
  tests/functional/c/consider/consider_using_with_open.txt
Labels: bug, false-positive

#4876 Add `consider-using-assignment-expr` to `CodeStyleChecker`
  ChangeLog
  doc/whatsnew/2.11.rst
  pylint/extensions/code_style.py
  pylint/extensions/typing.py
  pylint/lint/pylinter.py
  pylintrc
  setup.cfg
  tests/functional/ext/code_style/code_style_consider_using_assignment_expr.py
  tests/functional/ext/code_style/code_style_consider_using_assignment_expr.rc
  tests/functional/ext/code_style/code_style_consider_using_assignment_expr.txt
Labels: enhancement, blocked, checker-CodeStyle

#4841 Add `use-set-for-membership` check
  ChangeLog
  doc/whatsnew/2.11.rst
  pylint/extensions/set_membership.py
  tests/functional/ext/set_membership/set_membership_use_set_membership.py
  tests/functional/ext/set_membership/set_membership_use_set_membership.rc
  tests/functional/ext/set_membership/set_membership_use_set_membership.txt
Labels: enhancement

#4898 Add regression test for false positive on collections.abc
  tests/functional/u/unpacking_non_sequence_py37.py
  tests/functional/u/unpacking_non_sequence_py37.rc
Labels: maintenance, requires astroid update

#4923 Add regression tests for PyCQA/astroid#1151
  tests/functional/a/assign/assignment_from_no_return.py
  tests/functional/n/no/no_member.py
Labels: requires astroid update

#4924 Emit a correct invalid-name message when using multi-naming style.
  ChangeLog
  doc/whatsnew/2.11.rst
  pylint/checkers/base.py
  tests/checkers/unittest_base.py
  tests/functional/i/invalid/invalid_name_multinaming_style.py
  tests/functional/i/invalid/invalid_name_multinaming_style.rc
  tests/functional/i/invalid/invalid_name_multinaming_style.txt
Labels: enhancement

#4938 Fix false positive for `function-redefined` for simple type annotations
  ChangeLog
  doc/whatsnew/2.11.rst
  pylint/checkers/base.py
  tests/functional/f/function_redefined.py
  tests/functional/f/function_redefined.txt
Labels: bug

#4937 Fix false positive ``protected-access`` in typing
  ChangeLog
  doc/whatsnew/2.10.rst
  doc/whatsnew/2.11.rst
  pylint/checkers/classes.py
  tests/functional/a/access/access_to_protected_members_typing.py
  tests/functional/a/access/access_to_protected_members_typing.rc
  tests/functional/a/access/access_to_protected_members_typing.txt
Labels: bug, false-positive

#4939 Fix false pos. `dict-iter-missing-items` for tuple keys
  ChangeLog
  doc/whatsnew/2.11.rst
  pylint/checkers/typecheck.py
  tests/functional/d/dict_iter_missing_items.py
  tests/functional/d/dict_iter_missing_items.txt
Labels: false-positive
