Repository pylint-dev/pylint, pull requests merged in 2021-09, with the labels that each got.

#4943 Remove dead visit_exec method
  pylint/checkers/base.py
Labels: maintenance

#4947 Fix the ``raising-bad-type`` warning for string
  ChangeLog
  pylint/checkers/exceptions.py
  tests/functional/i/invalid/e/invalid_exceptions_raised.py
  tests/functional/i/invalid/e/invalid_exceptions_raised.txt
Labels: bug, false negative

#4948 Fix false positive ``superfluous-parens`` for tuples
  ChangeLog
  doc/whatsnew/2.11.rst
  pylint/checkers/format.py
  tests/checkers/unittest_format.py
  tests/functional/s/super/superfluous_parens.py
  tests/functional/s/super/superfluous_parens.txt
Labels: bug, false-positive

#4956 Add test to ``superfluous-parens``
  tests/functional/s/super/superfluous_parens.py
Labels: task

#4940 Refactor various typing related issues
  doc/how_tos/custom_checkers.rst
  pylint/checkers/async.py
  pylint/checkers/base.py
  pylint/checkers/classes.py
  pylint/checkers/deprecated.py
  pylint/checkers/design_analysis.py
  pylint/checkers/exceptions.py
  pylint/checkers/format.py
  pylint/checkers/imports.py
  pylint/checkers/logging.py
  pylint/checkers/newstyle.py
  pylint/checkers/refactoring/len_checker.py
  pylint/checkers/refactoring/not_checker.py
  pylint/checkers/refactoring/refactoring_checker.py
  pylint/checkers/similar.py
  pylint/checkers/spelling.py
  pylint/checkers/stdlib.py
  pylint/checkers/strings.py
  pylint/checkers/typecheck.py
  pylint/checkers/utils.py
  pylint/checkers/variables.py
  pylint/extensions/bad_builtin.py
  pylint/extensions/broad_try_clause.py
  pylint/extensions/check_elif.py
  pylint/extensions/code_style.py
  pylint/extensions/comparetozero.py
  pylint/extensions/confusing_elif.py
  pylint/extensions/docparams.py
  pylint/extensions/docstyle.py
  pylint/extensions/emptystring.py
  pylint/extensions/mccabe.py
  pylint/extensions/overlapping_exceptions.py
  pylint/extensions/redefined_variable_type.py
  pylint/extensions/typing.py
  pylint/extensions/while_used.py
  pylint/graph.py
  pylint/message/message_id_store.py
  pylint/pyreverse/diadefslib.py
  pylint/pyreverse/inspector.py
  pylint/pyreverse/main.py
  pylint/testutils/reporter_for_tests.py
  setup.cfg
  tests/extensions/test_check_docs.py
  tests/functional/g/generated_members.py
  tests/functional/g/generated_members.rc
  tests/functional/u/unused/unused_variable.py
  tests/pyreverse/test_utils.py
Labels: maintenance

#4957 Moved ``consider-using-f-string`` to `RecommendationChecker`
  pylint/checkers/refactoring/recommendation_checker.py
  pylint/checkers/strings.py
  tests/functional/c/consider/consider_using_f_string.txt
Labels: maintenance

#4969 Remove test dependency mypy-extensions
  requirements_test_min.txt
  tests/lint/test_pylinter.py
Labels: dependency, maintenance

#4971 Extend consider-using-in for attribute access
  ChangeLog
  doc/whatsnew/2.11.rst
  pylint/checkers/refactoring/refactoring_checker.py
  tests/functional/c/consider/consider_using_in.py
  tests/functional/c/consider/consider_using_in.txt
Labels: enhancement

#4970 Make ``min-similarity-lines == 0`` stop similarity check
  ChangeLog
  doc/whatsnew/2.11.rst
  pylint/checkers/similar.py
  tests/checkers/unittest_similar.py
Labels: enhancement

#4949 fix false positive W0238 with private staticmethod used from classmethod
  ChangeLog
  pylint/checkers/classes.py
  tests/functional/u/unused/unused_private_member.py
  tests/functional/u/unused/unused_private_member.txt
Labels: bug, false-positive

#4978 Use ``overload`` to type ``get_global_option``
  pylint/extensions/code_style.py
  pylint/extensions/typing.py
  pylint/utils/utils.py
Labels: maintenance

#4988 Fix bug with cache's parent directory not existing
  ChangeLog
  doc/whatsnew/2.11.rst
  pylint/config/__init__.py
Labels: bug

#4986 Fix no-self-use and docparams extension for async functions/methods
  CONTRIBUTORS.txt
  ChangeLog
  pylint/checkers/classes.py
  pylint/extensions/docparams.py
  tests/functional/a/assign/assignment_from_no_return_py3.py
  tests/functional/ext/docparams.py
  tests/functional/ext/docparams.txt
  tests/functional/n/no/no_self_use.py
  tests/functional/n/no/no_self_use.txt
Labels: false negative

#4990 Make ``global-variable-not-assigned`` check local scope
  ChangeLog
  doc/whatsnew/2.11.rst
  pylint/checkers/utils.py
  pylint/checkers/variables.py
  tests/functional/g/globals.py
  tests/functional/g/globals.txt
  tests/functional/u/unused/unused_variable.py
  tests/functional/u/unused/unused_variable.txt
Labels: bug, false negative

#4992 Documentation for ``pyreverse`` and ``symilar``
  ChangeLog
  doc/additional_commands/index.rst
  doc/index.rst
  doc/media/ClassChecker_diagram.png
  doc/media/pyreverse_example_classes.png
  doc/media/pyreverse_example_packages.png
Labels: topic-pyreverse, documentation

#5001 Fix false negative for use-symbolic-message
  ChangeLog
  pylint/message/message_id_store.py
  tests/functional/u/use/use_symbolic_message_instead.py
  tests/functional/u/use/use_symbolic_message_instead.txt
Labels: bug, false negative

#5002 Upgrade astroid to 2.8.0
  requirements_test_min.txt
  setup.cfg
Labels: maintenance

#5003 Pylint reporter cleanup
  pylint/reporters/ureports/__init__.py
  pylint/reporters/ureports/base_writer.py
  pylint/reporters/ureports/nodes.py
  tests/pyreverse/test_writer.py
Labels: maintenance

#4997 Make ``consider-iterating-dictionary`` consider memb. check
  ChangeLog
  doc/whatsnew/2.11.rst
  pylint/checkers/refactoring/recommendation_checker.py
  tests/functional/c/consider/consider_iterating_dictionary.py
  tests/functional/c/consider/consider_iterating_dictionary.txt
Labels: enhancement

#4965 Fix false positive ``unused-private-member`` for accessing attributes in a class using ``cls``
  ChangeLog
  doc/whatsnew/2.11.rst
  pylint/checkers/classes.py
  tests/functional/u/unused/unused_private_member.py
  tests/functional/u/unused/unused_private_member.txt
Labels: false-positive

#5006 Fix deprecation warning for AssignAttr in tests
  tests/checkers/unittest_stdlib.py
Labels: maintenance

#5009 Change `lines` to lists
  pylint/checkers/base.py
  pylint/checkers/raw_metrics.py
  pylint/lint/report_functions.py
Labels: maintenance

#5010 Fix PyreverseConfig imports in pyreverse's tests
  setup.cfg
  tests/pyreverse/test_diadefs.py
  tests/pyreverse/test_writer.py
Labels: maintenance

#4995 Remove most `typing.cast()` calls
  pylint/checkers/classes.py
  pylint/checkers/refactoring/recommendation_checker.py
  pylint/checkers/refactoring/refactoring_checker.py
Labels: maintenance, requires astroid update

#4973 Add typing to all calls to ``self.stats``
  pylint/checkers/__init__.py
  pylint/checkers/base.py
  pylint/checkers/base_checker.py
  pylint/checkers/design_analysis.py
  pylint/checkers/imports.py
  pylint/checkers/raw_metrics.py
  pylint/checkers/similar.py
  pylint/lint/parallel.py
  pylint/lint/pylinter.py
  pylint/lint/report_functions.py
  pylint/reporters/base_reporter.py
  pylint/reporters/multi_reporter.py
  pylint/reporters/reports_handler_mix_in.py
  pylint/reporters/ureports/nodes.py
  pylint/testutils/unittest_linter.py
  pylint/typing.py
  tests/lint/unittest_lint.py
  tests/test_check_parallel.py
  tests/test_regr.py
Labels: maintenance

#5013 Move PyreverseConfig to pylint.testutil
  pylint/testutils/pyreverse.py
  tests/pyreverse/conftest.py
  tests/pyreverse/test_diadefs.py
  tests/pyreverse/test_writer.py
Labels: maintenance

#5015 Move methods to `BaseLayout`
  pylint/checkers/imports.py
  pylint/reporters/ureports/nodes.py
Labels: maintenance

#5004 Add typing in ``pylint.reporters``
  pylint/checkers/__init__.py
  pylint/checkers/imports.py
  pylint/interfaces.py
  pylint/lint/report_functions.py
  pylint/reporters/__init__.py
  pylint/reporters/collecting_reporter.py
  pylint/reporters/multi_reporter.py
  pylint/reporters/reports_handler_mix_in.py
  pylint/reporters/ureports/base_writer.py
  pylint/reporters/ureports/nodes.py
  pylint/reporters/ureports/text_writer.py
Labels: maintenance

#4980 Add typing to ``filepath``
  pylint/config/option_manager_mixin.py
  pylint/lint/expand_modules.py
  pylint/lint/parallel.py
  pylint/lint/pylinter.py
  pylint/lint/utils.py
  pylint/reporters/base_reporter.py
  pylint/reporters/multi_reporter.py
  pylint/reporters/text.py
  pylint/testutils/reporter_for_tests.py
  pylint/typing.py
  tests/benchmark/test_baseline_benchmarks.py
  tests/checkers/unittest_variables.py
  tests/extensions/test_broad_try_clause.py
  tests/extensions/test_comparetozero.py
  tests/lint/test_utils.py
  tests/lint/unittest_lint.py
  tests/test_check_parallel.py
  tests/test_import_graph.py
  tests/test_regr.py
  tests/unittest_reporting.py
Labels: maintenance

#5020 Fix ``unspecified-encoding`` for `Path()`
  ChangeLog
  pylint/checkers/stdlib.py
  tests/functional/u/unspecified_encoding_py38.py
  tests/functional/u/unspecified_encoding_py38.txt
Labels: bug, false-positive

#5021 Add typing for ``json_reporter`` and sub-classes
  pylint/interfaces.py
  pylint/reporters/base_reporter.py
  pylint/reporters/collecting_reporter.py
  pylint/reporters/json_reporter.py
  pylint/reporters/multi_reporter.py
  pylint/reporters/text.py
  pylint/testutils/reporter_for_tests.py
  tests/extensions/test_broad_try_clause.py
  tests/extensions/test_comparetozero.py
  tests/test_self.py
  tests/unittest_reporting.py
Labels: maintenance

#5027 Spelling and grammar fixes
  .github/ISSUE_TEMPLATE/BUG-REPORT.yml
  ChangeLog
  doc/how_tos/custom_checkers.rst
  doc/whatsnew/1.7.rst
  doc/whatsnew/2.2.rst
  pylint/checkers/base.py
  pylint/checkers/classes.py
  pylint/checkers/format.py
  pylint/checkers/refactoring/refactoring_checker.py
  pylint/checkers/similar.py
  pylint/checkers/typecheck.py
  pylint/checkers/variables.py
  pylint/extensions/code_style.py
  pylint/extensions/consider_ternary_expression.py
  pylint/extensions/mccabe.py
  pylint/extensions/typing.py
  pylint/utils/pragma_parser.py
  tests/benchmark/test_baseline_benchmarks.py
  tests/extensions/data/broad_try_clause.py
  tests/extensions/test_check_docs.py
  tests/functional/a/abstract/abstract_method.py
  tests/functional/a/access/access_member_before_definition.py
  tests/functional/a/arguments.py
  tests/functional/a/arguments_out_of_order.py
  tests/functional/b/bad_reversed_sequence.py
  tests/functional/c/classes_meth_could_be_a_function.py
  tests/functional/c/continue_in_finally.py
  tests/functional/d/deprecated/dataclass_typecheck.py
  tests/functional/ext/code_style/code_style_consider_using_assignment_expr.py
  tests/functional/i/invalid/s/invalid_sequence_index.py
  tests/functional/l/long_utf8_lines.py
  tests/functional/n/no/no_member_if_statements.py
  tests/functional/n/non/non_iterator_returned.py
  tests/functional/p/pattern_matching.py
  tests/functional/r/return_outside_function.py
  tests/functional/s/string/string_formatting.py
  tests/functional/u/undefined/undefined_variable.py
  tests/functional/u/useless/useless_else_on_loop.py
  tests/functional/y/yield_from_outside_func.py
  tests/functional/y/yield_outside_func.py
  tests/input/func_w0801.py
  tests/input/w0801_same.py
  tests/lint/unittest_lint.py
  tests/pyreverse/test_diadefs.py
  tests/test_self.py
Labels: documentation

#5026 py-version-check help fixes
  pylint/lint/pylinter.py
Labels: documentation

#5028 Fix typing of `ReportsHandlerMixIn`
  pylint/reporters/reports_handler_mix_in.py
Labels: maintenance

#5033 Fix ``unspecified-encoding`` for ``Path.read_text()``
  ChangeLog
  pylint/checkers/stdlib.py
  tests/functional/u/unspecified_encoding_py38.py
  tests/functional/u/unspecified_encoding_py38.txt
Labels: bug, false-positive

#5034 Add ``flynt`` to 2.11 changelog
  doc/whatsnew/2.11.rst
Labels: documentation

#5035 Add typing to `lint_module_test`
  pylint/testutils/lint_module_test.py
Labels: maintenance

#5023 Add typing to `BaseReporter.out`
  pylint/reporters/base_reporter.py
  tests/test_self.py
Labels: maintenance

#5043 Rename `pylint.testutil.Message` to `pylint.testutil.TestMessage`
  pylint/testutils/__init__.py
  pylint/testutils/output_line.py
  pylint/testutils/unittest_linter.py
  tests/checkers/unittest_base.py
  tests/checkers/unittest_classes.py
  tests/checkers/unittest_deprecated.py
  tests/checkers/unittest_exceptions.py
  tests/checkers/unittest_format.py
  tests/checkers/unittest_imports.py
  tests/checkers/unittest_logging.py
  tests/checkers/unittest_misc.py
  tests/checkers/unittest_spelling.py
  tests/checkers/unittest_stdlib.py
  tests/checkers/unittest_strings.py
  tests/checkers/unittest_typecheck.py
  tests/checkers/unittest_variables.py
  tests/extensions/test_check_docs.py
  tests/extensions/test_check_raise_docs.py
  tests/extensions/test_check_return_docs.py
  tests/extensions/test_check_yields_docs.py
  tests/extensions/test_confusing_elif.py
  tests/extensions/test_while_used.py
Labels: maintenance

#5005 Use node_ancestors to get rid of some while-loops
  .gitignore
  pylint/checkers/base.py
  pylint/checkers/refactoring/refactoring_checker.py
  pylint/checkers/utils.py
Labels: maintenance

#5046 Remove `safe_decode()` and `deprecated_option()` from utils
  pylint/utils/__init__.py
  pylint/utils/utils.py
Labels: maintenance

#5049 Add typing to `FileState`
  pylint/utils/file_state.py
Labels: maintenance

#5051 Rename `TestMessage` to `MessageTest`
  pylint/testutils/__init__.py
  pylint/testutils/output_line.py
  pylint/testutils/unittest_linter.py
  tests/checkers/unittest_base.py
  tests/checkers/unittest_classes.py
  tests/checkers/unittest_deprecated.py
  tests/checkers/unittest_exceptions.py
  tests/checkers/unittest_format.py
  tests/checkers/unittest_imports.py
  tests/checkers/unittest_logging.py
  tests/checkers/unittest_misc.py
  tests/checkers/unittest_spelling.py
  tests/checkers/unittest_stdlib.py
  tests/checkers/unittest_strings.py
  tests/checkers/unittest_typecheck.py
  tests/checkers/unittest_variables.py
  tests/extensions/test_check_docs.py
  tests/extensions/test_check_raise_docs.py
  tests/extensions/test_check_return_docs.py
  tests/extensions/test_check_yields_docs.py
  tests/extensions/test_confusing_elif.py
  tests/extensions/test_while_used.py
Labels: maintenance

#5045 Fix bug with cell-var-from-loop and kw_defaults
  ChangeLog
  pylint/checkers/utils.py
  tests/functional/c/cellvar_escaping_loop.py
  tests/functional/c/cellvar_escaping_loop.txt
Labels: bug

#5041 Add typing to text reporter
  pylint/reporters/base_reporter.py
  pylint/reporters/text.py
Labels: maintenance

#5055 ``Consider-using-f-string`` skips `format()` with backslash
  ChangeLog
  pylint/checkers/refactoring/recommendation_checker.py
  tests/functional/c/consider/consider_using_f_string.py
  tests/functional/c/consider/consider_using_f_string.txt
Labels: false-positive

#5044 Fix false-positive undefined-variable with Lambda, IfExp, and :=
  ChangeLog
  pylint/checkers/variables.py
  tests/functional/a/assign/assignment_expression.py
Labels: false-positive, walrus operator

#5050 Type `add_message` and add `MessageLocationTuple`
  pylint/checkers/base_checker.py
  pylint/message/message.py
  pylint/message/message_handler_mix_in.py
  pylint/testutils/unittest_linter.py
  pylint/typing.py
  tests/message/unittest_message.py
  tests/testutils/test_output_line.py
Labels: maintenance

#5064 Refactor of ``FileState.handle_ignored_message()``
  pylint/message/message_handler_mix_in.py
  pylint/utils/file_state.py
Labels: maintenance

#5063 Fix ``useless-suppression`` for ``wrong-import-order``
  ChangeLog
  pylint/checkers/imports.py
  pylint/message/message_handler_mix_in.py
  tests/functional/u/useless/useless_suppression.py
Labels: bug, false-positive

#5067 Update toml dependency to >=0.9.2
  CONTRIBUTORS.txt
  ChangeLog
  pylint/config/find_default_config_files.py
  setup.cfg
Labels: crash, dependency

#5060 Refactor and typing of OutputLine
  pylint/testutils/output_line.py
  tests/testutils/test_output_line.py
Labels: maintenance

#5062 Fix loop in too-many-ancestors when an inheritance cycle is inferred
  pylint/checkers/design_analysis.py
  tests/regrtest_data/hang/pkg4972/__init__.py
  tests/regrtest_data/hang/pkg4972/string/__init__.py
  tests/test_regr.py
Labels: bug, topic-performance

#4954 Typing for ``./pylint``, batch 1
  pylint/reporters/base_reporter.py
  pylint/testutils/tokenize_str.py
  pylint/utils/pragma_parser.py
Labels: maintenance

#5069 Small py-version improvements
  pylint/checkers/refactoring/recommendation_checker.py
  pylint/config/option.py
  pylint/extensions/code_style.py
  pylint/utils/utils.py
Labels: documentation

#5076 Remove ``pytest`` marks in test_regr
  tests/test_regr.py
Labels: maintenance

#5079 Fix ``invalid-name`` for overwritten base ``object`` methods
  ChangeLog
  pylint/checkers/utils.py
  tests/functional/i/invalid/invalid_name.py
  tests/functional/i/invalid/invalid_name.txt
Labels: false negative

#5077 Fix false-positive ``useless-suppression`` for ``line-too-long``
  ChangeLog
  pylint/checkers/format.py
  pylint/message/message_handler_mix_in.py
  tests/functional/u/useless/useless_suppression.py
Labels: false-positive

#5093 Fix empty regex options not converting to regex
  pylint/config/option.py
  pylint/utils/utils.py
  tests/extensions/test_check_docs.py
Labels: bug
