Repository pylint-dev/pylint, pull requests merged in 2021-12, with the labels that each got.

#5241 Refactor of ``visit_name`` for ``variables``
  pylint/checkers/variables.py
Labels: maintenance, C: undefined-variable

#5454 Fix false positive for ``used-before-assignment`` for vars in methods
  ChangeLog
  pylint/checkers/variables.py
  tests/functional/u/use/used_before_assignment.py
  tests/functional/u/use/used_before_assignment.txt
  tests/functional/u/use/used_before_assignment_typing.py
  tests/functional/u/use/used_before_assignment_typing.txt
Labels: regression, false-positive, C: undefined-variable

#5455 Move various tests from ``TestTypeChecker`` to functional tests
  tests/checkers/unittest_typecheck.py
  tests/functional/i/invalid/m/invalid_metaclass.py
  tests/functional/i/invalid/m/invalid_metaclass.txt
  tests/functional/n/not_callable.py
  tests/functional/n/not_callable.txt
  tests/functional/u/unsubscriptable_object.py
Labels: maintenance

#5459 #5452: Fix false positive missing-doc-param from multi-line Google-st…
  CONTRIBUTORS.txt
  ChangeLog
  pylint/extensions/_check_docs_utils.py
  tests/functional/ext/docparams/parameter/missing_param_doc_required_Google.py
  tests/functional/ext/docparams/parameter/missing_param_doc_required_Google.rc
Labels: false-positive

#5453 Move ``no-member`` tests from ``TestTypeChecker``
  tests/checkers/unittest_typecheck.py
  tests/functional/n/no/no_member_imports.py
  tests/functional/n/no/no_member_imports.rc
  tests/functional/n/no/no_member_imports.txt
Labels: maintenance

#5450 Move Sphinx docstrings out of ``TestParamDocChecker``
  tests/extensions/test_check_docs.py
  tests/functional/ext/docparams/parameter/missing_param_doc_required_Sphinx.py
  tests/functional/ext/docparams/parameter/missing_param_doc_required_Sphinx.rc
  tests/functional/ext/docparams/parameter/missing_param_doc_required_Sphinx.txt
  tests/functional/ext/docparams/raise/missing_raises_doc_Sphinx.py
  tests/functional/ext/docparams/raise/missing_raises_doc_Sphinx.txt
  tests/functional/ext/docparams/return/missing_return_doc_Sphinx.py
  tests/functional/ext/docparams/return/missing_return_doc_Sphinx.txt
  tests/functional/ext/docparams/return/missing_return_doc_required_Sphinx.py
  tests/functional/ext/docparams/return/missing_return_doc_required_Sphinx.txt
Labels: maintenance

#5449 Update outdated class name in "How to Write a Checker" test example
  CONTRIBUTORS.txt
  doc/how_tos/custom_checkers.rst
Labels: documentation

#5456 Add endLine and endColumn keys to JSONReporter
  ChangeLog
  doc/whatsnew/2.12.rst
  pylint/reporters/json_reporter.py
  tests/unittest_reporters_json.py
  tests/unittest_reporting.py
Labels: enhancement

#5447 Deprecate ``is_inside_lambda`` from utils
  pylint/checkers/refactoring/recommendation_checker.py
  pylint/checkers/utils.py
  pylint/checkers/variables.py
  tests/checkers/unittest_utils.py
Labels: maintenance

#5464 Require ``\`` for asterisks in Sphinx-style parameter docstrings
  ChangeLog
  pylint/extensions/_check_docs_utils.py
  pylint/reporters/text.py
  tests/functional/ext/docparams/parameter/missing_param_doc_required_Sphinx.py
  tests/functional/ext/docparams/parameter/missing_param_doc_required_Sphinx.txt
Labels: regression, false-positive

#5272 Add mermaidjs as format output for pyreverse
  .pre-commit-config.yaml
  ChangeLog
  doc/additional_commands/index.rst
  doc/whatsnew/2.13.rst
  pylint/pyreverse/main.py
  pylint/pyreverse/mermaidjs_printer.py
  pylint/pyreverse/printer_factory.py
  tests/pyreverse/conftest.py
  tests/pyreverse/data/classes_No_Name.html
  tests/pyreverse/data/classes_No_Name.mmd
  tests/pyreverse/data/packages_No_Name.html
  tests/pyreverse/data/packages_No_Name.mmd
  tests/pyreverse/test_writer.py
Labels: enhancement, topic-pyreverse

#5344 fix(4716): fix false positive `unnecessary_dict_index_lookup` emitted when `del` is used
  ChangeLog
  doc/whatsnew/2.13.rst
  pylint/checkers/refactoring/refactoring_checker.py
  tests/functional/u/unnecessary/unnecessary_dict_index_lookup.py
  tests/functional/u/unnecessary/unnecessary_dict_index_lookup.txt
Labels: false-positive

#5443 Docker: Python 3.10 and Alpine 3.15
  CONTRIBUTORS.txt
  Dockerfile
Labels: enhancement

#5325 Add typing to ``PyLinter.reporter``
  ChangeLog
  doc/whatsnew/2.13.rst
  pylint/lint/pylinter.py
  pylint/reporters/multi_reporter.py
  tests/test_self.py
  tests/unittest_reporting.py
Labels: enhancement, maintenance

#5412 Fix #5371: Correctly count arguments to static methods missing @staticmethod decorator
  ChangeLog
  pylint/checkers/classes.py
  pylint/checkers/mapreduce_checker.py
  tests/functional/a/arguments_differ.py
  tests/functional/a/arguments_differ.txt
  tests/functional/a/arguments_differ_issue5371.py
  tests/test_check_parallel.py
Labels: bug, false-positive

#5468 Add tempfile.TemporaryFile to CALLS_RETURNING_CONTEXT_MANAGERS
  pylint/checkers/refactoring/refactoring_checker.py
Labels: enhancement

#5473 Revert renaming extension tests
  tests/functional/ext/code_style/cs_consider_using_assignment_expr.py
  tests/functional/ext/code_style/cs_consider_using_assignment_expr.rc
  tests/functional/ext/code_style/cs_consider_using_assignment_expr.txt
  tests/functional/ext/code_style/cs_consider_using_namedtuple_or_dataclass.py
  tests/functional/ext/code_style/cs_consider_using_namedtuple_or_dataclass.rc
  tests/functional/ext/code_style/cs_consider_using_namedtuple_or_dataclass.txt
  tests/functional/ext/code_style/cs_consider_using_tuple.py
  tests/functional/ext/code_style/cs_consider_using_tuple.rc
  tests/functional/ext/code_style/cs_consider_using_tuple.txt
  tests/functional/ext/code_style/cs_py_version_35.py
  tests/functional/ext/code_style/cs_py_version_35.rc
  tests/functional/ext/code_style/py_version_35.py
  tests/functional/ext/typing/typing_consider_using_alias.py
  tests/functional/ext/typing/typing_consider_using_alias.rc
  tests/functional/ext/typing/typing_consider_using_alias.txt
  tests/functional/ext/typing/typing_consider_using_alias_without_future.py
  tests/functional/ext/typing/typing_consider_using_alias_without_future.rc
  tests/functional/ext/typing/typing_consider_using_alias_without_future.txt
  tests/functional/ext/typing/typing_consider_using_union.py
  tests/functional/ext/typing/typing_consider_using_union.rc
  tests/functional/ext/typing/typing_consider_using_union.txt
  tests/functional/ext/typing/typing_consider_using_union_py310.py
  tests/functional/ext/typing/typing_consider_using_union_py310.rc
  tests/functional/ext/typing/typing_consider_using_union_py310.txt
  tests/functional/ext/typing/typing_consider_using_union_without_future.py
  tests/functional/ext/typing/typing_consider_using_union_without_future.rc
  tests/functional/ext/typing/typing_consider_using_union_without_future.txt
  tests/functional/ext/typing/typing_deprecated_alias.py
  tests/functional/ext/typing/typing_deprecated_alias.rc
  tests/functional/ext/typing/typing_deprecated_alias.txt
  tests/functional/p/py_version_35.py
  tests/functional/p/py_version_35.rc
Labels: maintenance

#5346 Treat `typing.NamedTuple` self as a sequence
  ChangeLog
  pylint/checkers/variables.py
  tests/functional/u/unbalanced_tuple_unpacking.py
  tests/functional/u/unbalanced_tuple_unpacking.txt
  tests/functional/u/unpacking_non_sequence.py
  tests/functional/u/unpacking_non_sequence.txt
Labels: bug, false-positive

#5484 Move tests for Google docstrings from ``TestParamDocChecker`` to functional tests
  tests/extensions/test_check_docs.py
  tests/functional/ext/docparams/parameter/missing_param_doc_required_Google.py
  tests/functional/ext/docparams/parameter/missing_param_doc_required_Google.rc
  tests/functional/ext/docparams/parameter/missing_param_doc_required_Google.txt
  tests/functional/ext/docparams/raise/missing_raises_doc_Google.py
  tests/functional/ext/docparams/raise/missing_raises_doc_Google.txt
  tests/functional/ext/docparams/return/missing_return_doc_Google.py
  tests/functional/ext/docparams/return/missing_return_doc_Google.txt
  tests/functional/ext/docparams/return/missing_return_doc_required_Google.py
  tests/functional/ext/docparams/return/missing_return_doc_required_Google.txt
Labels: maintenance

#5492 Move some of the Numpy tests out of ``TestParamDocChecker``
  tests/extensions/test_check_docs.py
  tests/functional/ext/docparams/parameter/missing_param_doc_required_Numpy.py
  tests/functional/ext/docparams/parameter/missing_param_doc_required_Numpy.rc
  tests/functional/ext/docparams/parameter/missing_param_doc_required_Numpy.txt
  tests/functional/ext/docparams/return/missing_return_doc_Numpy.py
  tests/functional/ext/docparams/return/missing_return_doc_Numpy.txt
Labels: maintenance

#5402 Fix #4761: Emit `used-before-assignment` where single assignment only made in except blocks
  ChangeLog
  doc/whatsnew/2.13.rst
  pylint/checkers/variables.py
  pylintrc
  tests/functional/u/undefined/undefined_variable.py
  tests/functional/u/undefined/undefined_variable.txt
  tests/functional/u/use/used_before_assignment_issue4761.py
  tests/functional/u/use/used_before_assignment_issue4761.txt
  tests/lint/test_utils.py
Labels: bug, topic-control-flow, false negative

#5505 Fix #5504: Fix crash if the output of items() is assigned to a 1-tuple
  ChangeLog
  doc/whatsnew/2.13.rst
  pylint/checkers/refactoring/refactoring_checker.py
  tests/functional/u/unnecessary/unnecessary_dict_index_lookup.py
Labels: blocker, crash

#5498 Fix incorrect classification of property docstrings in Numpy-style
  ChangeLog
  doc/whatsnew/2.13.rst
  pylint/extensions/_check_docs_utils.py
  pylint/extensions/docparams.py
  tests/extensions/test_check_docs.py
  tests/functional/ext/docparams/raise/missing_raises_doc_Numpy.py
  tests/functional/ext/docparams/raise/missing_raises_doc_Numpy.txt
Labels: bug, false-positive, maintenance

#5507 Move ``Numpy`` test from ``TestParamDocChecker`` to functional tests
  tests/extensions/test_check_docs.py
  tests/functional/ext/docparams/raise/missing_raises_doc_Numpy.py
  tests/functional/ext/docparams/raise/missing_raises_doc_Numpy.txt
  tests/functional/ext/docparams/return/missing_return_doc_required_Numpy.py
  tests/functional/ext/docparams/return/missing_return_doc_required_Numpy.txt
Labels: maintenance

#5384 Fix #85, #2615: Emit `used-before-assignment` in final or except blocks where try statements could have failed
  ChangeLog
  doc/whatsnew/2.13.rst
  pylint/checkers/variables.py
  tests/functional/u/use/used_before_assignment_issue2615.py
  tests/functional/u/use/used_before_assignment_issue2615.txt
  tests/functional/u/use/used_before_assignment_issue85.py
  tests/functional/u/use/used_before_assignment_issue85.txt
Labels: enhancement, topic-control-flow

#5509 Move tests from ``TestParamDocChecker`` to functional tests
  tests/extensions/test_check_docs.py
  tests/functional/ext/docparams/parameter/missing_param_doc.py
  tests/functional/ext/docparams/parameter/missing_param_doc.rc
  tests/functional/ext/docparams/parameter/missing_param_doc_required.py
  tests/functional/ext/docparams/parameter/missing_param_doc_required.rc
  tests/functional/ext/docparams/parameter/missing_param_doc_required.txt
  tests/functional/ext/docparams/parameter/missing_param_doc_required_min_length.py
  tests/functional/ext/docparams/parameter/missing_param_doc_required_min_length.rc
  tests/functional/ext/docparams/parameter/missing_param_doc_required_no_doc_rgx_check_init.py
  tests/functional/ext/docparams/parameter/missing_param_doc_required_no_doc_rgx_check_init.rc
  tests/functional/ext/docparams/parameter/missing_param_doc_required_no_doc_rgx_check_init.txt
  tests/functional/ext/docparams/parameter/missing_param_doc_required_no_doc_rgx_check_none.py
  tests/functional/ext/docparams/parameter/missing_param_doc_required_no_doc_rgx_check_none.rc
  tests/functional/ext/docparams/parameter/missing_param_doc_required_no_doc_rgx_default.py
  tests/functional/ext/docparams/parameter/missing_param_doc_required_no_doc_rgx_default.rc
  tests/functional/ext/docparams/parameter/missing_param_doc_required_no_doc_rgx_test_all.py
  tests/functional/ext/docparams/parameter/missing_param_doc_required_no_doc_rgx_test_all.rc
  tests/functional/ext/docparams/parameter/missing_param_doc_required_no_doc_rgx_test_all.txt
  tests/functional/ext/docparams/raise/missing_raises_doc.py
  tests/functional/ext/docparams/raise/missing_raises_doc.txt
Labels: maintenance

#5511 Add a DeprecationWarning to set_config_directly
  pylint/testutils/decorator.py
  tests/testutils/test_decorator.py
Labels: maintenance

#5512 Style - Remove unrelated error in tests for unnecessary-dict-index
  tests/functional/u/unnecessary/unnecessary_dict_index_lookup.py
  tests/functional/u/unnecessary/unnecessary_dict_index_lookup.txt
Labels: maintenance

#5510 Unify validation of functional test option files
  pylint/testutils/functional/test_file.py
  pylint/testutils/lint_module_test.py
Labels: maintenance

#5518 Remove redundant tests in ``TestWhileUsed``
  tests/extensions/test_while_used.py
Labels: maintenance

#5520 Move tests from ``TestComparison`` to functional tests
  tests/checkers/unittest_base.py
  tests/functional/n/nan_comparison_check.py
  tests/functional/n/nan_comparison_check.txt
  tests/functional/s/singleton_comparison.py
  tests/functional/s/singleton_comparison.txt
Labels: maintenance

#5517 Move tests from ``TestConfusingConsecutiveElifChecker`` to functional tests
  tests/extensions/test_confusing_elif.py
  tests/functional/ext/confusing_elif/confusing_elif.py
  tests/functional/ext/confusing_elif/confusing_elif.txt
Labels: maintenance

#5470 New checker - Detect use of unnecessary ellipsis
  ChangeLog
  doc/whatsnew/2.13.rst
  pylint/checkers/ellipsis_checker.py
  tests/functional/c/class_members.py
  tests/functional/s/statement_without_effect.py
  tests/functional/t/too/too_few_public_methods_excluded.py
  tests/functional/u/unnecessary/unnecessary_ellipsis.py
  tests/functional/u/unnecessary/unnecessary_ellipsis.txt
Labels: enhancement, checkers

#5383 Check `node` location attributes in unittests
  ChangeLog
  doc/whatsnew/2.13.rst
  pylint/testutils/checker_test_case.py
  pylint/testutils/output_line.py
  pylint/testutils/unittest_linter.py
  tests/checkers/unittest_base.py
  tests/checkers/unittest_deprecated.py
  tests/checkers/unittest_imports.py
  tests/checkers/unittest_typecheck.py
  tests/checkers/unittest_variables.py
Labels: enhancement, maintenance

#5519 Modify the description of HIGH confidence in pylint.interfaces
  pylint/interfaces.py
Labels: maintenance

#5409 Fix #3675: `safe_infer()` finds ambiguity among function definitions when number of arguments differ
  ChangeLog
  pylint/checkers/utils.py
  tests/functional/c/consider/consider_using_with.py
  tests/functional/c/consider/consider_using_with.txt
  tests/functional/t/too/too_many_function_args.py
Labels: false-positive

#5417 typecheck: simplify variadic positional detection, fixing some false positives
  CONTRIBUTORS.txt
  ChangeLog
  pylint/checkers/typecheck.py
  tests/functional/r/regression/regression_no_value_for_parameter.py
Labels: bug, false-positive

#5521 Fix #5451: Produce a score of 0 for fatal errors
  ChangeLog
  doc/faq.rst
  doc/whatsnew/2.13.rst
  examples/pylintrc
  pylint/lint/pylinter.py
  pylintrc
  tests/test_self.py
Labels: bug

#5278 Enable missing-raises-doc to understand class hierarchies
  ChangeLog
  doc/whatsnew/2.13.rst
  pylint/extensions/_check_docs_utils.py
  pylint/extensions/docparams.py
  tests/extensions/test_check_docs_utils.py
  tests/functional/ext/docparams/raise/missing_raises_doc_required_exc_inheritance.py
  tests/functional/ext/docparams/raise/missing_raises_doc_required_exc_inheritance.rc
  tests/functional/ext/docparams/raise/missing_raises_doc_required_exc_inheritance.txt
Labels: false-positive

#5525 Update typing of reporter attributes in ``PyLinter``
  pylint/lint/pylinter.py
  pylint/reporters/base_reporter.py
Labels: maintenance

#5523 Add additional test cases used-before-assignment with try-except
  tests/functional/u/use/used_before_assignment_except_handler_for_try_with_return.py
  tests/functional/u/use/used_before_assignment_except_handler_for_try_with_return.txt
Labels: regression, maintenance

#5457 Fix assigning-non-slot false positive with setattr
  CONTRIBUTORS.txt
  ChangeLog
  doc/whatsnew/2.13.rst
  pylint/checkers/classes.py
  tests/functional/a/assign/assigning_non_slot.py
Labels: enhancement, topic-control-flow

#5535 Upgrade mypy to 0.920
  .pre-commit-config.yaml
  pylint/extensions/__init__.py
  pylint/reporters/__init__.py
  requirements_test_pre_commit.txt
  tests/config/unittest_config.py
Labels: task, dependency

#5310 Add ``future=True`` to all ``NodeNG.statement()`` calls
  pylint/checkers/base.py
  pylint/checkers/classes.py
  pylint/checkers/format.py
  pylint/checkers/typecheck.py
  pylint/checkers/utils.py
  pylint/checkers/variables.py
  tests/functional/r/regression_02/regression_node_statement.py
Labels: maintenance

#5540 Fix typos
  CONTRIBUTORS.txt
  ChangeLog
  doc/whatsnew/2.11.rst
  doc/whatsnew/2.12.rst
  doc/whatsnew/2.13.rst
  doc/whatsnew/2.7.rst
  examples/pylintrc
  pylint/checkers/format.py
  pylint/checkers/mapreduce_checker.py
  pylint/checkers/similar.py
  pylint/checkers/variables.py
  pylint/epylint.py
  pylint/extensions/_check_docs_utils.py
  pylint/lint/pylinter.py
  pylint/lint/run.py
  pylintrc
  tests/benchmark/test_baseline_benchmarks.py
  tests/functional/a/assign/assignment_from_no_return_2.py
  tests/functional/ext/docparams/parameter/missing_param_doc_required_Sphinx.py
  tests/functional/ext/docparams/yield/missing_yield_doc_Google.py
  tests/functional/ext/docparams/yield/missing_yield_doc_Numpy.py
  tests/functional/m/method_hidden.py
  tests/functional/n/not_callable.py
  tests/functional/o/overloaded_operator.py
  tests/functional/r/regression/regression_property_no_member_3269.py
  tests/functional/t/too/too_few_public_methods_excluded.py
  tests/functional/u/use/used_before_assignment_except_handler_for_try_with_return.py
  tests/functional/u/useless/useless_else_on_loop.py
  tests/functional/u/useless/useless_super_delegation.py
  tests/unittest_reporting.py
Labels: documentation

#5537 Fix ``not-callable`` for attributes that alias ``NamedTuple``
  ChangeLog
  doc/whatsnew/2.13.rst
  pylint/checkers/typecheck.py
  tests/functional/n/not_callable.py
  tests/functional/n/not_callable.txt
Labels: false-positive

#5550 Add regression test for issue #5382
  tests/functional/r/regression_02/regression_node_statement_two.py
Labels: Regression, Maintenance

#5549 Fix crash on uninferable decorators on Python 3.6 and 3.7
  ChangeLog
  doc/whatsnew/2.13.rst
  pylint/checkers/utils.py
  tests/functional/o/overridden_final_method_regression.py
  tests/functional/o/overridden_final_method_regression.txt
Labels: Crash 💥

#5548 Add typing to ``_determine_callable``
  pylint/checkers/typecheck.py
Labels: Maintenance

#5534 Fixed extremely long processing of long lines with comma's
  ChangeLog
  doc/whatsnew/2.13.rst
  pylint/checkers/refactoring/refactoring_checker.py
  tests/checkers/unittest_refactoring.py
  tests/regrtest_data/very_long_line.py
Labels: Enhancement ✨, topic-performance

#5531 Remove unnecessary `if` statement in variable consumption checker
  pylint/checkers/variables.py
Labels: Maintenance, C: used-before-assignment

#5532 Fix ``used-before-assignment`` for conditional self-referential typing
  ChangeLog
  doc/whatsnew/2.13.rst
  pylint/checkers/variables.py
  tests/functional/u/use/used_before_assignment_typing.py
Labels: False Positive, C: used-before-assignment

#5547 Check if decorator returns use keyword (``unexpected-keyword-arg``)
  ChangeLog
  doc/whatsnew/2.13.rst
  pylint/checkers/typecheck.py
  tests/functional/u/unexpected_keyword_arg.py
  tests/functional/u/unexpected_keyword_arg.txt
Labels: topic-decorators, False Positive

#5553 Update default evaluation formula to match that in default pylintrc
  pylint/lint/pylinter.py
Labels: task, Maintenance

#5554 Ignore files with name that starts like an emacs lock files
  ChangeLog
  doc/whatsnew/2.13.rst
  pylint/lint/expand_modules.py
  pylint/lint/pylinter.py
  pylint/testutils/configuration_test.py
  pylint/utils/linterstats.py
  tests/functional/e/.#emacs_file_lock.py
  tests/functional/e/.#emacs_file_lock_by_conf.py
  tests/functional/e/.#emacs_file_lock_by_conf.rc
  tests/functional/e/.#emacs_file_lock_redefined_conf.py
  tests/functional/e/.#emacs_file_lock_redefined_conf.rc
  tests/functional/e/.#emacs_file_lock_redefined_conf.txt
Labels: Emacs 💾, Downstream Bug 🪲

#5555 Fix unexpected types used in 'get_global_option'
  tests/lint/unittest_expand_modules.py
Labels: Minor 💅, Maintenance

#5566 Add requirement files to list of files to run primer against
  .github/workflows/primer-test.yaml
Labels: Maintenance

#5567 Revert "Update tbump requirement from ~=6.6.0 to ~=6.6.1"
  requirements_test.txt
Labels: dependency

#5556 Add missing settings to pylintrc
  pylintrc
Labels: Documentation 📖, Maintenance

#5573 Add typing to some functions in ``testutils``
  pylint/testutils/configuration_test.py
  pylint/testutils/functional/test_file.py
  pylint/testutils/get_test_info.py
Labels: Maintenance

#5563 Fix #5557: Don't emit `comparison-with-callable` if the callable raises
  ChangeLog
  doc/whatsnew/2.13.rst
  pylint/checkers/base.py
  tests/functional/c/comparison_with_callable.py
  tests/functional/c/comparison_with_callable_typing_constants.py
Labels: topic-typing, False Positive 🦟

#5530 Fix ``used-before-assignment`` for assignment expressions in lambda
  ChangeLog
  doc/whatsnew/2.13.rst
  pylint/checkers/variables.py
  tests/functional/u/undefined/undefined_variable_py38.py
Labels: False Positive 🦟, C: used-before-assignment

#5576 Add typing to file visiting attributes of ``PyLinter``
  pylint/lint/pylinter.py
Labels: Maintenance

#5574 Add typing to checker and plugin attributes of ``PyLinter``
  pylint/lint/pylinter.py
  pylint/reporters/reports_handler_mix_in.py
Labels: Maintenance

#5581 Rename ``init_linter`` fixture to ``initialized_linter``, add filename
  tests/lint/unittest_lint.py
Labels: Maintenance

#5577 Make an implicitely abtract class explicitely abstract and remove disable
  pylint/config/man_help_formatter.py
Labels: Maintenance

#5579 Add types to option attributes of ``PyLinter`` and reorganize ``init``
  pylint/lint/pylinter.py
Labels: Maintenance

#5575 Fix typos accross the whole codebase
  pylint/checkers/base.py
  pylint/checkers/base_checker.py
  pylint/checkers/design_analysis.py
  pylint/checkers/exceptions.py
  pylint/checkers/format.py
  pylint/checkers/refactoring/recommendation_checker.py
  pylint/checkers/strings.py
  pylint/checkers/typecheck.py
  pylint/checkers/utils.py
  pylint/checkers/variables.py
  pylint/config/configuration_mixin.py
  pylint/config/find_default_config_files.py
  pylint/config/option_manager_mixin.py
  pylint/epylint.py
  pylint/extensions/_check_docs_utils.py
  pylint/extensions/code_style.py
  pylint/extensions/comparetozero.py
  pylint/extensions/docparams.py
  pylint/extensions/emptystring.py
  pylint/extensions/redefined_variable_type.py
  pylint/extensions/typing.py
  pylint/interfaces.py
  pylint/lint/parallel.py
  pylint/lint/pylinter.py
  pylint/lint/run.py
  pylint/lint/utils.py
  pylint/pyreverse/diadefslib.py
  pylint/pyreverse/diagrams.py
  pylint/pyreverse/mermaidjs_printer.py
  pylint/reporters/multi_reporter.py
  pylint/reporters/ureports/base_writer.py
  pylint/reporters/ureports/nodes.py
  pylint/testutils/configuration_test.py
  pylint/testutils/output_line.py
  pylint/testutils/primer.py
  pylint/testutils/pyreverse.py
  pylint/utils/ast_walker.py
  pylint/utils/pragma_parser.py
  pylint/utils/utils.py
  script/fix_documentation.py
  tests/checkers/unittest_imports.py
  tests/checkers/unittest_spelling.py
  tests/checkers/unittest_stdlib.py
  tests/checkers/unittest_typecheck.py
  tests/config/test_functional_config_loading.py
  tests/message/unittest_message.py
  tests/primer/test_primer_stdlib.py
  tests/pyreverse/test_diadefs.py
  tests/test_functional.py
  tests/test_regr.py
  tests/unittest_reporting.py
Labels: Documentation 📖, Maintenance

#5589 Add a code of conduct from template
  CODE_OF_CONDUCT.md
Labels: Maintenance

#5592 Upgrade mypy to 0.930
  .pre-commit-config.yaml
  pylint/checkers/utils.py
  requirements_test_pre_commit.txt
Labels: dependency

#5591 Create ``_config_initialization`` util and use in functional tests
  pylint/config/config_initialization.py
  pylint/lint/run.py
  pylint/testutils/lint_module_test.py
  tests/testutils/data/init_hook.py
  tests/testutils/data/init_hook.rc
  tests/testutils/test_functional_testutils.py
Labels: Maintenance

#5597 Add documentation about profiling and performance analysis
  doc/development_guide/index.rst
  doc/development_guide/profiling.rst
Labels: Documentation 📖

#5602 Bump CI cache version
  .github/workflows/ci.yaml
Labels: Maintenance

#5558 Add typing and uniformize the checker registering in Pylinter
  doc/how_tos/custom_checkers.rst
  doc/how_tos/plugins.rst
  doc/how_tos/transform_plugins.rst
  examples/custom.py
  examples/custom_raw.py
  examples/deprecation_checker.py
  pylint/checkers/async.py
  pylint/checkers/base.py
  pylint/checkers/classes/__init__.py
  pylint/checkers/design_analysis.py
  pylint/checkers/ellipsis_checker.py
  pylint/checkers/exceptions.py
  pylint/checkers/format.py
  pylint/checkers/imports.py
  pylint/checkers/logging.py
  pylint/checkers/misc.py
  pylint/checkers/newstyle.py
  pylint/checkers/raw_metrics.py
  pylint/checkers/refactoring/__init__.py
  pylint/checkers/similar.py
  pylint/checkers/spelling.py
  pylint/checkers/stdlib.py
  pylint/checkers/strings.py
  pylint/checkers/threading_checker.py
  pylint/checkers/typecheck.py
  pylint/checkers/unsupported_version.py
  pylint/checkers/variables.py
  pylint/extensions/bad_builtin.py
  pylint/extensions/broad_try_clause.py
  pylint/extensions/check_docs.py
  pylint/extensions/check_elif.py
  pylint/extensions/code_style.py
  pylint/extensions/comparetozero.py
  pylint/extensions/comparison_placement.py
  pylint/extensions/confusing_elif.py
  pylint/extensions/consider_ternary_expression.py
  pylint/extensions/docparams.py
  pylint/extensions/docstyle.py
  pylint/extensions/empty_comment.py
  pylint/extensions/emptystring.py
  pylint/extensions/for_any_all.py
  pylint/extensions/mccabe.py
  pylint/extensions/overlapping_exceptions.py
  pylint/extensions/redefined_variable_type.py
  pylint/extensions/set_membership.py
  pylint/extensions/typing.py
  pylint/extensions/while_used.py
  pylint/lint/pylinter.py
  pylint/reporters/json_reporter.py
  pylint/reporters/reports_handler_mix_in.py
  pylint/reporters/text.py
  tests/checkers/unittest_similar.py
  tests/regrtest_data/dummy_plugin/dummy_plugin.py
Labels: Maintenance

#5596 Refactor message disabling and enabling
  pylint/lint/pylinter.py
Labels: topic-performance, Maintenance

#5601 Fix reported node for `unnecessary-comprehension`
  pylint/checkers/refactoring/refactoring_checker.py
  tests/functional/u/unnecessary/unnecessary_comprehension.py
  tests/functional/u/unnecessary/unnecessary_comprehension.txt
Labels: Enhancement ✨

#5594 Make functional tests always go through config initialization
  pylint/config/config_initialization.py
  pylint/testutils/lint_module_test.py
  pylint/testutils/testing_pylintrc
Labels: Maintenance

#5595 Fix #2399: Avoid negative scores by default
  ChangeLog
  doc/faq.rst
  doc/whatsnew/2.13.rst
  examples/pylintrc
  pylint/lint/pylinter.py
  pylintrc
  tests/test_self.py
  tests/unittest_reporting.py
Labels: Enhancement ✨

#5606 Get the msgids directly from the MessageIdStore
  pylint/lint/pylinter.py
Labels: Enhancement ✨, topic-performance

#5605 Add caching to bottlenecks in the message store
  pylint/lint/pylinter.py
  pylint/message/message_definition_store.py
  pylint/message/message_id_store.py
Labels: Enhancement ✨, topic-performance

#5611 Update CACHE_VERSION of primer, add comment and update paths
  .github/workflows/ci.yaml
  .github/workflows/primer-test.yaml
Labels: Maintenance

#5609 Use ``dill`` to pickle when run in parallel mode
  ChangeLog
  doc/whatsnew/2.13.rst
  pylint/lint/parallel.py
  setup.cfg
  tests/test_check_parallel.py
Labels: Maintenance

#5612 Use ``with`` statement in ``parallel.py``
  pylint/lint/parallel.py
  tests/test_check_parallel.py
Labels: Maintenance

#5590 Fix false positive `consider-using-dict-comprehension` when creating a dict using a list of tuple where key AND value vary depending on the same condition
  .copyrite_aliases
  ChangeLog
  doc/whatsnew/2.13.rst
  pylint/checkers/refactoring/refactoring_checker.py
  tests/functional/c/consider/consider_using_dict_comprehension.py
  tests/functional/c/consider/consider_using_dict_comprehension.txt
Labels: False Positive 🦟

#5613 Allow passing arguments when entry points are used as functions
  ChangeLog
  doc/user_guide/run.rst
  doc/whatsnew/2.13.rst
  pylint/__init__.py
  tests/test_pylint_runners.py
Labels: Enhancement ✨

#5619 Rename ``arguments`` to ``argv`` in entry point functions
  pylint/__init__.py
  tests/test_pylint_runners.py
Labels: Maintenance

#5616 Allow passing arguments if ``epylint`` entry point is used as function
  ChangeLog
  doc/whatsnew/2.13.rst
  pylint/__init__.py
  pylint/epylint.py
  tests/test_pylint_runners.py
Labels: Maintenance
