Repository pylint-dev/pylint, pull requests merged in 2021-11, with the labels that each got.

#5238 Use single worker if importing `multiprocessing.synchronize` fails
  CONTRIBUTORS.txt
  ChangeLog
  doc/whatsnew/2.12.rst
  pylint/lint/run.py
Labels: bug

#5245 Inspection for `with threading.Lock():`
  CONTRIBUTORS.txt
  ChangeLog
  doc/whatsnew/2.12.rst
  pylint/checkers/threading_checker.py
  tests/functional/u/useless/useless_with_lock.py
  tests/functional/u/useless/useless_with_lock.txt
Labels: enhancement, checkers

#5248 Add script to generate new message category id
  doc/development_guide/contribute.rst
  pylint/extensions/__init__.py
  script/get_unused_message_id_category.py
Labels: documentation

#5256 Remove unwanted non-breaking whitespaces in comment
  pylint/checkers/similar.py
  pylint/utils/pragma_parser.py
  tests/functional/p/protocol_classes.py
Labels: maintenance

#5257 Update ``coveralls`` requirement to ~=3.3
  requirements_test.txt
Labels: maintenance

#5252 Remove ``render: python`` from bug description
  .github/ISSUE_TEMPLATE/BUG-REPORT.yml
Labels: maintenance

#5262 Fix crash on checking private members on ``__class__``
  ChangeLog
  doc/whatsnew/2.12.rst
  pylint/checkers/classes.py
  tests/functional/u/unused/unused_private_member.py
Labels: crash

#5268 Make ``self-cls-assignment`` check tuple assignment
  ChangeLog
  doc/whatsnew/2.12.rst
  pylint/checkers/variables.py
  tests/functional/s/self/self_cls_assignment.py
  tests/functional/s/self/self_cls_assignment.txt
Labels: false negative

#5271 Create and use a function for module stats initialization
  pylint/lint/pylinter.py
  pylint/utils/linterstats.py
Labels: maintenance

#5277 Simplify toml handling by removing else after try
  pylint/config/option_manager_mixin.py
Labels: maintenance

#5165 Add checker `using-final-decorator-in-unsupported-version`
  ChangeLog
  doc/whatsnew/2.12.rst
  pylint/checkers/classes.py
  pylint/checkers/unsupported_version.py
  pylint/checkers/utils.py
  tests/functional/o/overridden_final_method_py38.py
  tests/functional/o/overridden_final_method_py38.txt
  tests/functional/s/subclassed_final_class_py38.py
  tests/functional/s/subclassed_final_class_py38.txt
  tests/functional/u/unsupported/unsupported_version_for_final.py
  tests/functional/u/unsupported/unsupported_version_for_final.rc
  tests/functional/u/unsupported/unsupported_version_for_final.txt
Labels: enhancement

#5284 Simplify ``test_can_read_toml_env_variable`` to work like other tests
  tests/config/file_to_lint.py
  tests/config/test_config.py
Labels: maintenance

#5292 Add documentation for adding ``pylint`` to ``pre-commit``
  doc/tutorial.rst
  doc/user_guide/index.rst
  doc/user_guide/pre-commit-integration.rst
Labels: documentation

#5267 Add tests for crash on assignment expressions in if statemenpytts
  ChangeLog
  doc/whatsnew/2.12.rst
  tests/functional/a/assign/assignment_expression.py
Labels: crash, requires astroid update

#5287 Create a framework of functional tests for configuration files
  pylint/config/option_manager_mixin.py
  pylint/config/option_parser.py
  pylint/testutils/configuration_test.py
  tests/config/conftest.py
  tests/config/functional/ini/pylintrc_with_message_control.ini
  tests/config/functional/ini/pylintrc_with_message_control.result.json
  tests/config/functional/setup_cfg/setup_cfg_with_message_control.cfg
  tests/config/functional/setup_cfg/setup_cfg_with_message_control.result.json
  tests/config/functional/toml/issue_4746/loaded_plugin_does_not_exists.out
  tests/config/functional/toml/issue_4746/loaded_plugin_does_not_exists.result.json
  tests/config/functional/toml/issue_4746/loaded_plugin_does_not_exists.toml
  tests/config/functional/toml/rich_types.result.json
  tests/config/functional/toml/rich_types.toml
  tests/config/functional/toml/toml_with_enable.result.json
  tests/config/functional/toml/toml_with_enable.toml
  tests/config/functional/toml/toml_with_message_control.result.json
  tests/config/functional/toml/toml_with_message_control.toml
  tests/config/test_config.py
  tests/config/test_functional_config_loading.py
  tests/lint/test_pylinter.py
  tests/lint/unittest_lint.py
  tests/message/unittest_message_definition_store.py
Labels: topic-configuration, maintenance

#5294 Make y/n validator case insensitive
  ChangeLog
  doc/whatsnew/2.12.rst
  pylint/config/option.py
Labels: enhancement

#5296 Fix ``accept-no-yields/return-doc`` for partially correct docstrings
  ChangeLog
  doc/whatsnew/2.12.rst
  pylint/extensions/docparams.py
  tests/extensions/test_check_docs.py
  tests/extensions/test_check_return_docs.py
  tests/extensions/test_check_yields_docs.py
Labels: bug, false-positive

#4720 Pylint fix for invalid TOML config
  CONTRIBUTORS.txt
  ChangeLog
  doc/whatsnew/2.12.rst
  pylint/config/option_manager_mixin.py
  pylint/lint/pylinter.py
  tests/config/functional/toml/issue_4580/correct_basic_name_group.toml
  tests/config/functional/toml/issue_4580/correct_import_preferred_module.toml
  tests/config/functional/toml/issue_4580/empty_list.out
  tests/config/functional/toml/issue_4580/empty_list.toml
  tests/config/functional/toml/issue_4580/invalid_data_for_basic.out
  tests/config/functional/toml/issue_4580/invalid_data_for_basic.toml
  tests/config/functional/toml/issue_4580/invalid_data_for_import.result.json
  tests/config/functional/toml/issue_4580/invalid_data_for_import.toml
  tests/config/functional/toml/issue_4580/rich_types.result.json
  tests/config/functional/toml/issue_4580/rich_types.toml
  tests/config/functional/toml/issue_4580/top_level_disable.out
  tests/config/functional/toml/issue_4580/top_level_disable.toml
Labels: topic-configuration, crash

#5260 Clarify syntax in pylint.lint example
  CONTRIBUTORS.txt
  doc/user_guide/run.rst
Labels: documentation

#5297 Add a whatsnew entry for python <3.6.2 incompatibility
  doc/whatsnew/2.12.rst
Labels: documentation, task

#5301 Fix user specific path in functional conf tests for tox
  pylint/testutils/configuration_test.py
  tests/config/test_functional_config_loading.py
Labels: bug, maintenance

#5298 Move ``misplaced-comparison-constant`` to optional extension
  ChangeLog
  doc/whatsnew/2.12.rst
  pylint/checkers/base.py
  pylint/extensions/comparison_placement.py
  pylintrc
  tests/checkers/unittest_base.py
  tests/extensions/data/compare_to_zero.py
  tests/functional/a/assert_on_tuple.py
  tests/functional/c/comparison_with_callable.py
  tests/functional/c/consider/consider_using_in.py
  tests/functional/e/excess_escapes.py
  tests/functional/m/misplaced_bare_raise.py
  tests/functional/m/misplaced_bare_raise.txt
  tests/functional/m/misplaced_comparison_constant.py
  tests/functional/m/misplaced_comparison_constant.rc
  tests/functional/n/nan_comparison_check.py
  tests/functional/s/singleton_comparison.py
  tests/functional/u/use/use_implicit_booleaness_not_len.py
  tests/functional/u/use/using_constant_test.py
Labels: enhancement, checkers

#5305 Fix crash for ``protected-access`` on (outer)-class traversal
  ChangeLog
  doc/whatsnew/2.12.rst
  pylint/checkers/classes.py
  tests/functional/r/regression_02/regression_protected_access.py
  tests/functional/r/regression_02/regression_protected_access.txt
Labels: crash

#5315 Add ``enable-all-extensions`` option
  ChangeLog
  doc/whatsnew/2.12.rst
  pylint/lint/run.py
  tests/test_self.py
Labels: enhancement, topic-command-line

#5324 Add casts to ``linter.reporter`` in tests
  tests/test_regr.py
Labels: maintenance

#5329 Add error codes to all ``type: ignore``
  pylint/checkers/base.py
  pylint/checkers/similar.py
  pylint/checkers/spelling.py
  pylint/checkers/utils.py
  pylint/config/option.py
  pylint/config/option_manager_mixin.py
  pylint/extensions/__init__.py
  pylint/lint/parallel.py
  pylint/lint/pylinter.py
  pylint/lint/run.py
  pylint/reporters/__init__.py
  pylint/reporters/reports_handler_mix_in.py
  pylint/testutils/output_line.py
  setup.cfg
  tests/lint/test_pylinter.py
  tests/test_func.py
  tests/test_pylint_runners.py
  tests/test_self.py
Labels: maintenance

#5330 use isorts black profile
  setup.cfg
Labels: maintenance

#5335 Update documentation for command-line output options and custom reporters
  doc/user_guide/output.rst
Labels: documentation

#5332 Fix crash on ``open()`` calls for non-string ``mode`` arguments
  ChangeLog
  doc/whatsnew/2.12.rst
  pylint/checkers/stdlib.py
  tests/functional/u/unspecified_encoding_py38.py
  tests/functional/u/unspecified_encoding_py38.txt
Labels: crash

#5351 Update functional test updater to print actual string
  pylint/testutils/output_line.py
  tests/test_functional.py
Labels: task

#5352 Revert "Update functional test updater to print actual string"
  pylint/testutils/output_line.py
  tests/test_functional.py
Labels: maintenance

#5353 Add accetpance tests in CI for python 3.8+ instead of launching manually at release
  .github/workflows/ci.yaml
  setup.cfg
  tbump.toml
  tests/acceptance/test_stdlib.py
  tests/primer/test_primer_stdlib.py
Labels: maintenance

#5355 Upgrade astroid to 2.9.0
  ChangeLog
  pylint/checkers/typecheck.py
  requirements_test_min.txt
  setup.cfg
  tests/functional/d/deprecated/dataclass_typecheck.txt
  tests/functional/i/invalid/s/invalid_slice_index.txt
Labels: dependency

#5354 Add tests `inherit-non-class` with subscriptable class
  ChangeLog
  tests/functional/i/inherit_non_class.py
  tests/functional/i/inherit_non_class.txt
Labels: false-positive, requires astroid update

#5339 Add regression test for #4982
  tests/functional/r/regression_02/regression_4982.py
Labels: crash, requires astroid update

#5366 Update documentation on writing tests for ``pylint``
  doc/development_guide/contribute.rst
  doc/development_guide/index.rst
  doc/development_guide/testing.rst
Labels: documentation

#5373 Add additional tests for ``OutputLine``
  tests/testutils/test_output_line.py
Labels: maintenance

#5343 Add ``end_lineno`` and ``end_col_offset`` to ``MessageLocationTuple``
  pylint/checkers/base_checker.py
  pylint/lint/pylinter.py
  pylint/message/message.py
  pylint/testutils/unittest_linter.py
  pylint/typing.py
  tests/lint/unittest_lint.py
  tests/message/unittest_message.py
  tests/testutils/test_output_line.py
Labels: enhancement, High priority

#5303 Fix typo in pylintrc for useless-suppression
  .github/workflows/ci.yaml
  .pre-commit-config.yaml
  ChangeLog
  doc/development_guide/contribute.rst
  doc/whatsnew/2.12.rst
  pylint/checkers/exceptions.py
  pylint/checkers/format.py
  pylint/checkers/similar.py
  pylint/checkers/utils.py
  pylint/checkers/variables.py
  pylint/config/option.py
  pylint/extensions/overlapping_exceptions.py
  pylint/lint/pylinter.py
  pylint/lint/run.py
  pylint/reporters/text.py
  pylint/testutils/lint_module_test.py
  pylint/testutils/reporter_for_tests.py
  pylint/testutils/unittest_linter.py
  pylint/utils/file_state.py
  pylint/utils/utils.py
  pylintrc
  tests/benchmark/test_baseline_benchmarks.py
  tests/checkers/unittest_design.py
  tests/checkers/unittest_format.py
  tests/config/unittest_config.py
  tests/conftest.py
  tests/lint/unittest_lint.py
  tests/profile/test_profile_against_externals.py
  tests/pyreverse/test_diagrams.py
  tests/regrtest_data/unused_variable.py
  tests/test_func.py
  tests/unittest_reporting.py
Labels: minor, task, maintenance

#5381 Make parallel checker use ``MessageLocationTuple`` for ``Message``
  pylint/lint/parallel.py
Labels: maintenance

#5369 Fix a crash on psycopg2 for elif used
  ChangeLog
  pylint/checkers/classes.py
  pylint/extensions/check_elif.py
  tests/functional/ext/check_elif/check_elif.py
  tests/functional/ext/check_elif/check_elif.txt
Labels: crash

#5173 Primer tests "à la mypy"
  .github/workflows/ci.yaml
  .gitignore
  ChangeLog
  doc/whatsnew/2.12.rst
  pylint/constants.py
  pylint/testutils/primer.py
  requirements_test_min.txt
  setup.cfg
  tests/primer/packages_to_lint.json
  tests/primer/test_primer_external.py
  tests/primer/test_primer_stdlib.py
  tests/testutils/test_package_to_lint.py
Labels: maintenance, primer

#5372 Update reporters to (allow) use of ``end_line`` and ``end_column``
  ChangeLog
  doc/user_guide/output.rst
  doc/whatsnew/2.12.rst
  pylint/reporters/text.py
  tests/unittest_reporting.py
Labels: enhancement, documentation

#5376 Fix checking of ``confidence`` in the unittests
  ChangeLog
  doc/whatsnew/2.12.rst
  pylint/testutils/output_line.py
  pylint/testutils/unittest_linter.py
  tests/checkers/unittest_base.py
  tests/checkers/unittest_misc.py
  tests/checkers/unittest_typecheck.py
  tests/checkers/unittest_variables.py
Labels: enhancement, maintenance

#5386 Add ``min_pyver_end_position`` option
  ChangeLog
  doc/development_guide/testing.rst
  doc/whatsnew/2.12.rst
  pylint/testutils/functional_test_file.py
  pylint/testutils/lint_module_test.py
  pylint/testutils/output_line.py
  tests/testutils/test_output_line.py
Labels: bug, enhancement

#5387 Add documentation for primer and convert to command line option
  .github/workflows/ci.yaml
  doc/development_guide/testing.rst
  setup.cfg
  tests/conftest.py
Labels: enhancement, documentation, primer

#5379 Activate and fix existing use-set-for-membership checks
  pylint/checkers/base.py
  pylint/checkers/classes.py
  pylint/checkers/format.py
  pylint/checkers/imports.py
  pylint/checkers/refactoring/implicit_booleaness_checker.py
  pylint/checkers/refactoring/recommendation_checker.py
  pylint/checkers/refactoring/refactoring_checker.py
  pylint/checkers/similar.py
  pylint/checkers/stdlib.py
  pylint/checkers/strings.py
  pylint/checkers/typecheck.py
  pylint/checkers/utils.py
  pylint/checkers/variables.py
  pylint/config/option.py
  pylint/config/options_provider_mixin.py
  pylint/extensions/typing.py
  pylint/graph.py
  pylint/lint/pylinter.py
  pylint/utils/pragma_parser.py
  pylintrc
Labels: maintenance

#5316 Make ``unused-import`` check all ancestors for typing guards
  pylint/checkers/variables.py
  tests/functional/u/unused/unused_import.py
Labels: false-positive

#5400 Move ``TestVariablesChecker`` to functional tests
  tests/checkers/unittest_classes.py
  tests/functional/a/access/access_member_before_definition.py
  tests/functional/a/access/access_member_before_definition.txt
  tests/functional/m/method_hidden.py
  tests/functional/m/method_hidden.txt
  tests/functional/n/non/non_parent_init_called.py
  tests/functional/p/protected_access.py
  tests/functional/p/protected_access.rc
  tests/functional/p/protected_access.txt
  tests/functional/p/protected_access_special_methods_off.py
  tests/functional/p/protected_access_special_methods_off.rc
  tests/functional/p/protected_access_special_methods_off.txt
  tests/functional/p/protected_access_special_methods_on.py
  tests/functional/p/protected_access_special_methods_on.rc
  tests/functional/p/protected_access_special_methods_on.txt
  tests/functional/s/super/super_init_not_called.py
Labels: maintenance

#5404 Move ``TestDocstring`` to functional tests
  tests/checkers/unittest_base.py
  tests/functional/e/empty_docstring.py
  tests/functional/e/empty_docstring.rc
  tests/functional/e/empty_docstring.txt
  tests/functional/m/missing/missing_class_docstring.py
  tests/functional/m/missing/missing_class_docstring.txt
  tests/functional/m/missing/missing_function_docstring.py
  tests/functional/m/missing/missing_function_docstring.rc
  tests/functional/m/missing/missing_function_docstring.txt
  tests/functional/m/missing/missing_function_docstring_min_length.py
  tests/functional/m/missing/missing_function_docstring_min_length.rc
  tests/functional/m/missing/missing_function_docstring_min_length.txt
  tests/functional/m/missing/missing_function_docstring_rgx.py
  tests/functional/m/missing/missing_function_docstring_rgx.rc
  tests/functional/m/missing/missing_function_docstring_rgx.txt
  tests/functional/m/missing/missing_module_docstring.py
  tests/functional/m/missing/missing_module_docstring.txt
  tests/functional/m/missing/missing_module_docstring_empty.py
Labels: maintenance

#5410 Refactor ``_is_type_checking_import`` of ``unused-import``
  ChangeLog
  pylint/checkers/variables.py
Labels: maintenance

#5411 Update documentation of ``max_pyver`` test option
  doc/development_guide/testing.rst
Labels: documentation

#5419 Move ``TestVariablesChecker`` to functional tests
  tests/checkers/unittest_variables.py
  tests/functional/g/globals.py
  tests/functional/g/globals.txt
  tests/functional/n/no/no_name_in_module.py
  tests/functional/n/no/no_name_in_module.rc
  tests/functional/r/redefined_builtin.py
  tests/functional/r/redefined_builtin.rc
  tests/functional/r/redefined_builtin.txt
  tests/functional/u/undefined/undefined_variable_classes.py
  tests/functional/u/undefined/undefined_variable_decorators.py
  tests/functional/u/undefined/undefined_variable_typing.py
  tests/functional/u/undefined/undefined_variable_typing.rc
  tests/functional/u/unused/unused_module.py
Labels: maintenance

#5423 Move ``TestMultiStatementLine`` to functional tests
  tests/checkers/unittest_format.py
  tests/functional/m/multiple_statements.py
  tests/functional/m/multiple_statements.txt
  tests/functional/m/multiple_statements_single_line.py
  tests/functional/m/multiple_statements_single_line.rc
  tests/functional/m/multiple_statements_single_line.txt
Labels: maintenance

#5422 Move ``TestStringChecker`` to functional tests
  tests/checkers/unittest_strings.py
  tests/functional/b/bad_string_format_type.py
  tests/functional/b/bad_string_format_type.txt
Labels: maintenance

#5421 Move ``TestNameChecker`` to functional tests
  tests/checkers/unittest_base.py
  tests/functional/a/assign/assign_to_new_keyword.py
  tests/functional/a/assign/assign_to_new_keyword.rc
  tests/functional/a/assign/assign_to_new_keyword.txt
  tests/functional/i/invalid/invalid_name_module_level.py
  tests/functional/i/invalid/invalid_name_module_level.txt
  tests/functional/i/invalid/invalid_name_property.py
  tests/functional/i/invalid/invalid_name_property.rc
  tests/functional/i/invalid/invalid_name_property.txt
Labels: maintenance

#5415 Update description of ``ignore-paths``
  ChangeLog
  examples/pylintrc
Labels: documentation

#5420 Move ``TestExceptionsChecker`` to functional tests
  tests/checkers/unittest_exceptions.py
  tests/functional/b/bad_exception_context.py
  tests/functional/b/bad_exception_context.txt
  tests/functional/r/raise/raising_bad_type.py
  tests/functional/r/raise/raising_bad_type.txt
Labels: maintenance

#5428 Move ``TestLoggingModuleDetection`` to functional tests
  tests/checkers/unittest_logging.py
  tests/functional/l/logging_format_interpolation_style.py
  tests/functional/l/logging_format_interpolation_style.rc
  tests/functional/l/logging_fstring_interpolation_py37.py
  tests/functional/l/logging_fstring_interpolation_py37.rc
  tests/functional/l/logging_fstring_interpolation_py37.txt
  tests/functional/l/logging_not_lazy.py
  tests/functional/l/logging_not_lazy.txt
  tests/functional/l/logging_not_lazy_module.py
  tests/functional/l/logging_not_lazy_module.rc
  tests/functional/l/logging_not_lazy_module.txt
  tests/functional/l/logging_too_few_args.py
  tests/functional/l/logging_too_few_args.rc
  tests/functional/l/logging_too_few_args.txt
  tests/functional/l/logging_too_many_args.py
  tests/functional/l/logging_too_many_args.rc
  tests/functional/l/logging_too_many_args.txt
Labels: maintenance

#5427 Move most tests of ``TestStdlibChecker`` to functional tests
  tests/checkers/unittest_stdlib.py
  tests/functional/s/shallow_copy_environ.py
  tests/functional/s/shallow_copy_environ.txt
Labels: maintenance

#5425 Update ``primer`` tests to own file, separate batches and concurrent runs
  .github/workflows/ci.yaml
  .github/workflows/primer-test.yaml
  doc/development_guide/testing.rst
  setup.cfg
  tests/conftest.py
  tests/primer/packages_to_lint.json
  tests/primer/packages_to_lint_batch_one.json
  tests/primer/packages_to_lint_batch_two.json
  tests/primer/test_primer_external.py
Labels: maintenance, primer

#5318 Allow failing when score is affected by `Information` warning
  pylint/lint/run.py
Labels: bug

#5434 Move most tests out of ``TestImportsChecker``
  tests/checkers/unittest_imports.py
  tests/functional/i/import_error.py
  tests/functional/i/import_error.rc
  tests/functional/i/import_error.txt
  tests/functional/i/import_outside_toplevel.py
  tests/functional/i/import_outside_toplevel.rc
  tests/functional/i/import_outside_toplevel.txt
Labels: maintenance

#5435 Move ``TestDocstringCheckerYield`` to functional tests
  tests/extensions/test_check_yields_docs.py
  tests/functional/ext/docparams/yield/missing_yield_doc.py
  tests/functional/ext/docparams/yield/missing_yield_doc.rc
  tests/functional/ext/docparams/yield/missing_yield_doc_Google.py
  tests/functional/ext/docparams/yield/missing_yield_doc_Google.rc
  tests/functional/ext/docparams/yield/missing_yield_doc_Google.txt
  tests/functional/ext/docparams/yield/missing_yield_doc_Numpy.py
  tests/functional/ext/docparams/yield/missing_yield_doc_Numpy.rc
  tests/functional/ext/docparams/yield/missing_yield_doc_Numpy.txt
  tests/functional/ext/docparams/yield/missing_yield_doc_Sphinx.py
  tests/functional/ext/docparams/yield/missing_yield_doc_Sphinx.rc
  tests/functional/ext/docparams/yield/missing_yield_doc_required.py
  tests/functional/ext/docparams/yield/missing_yield_doc_required.rc
  tests/functional/ext/docparams/yield/missing_yield_doc_required.txt
  tests/functional/ext/docparams/yield/missing_yield_doc_required_Google.py
  tests/functional/ext/docparams/yield/missing_yield_doc_required_Google.rc
  tests/functional/ext/docparams/yield/missing_yield_doc_required_Google.txt
  tests/functional/ext/docparams/yield/missing_yield_doc_required_Numpy.py
  tests/functional/ext/docparams/yield/missing_yield_doc_required_Numpy.rc
  tests/functional/ext/docparams/yield/missing_yield_doc_required_Numpy.txt
  tests/functional/ext/docparams/yield/missing_yield_doc_required_Sphinx.py
  tests/functional/ext/docparams/yield/missing_yield_doc_required_Sphinx.rc
  tests/functional/ext/docparams/yield/missing_yield_doc_required_Sphinx.txt
Labels: maintenance

#5436 Move ``TestForAnyAll`` to functional tests
  tests/extensions/test_for_any_all.py
  tests/functional/ext/for_any_all/for_any_all.py
  tests/functional/ext/for_any_all/for_any_all.txt
Labels: maintenance

#5439 Fix ``_regexp_paths_csv_validator`` for already validated values
  ChangeLog
  pylint/config/option.py
  tests/test_self.py
Labels: regression, crash

#5438 Move ``TestDocstringCheckerReturn`` to functional tests
  tests/extensions/test_check_return_docs.py
  tests/functional/ext/docparams/return/missing_return_doc.py
  tests/functional/ext/docparams/return/missing_return_doc.rc
  tests/functional/ext/docparams/return/missing_return_doc_Google.py
  tests/functional/ext/docparams/return/missing_return_doc_Google.rc
  tests/functional/ext/docparams/return/missing_return_doc_Google.txt
  tests/functional/ext/docparams/return/missing_return_doc_Numpy.py
  tests/functional/ext/docparams/return/missing_return_doc_Numpy.rc
  tests/functional/ext/docparams/return/missing_return_doc_Numpy.txt
  tests/functional/ext/docparams/return/missing_return_doc_Sphinx.py
  tests/functional/ext/docparams/return/missing_return_doc_Sphinx.rc
  tests/functional/ext/docparams/return/missing_return_doc_Sphinx.txt
  tests/functional/ext/docparams/return/missing_return_doc_required.py
  tests/functional/ext/docparams/return/missing_return_doc_required.rc
  tests/functional/ext/docparams/return/missing_return_doc_required.txt
  tests/functional/ext/docparams/return/missing_return_doc_required_Google.py
  tests/functional/ext/docparams/return/missing_return_doc_required_Google.rc
  tests/functional/ext/docparams/return/missing_return_doc_required_Google.txt
  tests/functional/ext/docparams/return/missing_return_doc_required_Numpy.py
  tests/functional/ext/docparams/return/missing_return_doc_required_Numpy.rc
  tests/functional/ext/docparams/return/missing_return_doc_required_Numpy.txt
  tests/functional/ext/docparams/return/missing_return_doc_required_Sphinx.py
  tests/functional/ext/docparams/return/missing_return_doc_required_Sphinx.rc
  tests/functional/ext/docparams/return/missing_return_doc_required_Sphinx.txt
Labels: maintenance

#5444 Move ``TestDocstringCheckerRaise`` to functional tests
  tests/extensions/test_check_raise_docs.py
  tests/functional/ext/docparams/raise/missing_raises_doc.py
  tests/functional/ext/docparams/raise/missing_raises_doc.rc
  tests/functional/ext/docparams/raise/missing_raises_doc.txt
  tests/functional/ext/docparams/raise/missing_raises_doc_Google.py
  tests/functional/ext/docparams/raise/missing_raises_doc_Google.rc
  tests/functional/ext/docparams/raise/missing_raises_doc_Google.txt
  tests/functional/ext/docparams/raise/missing_raises_doc_Numpy.py
  tests/functional/ext/docparams/raise/missing_raises_doc_Numpy.rc
  tests/functional/ext/docparams/raise/missing_raises_doc_Numpy.txt
  tests/functional/ext/docparams/raise/missing_raises_doc_Sphinx.py
  tests/functional/ext/docparams/raise/missing_raises_doc_Sphinx.rc
  tests/functional/ext/docparams/raise/missing_raises_doc_Sphinx.txt
  tests/functional/ext/docparams/raise/missing_raises_doc_required.py
  tests/functional/ext/docparams/raise/missing_raises_doc_required.rc
  tests/functional/ext/docparams/raise/missing_raises_doc_required.txt
  tests/functional/ext/docparams/raise/missing_raises_doc_required_Google.py
  tests/functional/ext/docparams/raise/missing_raises_doc_required_Google.rc
  tests/functional/ext/docparams/raise/missing_raises_doc_required_Numpy.py
  tests/functional/ext/docparams/raise/missing_raises_doc_required_Numpy.rc
  tests/functional/ext/docparams/raise/missing_raises_doc_required_Sphinx.py
  tests/functional/ext/docparams/raise/missing_raises_doc_required_Sphinx.rc
Labels: maintenance

#5445 Add type of docstring to ``missing_raises_doc`` functional tests
  tests/functional/ext/docparams/raise/missing_raises_doc_Google.py
  tests/functional/ext/docparams/raise/missing_raises_doc_Numpy.py
  tests/functional/ext/docparams/raise/missing_raises_doc_Sphinx.py
Labels: maintenance

#5331 fix(consider-interating-dictionary): fix false negatives
  ChangeLog
  doc/whatsnew/2.13.rst
  pylint/checkers/refactoring/recommendation_checker.py
  pylint/checkers/utils.py
  tests/functional/c/consider/consider_iterating_dictionary.py
  tests/functional/c/consider/consider_iterating_dictionary.txt
Labels: enhancement, blocked, false negative
