Repository pylint-dev/pylint, pull requests merged in 2021-03, with the labels that each got.

#4162 Fix Enum invalid name with snake_case preset
  ChangeLog
  pylint/checkers/base.py
  tests/functional/n/name_preset_snake_case.py
  tests/functional/n/name_preset_snake_case.txt
Labels: bug, false-positive

#3643 Add allow-redefined-builtins option to variable checker
  CONTRIBUTORS.txt
  ChangeLog
  doc/whatsnew/2.7.rst
  pylint/checkers/variables.py
  tests/functional/r/redefined_builtin_allowed.py
  tests/functional/r/redefined_builtin_allowed.rc
  tests/functional/r/redefined_builtin_allowed.txt
Labels: needs review, proposal, waiting for author

#4164 Fix sys.path bug
  ChangeLog
  pylint/__init__.py
  pylint/__main__.py
  tests/test_self.py
Labels: bug

#4191 Exempt TypedDict from too-few-public-methods check
  ChangeLog
  pylint/checkers/design_analysis.py
  tests/functional/t/typedDict.py
Labels: enhancement, false-positive

#4194 Fix false-positive no-member for typed annotations without default value
  ChangeLog
  pylint/checkers/typecheck.py
  pylint/checkers/utils.py
  tests/functional/m/member_checks_typed_annotations.py
  tests/functional/m/member_checks_typed_annotations.txt
Labels: false-positive

#4173 Add tests for disables being ignored with multiple jobs
  tests/input/no_absolute_import.py
  tests/test_self.py
Labels: bug, topic- multiprocessing

#4198 Relax test's dependencies so we're not spammed by dependabot
  requirements_test.txt
  requirements_test_min.txt
Labels: task

#4127 Introduced deprecated attributes
  ChangeLog
  doc/whatsnew/2.8.rst
  examples/deprecation_checker.py
  pylint/checkers/deprecated.py
  tests/checkers/unittest_deprecated.py
Labels: checkers, enhancement

#3514 Fix score option for JSON export
  ChangeLog
  doc/whatsnew/3.0.rst
  doc/whatsnew/index.rst
  pylint/lint/pylinter.py
  pylint/reporters/json_reporter.py
  tests/test_self.py
  tests/unittest_reporters_json.py
Labels: Breaking changes for 3.0, bug

#4176 Print helpful error when toml decode fails
  CONTRIBUTORS.txt
  pylint/config/find_default_config_files.py
Labels: crash

#4205 Typing changes + disable unused pylint plugin for pre-commit
  .pre-commit-config.yaml
  examples/deprecation_checker.py
  pylint/checkers/deprecated.py
  tox.ini
Labels: task

#4216 Fix astroid.Inference error for undefined-variables with len()
  ChangeLog
  pylint/checkers/refactoring/len_checker.py
  tests/functional/l/len_checks.py
  tests/functional/l/len_checks.txt
Labels: crash, topic-inference

#4211 Improve fix-documentation pre-commit hook
  script/fix_documentation.py
Labels: documentation, task

#4234 Fix changelog: print removal need to be in '2.7.3'
  ChangeLog
Labels: task

#4236 Upgrade flake8 to 3.9.0 from 3.8.4
  .pre-commit-config.yaml
  requirements_test_pre_commit.txt
Labels: task

#4225 Move deprecated module checker to DeprecatedMixin
  ChangeLog
  pylint/checkers/deprecated.py
  pylint/checkers/imports.py
  tests/checkers/unittest_deprecated.py
Labels: enhancement

#4247 Update the release documentation for pre-commit autoupdate to works
  doc/release.md
Labels: documentation, maintenance

#4177 Fix private method hidden by ancestor class attribute
  ChangeLog
  pylint/checkers/classes.py
  tests/checkers/unittest_classes.py
Labels: bug, false-positive

#4246 Fix column index of FIXME warnings
  CONTRIBUTORS.txt
  ChangeLog
  pylint/checkers/misc.py
  tests/functional/f/fixme.txt
  tests/functional/f/fixme_bad_formatting_1139.txt
Labels: enhancement

#4255 Only print verbose logs if pytest -v
  pylint/testutils/lint_module_test.py
  tests/test_functional.py
Labels: enhancement

#4253 Improve handling of assignment expressions
  ChangeLog
  pylint/checkers/variables.py
  pylint/constants.py
  tests/functional/a/assignment_expression.py
  tests/functional/a/assignment_expression.txt
Labels: false-positive

#4258 Fix regression with sys.path filter
  ChangeLog
  pylint/__init__.py
  tests/test_self.py
Labels: bug, regression

#4260 Fix regession with sys.path filter (2)
  tests/test_self.py
Labels: bug, regression

#4259 Fix various problems with --import-graph filename parsing
  CONTRIBUTORS.txt
  ChangeLog
  pylint/checkers/imports.py
  pylint/graph.py
  tests/test_import_graph.py
Labels: documentation, enhancement, topic-pyreverse

#4261 Change version for 2.7.3 release, modify release process
  ChangeLog
  pylint/__init__.py
  pylint/__pkginfo__.py
  pylint/checkers/base.py
  pylint/checkers/classes.py
  pylint/checkers/design_analysis.py
  pylint/checkers/imports.py
  pylint/checkers/misc.py
  pylint/checkers/python3.py
  pylint/checkers/typecheck.py
  pylint/checkers/variables.py
  pylint/extensions/bad_builtin.py
  pylint/graph.py
  pylint/pyreverse/main.py
  pylint/pyreverse/writer.py
  pylint/utils/__init__.py
  tests/checkers/unittest_classes.py
  tests/test_functional.py
  tests/test_import_graph.py
  tests/unittest_pyreverse_writer.py
  tests/utils/unittest_utils.py
Labels: task

#4262 Upgrade project for 2.7.4, and 2.8.0
  ChangeLog
  doc/release.md
  pylint/__pkginfo__.py
Labels: documentation, task

#4266 Fix issue with annotated class constants
  ChangeLog
  pylint/checkers/utils.py
  tests/functional/n/name/name_styles.py
  tests/functional/n/name/name_styles.txt
Labels: regression

#4268 Fix disabled warning not ignored
  ChangeLog
  pylint/__pkginfo__.py
  pylint/message/message_handler_mix_in.py
  tests/functional/d/disabled_msgid_in_pylintrc.py
  tests/functional/d/disabled_msgid_in_pylintrc.rc
Labels: blocker, regression

#4269 Upgrade the version for development following 2.7.4 release
  ChangeLog
  doc/release.md
  pylint/__pkginfo__.py
Labels: documentation, task

#4270 Skip test_missing_graphviz if graphviz is installed
  tests/test_import_graph.py
Labels: bug, task
