Repository pylint-dev/pylint, pull requests merged in 2022-11, with the labels that each got.

#7622 Fix astroid error for custom ``next`` method
  doc/whatsnew/fragments/7610.bugfix
  pylint/checkers/refactoring/refactoring_checker.py
  tests/functional/s/stop_iteration_inside_generator.py
  tests/functional/s/stop_iteration_inside_generator.txt
Labels: Needs review 🔍, Needs backport, Crash 💥

#7651 Improve Github action workflows
  .github/workflows/changelog.yml
  .github/workflows/checks.yaml
  .github/workflows/primer-test.yaml
  .github/workflows/primer_comment.yaml
  .github/workflows/primer_run_main.yaml
  .github/workflows/primer_run_pr.yaml
  .github/workflows/release.yml
  .github/workflows/tests.yaml
  pyproject.toml
  requirements_test_min.txt
Labels: Needs backport, Maintenance, Skip news :mute:

#7711 Upgrade the documentation, fix 'magic-value-comparison' doc
  doc/data/messages/m/magic-value-comparison/bad.py
  doc/data/messages/m/magic-value-comparison/good.py
  doc/data/messages/m/magic-value-comparison/pylintrc
  doc/user_guide/checkers/extensions.rst
  doc/user_guide/checkers/features.rst
  doc/user_guide/configuration/all-options.rst
  doc/user_guide/messages/messages_overview.rst
Labels: Documentation :green_book:, Maintenance, Skip news :mute:

#7713 [doc] Document some messages where the code is not the problem
  doc/data/messages/a/astroid-error/details.rst
  doc/data/messages/a/astroid-error/good.py
  doc/data/messages/c/config-parse-error/details.rst
  doc/data/messages/c/config-parse-error/good.py
  doc/data/messages/f/fatal/details.rst
  doc/data/messages/f/fatal/good.py
  doc/data/messages/m/method-check-failed/details.rst
  doc/data/messages/m/method-check-failed/good.py
  doc/data/messages/p/parse-error/details.rst
  doc/data/messages/s/syntax-error/bad.py
  doc/data/messages/s/syntax-error/good.py
Labels: Documentation :green_book:, Skip news :mute:

#7712 [doc] Add examples for wrong-spelling-in-x
  doc/data/messages/i/invalid-characters-in-docstring/details.rst
  doc/data/messages/i/invalid-characters-in-docstring/good.py
  doc/data/messages/w/wrong-spelling-in-comment/bad.py
  doc/data/messages/w/wrong-spelling-in-comment/details.rst
  doc/data/messages/w/wrong-spelling-in-comment/good.py
  doc/data/messages/w/wrong-spelling-in-comment/pylintrc
  doc/data/messages/w/wrong-spelling-in-docstring/bad.py
  doc/data/messages/w/wrong-spelling-in-docstring/details.rst
  doc/data/messages/w/wrong-spelling-in-docstring/good.py
  doc/data/messages/w/wrong-spelling-in-docstring/pylintrc
Labels: Documentation :green_book:, Skip news :mute:

#7709 rename `broad-except` and new check `broad-exception-raised`
  doc/data/messages/b/broad-except/bad.py
  doc/data/messages/b/broad-exception-caught/bad.py
  doc/data/messages/b/broad-exception-caught/good.py
  doc/data/messages/b/broad-exception-raised/bad.py
  doc/data/messages/b/broad-exception-raised/good.py
  doc/user_guide/checkers/features.rst
  doc/user_guide/messages/messages_overview.rst
  doc/whatsnew/fragments/7494.new_check
  pylint/checkers/exceptions.py
  pylint/config/option.py
  pylint/lint/parallel.py
  pylint/pyreverse/vcg_printer.py
  tests/functional/b/bad_exception_cause.py
  tests/functional/b/bad_exception_cause.txt
  tests/functional/b/broad_except.txt
  tests/functional/b/broad_exception_caught.py
  tests/functional/b/broad_exception_caught.txt
  tests/functional/b/broad_exception_raised.py
  tests/functional/b/broad_exception_raised.txt
  tests/functional/c/comparison_with_callable.py
  tests/functional/ext/docparams/docparams.py
  tests/functional/ext/mccabe/mccabe.py
  tests/functional/ext/typing/typing_broken_noreturn.py
  tests/functional/ext/typing/typing_broken_noreturn_future_import.py
  tests/functional/ext/typing/typing_broken_noreturn_py372.py
  tests/functional/n/no/no_else_raise.py
  tests/functional/r/regression_02/regression_5048.py
  tests/functional/s/stop_iteration_inside_generator.py
  tests/functional/u/undefined/undefined_loop_variable.py
  tests/functional/u/unreachable.py
  tests/functional/u/unused/unused_variable.py
  tests/functional/u/used/used_before_assignment_comprehension_homonyms.py
  tests/functional/u/used/used_before_assignment_except_handler_for_try_with_return.py
  tests/lint/test_utils.py
  tests/test_check_parallel.py
  tests/test_self.py
Labels: Enhancement ✨

#7716 add confidence levels to all exception checkers
  pylint/checkers/exceptions.py
  tests/functional/b/bad_except_order.txt
  tests/functional/b/bare_except.txt
  tests/functional/b/broad_exception_caught.txt
  tests/functional/b/broad_exception_raised.txt
  tests/functional/d/duplicate_except.txt
  tests/functional/e/exception_is_binary_op.txt
  tests/functional/ext/docparams/raise/missing_raises_doc.txt
  tests/functional/i/invalid/invalid_exceptions/invalid_exceptions_raised.txt
  tests/functional/m/misplaced_bare_raise.txt
  tests/functional/r/raising/raising_bad_type.txt
  tests/functional/r/raising/raising_format_tuple.txt
  tests/functional/r/raising/raising_non_exception.txt
Labels: Maintenance, Skip news :mute:

#7719 [doc] Less personal style for the tutorial
  doc/tutorial.rst
Labels: Documentation :green_book:, Skip news :mute:

#7718 Use typed NamedTuple for `Confidence` + `PragmaRepresenter`
  pylint/interfaces.py
  pylint/utils/pragma_parser.py
Labels: Maintenance, Skip news :mute:

#7721 [implicit_booleaness_checker] Add the confidence to related messages
  .pyenchant_pylint_custom_dict.txt
  pylint/checkers/refactoring/implicit_booleaness_checker.py
  pylint/extensions/comparetozero.py
  pylint/extensions/emptystring.py
  tests/functional/ext/comparetozero/comparetozero.txt
  tests/functional/ext/emptystring/empty_string_comparison.txt
  tests/functional/u/use/use_implicit_booleaness_not_comparison.txt
  tests/functional/u/use/use_implicit_booleaness_not_len.txt
Labels: Maintenance, Skip news :mute:

#7708 Update Primer venv caching [ci]
  .github/workflows/primer_comment.yaml
  .github/workflows/primer_run_main.yaml
  .github/workflows/primer_run_pr.yaml
  pyproject.toml
  requirements_test_min.txt
Labels: Needs review 🔍, Needs backport, Maintenance, Skip news :mute:

#7728 use new msg names
  pylint/checkers/base/docstring_checker.py
  pylint/config/argument.py
Labels: Maintenance, Skip news :mute:

#7691 Extend R1735 use-dict-literal to highlight all usages of dict that can be replaced with a literal
  doc/data/messages/u/use-dict-literal/bad.py
  doc/data/messages/u/use-dict-literal/details.rst
  doc/data/messages/u/use-dict-literal/good.py
  doc/user_guide/checkers/features.rst
  doc/whatsnew/fragments/7690.new_check
  pylint/checkers/refactoring/refactoring_checker.py
  pylint/pyreverse/dot_printer.py
  pylint/pyreverse/main.py
  pylint/pyreverse/vcg_printer.py
  script/.contributors_aliases.json
  tests/functional/i/invalid/invalid_getnewargs/invalid_getnewargs_ex_returned.py
  tests/functional/i/invalid/invalid_getnewargs/invalid_getnewargs_returned.py
  tests/functional/i/iterable_context.py
  tests/functional/i/iterable_context.txt
  tests/functional/m/mapping_context.py
  tests/functional/u/unidiomatic_typecheck.py
  tests/functional/u/unnecessary/unnecessary_lambda.py
  tests/functional/u/unsubscriptable_value.py
  tests/functional/u/unsubscriptable_value.txt
  tests/functional/u/unsupported/unsupported_assignment_operation.py
  tests/functional/u/unsupported/unsupported_delete_operation.py
  tests/functional/u/use/use_literal_dict.py
  tests/functional/u/use/use_literal_dict.txt
Labels: Enhancement ✨

#7217 Ignore path doc: double escape to add escape character in rst
  pylint/lint/base_options.py
Labels: Documentation :green_book:, Skip news :mute:

#7726 [compare-to-empty-string] More actionnable and understandable message
  pylint/extensions/emptystring.py
  tests/functional/ext/emptystring/empty_string_comparison.py
  tests/functional/ext/emptystring/empty_string_comparison.txt
Labels: Documentation :green_book:, Skip news :mute:

#7678 Fix a false negative for ``unused-import``
  doc/whatsnew/fragments/7547.false_negative
  pylint/checkers/utils.py
  pylint/checkers/variables.py
  tests/checkers/unittest_utils.py
  tests/functional/u/unused/unused_import_py39.py
  tests/functional/u/unused/unused_import_py39.rc
  tests/functional/u/unused/unused_import_py39.txt
Labels: False Negative 🦋

#7743 Do not report `consider_iterating_dictionary` if bitwise operations are used
  doc/whatsnew/fragments/5478.bugfix
  pylint/checkers/refactoring/recommendation_checker.py
  tests/functional/c/consider/consider_iterating_dictionary.py
  tests/functional/c/consider/consider_iterating_dictionary.txt
  tests/functional/c/consider/consider_using_dict_items.txt
Labels: Needs backport, False Positive 🦟

#7746 Avoid deprecation warning in internal use of `may_be_emitted`
  pylint/lint/pylinter.py
  pylint/message/message_definition.py
  pylint/message/message_definition_store.py
Labels: Maintenance, Skip news :mute:

#7754 Tag primer commit strings with python version
  .github/workflows/primer_run_main.yaml
  .github/workflows/primer_run_pr.yaml
  pylint/testutils/_primer/primer_prepare_command.py
Labels: Bug :beetle:, primer, Skip news :mute:

#7755 Preserve file name when copying commit string file in primer job
  .github/workflows/primer_run_pr.yaml
Labels: Bug :beetle:, primer, Skip news :mute:

#7753 Add docs for unused / unsupported msgs
  doc/data/messages/u/unsupported-assignment-operation/bad.py
  doc/data/messages/u/unsupported-assignment-operation/details.rst
  doc/data/messages/u/unsupported-assignment-operation/good.py
  doc/data/messages/u/unsupported-delete-operation/bad.py
  doc/data/messages/u/unsupported-delete-operation/details.rst
  doc/data/messages/u/unsupported-delete-operation/good.py
  doc/data/messages/u/unsupported-membership-test/bad.py
  doc/data/messages/u/unsupported-membership-test/details.rst
  doc/data/messages/u/unsupported-membership-test/good.py
  doc/data/messages/u/unused-private-member/bad.py
  doc/data/messages/u/unused-private-member/details.rst
  doc/data/messages/u/unused-private-member/good.py
Labels: Documentation :green_book:, Skip news :mute:

#7744 Fix a crash when looking up an __init__ method
  doc/whatsnew/fragments/7742.bugfix
  pylint/checkers/classes/class_checker.py
  tests/functional/i/init_not_called.py
Labels: Needs backport, Crash 💥

#7758 Correct documentation about running primer locally
  doc/development_guide/contributor_guide/tests/launching_test.rst
Labels: Documentation :green_book:, Skip news :mute:

#7759 Remove unused `ExtSlice` code paths
  pylint/checkers/typecheck.py
  tests/functional/i/invalid/invalid_sequence_index.py
Labels: Maintenance, Skip news :mute:

#7497 Use qualified name when checking for overgeneral exceptions
  doc/user_guide/configuration/all-options.rst
  doc/whatsnew/fragments/7495.bugfix
  examples/pylintrc
  examples/pyproject.toml
  pylint/checkers/exceptions.py
  pylintrc
  tests/functional/b/bad_exception_cause.txt
  tests/functional/b/broad_exception_caught.py
  tests/functional/b/broad_exception_caught.rc
  tests/functional/b/broad_exception_caught.txt
  tests/functional/b/broad_exception_raised.py
  tests/functional/b/broad_exception_raised.rc
  tests/functional/b/broad_exception_raised.txt
Labels: Enhancement ✨

#7685 false positive `unnecessary-list-index-lookup` for enumerate
  doc/whatsnew/fragments/7682.false_positive
  pylint/checkers/refactoring/refactoring_checker.py
  tests/functional/u/unnecessary/unnecessary_list_index_lookup.py
  tests/functional/u/unnecessary/unnecessary_list_index_lookup.txt
Labels: Needs backport, False Positive 🦟

#7752 Flag `superfluous-parens` if parentheses are used during string concatenation.
  doc/whatsnew/fragments/4792.false_negative
  pylint/checkers/format.py
  tests/functional/a/alternative/alternative_union_syntax.py
  tests/functional/i/implicit/implicit_str_concat.py
  tests/functional/i/invalid/invalid_all_format.py
  tests/functional/i/invalid/invalid_all_format.txt
  tests/functional/s/slots_checks.py
  tests/functional/s/slots_checks.txt
  tests/functional/s/superfluous_parens.py
  tests/functional/s/superfluous_parens.txt
  tests/functional/s/superfluous_parens_walrus_py38.py
  tests/functional/s/superfluous_parens_walrus_py38.txt
Labels: Enhancement ✨, False Negative 🦋

#7481 Extend consider-using-join to detect non-empty separators
  doc/whatsnew/fragments/6639.false_negative
  pylint/checkers/refactoring/refactoring_checker.py
  tests/functional/c/consider/consider_join.py
  tests/functional/c/consider/consider_join.txt
  tests/functional/n/non_ascii_name/non_ascii_name_for_loop.py
Labels: Enhancement ✨

#7764 Update documentation for checkers
  doc/user_guide/checkers/extensions.rst
  doc/user_guide/checkers/features.rst
  tests/functional/ext/typing/typing_broken_noreturn.py
Labels: Maintenance, Skip news :mute:

#7520 Detect unreachable code after sys.exit call
  doc/whatsnew/fragments/519.false_negative
  pylint/checkers/base/basic_checker.py
  tests/functional/u/unreachable.py
  tests/functional/u/unreachable.txt
Labels: topic-control-flow, False Negative 🦋, Needs decision :lock:

#7763 Add `named-expr-without-context` check
  doc/data/messages/n/named-expr-without-context/bad.py
  doc/data/messages/n/named-expr-without-context/good.py
  doc/user_guide/checkers/features.rst
  doc/user_guide/messages/messages_overview.rst
  doc/whatsnew/fragments/7760.new_check
  pylint/checkers/base/basic_checker.py
  tests/functional/n/named_expr_without_context_py38.py
  tests/functional/n/named_expr_without_context_py38.rc
  tests/functional/n/named_expr_without_context_py38.txt
  tests/functional/s/superfluous_parens_walrus_py38.py
Labels: Enhancement ✨

#7757 Fix false positive for ``unhashable-member`` when subclassing ``dict``.
  doc/whatsnew/fragments/7501.false_positive
  pylint/checkers/utils.py
  tests/functional/u/unhashable_member.py
Labels: Needs backport, False Positive 🦟

#7766 Suppress `stop-iteration-return` on `itertools.cycle`
  doc/whatsnew/fragments/7765.false_positive
  pylint/checkers/refactoring/refactoring_checker.py
  tests/functional/s/stop_iteration_inside_generator.py
  tests/functional/s/stop_iteration_inside_generator.txt
Labels: Needs backport, False Positive 🦟

#7762 Improve `invalid-slice-index` and add `invalid-slice-step`
  doc/data/messages/i/invalid-slice-step/bad.py
  doc/data/messages/i/invalid-slice-step/good.py
  doc/user_guide/checkers/features.rst
  doc/user_guide/messages/messages_overview.rst
  doc/whatsnew/fragments/7762.false_negative
  doc/whatsnew/fragments/7762.new_check
  pylint/checkers/typecheck.py
  tests/functional/i/invalid/invalid_slice_index.py
  tests/functional/i/invalid/invalid_slice_index.txt
Labels: Enhancement ✨, False Negative 🦋

#7771 Bump timeout for docs check [ci]
  .github/workflows/checks.yaml
Labels: Needs backport, Maintenance, Skip news :mute:

#7617 Improve bad-threading-instantiation check
  doc/whatsnew/fragments/7570.bugfix
  pylint/checkers/stdlib.py
  tests/functional/b/bad_thread_instantiation.py
  tests/functional/b/bad_thread_instantiation.txt
Labels: False Negative 🦋

#7776 [release process] Add a github actions to backport fix automatically
  .github/workflows/backport.yml
  doc/development_guide/contributor_guide/release.md
Labels: Maintenance, Skip news :mute:, backport maintenance/2.15.x

#7777 [github actions] Set write permission for backport workflow
  .github/workflows/backport.yml
Labels: Maintenance, Skip news :mute:

#7707 Fix false negative for-any-all
  doc/whatsnew/fragments/7699.false_negative
  pylint/checkers/utils.py
  pylint/extensions/for_any_all.py
  tests/functional/ext/for_any_all/for_any_all.py
  tests/functional/ext/for_any_all/for_any_all.txt
Labels: False Negative 🦋

#7789 ``unnecessary-list-index-lookup`` false negative
  doc/whatsnew/fragments/7770.false_negative
  pylint/checkers/refactoring/refactoring_checker.py
  tests/functional/u/unnecessary/unnecessary_list_index_lookup.py
  tests/functional/u/unnecessary/unnecessary_list_index_lookup.txt
Labels: False Negative 🦋

#7784 fix FP For used-before-assignment if terminating func is used
  doc/whatsnew/fragments/7563.false_positive
  pylint/checkers/base/basic_checker.py
  pylint/checkers/utils.py
  pylint/checkers/variables.py
  tests/functional/u/used/used_before_assignment_else_return.py
  tests/functional/u/used/used_before_assignment_else_return.txt
Labels: False Positive 🦟, backport maintenance/2.15.x

#7792 [doc] Add link to Sublime Text integration
  doc/user_guide/installation/ide_integration/index.rst
Labels: Documentation :green_book:, Skip news :mute:

#7747 Deduplicate module file paths to prevent redundant scans.
  .pyenchant_pylint_custom_dict.txt
  doc/whatsnew/fragments/6242.bugfix
  pylint/lint/expand_modules.py
  pylint/lint/pylinter.py
  tests/lint/unittest_expand_modules.py
  tests/test_pylint_runners.py
Labels: Bug :beetle:, Needs review 🔍, Needs backport, backport maintenance/2.15.x

#7796 Enable broad-try-clause check
  pylint/lint/message_state_handler.py
  pylintrc
Labels: Maintenance, Skip news :mute:

#7785 Release branch 2.15.6
  CONTRIBUTORS.txt
  doc/whatsnew/2/2.15/index.rst
  doc/whatsnew/fragments/7214.bugfix
  doc/whatsnew/fragments/7501.false_positive
  doc/whatsnew/fragments/7610.bugfix
  doc/whatsnew/fragments/7661.bugfix
  doc/whatsnew/fragments/7682.false_positive
  doc/whatsnew/fragments/7742.bugfix
  doc/whatsnew/fragments/7765.false_positive
  pylint/__pkginfo__.py
  tbump.toml
Labels: Maintenance, Skip news :mute:

#7799 Merge maintenance/2.15.x in main following 2.15.6 release
  CONTRIBUTORS.txt
  doc/whatsnew/2/2.15/index.rst
  doc/whatsnew/fragments/7214.bugfix
  tests/functional/s/stop_iteration_inside_generator.py
Labels: Maintenance, Skip news :mute:

#7798 [primer] Fall back to no rcfile rather than pylint's
  pylint/testutils/_primer/package_to_lint.py
  tests/testutils/_primer/test_package_to_lint.py
Labels: primer, Skip news :mute:

#7791 Fix `valid-metaclass-classmethod-first-arg` default value
  doc/user_guide/configuration/all-options.rst
  doc/whatsnew/fragments/7782.bugfix
  examples/pylintrc
  examples/pyproject.toml
  pylint/checkers/classes/class_checker.py
  tests/functional/c/class_members_py30.py
  tests/functional/c/ctor_arguments.py
  tests/functional/f/first_arg.py
  tests/functional/f/first_arg.txt
  tests/functional/r/regression_02/regression_too_many_arguments_2335.py
  tests/functional/u/undefined/undefined_variable_py30.py
Labels: Documentation :green_book:, False Positive 🦟, False Negative 🦋

#7801 Run primer on 3.11
  .github/workflows/primer_comment.yaml
  .github/workflows/primer_run_main.yaml
  .github/workflows/primer_run_pr.yaml
Labels: primer, Skip news :mute:

#7778 Better error message for unpacking-non-sequence and unbalanced-tuple-unpacking
  doc/user_guide/checkers/features.rst
  doc/user_guide/configuration/all-options.rst
  pylint/checkers/variables.py
  tests/functional/u/unbalanced_tuple_unpacking.txt
  tests/functional/u/unpacking/unpacking_non_sequence.txt
Labels: Enhancement ✨, Documentation :green_book:, Skip news :mute:

#7783 Deprecation following the separation of emacs related file to https://github.com/emacsorphanage/pylint
  README.rst
  doc/development_guide/api/index.rst
  doc/user_guide/installation/ide_integration/flymake-emacs.rst
  doc/whatsnew/fragments/7737.other
  elisp/pylint-flymake.el
  elisp/pylint.el
  elisp/startup
  pylint/__init__.py
  pylint/epylint.py
  tests/test_epylint.py
  tests/test_pylint_runners.py
Labels: Maintenance, Emacs 💾

#7795 Fix ``deprecated-method`` false positive
  doc/whatsnew/fragments/5886.false_positive
  pylint/checkers/deprecated.py
  tests/checkers/unittest_deprecated.py
  tests/functional/d/deprecated/deprecated_methods_py38.py
Labels: False Positive 🦟, backport maintenance/2.15.x

#7750 New checker `unbalanced dict unpacking`
  doc/data/messages/u/unbalanced-dict-unpacking/bad.py
  doc/data/messages/u/unbalanced-dict-unpacking/good.py
  doc/user_guide/checkers/features.rst
  doc/user_guide/messages/messages_overview.rst
  doc/whatsnew/fragments/5797.new_check
  pylint/checkers/variables.py
  tests/functional/u/unbalanced_dict_unpacking.py
  tests/functional/u/unbalanced_dict_unpacking.txt
  tests/functional/u/unbalanced_tuple_unpacking.txt
  tests/functional/u/unbalanced_tuple_unpacking_py30.py
Labels: Enhancement ✨

#7823 fix end_col_offset deprecation msg
  tests/checkers/unittest_deprecated.py
Labels: Maintenance, Skip news :mute:

#7825 create `TERMINATING_FUNCS_QNAMES`
  pylint/checkers/utils.py
Labels: Maintenance, Skip news :mute:

#7815 [github actions] Permit to launch tests when backporting on maintenance branch
  .github/workflows/backport.yml
  .github/workflows/changelog.yml
  .github/workflows/checks.yaml
  .github/workflows/primer-test.yaml
  .github/workflows/primer_run_pr.yaml
  .github/workflows/tests.yaml
Labels: Maintenance, Skip news :mute:, backport maintenance/2.15.x

#6677 Emit `used-before-assignment` for variables only defined under always false tests
  doc/whatsnew/fragments/4913.false_negative
  pylint/checkers/variables.py
  tests/functional/ext/set_membership/use_set_membership.py
  tests/functional/r/redefined/redefined_except_handler.txt
  tests/functional/s/simplifiable/simplifiable_if_statement.py
  tests/functional/s/simplifiable/simplifiable_if_statement.txt
  tests/functional/u/undefined/undefined_variable_py38.py
  tests/functional/u/undefined/undefined_variable_py38.txt
  tests/functional/u/used/used_before_assignment.py
  tests/functional/u/used/used_before_assignment.txt
  tests/functional/u/used/used_before_assignment_except_handler_for_try_with_return.py
  tests/functional/u/used/used_before_assignment_issue626.txt
Labels: Enhancement ✨, topic-control-flow, False Negative 🦋, C: used-before-assignment

#7809 Fail pytest runs on warnings
  pyproject.toml
  tests/functional/b/bad_reversed_sequence_py37.txt
  tests/functional/s/star/star_needs_assignment_target_py37.txt
  tests/pyreverse/test_inspector.py
  tests/pyreverse/test_utils.py
  tests/reporters/unittest_reporting.py
Labels: Maintenance, Skip news :mute:

#7829 Drop dependency on py module
  tests/config/test_per_directory_config.py
  tests/lint/test_pylinter.py
  tests/pyreverse/test_pyreverse_functional.py
  tests/test_pylint_runners.py
  tests/test_self.py
Labels: Maintenance, Skip news :mute:

#7833 Catch UserWarning when linting stdlib
  tests/primer/test_primer_stdlib.py
Labels: Maintenance, Skip news :mute:

#7794 New check `dict-init-mutate`
  doc/data/messages/d/dict-init-mutate/bad.py
  doc/data/messages/d/dict-init-mutate/good.py
  doc/data/messages/d/dict-init-mutate/pylintrc
  doc/user_guide/checkers/extensions.rst
  doc/user_guide/messages/messages_overview.rst
  doc/whatsnew/fragments/2876.new_check
  pylint/extensions/dict_init_mutate.py
  tests/functional/ext/dict_init_mutate.py
  tests/functional/ext/dict_init_mutate.rc
  tests/functional/ext/dict_init_mutate.txt
Labels: Enhancement ✨

#7826 Add ``content: write`` rights for backporting job
  .github/workflows/backport.yml
  .github/workflows/primer-test.yaml
  .github/workflows/primer_run_pr.yaml
Labels: Maintenance, Skip news :mute:, backport maintenance/2.15.x

#7838 Upgrade the versions of astroid and dill
  .github/workflows/backport.yml
  pyproject.toml
  requirements_test_min.txt
Labels: Maintenance, Skip news :mute:, backport maintenance/2.15.x

#7831 Do not crash if next()` is called
  doc/whatsnew/fragments/7828.bugfix
  pylint/checkers/refactoring/refactoring_checker.py
  tests/functional/s/stop_iteration_inside_generator.py
Labels: Crash 💥, backport maintenance/2.15.x

#7824 Fix crash when using ``enumerate`` with ``start`` and a class attribute
  doc/whatsnew/fragments/7821.bugfix
  pylint/checkers/refactoring/refactoring_checker.py
  tests/functional/u/unnecessary/unnecessary_list_index_lookup.py
Labels: Crash 💥, backport maintenance/2.15.x

#7844 Enable dict-init-mutate extension
  pylint/extensions/bad_builtin.py
  pylintrc
Labels: Maintenance, Skip news :mute:

#7847 Prevent `used-before-assignment` for variables defined in assignment expressions
  pylint/checkers/variables.py
  tests/functional/u/undefined/undefined_variable_py38.py
  tests/functional/u/undefined/undefined_variable_py38.txt
Labels: False Positive 🦟, Unreleased, Skip news :mute:

#7846 Fix ``logging-fstring-interpolation`` FP
  doc/whatsnew/fragments/4984.false_positive
  pylint/checkers/logging.py
  tests/functional/l/logging/logging_fstring_interpolation_py37.py
  tests/functional/l/logging/logging_fstring_interpolation_py37.txt
Labels: False Positive 🦟, backport maintenance/2.15.x

#7836 Feature: distinct Composition and Aggregation arrows
  doc/whatsnew/fragments/6543.feature
  pylint/pyreverse/diagrams.py
  pylint/pyreverse/dot_printer.py
  pylint/pyreverse/inspector.py
  pylint/pyreverse/mermaidjs_printer.py
  pylint/pyreverse/plantuml_printer.py
  pylint/pyreverse/printer.py
  pylint/pyreverse/vcg_printer.py
  pylint/pyreverse/writer.py
  tests/pyreverse/data/classes_No_Name.dot
  tests/pyreverse/data/classes_No_Name.html
  tests/pyreverse/data/classes_No_Name.mmd
  tests/pyreverse/data/classes_No_Name.puml
  tests/pyreverse/data/classes_colorized.dot
  tests/pyreverse/data/classes_colorized.puml
  tests/pyreverse/test_diadefs.py
Labels: Enhancement ✨, topic-pyreverse

#7856 Fix ``dangerous-default-value`` false negative when `*` is used.
  doc/whatsnew/fragments/7818.false_negative
  pylint/checkers/base/basic_checker.py
  tests/functional/d/dangerous_default_value.py
  tests/functional/d/dangerous_default_value.txt
Labels: False Negative 🦋

#7855 Revert "Fix crash when using ``enumerate`` with ``start`` and a class attribute (#7824)"
  doc/whatsnew/fragments/7821.bugfix
  pylint/checkers/refactoring/refactoring_checker.py
  tests/functional/u/unnecessary/unnecessary_list_index_lookup.py
Labels: Maintenance

#7863 `multiple-statements` (`C0321`) now no longer triggers for function stubs using `...`
  doc/whatsnew/fragments/7860.false_positive
  pylint/checkers/format.py
  tests/functional/m/multiple_statements.py
  tests/functional/m/multiple_statements.txt
  tests/functional/m/multiple_statements_single_line.py
  tests/functional/m/multiple_statements_single_line.txt
Labels: False Positive 🦟, backport maintenance/2.15.x

#7845 Bump pylint to 2.15.7, update changelog
  CONTRIBUTORS.txt
  doc/whatsnew/2/2.15/index.rst
  doc/whatsnew/fragments/5886.false_positive
  doc/whatsnew/fragments/6242.bugfix
  doc/whatsnew/fragments/7609.false_positive
  doc/whatsnew/fragments/7828.bugfix
  pylint/__pkginfo__.py
  tbump.toml
Labels: Maintenance

#7861 [doc] clearer message for 'method-cache-max-size-none' warning
  doc/data/messages/m/method-cache-max-size-none/bad.py
  doc/data/messages/m/method-cache-max-size-none/good.py
Labels: Documentation :green_book:, Skip news :mute:

#7756 reimported should detect aliased imports
  doc/data/messages/s/shadowed-import/bad.py
  doc/data/messages/s/shadowed-import/good.py
  doc/user_guide/checkers/features.rst
  doc/user_guide/messages/messages_overview.rst
  doc/whatsnew/fragments/4836.bugfix
  pylint/checkers/imports.py
  tests/functional/i/import_aliasing.py
  tests/functional/r/reimport.txt
  tests/functional/r/reimported.py
  tests/functional/r/reimported.txt
  tests/functional/s/shadowed_import.py
  tests/functional/s/shadowed_import.txt
  tests/functional/u/unused/unused_import.py
  tests/functional/u/unused/unused_import_py30.txt
Labels: False Negative 🦋

#7870 Rephrase Functional tests section in writing_test docs page
  doc/development_guide/contributor_guide/tests/writing_test.rst
Labels: Documentation :green_book:, Skip news :mute:

#7839 Define Protocol as abstract to prevent abstract-method FP
  doc/whatsnew/fragments/7209.false_positive
  pylint/checkers/classes/class_checker.py
  pylint/checkers/utils.py
  tests/functional/p/protocol_classes_abstract.py
  tests/functional/p/protocol_classes_abstract.rc
  tests/functional/p/protocol_classes_abstract.txt
Labels: False Positive 🦟, backport maintenance/2.15.x

#7877 Cut oldstyle checks
  pylint/checkers/classes/class_checker.py
  pylint/checkers/typecheck.py
  pylint/checkers/utils.py
Labels: Maintenance, Skip news :mute:

#7745 add ``redundant-union-assign-typehint`` checker for duplicated assign typehints
  doc/whatsnew/fragments/7636.new_check
  pylint/extensions/typing.py
  tests/functional/ext/typing/redundant_typehint_argument.py
  tests/functional/ext/typing/redundant_typehint_argument.rc
  tests/functional/ext/typing/redundant_typehint_argument.txt
Labels: Enhancement ✨
