Repository pylint-dev/pylint, pull requests merged in 2022-09, with the labels that each got.

#7395 False positive for `too-many-function-args`
  doc/whatsnew/fragments/6592.false_positive
  pylint/checkers/typecheck.py
  tests/functional/a/arguments.py
Labels: False Positive 🦟

#7220 Do not lint ignored file on stdin
  doc/whatsnew/fragments/4354.bugfix
  pylint/lint/pylinter.py
  tests/test_self.py
Labels: Bug :beetle:, topic-command-line, Needs backport

#7406 Complete typing of all generic types
  pylint/checkers/classes/class_checker.py
  pylint/checkers/typecheck.py
  pylint/pyreverse/vcg_printer.py
  pylint/typing.py
  setup.cfg
  tests/checkers/unittest_stdlib.py
  tests/pyreverse/conftest.py
  tests/pyreverse/test_diadefs.py
  tests/pyreverse/test_diagrams.py
  tests/pyreverse/test_inspector.py
  tests/pyreverse/test_main.py
  tests/pyreverse/test_writer.py
  tests/test_import_graph.py
  tests/test_pylint_runners.py
  tests/testutils/test_output_line.py
Labels: Maintenance, Skip news :mute:

#7404 Add typing to ``unittest_config``
  pylint/config/option.py
  tests/config/unittest_config.py
Labels: Maintenance, Skip news :mute:

#7400 Fix #3299 false positives with names in string literal type annotations
  doc/whatsnew/fragments/3299.false_positive
  pylint/checkers/utils.py
  pylint/checkers/variables.py
  tests/checkers/unittest_utils.py
  tests/functional/u/unused/unused_name_in_string_literal_type_annotation.py
  tests/functional/u/unused/unused_name_in_string_literal_type_annotation_py310.py
  tests/functional/u/unused/unused_name_in_string_literal_type_annotation_py310.rc
  tests/functional/u/unused/unused_name_in_string_literal_type_annotation_py38.py
  tests/functional/u/unused/unused_name_in_string_literal_type_annotation_py38.rc
  tests/functional/u/unused/unused_name_in_string_literal_type_annotation_py38.txt
  tests/functional/u/unused/unused_name_in_string_literal_type_annotation_py39.py
  tests/functional/u/unused/unused_name_in_string_literal_type_annotation_py39.rc
Labels: Needs backport, False Positive 🦟

#7359 Trying out codeowners configuration
  .github/CODEOWNERS
Labels: Documentation :green_book:, Maintenance, Skip news :mute:

#7408 Emit `used-before-assignment` when function arguments are redefined in inner function
  doc/whatsnew/fragments/2374.false_negative
  pylint/checkers/utils.py
  tests/functional/u/used/used_before_assignment_nonlocal.py
  tests/functional/u/used/used_before_assignment_nonlocal.txt
Labels: False Negative 🦋

#7409 Add regression test for #3973
  tests/functional/i/invalid/invalid_name/invalid_name-module-disable.py
Labels: Maintenance, tests, Skip news :mute:

#7410 Make ``missing-return-doc`` respect the ``no-docstring-rgx`` option
  doc/whatsnew/fragments/4743.bugfix
  pylint/extensions/docparams.py
  tests/functional/ext/docparams/docparams.py
  tests/functional/ext/docparams/docparams.rc
  tests/functional/ext/docparams/docparams.txt
  tests/functional/ext/docparams/return/missing_return_doc_required.py
Labels: Bug :beetle:, topic-configuration, Needs backport

#7411 Make ``disable-next`` only consider the succeeding line
  doc/whatsnew/fragments/7401.bugfix
  pylint/checkers/variables.py
  pylint/lint/message_state_handler.py
  pylint/utils/file_state.py
  tests/functional/d/disable_msg_next_line.py
  tests/functional/d/disable_msg_next_line.txt
Labels: Bug :beetle:, Needs backport, C: Pragma's

#7421 Make ``missing-yield/raises-doc`` respect ``no-docstring-rgx`` option
  doc/whatsnew/fragments/4743.bugfix
  pylint/extensions/docparams.py
  tests/functional/ext/docparams/raise/missing_raises_doc_required.py
  tests/functional/ext/docparams/yield/missing_yield_doc_required.py
  tests/functional/ext/docparams/yield/missing_yield_doc_required.txt
Labels: Bug :beetle:, topic-configuration, Needs backport

#7413 Add regression test for dataclass kw_only support
  doc/whatsnew/fragments/7290.false_positive
  tests/functional/d/dataclass_kw_only.py
  tests/functional/d/dataclass_kw_only.rc
  tests/functional/d/dataclass_kw_only.txt
Labels: False Positive 🦟, Needs astroid update, topic-dataclasses

#7423 Suppress ``OSError`` in config file discovery
  doc/whatsnew/fragments/7169.bugfix
  pylint/config/find_default_config_files.py
  tests/config/test_find_default_config_files.py
Labels: topic-configuration, Needs backport

#7284 Add more cases that emit bad-plugin-value
  .pyenchant_pylint_custom_dict.txt
  doc/whatsnew/fragments/7264.bugfix
  pylint/lint/pylinter.py
  tests/lint/unittest_lint.py
Labels: Bug :beetle:, topic-configuration

#7431 [towncrier] Add whitespaces between fragment in towncrier
  doc/whatsnew/fragments/_template.rst
  towncrier.toml
Labels: Maintenance, Skip news :mute:

#7407 Turn on ``check-untyped-defs`` in ``mypy``
  doc/exts/pylint_extensions.py
  pylint/checkers/base_checker.py
  pylint/checkers/imports.py
  pylint/checkers/spelling.py
  pylint/checkers/variables.py
  pylint/config/__init__.py
  pylint/config/arguments_manager.py
  pylint/config/configuration_mixin.py
  pylint/config/option.py
  pylint/config/option_manager_mixin.py
  pylint/config/option_parser.py
  pylint/config/options_provider_mixin.py
  setup.cfg
  tests/lint/unittest_expand_modules.py
  tests/pyreverse/test_utils.py
  tests/reporters/unittest_reporting.py
  tests/test_func.py
Labels: Maintenance, Skip news :mute:

#7440 Add typing to several test files
  tests/checkers/unittest_non_ascii_name.py
  tests/checkers/unittest_unicode/unittest_bad_chars.py
  tests/checkers/unittest_unicode/unittest_bidirectional_unicode.py
  tests/checkers/unittest_unicode/unittest_invalid_encoding.py
  tests/conftest.py
  tests/test_func.py
  tests/test_pylint_runners.py
  tests/testutils/test_functional_testutils.py
Labels: Maintenance, Skip news :mute:

#7441 Finish some unfinished typing signatures
  pylint/checkers/similar.py
  pylint/checkers/spelling.py
  pylint/config/callback_actions.py
  pylint/config/deprecation_actions.py
  pylint/config/option.py
  pylint/config/option_manager_mixin.py
  pylint/pyreverse/vcg_printer.py
Labels: Maintenance, Skip news :mute:

#7432 Merge maintenance 2.15.x in main
  .github/workflows/changelog.yml
  .github/workflows/checks.yaml
  .github/workflows/primer-test.yaml
  .github/workflows/primer_comment.yaml
  .github/workflows/primer_run_main.yaml
  .github/workflows/primer_run_pr.yaml
  .github/workflows/tests.yaml
  CONTRIBUTORS.txt
  doc/whatsnew/2/2.15/index.rst
  pyproject.toml
  requirements_test_min.txt
Labels: Maintenance, Skip news :mute:

#7442 Finish some incomplete typing signatures
  pylint/checkers/base/basic_error_checker.py
  pylint/checkers/classes/class_checker.py
  pylint/checkers/typecheck.py
  pylint/checkers/utils.py
  tests/checkers/unittest_unicode/unittest_bad_chars.py
  tests/checkers/unittest_unicode/unittest_functions.py
  tests/config/test_functional_config_loading.py
  tests/extensions/test_private_import.py
  tests/lint/test_pylinter.py
  tests/pyreverse/test_main.py
  tests/pyreverse/test_printer.py
  tests/reporters/unittest_reporting.py
  tests/test_func.py
Labels: Maintenance, Skip news :mute:

#7443 Finish unfinished typing in non core directories
  doc/exts/pylint_extensions.py
  doc/exts/pylint_features.py
  script/create_contributor_list.py
  tests/checkers/base/unittest_base.py
  tests/checkers/unittest_non_ascii_name.py
  tests/checkers/unittest_spelling.py
  tests/checkers/unittest_utils.py
  tests/config/test_find_default_config_files.py
  tests/conftest.py
  tests/extensions/test_check_docs_utils.py
  tests/lint/unittest_expand_modules.py
  tests/message/unittest_message_definition_store.py
  tests/primer/test_primer_stdlib.py
  tests/profile/test_profile_against_externals.py
  tests/pyreverse/test_printer_factory.py
  tests/pyreverse/test_utils.py
  tests/pyreverse/test_writer.py
  tests/reporters/unittest_json_reporter.py
  tests/reporters/unittest_reporting.py
  tests/test_check_parallel.py
  tests/test_func.py
  tests/test_numversion.py
  tests/test_self.py
  tests/test_similar.py
  tests/utils/unittest_ast_walker.py
Labels: Maintenance, Skip news :mute:

#7445 Finish typing of ``typecheck``
  pylint/checkers/typecheck.py
Labels: Maintenance, Skip news :mute:

#7446 Finish typing of ``variables``
  pylint/checkers/variables.py
Labels: Maintenance, Skip news :mute:

#7447 Finish typing across the codebase
  pylint/checkers/classes/class_checker.py
  pylint/checkers/imports.py
  pylint/checkers/refactoring/recommendation_checker.py
  pylint/checkers/refactoring/refactoring_checker.py
  pylint/checkers/similar.py
  pylint/checkers/spelling.py
  pylint/checkers/strings.py
  pylint/config/_pylint_config/__init__.py
  pylint/extensions/emptystring.py
  pylint/lint/pylinter.py
  tests/message/unittest_message_definition.py
Labels: Maintenance, Skip news :mute:

#7448 Turn on ``mypy`` strict mode 🎉
  pylint/checkers/base/name_checker/checker.py
  pylint/checkers/classes/class_checker.py
  pylint/checkers/design_analysis.py
  pylint/checkers/modified_iterating_checker.py
  pylint/checkers/refactoring/refactoring_checker.py
  pylint/checkers/similar.py
  pylint/checkers/spelling.py
  pylint/checkers/typecheck.py
  pylint/checkers/utils.py
  pylint/checkers/variables.py
  pylint/config/configuration_mixin.py
  pylint/config/option.py
  pylint/extensions/_check_docs_utils.py
  pylint/extensions/code_style.py
  pylint/extensions/mccabe.py
  pylint/extensions/private_import.py
  pylint/lint/expand_modules.py
  pylint/lint/pylinter.py
  pylint/pyreverse/diadefslib.py
  pylint/pyreverse/diagrams.py
  pylint/pyreverse/utils.py
  pylint/pyreverse/writer.py
  pylint/testutils/lint_module_test.py
  pylint/utils/file_state.py
  pylint/utils/utils.py
  setup.cfg
  tests/lint/test_pylinter.py
  tests/reporters/unittest_json_reporter.py
  tests/test_pylint_runners.py
  tests/test_self.py
Labels: Maintenance, Skip news :mute:

#7450 Add ``tomlkit`` and ``isort`` to ``mypy`` dependencies
  .pre-commit-config.yaml
  pylint/utils/utils.py
  setup.cfg
Labels: Maintenance, Skip news :mute:

#7451 Add a functional regression test.
  tests/functional/r/regression_02/regression_2964.py
Labels: tests, Skip news :mute:

#7414 Disambiguate between str and enum member args to typing.Literal
  doc/whatsnew/fragments/3299.bugfix
  pylint/checkers/variables.py
  tests/functional/u/unused/unused_name_in_string_literal_type_annotation.py
  tests/functional/u/unused/unused_name_in_string_literal_type_annotation_py38.py
  tests/functional/u/unused/unused_name_in_string_literal_type_annotation_py38.txt
Labels: Needs backport, False Positive 🦟

#7454 Fix `unhashable-member` crash when `lambda` used as a dict key
  doc/whatsnew/fragments/7453.bugfix
  pylint/checkers/utils.py
  tests/functional/u/unhashable_member.py
Labels: Needs backport, Crash 💥

#7455 Fix typevar-rgx description in pylintrc
  pylintrc
Labels: Documentation :green_book:, Skip news :mute:

#7436 Feature italics abstract methods
  doc/whatsnew/fragments/7346.other
  pylint/pyreverse/dot_printer.py
  pylint/pyreverse/mermaidjs_printer.py
  pylint/pyreverse/plantuml_printer.py
  script/.contributors_aliases.json
  tests/pyreverse/data/classes_No_Name.dot
  tests/pyreverse/data/classes_No_Name.html
  tests/pyreverse/data/classes_No_Name.mmd
  tests/pyreverse/data/classes_No_Name.puml
  tests/pyreverse/data/classes_colorized.dot
  tests/pyreverse/data/classes_colorized.puml
  tests/pyreverse/data/packages_No_Name.dot
  tests/pyreverse/data/packages_colorized.dot
  tests/pyreverse/functional/class_diagrams/annotations/attributes_annotation.dot
Labels: Enhancement ✨, topic-pyreverse

#7465 Use stacklevel=2 in warnings.warn calls to DeprecationWarning where makes sense.
  doc/whatsnew/fragments/7463.other
  pylint/checkers/base_checker.py
  pylint/checkers/mapreduce_checker.py
  pylint/checkers/utils.py
  pylint/config/__init__.py
  pylint/config/arguments_manager.py
  pylint/config/arguments_provider.py
  pylint/config/configuration_mixin.py
  pylint/config/find_default_config_files.py
  pylint/config/option.py
  pylint/config/option_manager_mixin.py
  pylint/config/option_parser.py
  pylint/config/options_provider_mixin.py
  pylint/interfaces.py
  pylint/lint/pylinter.py
  pylint/message/message.py
  pylint/reporters/base_reporter.py
  pylint/reporters/text.py
  pylint/testutils/checker_test_case.py
  pylint/testutils/functional_test_file.py
  pylint/testutils/output_line.py
  pylint/utils/file_state.py
  pylint/utils/utils.py
Labels: Maintenance

#7466 add deprecated mailcap module
  doc/whatsnew/fragments/7457.bugfix
  pylint/checkers/imports.py
Labels: False Negative 🦋

#7472 Fix a crash in the `modified-iterating-dict` checker involving instance attributes
  doc/whatsnew/fragments/7461.bugfix
  pylint/checkers/modified_iterating_checker.py
  tests/functional/m/modified_iterating.py
Labels: Needs backport

#7469 Provide more context in these two DeprecationWarning.
  pylint/config/utils.py
Labels: Maintenance, Skip news :mute:

#7475 Add and fix tests for init-hook based plugin load
  doc/whatsnew/fragments/7264.internal
  tests/lint/unittest_lint.py
Labels: Maintenance

#5593 False positive - not callable
  tests/functional/n/not_callable.py
Labels: Bug :beetle:, False Positive 🦟, Needs astroid update, Skip news :mute:

#7480 [openssf] Add the badge for the openssf foundation
  README.rst
Labels: Documentation :green_book:, Skip news :mute:

#7483 Fix the documented shorthand for --reports=y
  doc/user_guide/usage/output.rst
Labels: Documentation :green_book:, Skip news :mute:

#7482 Update W1402 message example to be an actually working code
  doc/data/messages/a/anomalous-unicode-escape-in-string/bad.py
  doc/data/messages/a/anomalous-unicode-escape-in-string/good.py
Labels: Documentation :green_book:, Skip news :mute:

#7479 False positive `global-variable-not-assigned`
  doc/whatsnew/fragments/4809.false_positive
  pylint/checkers/variables.py
  tests/functional/g/globals.py
  tests/functional/g/globals.txt
  tests/functional/u/unused/unused_variable.py
  tests/functional/u/unused/unused_variable.txt
Labels: Needs backport, False Positive 🦟

#7490 Accept a comma-separated list of messages IDs in ``--help-msg``
  doc/whatsnew/fragments/7471.bugfix
  pylint/config/callback_actions.py
  tests/test_self.py
Labels: Bug :beetle:, Needs backport

#7476 Fix `undefined-loop-variable` with `NoReturn` and `Never`
  doc/whatsnew/fragments/7311.false_positive
  pylint/checkers/variables.py
  pylint/constants.py
  pylint/extensions/typing.py
  tests/functional/u/undefined/undefined_loop_variable.py
  tests/functional/u/undefined/undefined_loop_variable.txt
  tests/functional/u/undefined/undefined_loop_variable_py311.py
  tests/functional/u/undefined/undefined_loop_variable_py311.rc
Labels: Needs backport, False Positive 🦟

#7489 Add ``minimal`` option to ``pylint-config``
  doc/whatsnew/fragments/7485.other
  pylint/config/_pylint_config/generate_command.py
  pylint/config/_pylint_config/utils.py
  pylint/config/arguments_manager.py
  tests/config/pylint_config/test_pylint_config_generate.py
Labels: Enhancement ✨, pylint-config

#7493 Post release branch 2.15.3
  .github/workflows/changelog.yml
  .github/workflows/checks.yaml
  .github/workflows/primer-test.yaml
  .github/workflows/primer_comment.yaml
  .github/workflows/primer_run_main.yaml
  .github/workflows/primer_run_pr.yaml
  .github/workflows/tests.yaml
  doc/whatsnew/2/2.15/index.rst
  pyproject.toml
  requirements_test_min.txt
Labels: Maintenance, Skip news :mute:

#7502 Improve docs clarity on loading custom checkers - FIXED
  doc/development_guide/how_tos/custom_checkers.rst
Labels: Documentation :green_book:, Skip news :mute:

#7503 add child class name to abstract-method message
  doc/whatsnew/fragments/7124.other
  pylint/checkers/classes/class_checker.py
  tests/functional/a/abstract/abstract_method.txt
  tests/functional/g/generic_alias/generic_alias_collections.txt
  tests/functional/g/generic_alias/generic_alias_collections_py37.txt
  tests/functional/g/generic_alias/generic_alias_collections_py37_with_typing.txt
  tests/functional/g/generic_alias/generic_alias_mixed_py37.txt
  tests/functional/g/generic_alias/generic_alias_mixed_py39.txt
  tests/functional/g/generic_alias/generic_alias_postponed_evaluation_py37.txt
  tests/functional/g/generic_alias/generic_alias_related.txt
  tests/functional/g/generic_alias/generic_alias_related_py39.txt
  tests/functional/g/generic_alias/generic_alias_typing.txt
Labels: Documentation :green_book:

#7504 Update wording to clarify overriding object.
  doc/whatsnew/fragments/7390.bugfix
  pylint/checkers/classes/class_checker.py
  tests/functional/a/arguments_differ.txt
  tests/functional/a/arguments_renamed.txt
Labels: Documentation :green_book:, Skip news :mute:

#7512 A collection of documentation updates
  README.rst
  doc/data/messages/e/exec-used/details.rst
  doc/development_guide/how_tos/plugins.rst
  doc/user_guide/configuration/index.rst
Labels: Documentation :green_book:, Skip news :mute:

#7513 Migrate configs for isort, mypy, and pytest into pyproject.toml
  pyproject.toml
  setup.cfg
Labels: Maintenance, Skip news :mute:

#7510 Regression test for `unused-import`
  tests/functional/u/unused/unused_import.py
  tests/functional/u/unused/unused_import.txt
Labels: Skip news :mute:

#7385 Add a functional test for bitwise combinations of ``enum.Flag`` members
  tests/functional/e/enum_subclasses.py
Labels: Skip news :mute:

#7514 Add ``consider-using-augmented-assign`` checker
  doc/data/messages/c/consider-using-augmented-assign/bad.py
  doc/data/messages/c/consider-using-augmented-assign/good.py
  doc/whatsnew/fragments/3391.new_check
  pylint/checkers/refactoring/recommendation_checker.py
  pylint/checkers/utils.py
  tests/functional/c/consider/consider_using_augmented_assign.py
  tests/functional/c/consider/consider_using_augmented_assign.txt
  tests/functional/e/e1101_9588_base_attr_aug_assign.py
  tests/functional/i/inconsistent/inconsistent_returns.py
  tests/functional/u/undefined/undefined_variable_py38.py
  tests/functional/u/use/use_maxsplit_arg.py
  tests/functional/u/used/used_before_assignment_conditional.py
  tests/functional/u/used/used_before_assignment_conditional.txt
  tests/functional/u/used/used_before_assignment_nonlocal.py
  tests/test_similar.py
Labels: Enhancement ✨

#7518 Replace no-method-argument with no-self-argument when variadic args present
  doc/whatsnew/fragments/7507.bugfix
  doc/whatsnew/fragments/7507.other
  pylint/checkers/classes/class_checker.py
  tests/functional/m/missing/missing_self_argument.txt
  tests/functional/n/no/no_method_argument_py38.py
  tests/functional/n/no/no_self_argument.py
  tests/functional/n/no/no_self_argument.txt
  tests/functional/n/no/no_self_argument_py37.txt
  tests/functional/r/regression/regression_4723.txt
  tests/functional/u/unexpected_special_method_signature.txt
Labels: Bug :beetle:, Needs backport

#7509 Fix false negative ``no-member`` when the code was a `manual` augmented assignments
  doc/whatsnew/fragments/4562.bugfix
  pylint/checkers/typecheck.py
  tests/functional/n/no/no_member_augassign.py
  tests/functional/n/no/no_member_augassign.txt
Labels: False Negative 🦋

#7531 Hotfix mypy precommit errors for colorama and typing on Windows
  pylint/config/configuration_mixin.py
  pyproject.toml
Labels: Maintenance, Windows 🪟, Skip news :mute:

#7537 Fix bug in detecting ``unused-variable`` when iterating on variable.
  doc/whatsnew/fragments/3044.bugfix
  pylint/checkers/variables.py
  tests/functional/u/unused/unused_variable.py
Labels: Needs backport, False Positive 🦟

#7525 Prevent `redefined-outer-name` for `if t.TYPE_CHECKING`
  doc/whatsnew/fragments/7524.bugfix
  pylint/checkers/variables.py
  tests/functional/r/redefined/redefined_outer_name_type_checking.py
Labels: Needs backport, False Positive 🦟

#7541 bugfix for Attribute.attrname
  doc/whatsnew/fragments/7528.bugfix
  pylint/checkers/modified_iterating_checker.py
  tests/functional/m/modified_iterating.py
  tests/functional/m/modified_iterating.txt
Labels: Needs backport, Crash 💥

#6551 Use 3.11 for Github actions
  .github/workflows/changelog.yml
  .github/workflows/checks.yaml
  .github/workflows/primer-test.yaml
  .github/workflows/primer_comment.yaml
  .github/workflows/primer_run_main.yaml
  .github/workflows/primer_run_pr.yaml
  .github/workflows/release.yml
  .github/workflows/tests.yaml
  doc/whatsnew/fragments/5920.other
  pyproject.toml
  tox.ini
Labels: Maintenance, Needs astroid update, python 3.11
