Repository pylint-dev/pylint, pull requests merged in 2022-06, with the labels that each got.

#6783 Add commit hash in the primer comment
  .github/workflows/primer_comment.yaml
  tests/primer/primer_tool.py
Labels: primer

#6735 [doc] Add a check for changelogs and fix the issues encountered
  .pre-commit-config.yaml
  .pyenchant_pylint_custom_dict.txt
  doc/development_guide/contributor_guide/tests/install.rst
  doc/whatsnew/0/0.x.rst
  doc/whatsnew/1/1.2.rst
  doc/whatsnew/1/1.3.rst
  doc/whatsnew/1/1.4.rst
  doc/whatsnew/1/1.5.rst
  doc/whatsnew/1/1.6/full.rst
  doc/whatsnew/1/1.7/full.rst
  doc/whatsnew/1/1.8/full.rst
  doc/whatsnew/1/1.8/summary.rst
  doc/whatsnew/1/1.9/full.rst
  doc/whatsnew/2/2.0/full.rst
  doc/whatsnew/2/2.1/full.rst
  doc/whatsnew/2/2.10/full.rst
  doc/whatsnew/2/2.10/summary.rst
  doc/whatsnew/2/2.11/full.rst
  doc/whatsnew/2/2.11/summary.rst
  doc/whatsnew/2/2.12/full.rst
  doc/whatsnew/2/2.12/summary.rst
  doc/whatsnew/2/2.13/full.rst
  doc/whatsnew/2/2.13/summary.rst
  doc/whatsnew/2/2.14/full.rst
  doc/whatsnew/2/2.14/summary.rst
  doc/whatsnew/2/2.2/full.rst
  doc/whatsnew/2/2.2/summary.rst
  doc/whatsnew/2/2.3/full.rst
  doc/whatsnew/2/2.4/full.rst
  doc/whatsnew/2/2.4/summary.rst
  doc/whatsnew/2/2.5/full.rst
  doc/whatsnew/2/2.6/full.rst
  doc/whatsnew/2/2.7/full.rst
  doc/whatsnew/2/2.8/full.rst
  doc/whatsnew/2/2.9/full.rst
  script/check_changelog.py
Labels: Documentation 📖

#6786 Bump all cache versions
  .github/workflows/checks.yaml
  .github/workflows/primer-test.yaml
  .github/workflows/primer_comment.yaml
  .github/workflows/primer_run_main.yaml
  .github/workflows/primer_run_pr.yaml
  .github/workflows/tests.yaml
Labels: Maintenance

#6797 Rename clashing import name in one test case
  tests/functional/r/regression/regression_4680.py
  tests/functional/r/regression/regression_4680.txt
Labels: Maintenance, Solaris

#6806 Don't crash if we can't find the user's home directory
  doc/whatsnew/2/2.14/full.rst
  pylint/config/find_default_config_files.py
  tests/config/test_find_default_config_files.py
Labels: Needs Backport, Regression, Crash 💥

#6807 Updated link in README
  .github/CONTRIBUTING.md
  README.rst
Labels: Documentation 📖

#6814 Add disable and exclude pylint files in CI
  .pre-commit-config.yaml
  pylint/checkers/base/__init__.py
Labels: Maintenance

#6801 Fix parsing of unrelated options in tox.ini
  doc/whatsnew/2/2.14/full.rst
  pylint/config/config_file_parser.py
  tests/config/functional/tox/unrecognized_options/tox.ini
  tests/config/functional/tox/unrecognized_options/tox.result.json
Labels: topic-configuration, Needs Backport, Regression

#6819 [check-changelog] Temporarily remove the check in wait of #6688
  .pre-commit-config.yaml
  script/check_changelog.py
Labels: Maintenance

#6820 Fix the use of abbreviations for preprocessable options on the CLI
  doc/whatsnew/2/2.14/full.rst
  pylint/config/utils.py
  tests/config/test_find_default_config_files.py
Labels: Bug 🪳, topic-configuration, Needs Backport

#6808 Prevent warnings on dict / list index lookup with destructuring assignment
  doc/whatsnew/2/2.14/full.rst
  pylint/checkers/refactoring/refactoring_checker.py
  tests/functional/u/unnecessary/unnecessary_dict_index_lookup.py
  tests/functional/u/unnecessary/unnecessary_list_index_lookup.py
Labels: Needs Backport, False Positive 🦟

#6827 [spellcheck] Fix the spellcheck hopefully for all environnements
  pylint/config/utils.py
Labels: Maintenance

#6652 Emit `modified-iterating-{list|dict|set}` when iterating literals or using `del`
  doc/whatsnew/2/2.15/index.rst
  pylint/checkers/modified_iterating_checker.py
  pylint/checkers/utils.py
  pylint/checkers/variables.py
  tests/functional/m/modified_iterating.py
  tests/functional/m/modified_iterating.txt
Labels: False Negative 🦋

#6789 Store namespaces respective to directories
  .pyenchant_pylint_custom_dict.txt
  pylint/config/arguments_manager.py
  pylint/config/config_initialization.py
  pylint/lint/pylinter.py
  pylint/lint/utils.py
  pylint/typing.py
  tests/config/test_per_directory_config.py
Labels: topic-per-directory-config

#6831 Move changelog to 2.14.1 for #6790 fix
  doc/whatsnew/2/2.14/full.rst
Labels: Documentation 📖, Needs Backport

#6830 Fix a crash in the optional `private_import` extension
  doc/whatsnew/2/2.14/full.rst
  pylint/extensions/private_import.py
  tests/functional/ext/private_import/private_import.py
Labels: Needs Backport, Crash 💥

#6829 [bad-option-value] Use the right confidence and refactor message
  pylint/lint/message_state_handler.py
  pylint/lint/pylinter.py
  tests/config/functional/ini/pylintrc_with_deleted_message.2.out
  tests/config/functional/ini/pylintrc_with_missing_comma.2.out
  tests/config/functional/setup_cfg/do_not_read_other_tools_configuration/setup.2.out
  tests/config/functional/toml/issue_3122/toml_with_missing_comma.2.out
  tests/config/functional/toml/unknown_msgid/enable_unknown_msgid.2.out
  tests/config/test_config.py
  tests/functional/b/bad_option_value.py
  tests/functional/b/bad_option_value.txt
  tests/functional/b/bad_option_value_disable.txt
  tests/functional/u/use/use_symbolic_message_instead.txt
Labels: Documentation 📖, Needs Backport, Maintenance

#6835 Add `redefined-builtin` example
  doc/data/messages/r/redefined-builtin/bad.py
  doc/data/messages/r/redefined-builtin/details.rst
  doc/data/messages/r/redefined-builtin/good.py
Labels: Documentation 📖

#6834 Add `unused-argument` example
  doc/data/messages/u/unused-argument/bad.py
  doc/data/messages/u/unused-argument/details.rst
  doc/data/messages/u/unused-argument/good.py
Labels: Documentation 📖

#6838 Add `use-implicit-booleaness-not-len` example
  doc/data/messages/u/use-implicit-booleaness-not-len/bad.py
  doc/data/messages/u/use-implicit-booleaness-not-len/details.rst
  doc/data/messages/u/use-implicit-booleaness-not-len/good.py
Labels: Documentation 📖

#6837 Add `unused-variable` example
  doc/data/messages/u/unused-variable/bad.py
  doc/data/messages/u/unused-variable/details.rst
  doc/data/messages/u/unused-variable/good.py
Labels: Documentation 📖

#6836 Add `trailing-whitespace` example
  .pre-commit-config.yaml
  doc/data/messages/t/trailing-whitespace/bad.py
  doc/data/messages/t/trailing-whitespace/details.rst
  doc/data/messages/t/trailing-whitespace/good.py
Labels: Documentation 📖

#6841 Add `unexpected-keyword-arg` example
  doc/data/messages/u/unexpected-keyword-arg/bad.py
  doc/data/messages/u/unexpected-keyword-arg/details.rst
  doc/data/messages/u/unexpected-keyword-arg/good.py
Labels: Documentation 📖

#6842 Add `single-string-used-for-slots` example
  doc/data/messages/s/single-string-used-for-slots/bad.py
  doc/data/messages/s/single-string-used-for-slots/details.rst
  doc/data/messages/s/single-string-used-for-slots/good.py
Labels: Documentation 📖

#6843 Add `unused-format-string-argument` example
  doc/data/messages/u/unused-format-string-argument/bad.py
  doc/data/messages/u/unused-format-string-argument/details.rst
  doc/data/messages/u/unused-format-string-argument/good.py
Labels: Documentation 📖

#6844 Add `unnecessary-lambda` example
  doc/data/messages/u/unnecessary-lambda/bad.py
  doc/data/messages/u/unnecessary-lambda/details.rst
  doc/data/messages/u/unnecessary-lambda/good.py
Labels: Documentation 📖

#6846 Added documentation examples for `expression-not-assigned`.
  doc/data/messages/e/expression-not-assigned/bad.py
  doc/data/messages/e/expression-not-assigned/details.rst
  doc/data/messages/e/expression-not-assigned/good.py
Labels: Documentation 📖

#6852 Add `redefined-variable-type` example
  doc/data/messages/r/redefined-variable-type/bad.py
  doc/data/messages/r/redefined-variable-type/details.rst
  doc/data/messages/r/redefined-variable-type/good.py
Labels: Documentation 📖

#6849 Add `format-needs-mapping` example
  doc/data/messages/f/format-needs-mapping/bad.py
  doc/data/messages/f/format-needs-mapping/details.rst
  doc/data/messages/f/format-needs-mapping/good.py
Labels: Documentation 📖

#6839 Add `trailing-newlines` example
  .pre-commit-config.yaml
  doc/data/messages/t/trailing-newlines/bad.py
  doc/data/messages/t/trailing-newlines/details.rst
  doc/data/messages/t/trailing-newlines/good.py
  doc/exts/pylint_messages.py
Labels: Documentation 📖

#6854 Add `keyword-arg-before-vararg` example
  doc/data/messages/k/keyword-arg-before-vararg/bad.py
  doc/data/messages/k/keyword-arg-before-vararg/details.rst
  doc/data/messages/k/keyword-arg-before-vararg/good.py
Labels: Documentation 📖

#6855 Add `raising-non-exception` example
  doc/data/messages/r/raising-non-exception/bad.py
  doc/data/messages/r/raising-non-exception/details.rst
  doc/data/messages/r/raising-non-exception/good.py
Labels: Documentation 📖

#6847 Add `subprocess-run-check` example
  doc/data/messages/s/subprocess-run-check/bad.py
  doc/data/messages/s/subprocess-run-check/details.rst
  doc/data/messages/s/subprocess-run-check/good.py
Labels: Documentation 📖

#6850 Add `missing-format-attribute` example
  doc/data/messages/m/missing-format-attribute/bad.py
  doc/data/messages/m/missing-format-attribute/details.rst
  doc/data/messages/m/missing-format-attribute/good.py
Labels: Documentation 📖

#6848 Add `f-string-without-interpolation` example
  doc/data/messages/f/f-string-without-interpolation/bad.py
  doc/data/messages/f/f-string-without-interpolation/details.rst
  doc/data/messages/f/f-string-without-interpolation/good.py
Labels: Documentation 📖

#6851 Add `overlapping-except` example
  doc/data/messages/o/overlapping-except/bad.py
  doc/data/messages/o/overlapping-except/details.rst
  doc/data/messages/o/overlapping-except/good.py
  doc/data/messages/o/overlapping-except/related.rst
Labels: Documentation 📖

#6853 Add `repeated-keyword` example
  doc/data/messages/r/repeated-keyword/bad.py
  doc/data/messages/r/repeated-keyword/details.rst
  doc/data/messages/r/repeated-keyword/good.py
Labels: Documentation 📖

#6857 Added documentation examples for `global-variable-not-assigned`.
  doc/data/messages/g/global-variable-not-assigned/bad.py
  doc/data/messages/g/global-variable-not-assigned/details.rst
  doc/data/messages/g/global-variable-not-assigned/good.py
Labels: Documentation 📖

#6858 Added documentation examples for `global-variable-undefined`.
  doc/data/messages/g/global-variable-undefined/bad.py
  doc/data/messages/g/global-variable-undefined/details.rst
  doc/data/messages/g/global-variable-undefined/good.py
Labels: Documentation 📖

#6859 Added documentation examples for `used-prior-global-declaration`.
  doc/data/messages/u/used-prior-global-declaration/bad.py
  doc/data/messages/u/used-prior-global-declaration/details.rst
  doc/data/messages/u/used-prior-global-declaration/good.py
Labels: Documentation 📖

#6863 Add `multiple-imports` example
  .pre-commit-config.yaml
  doc/data/messages/m/multiple-imports/bad.py
  doc/data/messages/m/multiple-imports/details.rst
  doc/data/messages/m/multiple-imports/good.py
Labels: Documentation 📖

#6862 Add `no-self-argument` example
  doc/data/messages/n/no-self-argument/bad.py
  doc/data/messages/n/no-self-argument/details.rst
  doc/data/messages/n/no-self-argument/good.py
Labels: Documentation 📖

#6822 typecheck/Enum: fix crash in Enum attributes check
  doc/whatsnew/2/2.14/full.rst
  pylint/checkers/typecheck.py
  tests/functional/e/enum_self_defined_member_6805.py
  tests/functional/e/enum_self_defined_member_6805.txt
Labels: Needs Backport, Crash 💥

#6867 Print the launched command in doc examples tests
  doc/test_messages_documentation.py
Labels: Needs Backport, Maintenance

#6869 Better target DeprecationWarnings in pyreverse
  pylint/pyreverse/inspector.py
Labels: topic-pyreverse, Needs Backport, Maintenance

#6665 Remove redundant options documentation and improve formatting
  doc/exts/pylint_extensions.py
  doc/exts/pylint_features.py
  doc/exts/pylint_options.py
  doc/user_guide/checkers/extensions.rst
  doc/user_guide/checkers/features.rst
  doc/user_guide/configuration/all-options.rst
  pylint/checkers/base_checker.py
  pylint/utils/docs.py
Labels: Documentation 📖

#6873 [doc] Fix the assert for placeholders following #6839
  doc/exts/pylint_messages.py
Labels: Bug 🪳, Documentation 📖, Maintenance

#6874 Add `implicit-str-concat` example
  doc/data/messages/i/implicit-str-concat/bad.py
  doc/data/messages/i/implicit-str-concat/details.rst
  doc/data/messages/i/implicit-str-concat/good.py
Labels: Documentation 📖

#6787 Prevent `unused-import` for `if t.TYPE_CHECKING`
  doc/whatsnew/2/2.14/full.rst
  pylint/checkers/utils.py
  tests/functional/u/unused/unused_import.py
  tests/functional/u/unused/unused_import.txt
Labels: Needs Backport, False Positive 🦟

#6881 Add documentation examples for `dangerous-default-value`.
  doc/data/messages/d/dangerous-default-value/bad.py
  doc/data/messages/d/dangerous-default-value/details.rst
  doc/data/messages/d/dangerous-default-value/good.py
Labels: Documentation 📖

#6893 Add typing to extensions
  pylint/extensions/_check_docs_utils.py
  pylint/extensions/broad_try_clause.py
  pylint/extensions/check_elif.py
  pylint/extensions/docparams.py
  pylint/extensions/redefined_variable_type.py
Labels: topic-typing

#6899 [primer] Truncate comments that are too long for github
  tests/primer/primer_tool.py
Labels: primer

#6897 [primer] stop overwriting `--rcfile`
  tests/primer/primer_tool.py
Labels: primer

#6905 [refactor] Create a primer package in 'pylint.testutils'
  doc/whatsnew/2/2.15/index.rst
  pylint/testutils/_primer/__init__.py
  pylint/testutils/_primer/package_to_lint.py
  tests/primer/primer_tool.py
  tests/primer/test_primer_external.py
  tests/testutils/_primer/test_package_to_lint.py
Labels: Maintenance

#6904 Factor out `_defines_name_raises_or_returns_recursive`
  pylint/checkers/variables.py
Labels: topic-performance, C: used-before-assignment, skip news :mute:

#6910 Avoid `used-before-assignment` in except handlers employing type annotations
  doc/whatsnew/2/2.14/full.rst
  pylint/checkers/variables.py
  tests/functional/u/used/used_before_assignment_except_handler_for_try_with_return.py
  tests/functional/u/used/used_before_assignment_except_handler_for_try_with_return.txt
Labels: Needs Backport, False Positive 🦟, C: used-before-assignment

#6845 Suppress ``unnecessary-list-index-lookup`` for whole loop on write
  doc/whatsnew/2/2.14/full.rst
  pylint/checkers/refactoring/refactoring_checker.py
  tests/functional/u/unnecessary/unnecessary_dict_index_lookup.py
  tests/functional/u/unnecessary/unnecessary_list_index_lookup.py
  tests/functional/u/unnecessary/unnecessary_list_index_lookup.txt
Labels: False Positive 🦟

#6912 Add `empty-comment` example
  doc/data/messages/e/empty-comment/bad.py
  doc/data/messages/e/empty-comment/details.rst
  doc/data/messages/e/empty-comment/good.py
  doc/data/messages/e/empty-comment/pylintrc
  doc/data/messages/t/trailing-newlines/bad.py
  doc/test_messages_documentation.py
Labels: Documentation 📖

#6913 Add `eval-used` example
  doc/data/messages/e/eval-used/bad.py
  doc/data/messages/e/eval-used/details.rst
  doc/data/messages/e/eval-used/good.py
Labels: Documentation 📖

#6907 Move the primer helpers from ``tests/`` to ``pylint.testutil._primer``
  .github/workflows/primer_comment.yaml
  .github/workflows/primer_run_main.yaml
  .github/workflows/primer_run_pr.yaml
  pylint/testutils/_primer/primer.py
  tests/primer/__main__.py
Labels: Maintenance

#6911 Emit `using-constant-test` when testing truth value of a call returning a generator
  doc/whatsnew/2/2.15/index.rst
  pylint/checkers/base/basic_checker.py
  tests/functional/m/missing/missing_parentheses_for_call_in_test.txt
  tests/functional/u/using_constant_test.py
  tests/functional/u/using_constant_test.txt
Labels: Enhancement ✨

#6914 Fixed misinterpreted modulo sign for ``consider-using-f-string``
  doc/whatsnew/2/2.14/full.rst
  pylint/checkers/refactoring/recommendation_checker.py
  tests/functional/c/consider/consider_using_f_string.py
  tests/functional/c/consider/consider_using_f_string.txt
Labels: Needs Backport, False Positive 🦟

#6903 Prevent pylint.run._cpu_count() from returning 0
  doc/whatsnew/2/2.14/full.rst
  pylint/lint/run.py
  tests/test_pylint_runners.py
Labels: Bug 🪳, Needs Backport

#6922 Add `format-string-without-interpolation` example
  doc/data/messages/f/format-string-without-interpolation/bad.py
  doc/data/messages/f/format-string-without-interpolation/details.rst
  doc/data/messages/f/format-string-without-interpolation/good.py
Labels: Documentation 📖

#6920 Add `mixed-format-string` example
  doc/data/messages/m/mixed-format-string/bad.py
  doc/data/messages/m/mixed-format-string/details.rst
  doc/data/messages/m/mixed-format-string/good.py
Labels: Documentation 📖

#6919 Add `too-many-branches` example
  doc/data/messages/t/too-many-branches/bad.py
  doc/data/messages/t/too-many-branches/details.rst
  doc/data/messages/t/too-many-branches/good.py
  doc/data/messages/t/too-many-branches/pylintrc
Labels: Documentation 📖

#6921 Add `multiple-constructor-doc` example
  doc/data/messages/m/multiple-constructor-doc/bad.py
  doc/data/messages/m/multiple-constructor-doc/details.rst
  doc/data/messages/m/multiple-constructor-doc/good.py
  doc/data/messages/m/multiple-constructor-doc/pylintrc
Labels: Documentation 📖

#6915 Warn about self-referencing named expressions lacking prior assignments
  doc/whatsnew/2/2.15/index.rst
  pylint/checkers/variables.py
  tests/functional/u/undefined/undefined_variable_py38.py
  tests/functional/u/undefined/undefined_variable_py38.txt
Labels: False Negative 🦋, C: used-before-assignment

#6924 Dunder methods: Fix typo in details about the error.
  pylint/checkers/dunder_methods.py
Labels: Documentation 📖

#6925 Avoid raising `undefined-loop-variable` twice on same line
  doc/whatsnew/2/2.14/full.rst
  pylint/checkers/variables.py
  tests/functional/u/undefined/undefined_loop_variable.py
  tests/functional/u/undefined/undefined_loop_variable.txt
Labels: Needs Backport, False Positive 🦟

#6927 Add `shallow-copy-environ` example
  doc/data/messages/s/shallow-copy-environ/bad.py
  doc/data/messages/s/shallow-copy-environ/details.rst
  doc/data/messages/s/shallow-copy-environ/good.py
Labels: Documentation 📖

#6926 Add `misplaced-bare-raise` example
  doc/data/messages/m/misplaced-bare-raise/bad.py
  doc/data/messages/m/misplaced-bare-raise/details.rst
  doc/data/messages/m/misplaced-bare-raise/good.py
  doc/data/messages/m/misplaced-future/details.rst
Labels: Documentation 📖

#6923 Add `undefined-loop-variable` example
  doc/data/messages/u/undefined-loop-variable/bad.py
  doc/data/messages/u/undefined-loop-variable/details.rst
  doc/data/messages/u/undefined-loop-variable/good.py
Labels: Documentation 📖

#6933 Added documentation examples for `invalid-slice-index`.
  doc/data/messages/i/invalid-slice-index/bad.py
  doc/data/messages/i/invalid-slice-index/details.rst
  doc/data/messages/i/invalid-slice-index/good.py
Labels: Documentation 📖

#6930 Add `bad-inline-option` example
  doc/data/messages/b/bad-inline-option/bad.py
  doc/data/messages/b/bad-inline-option/details.rst
  doc/data/messages/b/bad-inline-option/good.py
Labels: Documentation 📖

#6928 Add `used-before-assignment` example
  doc/data/messages/u/used-before-assignment/bad.py
  doc/data/messages/u/used-before-assignment/details.rst
  doc/data/messages/u/used-before-assignment/good.py
Labels: Documentation 📖

#6892 [refactor] Make sure we have the expected typing in visitors
  pylint/checkers/exceptions.py
  pylint/checkers/refactoring/refactoring_checker.py
  pylint/checkers/spelling.py
  pylint/checkers/typecheck.py
  pylint/checkers/variables.py
  pylint/extensions/broad_try_clause.py
  pylint/extensions/docparams.py
Labels: Maintenance

#6916 Emit `using-constant-test` when testing truth value of a variable holding a generator
  doc/whatsnew/2/2.15/index.rst
  pylint/checkers/base/basic_checker.py
  tests/functional/ext/docparams/raise/missing_raises_doc_Google.txt
  tests/functional/u/using_constant_test.py
  tests/functional/u/using_constant_test.txt
Labels: Enhancement ✨

#6891 Makes functional tests auto-update works even if the current output is wrong
  doc/whatsnew/2/2.15/index.rst
  pylint/testutils/output_line.py
  tests/testutils/test_output_line.py
Labels: Maintenance

#6932 Mark `no-self-use` as moved to extensions
  pylint/config/callback_actions.py
  pylint/exceptions.py
  pylint/lint/message_state_handler.py
  pylint/message/_deleted_message_ids.py
  pylint/message/message_id_store.py
  tests/functional/b/bad_option_value.py
  tests/functional/b/bad_option_value.txt
Labels: Needs Backport, Maintenance

#6945 Search for successful instead of completed runs on ``main`` for primer
  .github/workflows/primer_run_pr.yaml
Labels: primer

#6898 Add regression test for #6895
  doc/whatsnew/2/2.14/full.rst
  requirements_test_min.txt
  setup.cfg
  tests/functional/u/unused/unused_variable_after_inference.py
  tests/functional/u/unused/unused_variable_after_inference.rc
Labels: Needs Backport, False Positive 🦟, Requires Astroid Update

#6944 Mix incorrect parsing of multi-line options in ``ini`` files
  doc/whatsnew/2/2.14/full.rst
  pylint/config/config_file_parser.py
  pylint/config/config_initialization.py
  tests/config/functional/ini/pylintrc_with_missing_comma.4.out
  tests/config/functional/ini/pylintrc_with_multi_line_init_hook.ini
Labels: Bug 🪳, Needs Backport, Regression

#6937 Treat `--errors-only` as a disable, not a paired enable/disable
  doc/whatsnew/2/2.14/full.rst
  pylint/lint/base_options.py
  pylint/lint/message_state_handler.py
  tests/test_self.py
Labels: Bug 🪳, topic-configuration, Needs Backport

#6952 Add doc example for 'useless-super-delegation'
  doc/data/messages/u/useless-super-delegation/bad.py
  doc/data/messages/u/useless-super-delegation/details.rst
  doc/data/messages/u/useless-super-delegation/good.py
  doc/data/messages/u/useless-super-delegation/related.rst
Labels: Documentation 📖

#6949 Fix false positive for ``useless-super-delegation`` for variadics
  doc/whatsnew/2/2.14/full.rst
  pylint/checkers/classes/class_checker.py
  tests/functional/u/useless/useless_super_delegation.py
  tests/functional/u/useless/useless_super_delegation.txt
Labels: Bug 🪳, Needs Backport, False Positive 🦟

#6957 Fix ``undefined-variable`` for ``__class__`` in inner methods
  doc/whatsnew/2/2.14/full.rst
  pylint/checkers/variables.py
  tests/functional/u/undefined/undefined_variable.py
  tests/functional/u/undefined/undefined_variable.txt
Labels: Needs Backport, False Positive 🦟

#6958 Emit `used-before-assignment` for self-referencing assignments under if conditions
  doc/whatsnew/2/2.15/index.rst
  pylint/checkers/utils.py
  pylint/checkers/variables.py
  tests/functional/u/undefined/undefined_variable_py38.py
  tests/functional/u/undefined/undefined_variable_py38.txt
  tests/functional/u/used/used_before_assignment_conditional.py
  tests/functional/u/used/used_before_assignment_conditional.txt
Labels: False Negative 🦋, C: used-before-assignment

#6956 Fix ``bad-super-call`` for non-direct parents
  doc/data/messages/b/bad-super-call/bad.py
  doc/data/messages/b/bad-super-call/details.rst
  doc/data/messages/b/bad-super-call/good.py
  doc/whatsnew/2/2.14/full.rst
  pylint/checkers/newstyle.py
  tests/functional/s/super/super_checks.py
  tests/functional/s/super/super_checks.txt
Labels: Bug 🪳, Needs Backport, False Positive 🦟

#6693 Add support of sharing message in multiple checkers. Fix DeprecatedChecker example
  doc/exts/pylint_messages.py
  examples/deprecation_checker.py
  pylint/checkers/base_checker.py
  pylint/checkers/deprecated.py
  pylint/checkers/imports.py
  pylint/checkers/stdlib.py
  pylint/message/message_definition.py
  pylint/typing.py
  tests/message/unittest_message_definition.py
  tests/message/unittest_message_id_store.py
  tests/pyreverse/functional/class_diagrams/colorized_output/colorized.puml
Labels: Bug 🪳, Documentation 📖

#6959 Emit `used-before-assignment` when calling nested functions before assignment
  doc/whatsnew/2/2.15/index.rst
  pylint/checkers/variables.py
  tests/functional/u/used/used_before_assignment.py
  tests/functional/u/used/used_before_assignment.txt
Labels: False Negative 🦋, C: used-before-assignment

#6960 Add small code sample to custom checker documentation
  doc/development_guide/how_tos/custom_checkers.rst
Labels: Documentation 📖

#6966 Update refactoring_checker.py
  pylint/checkers/refactoring/refactoring_checker.py
Labels: Documentation 📖

#6947 [Docs] Move Message definition to separate section, add extra options
  doc/development_guide/how_tos/custom_checkers.rst
Labels: Documentation 📖

#6969 [primer] Add tests for the primer comment generated for PR
  tests/testutils/_primer/fixtures/both_empty/expected.txt
  tests/testutils/_primer/fixtures/both_empty/main.json
  tests/testutils/_primer/fixtures/both_empty/pr.json
  tests/testutils/_primer/fixtures/message_changed/expected.txt
  tests/testutils/_primer/fixtures/message_changed/main.json
  tests/testutils/_primer/fixtures/message_changed/pr.json
  tests/testutils/_primer/fixtures/no_change/expected.txt
  tests/testutils/_primer/fixtures/no_change/main.json
  tests/testutils/_primer/fixtures/no_change/pr.json
  tests/testutils/_primer/test_primer.py
Labels: Maintenance, primer

#6970 Pin ``colorama`` to lowest supported version
  setup.cfg
Labels: Needs Backport, dependency

#6971 Fix ``undefined-loop-variable`` and ``useless-suppression``
  doc/whatsnew/2/2.14/full.rst
  pylint/checkers/variables.py
Labels: Needs Backport, False Positive 🦟

#6975 Update docstring of `_check_keyword_parentheses`
  pylint/checkers/format.py
Labels: Documentation 📖

#6976 Import and extend superfluous parens examples
  doc/data/messages/s/superfluous-parens/bad.py
  doc/data/messages/s/superfluous-parens/details.rst
  doc/data/messages/s/superfluous-parens/good.py
Labels: Documentation 📖

#6977 [release doc] Add instruction for readthedoc cleanup
  doc/development_guide/contributor_guide/release.md
Labels: Documentation 📖, Maintenance

#6981 Clean up and add typing to the ``mccabe`` extension
  pylint/extensions/mccabe.py
Labels: topic-typing

#6995 [doc] spelling fixes
  doc/data/messages/l/logging-not-lazy/bad.py
  doc/data/messages/l/logging-not-lazy/good.py
  doc/data/messages/l/logging-too-few-args/bad.py
  doc/data/messages/l/logging-too-few-args/good.py
  doc/data/messages/l/logging-too-many-args/bad.py
  doc/data/messages/l/logging-too-many-args/good.py
  doc/whatsnew/1/1.8/full.rst
  doc/whatsnew/2/2.12/full.rst
  doc/whatsnew/2/2.12/summary.rst
  doc/whatsnew/2/2.13/full.rst
  doc/whatsnew/2/2.13/summary.rst
Labels: Documentation 📖

#6997 [doc] Add some examples for 'stop-iteration-return'
  doc/data/messages/s/stop-iteration-return/bad.py
  doc/data/messages/s/stop-iteration-return/details.rst
  doc/data/messages/s/stop-iteration-return/good.py
  doc/data/messages/s/stop-iteration-return/related.rst
Labels: Documentation 📖

#6998 Fix homepage link
  setup.cfg
Labels: Bug 🪳, Documentation 📖, Skip news :mute:

#7001 [chained-comparison] [consider-using-dict-comprehension] [consider-using-set-comprehension] Add whitespaces in the message description
  pylint/checkers/refactoring/refactoring_checker.py
Labels: Documentation 📖

#7002 Add whitespace to some message description
  pylint/checkers/refactoring/implicit_booleaness_checker.py
Labels: Documentation :green_book:

#6664 Fix ``unsupported-binary-operation`` on classes that overload or
  doc/whatsnew/2/2.15/index.rst
  pylint/checkers/typecheck.py
  tests/functional/a/alternative/alternative_union_syntax.py
  tests/functional/a/alternative/alternative_union_syntax_error.py
  tests/functional/a/alternative/alternative_union_syntax_error.txt
Labels: Bug :beetle:, False Positive 🦟

#6780 [ADD] missing-timeout: Used when a method calls an external request
  CONTRIBUTORS.txt
  doc/data/messages/m/missing-timeout/bad.py
  doc/data/messages/m/missing-timeout/details.rst
  doc/data/messages/m/missing-timeout/good.py
  doc/whatsnew/2/2.15/index.rst
  pylint/checkers/method_args.py
  requirements_test_min.txt
  tests/functional/m/missing/missing_timeout.py
  tests/functional/m/missing/missing_timeout.txt
Labels: Enhancement ✨, Optional Checkers

#6980 Fix differing param doc false positive
  doc/whatsnew/2/2.15/index.rst
  pylint/extensions/docparams.py
  tests/functional/ext/docparams/docparams.py
  tests/functional/ext/docparams/docparams.txt
  tests/functional/ext/docparams/docparams_py38.py
  tests/functional/ext/docparams/docparams_py38.rc
  tests/functional/ext/docparams/docparams_py38.txt
Labels: Needs backport, False Positive 🦟

#7009 Add whitespace/punctuation to some message descriptions
  pylint/checkers/base/comparison_checker.py
  pylint/checkers/base/docstring_checker.py
  pylint/checkers/base_checker.py
  pylint/checkers/imports.py
  pylint/checkers/stdlib.py
Labels: Maintenance

#6979 Emit `used-before-assignment` when reimporting later in a function
  doc/whatsnew/2/2.15/index.rst
  pylint/checkers/variables.py
  tests/functional/u/used/used_before_assignment.py
  tests/functional/u/used/used_before_assignment.txt
Labels: False Negative 🦋

#7010 Fix handling of quoted ``init-hook``
  doc/whatsnew/2/2.14/full.rst
  pylint/config/config_initialization.py
  tests/config/functional/ini/pylintrc_with_quoted_init_hook.0.out
  tests/config/functional/ini/pylintrc_with_quoted_init_hook.ini
Labels: Needs backport, Regression

#7014 Add documentation examples for `bad-docstring-quotes`
  doc/data/messages/b/bad-docstring-quotes/bad.py
  doc/data/messages/b/bad-docstring-quotes/details.rst
  doc/data/messages/b/bad-docstring-quotes/good.py
  doc/data/messages/b/bad-docstring-quotes/pylintrc
  doc/data/messages/b/bad-docstring-quotes/related.rst
Labels: Documentation :green_book:

#7016 Add documentation examples for `consider-swap-variables`
  doc/data/messages/c/consider-swap-variables/bad.py
  doc/data/messages/c/consider-swap-variables/details.rst
  doc/data/messages/c/consider-swap-variables/good.py
Labels: Documentation :green_book:

#7021 Add documentation examples for `inherit-non-class`
  doc/data/messages/i/inherit-non-class/bad.py
  doc/data/messages/i/inherit-non-class/details.rst
  doc/data/messages/i/inherit-non-class/good.py
Labels: Documentation :green_book:

#7017 Add documentation examples for `duplicate-except`
  doc/data/messages/d/duplicate-except/bad.py
  doc/data/messages/d/duplicate-except/details.rst
  doc/data/messages/d/duplicate-except/good.py
Labels: Documentation :green_book:

#7024 Add documentation examples for `invalid-envvar-default`
  doc/data/messages/i/invalid-envvar-default/bad.py
  doc/data/messages/i/invalid-envvar-default/details.rst
  doc/data/messages/i/invalid-envvar-default/good.py
Labels: Documentation :green_book:

#7031 Add documentation examples for `invalid-unary-operand-type`
  doc/data/messages/i/invalid-unary-operand-type/bad.py
  doc/data/messages/i/invalid-unary-operand-type/details.rst
  doc/data/messages/i/invalid-unary-operand-type/good.py
Labels: Documentation :green_book:

#7026 Add documentation examples for `invalid-format-index`
  doc/data/messages/i/invalid-format-index/bad.py
  doc/data/messages/i/invalid-format-index/details.rst
  doc/data/messages/i/invalid-format-index/good.py
Labels: Documentation :green_book:

#7025 Add documentation examples for `invalid-envvar-value`
  doc/data/messages/i/invalid-envvar-value/bad.py
  doc/data/messages/i/invalid-envvar-value/details.rst
  doc/data/messages/i/invalid-envvar-value/good.py
Labels: Documentation :green_book:

#7029 Add documentation examples for `invalid-sequence-index`
  doc/data/messages/i/invalid-sequence-index/bad.py
  doc/data/messages/i/invalid-sequence-index/details.rst
  doc/data/messages/i/invalid-sequence-index/good.py
Labels: Documentation :green_book:

#7023 Add documentation examples for `invalid-all-object`
  doc/data/messages/i/invalid-all-object/bad.py
  doc/data/messages/i/invalid-all-object/details.rst
  doc/data/messages/i/invalid-all-object/good.py
  doc/data/messages/i/invalid-all-object/related.rst
Labels: Documentation :green_book:

#7033 Added documentation examples for `unhashable-dict-key`.
  doc/data/messages/u/unhashable-dict-key/bad.py
  doc/data/messages/u/unhashable-dict-key/details.rst
  doc/data/messages/u/unhashable-dict-key/good.py
Labels: Documentation :green_book:

#7012 Prevent additional `unsupported-binary-operation` messages for metaclasses defining `__or__`
  pylint/checkers/typecheck.py
  tests/functional/a/alternative/alternative_union_syntax_error.py
  tests/functional/a/alternative/alternative_union_syntax_error.txt
  tests/functional/a/alternative/alternative_union_syntax_py37.txt
Labels: False Positive 🦟

#7038 Fix spelling in `invalid-sequence-index` `details.rst`
  doc/data/messages/i/invalid-sequence-index/details.rst
Labels: Documentation :green_book:

#7018 Add documentation examples for `exec-used`
  doc/data/messages/e/exec-used/bad.py
  doc/data/messages/e/exec-used/details.rst
  doc/data/messages/e/exec-used/good.py
  doc/data/messages/e/exec-used/related.rst
  pylint/checkers/base/basic_checker.py
Labels: Documentation :green_book:

#7035 Avoid hangs on many-core Windows machines
  doc/whatsnew/2/2.14/full.rst
  pylint/lint/base_options.py
  pylint/lint/run.py
Labels: Needs backport, Crash 💥, topic-multiprocessing

#7040 Add documentation examples for `logging-format-truncated`
  doc/data/messages/l/logging-format-truncated/bad.py
  doc/data/messages/l/logging-format-truncated/details.rst
  doc/data/messages/l/logging-format-truncated/good.py
Labels: Documentation :green_book:

#7043 Add documentation examples for `misplaced-format-function`
  doc/data/messages/m/misplaced-format-function/bad.py
  doc/data/messages/m/misplaced-format-function/details.rst
  doc/data/messages/m/misplaced-format-function/good.py
Labels: Documentation :green_book:

#7044 Add documentation examples for `no-staticmethod-decorator`
  doc/data/messages/n/no-staticmethod-decorator/bad.py
  doc/data/messages/n/no-staticmethod-decorator/details.rst
  doc/data/messages/n/no-staticmethod-decorator/good.py
Labels: Documentation :green_book:

#7045 Add documentation examples for `no-value-for-parameter`
  doc/data/messages/n/no-value-for-parameter/bad.py
  doc/data/messages/n/no-value-for-parameter/details.rst
  doc/data/messages/n/no-value-for-parameter/good.py
Labels: Documentation :green_book:

#7049 Add documentation examples for `not-async-context-manager`
  doc/data/messages/n/not-async-context-manager/bad.py
  doc/data/messages/n/not-async-context-manager/details.rst
  doc/data/messages/n/not-async-context-manager/good.py
Labels: Documentation :green_book:

#7050 [primer] Move `django` to new primer
  tests/primer/packages_to_lint_batch_one.json
  tests/primer/packages_to_prime.json
Labels: primer, Skip news :mute:

#7037 Don't emit `modified-iterating-dict` when updating existing keys
  doc/whatsnew/2/2.14/full.rst
  pylint/checkers/modified_iterating_checker.py
  tests/functional/m/modified_iterating.py
  tests/functional/m/modified_iterating.txt
Labels: Needs backport, False Positive 🦟

#7052 Add documentation examples for `notimplemented-raised`
  doc/data/messages/n/notimplemented-raised/bad.py
  doc/data/messages/n/notimplemented-raised/details.rst
  doc/data/messages/n/notimplemented-raised/good.py
Labels: Documentation :green_book:

#7051 Add documentation examples for `not-context-manager`
  doc/data/messages/n/not-context-manager/bad.py
  doc/data/messages/n/not-context-manager/details.rst
  doc/data/messages/n/not-context-manager/good.py
Labels: Documentation :green_book:

#7053 Add documentation examples for `property-with-parameters`
  doc/data/messages/p/property-with-parameters/bad.py
  doc/data/messages/p/property-with-parameters/details.rst
  doc/data/messages/p/property-with-parameters/good.py
Labels: Documentation :green_book:

#7057 Avoid deprecated `self.config` access in `missing-timeout`
  pylint/checkers/method_args.py
Labels: Maintenance, Skip news :mute:

#7060 Add documentation examples for `redefined-argument-from-local`
  doc/data/messages/r/redefined-argument-from-local/bad.py
  doc/data/messages/r/redefined-argument-from-local/details.rst
  doc/data/messages/r/redefined-argument-from-local/good.py
Labels: Documentation :green_book:

#7061 Add documentation examples for `raising-format-tuple`
  doc/data/messages/r/raising-format-tuple/bad.py
  doc/data/messages/r/raising-format-tuple/details.rst
  doc/data/messages/r/raising-format-tuple/good.py
Labels: Documentation :green_book:

#7064 Add documentation examples for `redundant-keyword-arg`
  doc/data/messages/r/redundant-keyword-arg/bad.py
  doc/data/messages/r/redundant-keyword-arg/details.rst
  doc/data/messages/r/redundant-keyword-arg/good.py
Labels: Documentation :green_book:

#7066 Add documentation examples for `too-few-public-methods`
  doc/data/messages/t/too-few-public-methods/bad.py
  doc/data/messages/t/too-few-public-methods/details.rst
  doc/data/messages/t/too-few-public-methods/good.py
Labels: Documentation :green_book:

#7065 Add documentation examples for `star-needs-assignment-target`
  doc/data/messages/s/star-needs-assignment-target/bad.py
  doc/data/messages/s/star-needs-assignment-target/details.rst
  doc/data/messages/s/star-needs-assignment-target/good.py
Labels: Documentation :green_book:

#7071 Add documentation examples for `too-many-star-expressions`
  doc/data/messages/t/too-many-star-expressions/bad.py
  doc/data/messages/t/too-many-star-expressions/details.rst
  doc/data/messages/t/too-many-star-expressions/good.py
Labels: Documentation :green_book:

#7068 Add documentation examples for `too-many-boolean-expressions`
  doc/data/messages/t/too-many-boolean-expressions/bad.py
  doc/data/messages/t/too-many-boolean-expressions/details.rst
  doc/data/messages/t/too-many-boolean-expressions/good.py
Labels: Documentation :green_book:

#7072 Add documentation examples for `unexpected-special-method-signature`
  doc/data/messages/u/unexpected-special-method-signature/bad.py
  doc/data/messages/u/unexpected-special-method-signature/details.rst
  doc/data/messages/u/unexpected-special-method-signature/good.py
Labels: Documentation :green_book:

#7067 Add documentation examples for `too-many-ancestors`
  doc/data/messages/t/too-many-ancestors/bad.py
  doc/data/messages/t/too-many-ancestors/details.rst
  doc/data/messages/t/too-many-ancestors/good.py
Labels: Documentation :green_book:

#7079 Don't report `import-private-name` for relative imports
  doc/whatsnew/2/2.14/full.rst
  pylint/extensions/private_import.py
  tests/functional/ext/private_import/private_import.py
Labels: Needs backport, False Positive 🦟

#7080 Normalize path before checking if path should be ignored
  doc/whatsnew/2/2.14/full.rst
  pylint/lint/expand_modules.py
  tests/test_self.py
Labels: Bug :beetle:, topic-configuration, Needs backport

#7076 Improve packaging [PEP 517 + 621]
  .flake8
  .github/workflows/release.yml
  .pre-commit-config.yaml
  .pyenchant_pylint_custom_dict.txt
  Dockerfile
  MANIFEST.in
  pyproject.toml
  setup.cfg
  setup.py
Labels: Maintenance
