Repository pylint-dev/pylint, pull requests merged in 2022-03, with the labels that each got.

#5859 Fix matching note tags with a non-word char last
  CONTRIBUTORS.txt
  ChangeLog
  doc/whatsnew/2.13.rst
  pylint/checkers/misc.py
  tests/checkers/unittest_misc.py
Labels: Bug 🪳, False Negative 🦋

#5446 Allow disabling ``duplicate-code`` with a disable comment
  ChangeLog
  doc/whatsnew/2.13.rst
  pylint/checkers/similar.py
  tests/regrtest_data/duplicate_code/raw_strings_all/__init__.py
  tests/regrtest_data/duplicate_code/raw_strings_all/first.py
  tests/regrtest_data/duplicate_code/raw_strings_all/second.py
  tests/regrtest_data/duplicate_code/raw_strings_all/third.py
  tests/regrtest_data/duplicate_code/raw_strings_disable_file/__init__.py
  tests/regrtest_data/duplicate_code/raw_strings_disable_file/first.py
  tests/regrtest_data/duplicate_code/raw_strings_disable_file/second.py
  tests/regrtest_data/duplicate_code/raw_strings_disable_file/third.py
  tests/regrtest_data/duplicate_code/raw_strings_disable_file_double/__init__.py
  tests/regrtest_data/duplicate_code/raw_strings_disable_file_double/first.py
  tests/regrtest_data/duplicate_code/raw_strings_disable_file_double/second.py
  tests/regrtest_data/duplicate_code/raw_strings_disable_file_double/third.py
  tests/regrtest_data/duplicate_code/raw_strings_disable_line_begin/__init__.py
  tests/regrtest_data/duplicate_code/raw_strings_disable_line_begin/first.py
  tests/regrtest_data/duplicate_code/raw_strings_disable_line_begin/second.py
  tests/regrtest_data/duplicate_code/raw_strings_disable_line_disable_all/__init__.py
  tests/regrtest_data/duplicate_code/raw_strings_disable_line_disable_all/first.py
  tests/regrtest_data/duplicate_code/raw_strings_disable_line_disable_all/second.py
  tests/regrtest_data/duplicate_code/raw_strings_disable_line_end/__init__.py
  tests/regrtest_data/duplicate_code/raw_strings_disable_line_end/first.py
  tests/regrtest_data/duplicate_code/raw_strings_disable_line_end/second.py
  tests/regrtest_data/duplicate_code/raw_strings_disable_line_middle/__init__.py
  tests/regrtest_data/duplicate_code/raw_strings_disable_line_middle/first.py
  tests/regrtest_data/duplicate_code/raw_strings_disable_line_middle/second.py
  tests/regrtest_data/duplicate_code/raw_strings_disable_scope/__init__.py
  tests/regrtest_data/duplicate_code/raw_strings_disable_scope/first.py
  tests/regrtest_data/duplicate_code/raw_strings_disable_scope/second.py
  tests/regrtest_data/duplicate_code/raw_strings_disable_scope/third.py
  tests/regrtest_data/duplicate_code/raw_strings_disable_scope_double/__init__.py
  tests/regrtest_data/duplicate_code/raw_strings_disable_scope_double/first.py
  tests/regrtest_data/duplicate_code/raw_strings_disable_scope_double/second.py
  tests/regrtest_data/duplicate_code/raw_strings_disable_scope_double/third.py
  tests/regrtest_data/duplicate_code/raw_strings_disable_scope_second_function/__init__.py
  tests/regrtest_data/duplicate_code/raw_strings_disable_scope_second_function/first.py
  tests/regrtest_data/duplicate_code/raw_strings_disable_scope_second_function/second.py
  tests/test_self.py
  tests/test_similar.py
Labels: Enhancement ✨

#5863 Add stdlib `xml.etree.cElementTree` to deprecated modules
  ChangeLog
  doc/whatsnew/2.13.rst
  pylint/checkers/stdlib.py
  tests/functional/d/deprecated/deprecated_module_py33.py
  tests/functional/d/deprecated/deprecated_module_py33.txt
Labels: Enhancement ✨

#5870 Fix Markdown link in ReStructuredText README
  README.rst
Labels: Documentation 📖

#5868 Improve CI workflow
  .github/workflows/ci.yaml
Labels: Maintenance

#5869 Fix pre-commit configuration hook URL
  .pre-commit-config.yaml
  CONTRIBUTORS.txt
Labels: Maintenance

#5853 Also test on PyPy 3.7
  .github/workflows/ci.yaml
Labels: Maintenance

#5843 Restore the useful part of the python3 checker
  ChangeLog
  doc/whatsnew/2.13.rst
  pylint/constants.py
  pylint/extensions/__init__.py
  pylint/extensions/code_style.py
  pylint/extensions/eq_without_hash.py
  tests/functional/ext/eq_without_hash/eq_without_hash.py
  tests/functional/ext/eq_without_hash/eq_without_hash.rc
  tests/functional/ext/eq_without_hash/eq_without_hash.txt
Labels: Bug 🪳, Regression, Optional Checkers

#5874 Removed unused detection of site-packages directory
  pylint/checkers/imports.py
Labels: Maintenance

#5864 Add `distutils` to deprecated modules
  ChangeLog
  doc/whatsnew/2.13.rst
  pylint/checkers/stdlib.py
  tests/functional/d/deprecated/deprecated_module_py310.py
  tests/functional/d/deprecated/deprecated_module_py310.rc
  tests/functional/d/deprecated/deprecated_module_py310.txt
  tests/functional/r/regression_02/regression_distutil_import_error_73.py
Labels: Enhancement ✨

#5881 Fix pyreverse type hinting for class methods
  ChangeLog
  pylint/pyreverse/printer.py
  tests/data/clientmodule_test.py
  tests/pyreverse/data/classes_No_Name.dot
  tests/pyreverse/data/classes_No_Name.html
  tests/pyreverse/data/classes_No_Name.mmd
  tests/pyreverse/data/classes_No_Name.puml
  tests/pyreverse/data/classes_No_Name.vcg
  tests/pyreverse/data/classes_colorized.dot
  tests/pyreverse/data/classes_colorized.puml
  tests/pyreverse/test_printer.py
Labels: Bug 🪳, topic-pyreverse

#5887 Use the ``tomli`` package instead of ``toml`` to parse ``.toml``
  .pre-commit-config.yaml
  ChangeLog
  doc/whatsnew/2.13.rst
  pylint/config/find_default_config_files.py
  pylint/config/option_manager_mixin.py
  requirements_test.txt
  setup.cfg
  tests/config/functional/toml/issue_3181/toml_decode_error.1.out
Labels: dependency, Maintenance, python 3.11

#5891 Add broken Callable check
  ChangeLog
  doc/whatsnew/2.13.rst
  pylint/extensions/typing.py
  tests/functional/ext/typing/typing_broken_callable.py
  tests/functional/ext/typing/typing_broken_callable.rc
  tests/functional/ext/typing/typing_broken_callable.txt
  tests/functional/ext/typing/typing_broken_callable_deprecated_alias.py
  tests/functional/ext/typing/typing_broken_callable_deprecated_alias.rc
  tests/functional/ext/typing/typing_broken_callable_future_import.py
  tests/functional/ext/typing/typing_broken_callable_future_import.rc
  tests/functional/ext/typing/typing_broken_callable_future_import.txt
Labels: Enhancement ✨, topic-typing, Optional Checkers

#5892 Add confidence value to typing extension messages
  pylint/extensions/typing.py
  tests/functional/ext/typing/typing_consider_using_alias.txt
  tests/functional/ext/typing/typing_consider_using_alias_without_future.txt
  tests/functional/ext/typing/typing_consider_using_union.txt
  tests/functional/ext/typing/typing_consider_using_union_py310.txt
  tests/functional/ext/typing/typing_consider_using_union_without_future.txt
  tests/functional/ext/typing/typing_deprecated_alias.txt
Labels: Maintenance

#5896 Mccabe 0.7
  CONTRIBUTORS.txt
  ChangeLog
  setup.cfg
Labels: Enhancement ✨

#5876 Prevent `useless-suppression` on disables for stdlib deprecation checker
  ChangeLog
  doc/whatsnew/2.13.rst
  pylint/checkers/stdlib.py
  pylint/constants.py
  pylint/utils/file_state.py
  tests/functional/d/deprecated/deprecated_method_suppression.py
  tests/functional/d/deprecated/deprecated_methods_py39.py
  tests/functional/d/deprecated/deprecated_methods_py39.rc
  tests/functional/d/deprecated/deprecated_methods_py39.txt
  tests/functional/d/deprecated/deprecated_module_py3.txt
  tests/functional/d/deprecated/deprecated_module_py39.py
  tests/functional/d/deprecated/deprecated_module_py39.rc
  tests/functional/d/deprecated/deprecated_module_py39.txt
  tests/functional/d/deprecated/deprecated_module_py39_earlier_pyversion.py
  tests/functional/d/deprecated/deprecated_module_py39_earlier_pyversion.rc
  tests/functional/d/deprecated/deprecated_module_py39_earlier_pyversion.txt
Labels: Enhancement ✨

#5825 Add ``typevar-name-missing-variance`` checker
  CONTRIBUTORS.txt
  ChangeLog
  doc/whatsnew/2.13.rst
  pylint/checkers/base.py
  tests/functional/g/generic_alias/generic_alias_side_effects.py
  tests/functional/r/regression/regression_2443_duplicate_bases.py
  tests/functional/t/typevar_name_incorrect_variance.py
  tests/functional/t/typevar_name_incorrect_variance.txt
Labels: Enhancement ✨

#5900 Upgrade mypy to 0.940
  .pre-commit-config.yaml
  pylint/testutils/functional/test_file.py
  requirements_test_pre_commit.txt
  setup.cfg
Labels: dependency

#5795 Add regression test for issue #5408
  ChangeLog
  doc/whatsnew/2.13.rst
  tests/functional/r/regression_02/regression_5408.py
Labels: Crash 💥, Requires Astroid Update

#5696 Add tests for #4826
  ChangeLog
  doc/whatsnew/2.13.rst
  tests/functional/n/no/no_member_binary_operations.py
Labels: False Positive 🦟, Requires Astroid Update

#5725 Add regression test for #5679
  ChangeLog
  doc/whatsnew/2.13.rst
  tests/regrtest_data/max_inferable_limit_for_classes/main.py
  tests/regrtest_data/max_inferable_limit_for_classes/nodes/roles.py
  tests/regrtest_data/max_inferable_limit_for_classes/other_funcs.py
  tests/test_self.py
Labels: Regression, Crash 💥, Requires Astroid Update

#5901 Fix false positive for `invalid-class-object` when inference fails
  ChangeLog
  doc/whatsnew/2.13.rst
  pylint/checkers/classes/class_checker.py
  tests/functional/i/invalid/invalid_class_object.py
Labels: False Positive 🦟

#5904 Fix end position in unittests
  pylint/testutils/checker_test_case.py
  tests/checkers/unittest_base.py
Labels: Maintenance

#5903 Fix disabling of ``ungrouped-imports``
  ChangeLog
  doc/whatsnew/2.13.rst
  pylint/checkers/imports.py
  tests/functional/u/ungrouped_imports_suppression.py
  tests/functional/u/ungrouped_imports_suppression.txt
Labels: Bug 🪳

#5907 Use ``functools.cached_property`` on 3.8+
  pylint/checkers/classes/class_checker.py
  pylint/checkers/design_analysis.py
  pylint/checkers/refactoring/refactoring_checker.py
  pylint/checkers/typecheck.py
  pylint/checkers/variables.py
Labels: Maintenance

#5908 Add regression test for #5771
  ChangeLog
  doc/whatsnew/2.13.rst
  pylint/checkers/variables.py
  tests/functional/u/unused/unused_argument.py
  tests/functional/u/unused/unused_argument.txt
Labels: Astroid, False Positive 🦟

#5910 Upgrade ``pydocstringformatter`` to ``0.5.0``
  .pre-commit-config.yaml
  doc/exts/pylint_messages.py
  pylint/checkers/__init__.py
  pylint/checkers/base.py
  pylint/checkers/base_checker.py
  pylint/checkers/classes/class_checker.py
  pylint/checkers/deprecated.py
  pylint/checkers/design_analysis.py
  pylint/checkers/ellipsis_checker.py
  pylint/checkers/exceptions.py
  pylint/checkers/format.py
  pylint/checkers/imports.py
  pylint/checkers/misc.py
  pylint/checkers/newstyle.py
  pylint/checkers/raw_metrics.py
  pylint/checkers/refactoring/implicit_booleaness_checker.py
  pylint/checkers/refactoring/refactoring_checker.py
  pylint/checkers/similar.py
  pylint/checkers/stdlib.py
  pylint/checkers/strings.py
  pylint/checkers/typecheck.py
  pylint/checkers/utils.py
  pylint/checkers/variables.py
  pylint/extensions/_check_docs_utils.py
  pylint/extensions/code_style.py
  pylint/extensions/comparetozero.py
  pylint/extensions/docparams.py
  pylint/extensions/emptystring.py
  pylint/extensions/eq_without_hash.py
  pylint/extensions/overlapping_exceptions.py
  pylint/extensions/typing.py
  pylint/graph.py
  pylint/lint/expand_modules.py
  pylint/lint/parallel.py
  pylint/lint/run.py
  pylint/pyreverse/dot_printer.py
  pylint/pyreverse/inspector.py
  pylint/pyreverse/mermaidjs_printer.py
  pylint/pyreverse/plantuml_printer.py
  pylint/pyreverse/printer.py
  pylint/pyreverse/utils.py
  pylint/pyreverse/vcg_printer.py
  pylint/reporters/multi_reporter.py
  pylint/testutils/output_line.py
  pylint/testutils/pyreverse.py
  pylint/utils/utils.py
Labels: dependency, Maintenance

#5846 Add regression test for #5770
  ChangeLog
  doc/whatsnew/2.13.rst
  tests/functional/ext/redefined_variable_type/regression_newtype_fstring.py
  tests/functional/ext/redefined_variable_type/regression_newtype_fstring.rc
Labels: Regression, Maintenance, Requires Astroid Update

#5911 Fix English punctuation and grammar (FAQs)
  doc/faq.rst
Labels: Documentation 📖, Maintenance

#5902 Fix typing of ``safe_infer``
  pylint/checkers/utils.py
Labels: Maintenance

#5610 Introduce new 'import-private-name' checker
  ChangeLog
  doc/whatsnew/2.13.rst
  pylint/checkers/__init__.py
  pylint/checkers/utils.py
  pylint/extensions/private_import.py
  tests/extensions/test_private_import.py
  tests/functional/ext/private_import/private_import.py
  tests/functional/ext/private_import/private_import.rc
  tests/functional/ext/private_import/private_import.txt
Labels: Enhancement ✨, High Effort 🏋

#5915 Simplify ``cached_property`` import guards
  pylint/checkers/classes/class_checker.py
  pylint/checkers/design_analysis.py
  pylint/checkers/refactoring/refactoring_checker.py
  pylint/checkers/typecheck.py
  pylint/checkers/variables.py
Labels: Maintenance

#5918 Update ``pydocstringformatter`` to ``0.5.3``
  .pre-commit-config.yaml
Labels: dependency, Maintenance

#5905 Remove uses of ``NodeNG.doc`` in favour of ``doc_node``
  pylint/checkers/base.py
  pylint/checkers/ellipsis_checker.py
  pylint/checkers/spelling.py
  pylint/extensions/_check_docs_utils.py
  pylint/extensions/docparams.py
  pylint/extensions/docstyle.py
Labels: Maintenance

#5345 fix(4756): fix false positive `unused-private-member` for private methods
  ChangeLog
  doc/whatsnew/2.13.rst
  pylint/checkers/classes/class_checker.py
  tests/functional/u/unused/unused_private_member.py
  tests/functional/u/unused/unused_private_member.txt
Labels: False Positive 🦟

#5923 Handle ``ComprehensionScope`` and their behaviour better
  pylint/checkers/classes/special_methods_checker.py
  pylint/checkers/typecheck.py
  pylint/checkers/utils.py
Labels: Enhancement ✨, Maintenance

#5925 Optimize handling of long lines for checkers like 'missing-final-newline'
  CONTRIBUTORS.txt
  ChangeLog
  doc/whatsnew/2.13.rst
  pylint/utils/pragma_parser.py
  tests/checkers/unittest_refactoring.py
  tests/regrtest_data/issue_5724.py
Labels: Enhancement ✨, topic-performance

#5916 Fix pyreverse type hints for methods returning None
  ChangeLog
  doc/whatsnew/2.13.rst
  pylint/pyreverse/utils.py
  tests/data/clientmodule_test.py
  tests/pyreverse/data/classes_No_Name.dot
  tests/pyreverse/data/classes_No_Name.html
  tests/pyreverse/data/classes_No_Name.mmd
  tests/pyreverse/data/classes_No_Name.puml
  tests/pyreverse/data/classes_No_Name.vcg
  tests/pyreverse/data/classes_colorized.dot
  tests/pyreverse/data/classes_colorized.puml
  tests/pyreverse/test_utils.py
Labels: Needs Review 🔍

#5939 Update "How to Write a Checker" docs
  doc/how_tos/custom_checkers.rst
Labels: Documentation 📖

#5941 Add missing __magic__ methods to `_SPECIAL_METHODS_PARAMS`
  CONTRIBUTORS.txt
  ChangeLog
  doc/whatsnew/2.13.rst
  pylint/checkers/utils.py
  tests/functional/u/unexpected_special_method_signature.py
  tests/functional/u/unexpected_special_method_signature.txt
Labels: Enhancement ✨

#5937 Fix `used-before-assignment` false positive for class definition in function scope
  ChangeLog
  doc/whatsnew/2.13.rst
  pylint/checkers/variables.py
  tests/functional/u/used/used_before_assignment_class_nested_under_function.py
Labels: False Positive 🦟

#5948 Migrate copyrite configuration
  script/.contributors_aliases.json
Labels: Maintenance

#5951 ``pyreverse``: better error messages for unsupported file formats
  ChangeLog
  doc/whatsnew/2.13.rst
  pylint/pyreverse/dot_printer.py
  pylint/pyreverse/main.py
  pylint/pyreverse/utils.py
  tests/pyreverse/test_main.py
Labels: topic-pyreverse, Documentation 📖

#5934 Set up system of code examples and details for message documentation
  .pre-commit-config.yaml
  doc/conf.py
  doc/data/messages/e/empty-docstring/bad.py
  doc/data/messages/e/empty-docstring/good.py
  doc/data/messages/y/yield-inside-async-function/bad.py
  doc/data/messages/y/yield-inside-async-function/details.rst
  doc/data/messages/y/yield-inside-async-function/good.py
  doc/data/messages/y/yield-inside-async-function/related.rst
  doc/exts/pylint_messages.py
Labels: Documentation 📖

#5956 Add CI test for message documentation
  .github/workflows/ci.yaml
  doc/data/messages/e/empty-docstring/bad.py
  doc/test_messages_documentation.py
Labels: Documentation 📖, Maintenance

#5958 Add documentation for access-member-before-definition
  doc/data/messages/a/access-member-before-definition/bad.py
  doc/data/messages/a/access-member-before-definition/good.py
  pylint/checkers/classes/class_checker.py
Labels: Documentation 📖

#5539 Make ``arguments-differ`` check extra parameters for default values
  ChangeLog
  doc/whatsnew/2.13.rst
  pylint/checkers/classes/class_checker.py
  tests/functional/a/arguments_differ.py
  tests/functional/a/arguments_differ.txt
  tests/functional/a/arguments_renamed.py
  tests/functional/a/arguments_renamed.txt
Labels: False Positive 🦟, C: arguments-differ

#5894 Create a ``TypeVar`` style for ``invalid-name``
  ChangeLog
  doc/user_guide/options.rst
  doc/whatsnew/2.13.rst
  pylint/checkers/base.py
  pylint/constants.py
  pylint/utils/linterstats.py
  pylintrc
  tests/checkers/unittest_base.py
  tests/functional/t/typevar_naming_style_default.py
  tests/functional/t/typevar_naming_style_default.txt
  tests/functional/t/typevar_naming_style_rgx.py
  tests/functional/t/typevar_naming_style_rgx.rc
  tests/functional/t/typevar_naming_style_rgx.txt
Labels: Enhancement ✨, Maintenance

#5957 Pylint errors 1
  doc/data/messages/a/abstract-class-instantiated/bad.py
  doc/data/messages/a/abstract-class-instantiated/good.py
  doc/data/messages/a/abstract-method/bad.py
  doc/data/messages/a/abstract-method/good.py
Labels: Documentation 📖

#5961 Add documentation for messages with anomalous in their name
  doc/data/messages/a/anomalous-backslash-in-string/bad.py
  doc/data/messages/a/anomalous-backslash-in-string/good.py
  doc/data/messages/a/anomalous-unicode-escape-in-string/bad.py
  doc/data/messages/a/anomalous-unicode-escape-in-string/good.py
  doc/test_messages_documentation.py
Labels: Documentation 📖

#5544 Fix #1555: Fix false negatives for `no-member` from self-referencing assignments
  ChangeLog
  doc/whatsnew/2.14.rst
  pylint/checkers/typecheck.py
  tests/functional/n/no/no_member_assign_same_line.py
  tests/functional/n/no/no_member_assign_same_line.txt
Labels: False Negative 🦋, C: undefined-variable

#5552 Add ``potential-index-error`` checker
  ChangeLog
  doc/data/messages/p/potential-index-error/bad.py
  doc/data/messages/p/potential-index-error/good.py
  doc/whatsnew/2.14.rst
  pylint/checkers/variables.py
  tests/functional/p/potential_index_error.py
  tests/functional/p/potential_index_error.txt
Labels: Enhancement ✨

#5974 Update configuration of pre-commit hooks and tools
  .pre-commit-config.yaml
  doc/conf.py
  doc/exts/pylint_extensions.py
  doc/exts/pylint_features.py
  pylintrc
  setup.cfg
Labels: Maintenance

#5966 Fix nonlocal in try block regression for `used-before-assignment`
  ChangeLog
  pylint/checkers/variables.py
  tests/functional/u/used/used_before_assignment_issue4761.py
  tests/functional/u/used/used_before_assignment_issue4761.txt
Labels: Needs Backport, False Positive 🦟

#5968 Don't emit `raising-bad-type` when there is ambiguity
  ChangeLog
  doc/whatsnew/2.13.rst
  pylint/checkers/exceptions.py
  tests/functional/i/invalid/invalid_exceptions/invalid_exceptions_raised.py
Labels: Needs Backport, False Positive 🦟

#5906 Fix false positive for `unused-argument` where nested function uses parent argument as a `nonlocal`
  ChangeLog
  doc/whatsnew/2.13.rst
  pylint/checkers/variables.py
  tests/functional/u/unused/unused_argument_py3.py
  tests/functional/u/unused/unused_name_from_wildcard_import.py
  tests/functional/u/unused/unused_name_from_wildcard_import.txt
Labels: Bug 🪳, Needs Backport

#5977 Add basic typing to ``pylint/utils.py``
  pylint/checkers/__init__.py
  pylint/utils/utils.py
Labels: Maintenance

#5978 Add basic typing to ``pylint/reporters``
  pylint/reporters/multi_reporter.py
  pylint/reporters/reports_handler_mix_in.py
Labels: Maintenance

#5979 Final typing for ``pylint/reporters/ureports``
  pylint/reporters/ureports/base_writer.py
  pylint/reporters/ureports/nodes.py
  pylint/reporters/ureports/text_writer.py
Labels: Maintenance

#5834 New checker `unnecessary-list-index-lookup` (#4525)
  ChangeLog
  doc/data/messages/u/unnecessary-list-index-lookup/bad.py
  doc/data/messages/u/unnecessary-list-index-lookup/good.py
  doc/whatsnew/2.14.rst
  pylint/checkers/refactoring/refactoring_checker.py
  tests/functional/c/consider/consider_using_enumerate.py
  tests/functional/u/unnecessary/unnecessary_list_index_lookup.py
  tests/functional/u/unnecessary/unnecessary_list_index_lookup.txt
  tests/functional/u/unnecessary/unnecessary_list_index_lookup_py38.py
  tests/functional/u/unnecessary/unnecessary_list_index_lookup_py38.rc
Labels: Enhancement ✨, Checkers

#5983 Loosen TypeVar name pattern
  ChangeLog
  doc/user_guide/options.rst
  pylint/checkers/base/name_checker/checker.py
  tests/functional/t/typevar_naming_style_default.py
  tests/functional/t/typevar_naming_style_default.txt
Labels: Enhancement ✨, Needs Backport, C: invalid-name

#5984 Don't emit broken typing errors inside TYPE_CHECKING blocks
  ChangeLog
  pylint/checkers/utils.py
  pylint/checkers/variables.py
  pylint/constants.py
  pylint/extensions/typing.py
  tests/functional/ext/typing/typing_broken_callable.py
  tests/functional/ext/typing/typing_broken_callable.txt
  tests/functional/ext/typing/typing_broken_noreturn.py
  tests/functional/ext/typing/typing_broken_noreturn_future_import.py
  tests/functional/ext/typing/typing_broken_noreturn_py372.py
Labels: Needs Backport, False Positive 🦟

#5986 Fix issue #5969 for `modified_iterating-list`
  ChangeLog
  pylint/checkers/modified_iterating_checker.py
  tests/functional/m/modified_iterating.py
Labels: Needs Backport, Crash 💥

#5964 Fix false positive for `superfluous-parens` for `return (a or b) in iterable`
  ChangeLog
  doc/whatsnew/2.13.rst
  pylint/checkers/format.py
  tests/functional/s/superfluous_parens.py
Labels: Needs Backport, False Positive 🦟

#5991 Added message doc for assigning-non-slot
  doc/data/messages/a/assigning-non-slot/bad.py
  doc/data/messages/a/assigning-non-slot/good.py
Labels: Documentation 📖

#5995 Added example for attribute-defined-outside-init
  doc/data/messages/a/attribute-defined-outside-init/bad.py
  doc/data/messages/a/attribute-defined-outside-init/good.py
Labels: Documentation 📖

#5996 Added bad-classmethod-argument example
  doc/data/messages/b/bad-classmethod-argument/bad.py
  doc/data/messages/b/bad-classmethod-argument/good.py
Labels: Documentation 📖

#5988 Add regression test for #5982
  ChangeLog
  requirements_test_min.txt
  setup.cfg
  tests/functional/u/used/used_before_assignment_py37.py
  tests/functional/u/used/used_before_assignment_py37.txt
Labels: Needs Backport, Requires Astroid Update

#5990 Fix false negative for `protected-access` on functions
  ChangeLog
  pylint/checkers/classes/class_checker.py
  tests/functional/p/protected_access.py
  tests/functional/p/protected_access.txt
Labels: Needs Backport, False Negative 🦋

#5987 Better error message when we cant write the crash files
  pylint/config/__init__.py
  pylint/lint/utils.py
Labels: Enhancement ✨, Needs Backport

#5993 Added example for bad-builtin
  doc/data/messages/b/bad-builtin/bad.py
  doc/data/messages/b/bad-builtin/good.py
Labels: Documentation 📖

#6002 Added example for bad-staticmethod-argument
  doc/data/messages/b/bad-staticmethod-argument/bad.py
  doc/data/messages/b/bad-staticmethod-argument/good.py
Labels: Documentation 📖

#6000 Added example for bad-indentation
  doc/data/messages/b/bad-indentation/bad.py
  doc/data/messages/b/bad-indentation/details.rst
  doc/data/messages/b/bad-indentation/good.py
Labels: Documentation 📖

#5999 Fix crash on unbalanced tuple unpacking
  ChangeLog
  pylint/checkers/base/name_checker/checker.py
  tests/functional/u/unbalanced_tuple_unpacking.py
  tests/functional/u/unbalanced_tuple_unpacking.txt
Labels: Needs Backport, Crash 💥

#5997 Added example for bad-except-order
  doc/data/messages/b/bad-except-order/bad.py
  doc/data/messages/b/bad-except-order/good.py
Labels: Documentation 📖

#5992 Added assignment-from-no-return message example
  doc/data/messages/a/assignment-from-no-return/bad.py
  doc/data/messages/a/assignment-from-no-return/good.py
Labels: Documentation 📖

#5994 Added example for assignment-from-none
  doc/data/messages/a/assignment-from-none/bad.py
  doc/data/messages/a/assignment-from-none/good.py
Labels: Documentation 📖

#6007 `unnecessary-ellipsis` false positive: allow ellipsis as default argument
  ChangeLog
  doc/whatsnew/2.13.rst
  pylint/checkers/ellipsis_checker.py
  tests/functional/u/unnecessary/unnecessary_ellipsis.py
Labels: Needs Backport, False Positive 🦟

#6016 Add examples for ``await-outside-async`` and fix activation of message
  ChangeLog
  doc/data/messages/a/await-outside-async/bad.py
  doc/data/messages/a/await-outside-async/good.py
  doc/data/messages/a/await-outside-async/related.rst
  pylint/checkers/typecheck.py
Labels: Bug 🪳, Documentation 📖

#6020 Added example of bare-except
  doc/data/messages/b/bare-except/bad.py
  doc/data/messages/b/bare-except/good.py
Labels: Documentation 📖

#6021 Added example of bad-reversed-sequence
  doc/data/messages/b/bad-reversed-sequence/bad.py
  doc/data/messages/b/bad-reversed-sequence/good.py
Labels: Documentation 📖

#6024 Document means of clearing inference cache
  doc/user_guide/run.rst
Labels: Documentation 📖

#6008 Change 'nonexistent-operator' to allow repeated unary ops (with space or parens)
  ChangeLog
  doc/whatsnew/2.13.rst
  pylint/checkers/base/basic_error_checker.py
  tests/functional/n/nonexistent_operator.py
Labels: Needs Backport, False Positive 🦟

#6026 Examples for ``bad-exception-context``
  doc/data/messages/b/bad-exception-context/bad.py
  doc/data/messages/b/bad-exception-context/good.py
  doc/data/messages/b/bad-exception-context/related.rst
Labels: Documentation 📖

#5584 Create an `Argument` class and allow convertion of optdict into them
  pylint/checkers/base_checker.py
  pylint/checkers/logging.py
  pylint/config/__init__.py
  pylint/config/argument.py
  pylint/config/arguments_manager.py
  pylint/config/config_initialization.py
  pylint/config/exceptions.py
  pylint/config/utils.py
  pylint/lint/pylinter.py
  pylintrc
  tests/config/data/logging_format_interpolation_style.py
  tests/config/data/logging_format_interpolation_style.rc
  tests/config/test_argparse_config.py
  tests/test_regr.py
Labels: Enhancement ✨, topic-configuration

#6029 Include ``testing_pylintrc`` in source and wheel distributions
  ChangeLog
  doc/whatsnew/2.13.rst
  setup.cfg
Labels: Needs Backport, Crash 💥, Maintenance

#6041 Move ``long-help`` to the ``Run`` class
  pylint/config/option_manager_mixin.py
  pylint/lint/run.py
  tests/test_self.py
Labels: Maintenance

#6046 Move setting of the current module to a better place in config init
  pylint/config/config_initialization.py
  pylint/config/option_manager_mixin.py
Labels: Maintenance

#5938 C2801: New check for manual __magic__ methods
  ChangeLog
  doc/data/messages/u/unnecessary-dunder-call/bad.py
  doc/data/messages/u/unnecessary-dunder-call/good.py
  doc/whatsnew/2.14.rst
  pylint/checkers/base_checker.py
  pylint/checkers/dunder_methods.py
  tests/functional/a/assigning/assigning_non_slot.py
  tests/functional/c/class_members_py30.py
  tests/functional/g/generic_alias/generic_alias_typing.py
  tests/functional/i/inner_classes.py
  tests/functional/n/non/non_init_parent_called.py
  tests/functional/t/too/too_many_arguments.py
  tests/functional/u/unnecessary/unnecessary_dunder_call.py
  tests/functional/u/unnecessary/unnecessary_dunder_call.txt
Labels: Enhancement ✨

#6054 Add an explicit marker for ``pytest-timeout``
  setup.cfg
Labels: Maintenance

#6038 Fix crash for ``unneccessary-ellipsis`` checker
  ChangeLog
  pylint/checkers/ellipsis_checker.py
  tests/functional/u/unnecessary/unnecessary_ellipsis.py
Labels: Needs Backport, Crash 💥

#6039 Fix false positive for the ``unnecessary-ellipsis`` checker
  ChangeLog
  pylint/checkers/ellipsis_checker.py
  tests/functional/u/unnecessary/unnecessary_ellipsis.py
Labels: Needs Backport, False Positive 🦟

#6040 Remove assumption of direct parentage for `used-before-assignment` homonym handling for try/except blocks and filtered comprehensions
  ChangeLog
  pylint/checkers/variables.py
  tests/functional/u/used/used_before_assignment_filtered_comprehension.py
Labels: Needs Backport, Regression, False Positive 🦟

#6063 Add ``unnecessary-ellipsis`` documentation examples
  doc/data/messages/u/unnecessary-ellipsis/bad.py
  doc/data/messages/u/unnecessary-ellipsis/good.py
Labels: Documentation 📖

#6059 Total ordering unit test
  pylint/checkers/base_checker.py
  tests/checkers/unittest_base_checker.py
Labels: Maintenance

#6043 Fix crash in ``super-init-not-called`` checker
  ChangeLog
  pylint/checkers/classes/class_checker.py
  tests/functional/s/super/super_init_not_called.py
  tests/functional/s/super/super_init_not_called.txt
Labels: Needs Backport, Regression, Crash 💥

#6061 Fix crash in ``unnecessary-list-index-lookup`` checker (#6049)
  pylint/checkers/refactoring/refactoring_checker.py
  tests/functional/u/unnecessary/unnecessary_list_index_lookup.py
Labels: Crash 💥

#6065 Fix Tidelift logo in README.rst
  README.rst
Labels: Documentation 📖

#6058 Docs: Generate note about extensions module in message documentation
  doc/exts/pylint_messages.py
Labels: Documentation 📖, Maintenance

#6057 Deprecate ``find_pylintrc``
  pylint/config/environment_variable.py
  pylint/config/find_default_config_files.py
  tests/lint/unittest_lint.py
Labels: Maintenance

#6056 More tests for config file finding, handle malformatted setup.cfg
  pylint/config/find_default_config_files.py
  tests/config/test_find_default_config_files.py
Labels: Maintenance

#6072 Re-use regex pattern in naming style
  pylint/checkers/base/name_checker/naming_style.py
Labels: topic-performance

#6079 Add ``redefined-slots-in-subclass`` documentation examples
  doc/data/messages/r/redefined-slots-in-subclass/bad.py
  doc/data/messages/r/redefined-slots-in-subclass/good.py
Labels: Documentation 📖
