Repository pylint-dev/pylint, pull requests merged in 2022-04, with the labels that each got.

#6086 Examples for ``bad-format-character``
  doc/data/messages/b/bad-format-character/bad.py
  doc/data/messages/b/bad-format-character/details.rst
  doc/data/messages/b/bad-format-character/good.py
  doc/data/messages/b/bad-format-character/related.rst
Labels: Documentation 📖

#6088 Documentation examples for ``bad-option-value``
  doc/data/messages/b/bad-option-value/bad.py
  doc/data/messages/b/bad-option-value/good.py
Labels: Documentation 📖

#6090 Add examples for ``bad-str-strip-call``
  doc/data/messages/b/bad-str-strip-call/bad.py
  doc/data/messages/b/bad-str-strip-call/details.rst
  doc/data/messages/b/bad-str-strip-call/good.py
  doc/data/messages/b/bad-str-strip-call/related.rst
Labels: Documentation 📖

#6083 Add example for `duplicate-bases` message documentation
  doc/data/messages/d/duplicate-bases/bad.py
  doc/data/messages/d/duplicate-bases/good.py
  pylint/checkers/classes/class_checker.py
Labels: Documentation 📖

#6093 [doc] Add example to bad strip call
  doc/data/messages/b/bad-str-strip-call/bad.py
  doc/data/messages/b/bad-str-strip-call/good.py
Labels: Documentation 📖

#6092 Add example for `duplicate-key` message documentation
  doc/data/messages/d/duplicate-key/bad.py
  doc/data/messages/d/duplicate-key/good.py
  doc/data/messages/d/duplicate-key/related.rst
Labels: Documentation 📖

#6095 Close and join pools correctly in ``parallel.py``
  pylint/lint/parallel.py
Labels: Bug 🪳, topic-multiprocessing, Maintenance

#6052 Some refactors of configuration file discovery
  doc/test_messages_documentation.py
  pylint/config/config_initialization.py
  pylint/config/option_manager_mixin.py
  pylint/config/options_provider_mixin.py
  pylint/lint/pylinter.py
  pylint/lint/run.py
Labels: Maintenance

#6081 Narrow the scope of the ``unnecessary-ellipsis`` checker
  ChangeLog
  pylint/checkers/ellipsis_checker.py
  tests/functional/u/unnecessary/unnecessary_ellipsis.py
Labels: Enhancement ✨, Needs Backport, False Positive 🦟

#6034 Remove the concept of checker priority
  ChangeLog
  doc/how_tos/custom_checkers.rst
  doc/whatsnew/2.14.rst
  examples/custom.py
  pylint/checkers/classes/class_checker.py
  pylint/checkers/classes/special_methods_checker.py
  pylint/checkers/design_analysis.py
  pylint/checkers/exceptions.py
  pylint/checkers/imports.py
  pylint/checkers/modified_iterating_checker.py
  pylint/checkers/newstyle.py
  pylint/checkers/non_ascii_names.py
  pylint/checkers/refactoring/implicit_booleaness_checker.py
  pylint/checkers/refactoring/refactoring_checker.py
  pylint/checkers/typecheck.py
  pylint/checkers/unicode.py
  pylint/checkers/variables.py
  pylint/config/arguments_manager.py
  pylint/config/option_manager_mixin.py
  pylint/config/options_provider_mixin.py
  pylint/extensions/broad_try_clause.py
  pylint/extensions/code_style.py
  pylint/extensions/comparetozero.py
  pylint/extensions/confusing_elif.py
  pylint/extensions/docparams.py
  pylint/extensions/empty_comment.py
  pylint/extensions/emptystring.py
  pylint/extensions/overlapping_exceptions.py
  pylint/extensions/set_membership.py
  pylint/extensions/typing.py
  pylint/lint/pylinter.py
Labels: Maintenance

#6067 Refactor ``find_default_config_files``
  pylint/config/find_default_config_files.py
  pylint/testutils/__init__.py
  pylint/testutils/utils.py
  tests/config/test_find_default_config_files.py
  tests/lint/unittest_lint.py
Labels: Maintenance

#6075 Fix false-positive for unnecessary-ellipsis checker on comparisons
  tests/functional/u/unnecessary/unnecessary_ellipsis.py
Labels: Needs Backport, False Positive 🦟

#5962 Add documentation for messages with arguments in their name
  doc/data/messages/a/arguments-differ/bad.py
  doc/data/messages/a/arguments-differ/details.rst
  doc/data/messages/a/arguments-differ/good.py
  doc/data/messages/a/arguments-differ/related.rst
  doc/data/messages/a/arguments-out-of-order/bad.py
  doc/data/messages/a/arguments-out-of-order/good.py
  doc/data/messages/a/arguments-renamed/bad.py
  doc/data/messages/a/arguments-renamed/good.py
  doc/data/messages/s/super-with-arguments/bad.py
  doc/data/messages/s/super-with-arguments/good.py
  doc/data/messages/t/too-many-arguments/bad.py
  doc/data/messages/t/too-many-arguments/good.py
Labels: Documentation 📖

#6099 Use transformers instead of validators for ``Argument``
  pylint/config/argument.py
Labels: Maintenance

#6103 Added broad-except message example
  doc/data/messages/b/broad-except/bad.py
  doc/data/messages/b/broad-except/good.py
Labels: Documentation 📖

#6105 Add catching-non-exception message example
  doc/data/messages/c/catching-non-exception/bad.py
  doc/data/messages/c/catching-non-exception/good.py
Labels: Documentation 📖

#6055 Create ``_ConfigurationFileParser`` class
  pylint/config/__init__.py
  pylint/config/arguments_manager.py
  pylint/config/config_file_parser.py
  pylint/config/config_initialization.py
  pylint/config/option_manager_mixin.py
Labels: Maintenance

#6108 Use the ``argparse`` config handler in ``docstring_checker.py``
  pylint/checkers/base/docstring_checker.py
  pylint/config/argument.py
Labels: Maintenance

#6115 add example for `missing-format-argument-key` message documentation
  doc/data/messages/m/missing-format-argument-key/bad.py
  doc/data/messages/m/missing-format-argument-key/good.py
  doc/data/messages/m/missing-format-argument-key/related.rst
Labels: Documentation 📖

#6114 add example for `too-many-format-args` and `too-few-format-args` message documentation
  doc/data/messages/t/too-few-format-args/bad.py
  doc/data/messages/t/too-few-format-args/good.py
  doc/data/messages/t/too-few-format-args/related.rst
  doc/data/messages/t/too-many-format-args/bad.py
  doc/data/messages/t/too-many-format-args/good.py
  doc/data/messages/t/too-many-format-args/related.rst
Labels: Documentation 📖

#6084 Change documentation theme to use `furo` theme
  doc/conf.py
  doc/requirements.txt
Labels: Documentation 📖

#6068 Fix E1102 / ``not-callable`` false positive for property that returns a lambda function conditionally
  ChangeLog
  doc/whatsnew/2.14.rst
  pylint/checkers/typecheck.py
  tests/functional/n/not_callable.py
Labels: topic-control-flow, Needs Backport, False Positive 🦟

#5928 Add new message called duplicate-value
  ChangeLog
  doc/data/messages/d/duplicate-value/bad.py
  doc/data/messages/d/duplicate-value/good.py
  doc/whatsnew/2.14.rst
  pylint/checkers/base/basic_checker.py
  pylint/checkers/format.py
  tests/functional/d/duplicate_value.py
  tests/functional/d/duplicate_value.txt
Labels: Enhancement ✨

#6111 Add typing to two utility functions
  pylint/config/argument.py
  pylint/reporters/text.py
  pylint/utils/utils.py
Labels: Maintenance

#6109 Use the ``argparse`` config handler in ``class_checker.py``
  pylint/checkers/classes/class_checker.py
  pylint/config/argument.py
Labels: Maintenance

#6110 Use the ``argparse`` config handler in ``imports.py``
  pylint/checkers/imports.py
  pylint/config/argument.py
  pylint/testutils/unittest_linter.py
  pylint/utils/utils.py
  tests/test_import_graph.py
Labels: Maintenance

#6116 Use for v in *.values() instead of _, v in *.items()
  pylint/checkers/refactoring/refactoring_checker.py
  pylintrc
  tests/pyreverse/test_utils.py
Labels: Maintenance

#6117 Use ``argparse`` config handler in ``imports.py`` & ``exceptions.py``
  pylint/checkers/exceptions.py
  pylint/checkers/format.py
  pylint/config/argument.py
Labels: Maintenance

#6118 Use ``argparse`` config handler in ``design_analysis.py``
  pylint/checkers/design_analysis.py
  pylint/config/argument.py
Labels: Maintenance

#6120 Use ``argparse`` config handler on two checkers
  pylint/checkers/strings.py
  pylint/checkers/typecheck.py
  pylint/config/arguments_manager.py
Labels: Maintenance

#6119 Do ``argparse`` parsing of config file first
  pylint/config/config_initialization.py
Labels: Maintenance

#6123 Remove ``set_config_directly``
  ChangeLog
  doc/whatsnew/2.14.rst
  pylint/testutils/decorator.py
  tests/testutils/test_decorator.py
Labels: Maintenance

#6122 Use ``argparse`` config handler in ``misc.py``
  pylint/checkers/misc.py
  pylint/config/config_file_parser.py
  pylint/testutils/decorator.py
Labels: Maintenance

#6112 ``redefined-slots-in-subclass`` crash when slot type is neither a string or constant node
  ChangeLog
  pylint/checkers/classes/class_checker.py
  tests/functional/r/redefined/redefined_slots.py
Labels: Needs Backport, Crash 💥

#6127 Move ``_parse_rich_type_value`` to ``utils``
  pylint/config/config_file_parser.py
  pylint/config/utils.py
  pylint/testutils/decorator.py
Labels: Maintenance

#6128 Use ``argparse`` config handler in all extensions
  pylint/extensions/bad_builtin.py
  pylint/extensions/broad_try_clause.py
  pylint/extensions/code_style.py
  pylint/extensions/docparams.py
  pylint/extensions/mccabe.py
  pylint/extensions/typing.py
Labels: Maintenance

#6073 Account for more node types in handling of except block homonyms with comprehensions
  ChangeLog
  pylint/checkers/variables.py
  tests/functional/u/unused/unused_argument.py
  tests/functional/u/unused/unused_argument.txt
  tests/functional/u/used/used_before_assignment_comprehension_homonyms.py
Labels: Needs Backport, C: used-before-assignment

#6129 Clean up docs `conf.py`
  doc/conf.py
Labels: Maintenance

#6126 Remove broken ``generate-man`` option
  ChangeLog
  doc/whatsnew/2.14.rst
  pylint/config/__init__.py
  pylint/config/man_help_formatter.py
  pylint/config/option_manager_mixin.py
  pylint/lint/run.py
Labels: Maintenance

#6130 Use ``argparse`` config handler in ``similar.py``
  pylint/checkers/base_checker.py
  pylint/checkers/similar.py
  tests/checkers/unittest_similar.py
Labels: topic-multiprocessing, Maintenance

#6132 Add `wildcard-import` doc example
  doc/data/messages/w/wildcard-import/bad.py
  doc/data/messages/w/wildcard-import/good.py
Labels: Documentation 📖

#6134 Allow setting a ``CallbackAction`` instead of ``"callback"``
  pylint/config/callback_actions.py
  pylint/config/option_manager_mixin.py
  pylint/config/options_provider_mixin.py
  pylint/lint/run.py
Labels: Maintenance

#6135 Add last missing transformers
  pylint/config/argument.py
Labels: Maintenance

#6131 Enable usage of custom pylintrc file for message documentation tests
  doc/data/messages/c/confusing-consecutive-elif/bad.py
  doc/data/messages/c/confusing-consecutive-elif/details.rst
  doc/data/messages/c/confusing-consecutive-elif/good.py
  doc/data/messages/c/confusing-consecutive-elif/pylintrc
  doc/test_messages_documentation.py
Labels: Documentation 📖

#6145 Assert number of messages in test_messages_documentation.py
  doc/test_messages_documentation.py
Labels: Maintenance

#6107 Added chained-comparison message example
  doc/data/messages/c/chained-comparison/bad.py
  doc/data/messages/c/chained-comparison/good.py
Labels: Documentation 📖

#6153 add example for `unreachable` message documentation
  doc/data/messages/u/unreachable/bad.py
  doc/data/messages/u/unreachable/good.py
Labels: Documentation 📖

#6152 add example for `unidiomatic-typecheck` message documentation
  doc/data/messages/u/unidiomatic-typecheck/bad.py
  doc/data/messages/u/unidiomatic-typecheck/good.py
  doc/data/messages/u/unidiomatic-typecheck/related.rst
Labels: Documentation 📖

#6149 add example for `undefined-variable` message documentation
  doc/data/messages/u/undefined-variable/bad.py
  doc/data/messages/u/undefined-variable/good.py
Labels: Documentation 📖

#6106 Added cell-var-from-loop message example
  doc/data/messages/c/cell-var-from-loop/bad.py
  doc/data/messages/c/cell-var-from-loop/good.py
  doc/data/messages/c/cell-var-from-loop/related.rst
Labels: Documentation 📖

#6161 Fix version constraint in ``test_messages_documentation``
  doc/test_messages_documentation.py
Labels: Bug 🪳

#6154 Fix handling of "for x in x" homonyms
  ChangeLog
  pylint/checkers/variables.py
  tests/functional/u/undefined/undefined_variable_py38.py
  tests/functional/u/undefined/undefined_variable_py38.txt
  tests/functional/u/unused/unused_variable.py
Labels: Needs Backport, False Positive 🦟

#6151 Add example `useless-import-alias` message documentation
  doc/data/messages/u/useless-import-alias/bad.py
  doc/data/messages/u/useless-import-alias/details.rst
  doc/data/messages/u/useless-import-alias/good.py
  doc/data/messages/u/useless-import-alias/related.rst
Labels: Documentation 📖

#6162 Remove TODOs in `unused-variable` tests
  tests/functional/u/unused/unused_variable.py
  tests/functional/u/unused/unused_variable.txt
Labels: Maintenance

#6164 Add examples for ``bad-string-format-type``
  doc/data/messages/b/bad-string-format-type/bad.py
  doc/data/messages/b/bad-string-format-type/details.rst
  doc/data/messages/b/bad-string-format-type/good.py
  doc/data/messages/b/bad-string-format-type/related.rst
Labels: Documentation 📖

#6096 Fix false positive for ``unused-import`` when disabling both ``used-before-assignment`` and ``undefined-variable``
  ChangeLog
  doc/whatsnew/2.13.rst
  pylint/checkers/variables.py
  tests/functional/u/unused/unused_import_everything_disabled.py
Labels: Needs Backport, False Positive 🦟

#6160 Add example for `undefined-all-variable` message documentation
  doc/data/messages/u/undefined-all-variable/bad.py
  doc/data/messages/u/undefined-all-variable/good.py
  doc/data/messages/u/undefined-all-variable/related.rst
Labels: Documentation 📖

#6133 Add `unused-wildcard-import` doc example
  doc/data/messages/u/unused-wildcard-import/bad.py
  doc/data/messages/u/unused-wildcard-import/detail.rst
  doc/data/messages/u/unused-wildcard-import/good.py
Labels: Documentation 📖

#6167 Add example for ``broken-collections-callable``
  doc/data/messages/b/broken-collections-callable/bad.py
  doc/data/messages/b/broken-collections-callable/good.py
  doc/data/messages/b/broken-collections-callable/pylintrc
  doc/data/messages/b/broken-collections-callable/related.rst
Labels: Documentation 📖

#6159 Added literal-comparison message example
  doc/data/messages/l/literal-comparison/bad.py
  doc/data/messages/l/literal-comparison/good.py
  doc/data/messages/l/literal-comparison/related.rst
Labels: Documentation 📖

#6166 Add example for ``bad-super-call``
  doc/data/messages/b/bad-super-call/bad.py
  doc/data/messages/b/bad-super-call/details.rst
  doc/data/messages/b/bad-super-call/good.py
  doc/data/messages/b/bad-super-call/related.rst
Labels: Documentation 📖

#6158 Added singleton-comparison message example
  doc/data/messages/s/singleton-comparison/bad.py
  doc/data/messages/s/singleton-comparison/good.py
  doc/data/messages/s/singleton-comparison/related.rst
Labels: Documentation 📖

#6157 Added comparison-with-itself message example
  doc/data/messages/c/comparison-with-itself/bad.py
  doc/data/messages/c/comparison-with-itself/good.py
Labels: Documentation 📖

#6148 Re-enable checker ``bad-docstring-quotes`` for Python <= 3.7.
  ChangeLog
  doc/whatsnew/2.14.rst
  pylint/extensions/docstyle.py
  tests/functional/ext/docstyle/docstyle_quotes.py
  tests/functional/ext/docstyle/docstyle_quotes.rc
  tests/functional/ext/docstyle/docstyle_quotes.txt
  tests/functional/ext/docstyle/docstyle_quotes_py37.py
  tests/functional/ext/docstyle/docstyle_quotes_py38.rc
Labels: Maintenance

#6015 New check C0106: typevar-double-invariance
  ChangeLog
  doc/data/messages/t/typevar-double-variance/bad.py
  doc/data/messages/t/typevar-double-variance/good.py
  doc/whatsnew/2.14.rst
  pylint/checkers/base/name_checker/checker.py
  pylint/lint/pylinter.py
  tests/functional/t/typevar_double_variance.py
  tests/functional/t/typevar_double_variance.txt
  tests/functional/t/typevar_name_incorrect_variance.txt
  tests/functional/t/typevar_naming_style_default.py
  tests/functional/t/typevar_naming_style_default.txt
Labels: Enhancement ✨

#6018 New check E0244: Extending inherited Enum class
  ChangeLog
  doc/data/messages/i/invalid-enum-extension/bad.py
  doc/data/messages/i/invalid-enum-extension/good.py
  doc/whatsnew/2.14.rst
  pylint/checkers/classes/class_checker.py
  tests/functional/i/invalid/invalid_enum_extension.py
  tests/functional/i/invalid/invalid_enum_extension.txt
Labels: Enhancement ✨, Checkers

#6146 Refactor the help message
  pylint/config/argument.py
  pylint/config/arguments_manager.py
  pylint/config/callback_actions.py
  pylint/config/config_initialization.py
  pylint/config/help_formatter.py
  pylint/config/option_manager_mixin.py
  pylint/config/utils.py
  pylint/lint/pylinter.py
  pylint/lint/run.py
Labels: Maintenance

#6168 New check: TypeVar name mismatch
  ChangeLog
  doc/data/messages/t/typevar-name-mismatch/bad.py
  doc/data/messages/t/typevar-name-mismatch/good.py
  doc/whatsnew/2.14.rst
  pylint/checkers/base/name_checker/checker.py
  tests/functional/t/typevar_name_mismatch.py
  tests/functional/t/typevar_name_mismatch.txt
Labels: Enhancement ✨

#6156 Added comparison-with-callable message example
  doc/data/messages/c/comparison-with-callable/bad.py
  doc/data/messages/c/comparison-with-callable/good.py
Labels: Documentation 📖

#6124 Use ``argparse`` config handler on three checkers
  pylint/checkers/base/docstring_checker.py
  pylint/checkers/refactoring/refactoring_checker.py
  pylint/checkers/spelling.py
Labels: Blocked 🚧, Maintenance

#6189 Finalize ``_parse_command_line_configuration``
  pylint/config/arguments_manager.py
  pylint/config/config_initialization.py
  pylint/config/deprecation_actions.py
  tests/config/test_argparse_config.py
Labels: Maintenance

#6080 Add documentation examples for ``overridden-final-method`` checker
  doc/data/messages/o/overridden-final-method/bad.py
  doc/data/messages/o/overridden-final-method/details.rst
  doc/data/messages/o/overridden-final-method/good.py
  doc/data/messages/o/overridden-final-method/pylintrc
  doc/data/messages/o/overridden-final-method/related.rst
Labels: Documentation 📖

#6181 Only emit ``lru-cache-decorating-method`` when ``maxsize`` is ``None``
  ChangeLog
  doc/whatsnew/2.13.rst
  pylint/checkers/stdlib.py
  pylint/message/message_definition_store.py
  tests/functional/c/cache_max_size_none.py
  tests/functional/c/cache_max_size_none.txt
  tests/functional/l/lru_cache_decorating_method.py
  tests/functional/l/lru_cache_decorating_method.txt
Labels: Bug 🪳, Needs Backport, False Positive 🦟

#6194 Fix false negative for ``bad-string-format-type`` when using a variable as input
  ChangeLog
  doc/whatsnew/2.14.rst
  pylint/checkers/strings.py
  tests/functional/b/bad_string_format_type.py
  tests/functional/b/bad_string_format_type.txt
Labels: Bug 🪳, False Negative 🦋

#6191 Partially use ``namespace`` in ``PyLinter``
  pylint/lint/pylinter.py
  pylint/lint/run.py
  pylint/testutils/checker_test_case.py
  tests/benchmark/test_baseline_benchmarks.py
  tests/config/test_config.py
  tests/lint/unittest_lint.py
  tests/test_check_parallel.py
Labels: Maintenance

#6197 Use namespace in PyLinter and tests
  doc/test_messages_documentation.py
  pylint/lint/pylinter.py
  pylint/reporters/text.py
  pylint/testutils/global_test_linter.py
  pylint/testutils/lint_module_test.py
  tests/lint/unittest_lint.py
  tests/unittest_reporters_json.py
  tests/unittest_reporting.py
Labels: Maintenance

#6198 Increase the cache version to fix pypy 3.7
  .github/workflows/tests.yaml
Labels: Maintenance

#6205 add example for `self-assigning-variable` message documentation
  doc/data/messages/s/self-assigning-variable/bad.py
  doc/data/messages/s/self-assigning-variable/good.py
  doc/data/messages/s/self-assigning-variable/related.rst
Labels: Documentation 📖

#6203 add example for `global-at-module-level` message documentation
  doc/data/messages/g/global-at-module-level/bad.py
  doc/data/messages/g/global-at-module-level/good.py
  doc/data/messages/g/global-at-module-level/related.rst
Labels: Documentation 📖

#6201 add example for `unbalaced-tuple-unpacking` message documentation
  doc/data/messages/u/unbalanced-tuple-unpacking/bad.py
  doc/data/messages/u/unbalanced-tuple-unpacking/good.py
  doc/data/messages/u/unbalanced-tuple-unpacking/related.rst
Labels: Documentation 📖

#6206 add example for `reimported` message documentation
  .pre-commit-config.yaml
  doc/data/messages/r/reimported/bad.py
  doc/data/messages/r/reimported/good.py
Labels: Documentation 📖

#6200 add example for `function-redefined` message documentation
  doc/data/messages/f/function-redefined/bad.py
  doc/data/messages/f/function-redefined/good.py
Labels: Documentation 📖

#6207 Handle ``group`` in optdicts and ``option_groups``
  pylint/config/argument.py
  pylint/config/arguments_manager.py
  pylint/config/utils.py
  pylint/lint/pylinter.py
Labels: Maintenance

#6185 Prevent `used-before-assignment` for assignment via nonlocal after type annotation
  ChangeLog
  doc/whatsnew/2.13.rst
  pylint/checkers/variables.py
  tests/functional/u/used/used_before_assignment_nonlocal.py
  tests/functional/u/used/used_before_assignment_nonlocal.txt
Labels: Needs Backport, False Positive 🦟

#6183 Add ``Options`` and ``OptionsDict`` to typing utils
  pylint/checkers/base_checker.py
  pylint/checkers/similar.py
  pylint/config/options_provider_mixin.py
  pylint/lint/pylinter.py
  pylint/pyreverse/main.py
  pylint/typing.py
Labels: Maintenance

#6212 Handle asterisks better in Sphinx and Google style docstrings
  ChangeLog
  doc/whatsnew/2.13.rst
  pylint/extensions/_check_docs_utils.py
  pylint/extensions/docparams.py
  tests/functional/ext/docparams/parameter/missing_param_doc_required_Google.py
  tests/functional/ext/docparams/parameter/missing_param_doc_required_Google.txt
  tests/functional/ext/docparams/parameter/missing_param_doc_required_Numpy.py
  tests/functional/ext/docparams/parameter/missing_param_doc_required_Sphinx.py
  tests/functional/ext/docparams/parameter/missing_param_doc_required_Sphinx.txt
Labels: Bug 🪳, Needs Backport, False Positive 🦟

#6213 Assert that links in related.rst are a list
  doc/data/messages/c/cell-var-from-loop/related.rst
  doc/data/messages/d/duplicate-key/related.rst
  doc/data/messages/g/global-at-module-level/related.rst
  doc/data/messages/l/literal-comparison/related.rst
  doc/data/messages/m/missing-format-argument-key/related.rst
  doc/data/messages/s/self-assigning-variable/related.rst
  doc/data/messages/s/singleton-comparison/related.rst
  doc/data/messages/t/too-few-format-args/related.rst
  doc/data/messages/t/too-many-format-args/related.rst
  doc/data/messages/u/unbalanced-tuple-unpacking/related.rst
  doc/data/messages/u/undefined-all-variable/related.rst
  doc/data/messages/u/unidiomatic-typecheck/related.rst
  doc/data/messages/u/useless-import-alias/related.rst
  doc/test_messages_documentation.py
Labels: Documentation 📖, Maintenance

#6214 Copy all of ``OptionsManagerMixIn`` methods into ``_ArgumentsManager``
  pylint/config/arguments_manager.py
  pylint/config/option_manager_mixin.py
  pylint/lint/pylinter.py
  pylint/testutils/unittest_linter.py
  tests/lint/unittest_lint.py
  tests/test_regr.py
Labels: Maintenance

#6217 Deprecate ``register_options_provider``
  pylint/config/arguments_manager.py
  pylint/lint/pylinter.py
Labels: Maintenance

#6219 Deprecate ``add_option_group``
  pylint/config/arguments_manager.py
Labels: Maintenance

#6220 Deprecate ``add_optik_option`` and ``optik_option``
  pylint/config/arguments_manager.py
Labels: Maintenance

#6222 Deprecate ``generate_config``
  pylint/config/arguments_manager.py
  pylint/config/callback_actions.py
  pylint/utils/utils.py
Labels: Maintenance

#6224 Deprecate ``load_provider_defaults`` and ``read_config_file``
  pylint/config/arguments_manager.py
  pylint/config/config_initialization.py
  pylint/lint/pylinter.py
Labels: Maintenance

#6230 Added example for use-list-literal message
  doc/data/messages/u/use-list-literal/bad.py
  doc/data/messages/u/use-list-literal/good.py
Labels: Documentation 📖

#6227 Deprecate ``load_config_file``, ``load_configuration`` and ``load_configuration_from_config``
  pylint/config/arguments_manager.py
  pylint/config/config_initialization.py
  tests/config/test_deprecations.py
Labels: Maintenance

#6232 Add example for `use-maxsplit-arg` message documentation
  doc/data/messages/u/use-maxsplit-arg/bad.py
  doc/data/messages/u/use-maxsplit-arg/details.rst
  doc/data/messages/u/use-maxsplit-arg/good.py
Labels: Documentation 📖

#6223 Decrease number of runners used in CI
  .github/workflows/tests.yaml
Labels: Maintenance

#6237 Added import-outside-toplevel message example
  doc/data/messages/i/import-outside-toplevel/bad.py
  doc/data/messages/i/import-outside-toplevel/good.py
Labels: Documentation 📖

#6241 increase timeout for test_issue_5724
  tests/checkers/unittest_refactoring.py
Labels: Maintenance

#6239 Added wrong-import-order message example
  .pre-commit-config.yaml
  doc/data/messages/w/wrong-import-order/bad.py
  doc/data/messages/w/wrong-import-order/good.py
Labels: Documentation 📖

#6240 Added wrong-import-position message example
  doc/data/messages/w/wrong-import-position/bad.py
  doc/data/messages/w/wrong-import-position/good.py
Labels: Documentation 📖

#6238 Added ungrouped-imports message example
  .pre-commit-config.yaml
  doc/data/messages/u/ungrouped-imports/bad.py
  doc/data/messages/u/ungrouped-imports/good.py
Labels: Documentation 📖

#6192 Improve `invalid-slots-object` message output
  ChangeLog
  doc/whatsnew/2.14.rst
  pylint/checkers/classes/class_checker.py
  tests/functional/s/slots_checks.py
  tests/functional/s/slots_checks.txt
Labels: Maintenance

#5720 Suppress `unsubscriptable-object` warnings in type-checking blocks
  ChangeLog
  doc/whatsnew/2.14.rst
  pylint/checkers/typecheck.py
  tests/functional/r/regression_02/regression_3979.py
Labels: Bug 🪳, Regression, False Positive 🦟

#6243 Added misplaced-future message example
  .pre-commit-config.yaml
  doc/data/messages/m/misplaced-future/bad.py
  doc/data/messages/m/misplaced-future/good.py
Labels: Documentation 📖

#6244 Added example of use-dict-literal message
  doc/data/messages/u/use-dict-literal/bad.py
  doc/data/messages/u/use-dict-literal/good.py
Labels: Documentation 📖

#6245 Added message example for return-in-init
  doc/data/messages/r/return-in-init/bad.py
  doc/data/messages/r/return-in-init/good.py
  doc/data/messages/r/return-in-init/related.rst
Labels: Documentation 📖

#6165 Add test coverage for sibling except handlers
  tests/functional/u/unused/unused_variable.py
Labels: Maintenance

#6249 Added missing-module-docstring message example
  doc/data/messages/m/missing-module-docstring/bad.py
  doc/data/messages/m/missing-module-docstring/good.py
Labels: Documentation 📖

#6248 Added missing-function-docstring message example
  doc/data/messages/m/missing-function-docstring/bad.py
  doc/data/messages/m/missing-function-docstring/good.py
Labels: Documentation 📖

#6247 Added useless-return message example
  doc/data/messages/u/useless-return/bad.py
  doc/data/messages/u/useless-return/good.py
Labels: Documentation 📖

#6104 Added binary-op-exception message example
  doc/data/messages/b/binary-op-exception/bad.py
  doc/data/messages/b/binary-op-exception/good.py
Labels: Documentation 📖

#6188 Make ``linter`` non-optional for ``BaseChecker``
  ChangeLog
  doc/whatsnew/2.14.rst
  pylint/checkers/base_checker.py
  pylint/checkers/stdlib.py
  tests/checkers/unittest_base_checker.py
  tests/message/conftest.py
  tests/message/unittest_message_definition.py
  tests/message/unittest_message_definition_store.py
Labels: Enhancement ✨, Maintenance

#6251 Handle missing keys in option dictionaries
  pylint/config/utils.py
  tests/config/test_deprecations.py
  tests/config/unittest_config.py
  tests/lint/unittest_expand_modules.py
  tests/regrtest_data/dummy_plugin/dummy_plugin.py
Labels: Bug 🪳, Maintenance

#6229 Update TODOs and add changelog entry about ``ArgumentsManager``
  ChangeLog
  doc/whatsnew/2.14.rst
  pylint/config/arguments_manager.py
Labels: Maintenance

#6253 Remove the ``future_option_parsing`` keyword
  pylint/checkers/async.py
  pylint/checkers/base/docstring_checker.py
  pylint/checkers/base_checker.py
  pylint/checkers/classes/class_checker.py
  pylint/checkers/design_analysis.py
  pylint/checkers/exceptions.py
  pylint/checkers/format.py
  pylint/checkers/imports.py
  pylint/checkers/logging.py
  pylint/checkers/misc.py
  pylint/checkers/raw_metrics.py
  pylint/checkers/refactoring/refactoring_checker.py
  pylint/checkers/similar.py
  pylint/checkers/spelling.py
  pylint/checkers/strings.py
  pylint/checkers/typecheck.py
  pylint/config/exceptions.py
  pylint/extensions/bad_builtin.py
  pylint/extensions/broad_try_clause.py
  pylint/extensions/code_style.py
  pylint/extensions/docparams.py
  pylint/extensions/mccabe.py
  pylint/extensions/typing.py
  pylint/lint/pylinter.py
Labels: Maintenance

#5921 Require python ``3.7.2+``
  .github/workflows/tests.yaml
  ChangeLog
  README.rst
  doc/development_guide/testing.rst
  doc/faq.rst
  doc/whatsnew/2.14.rst
  pylint/checkers/non_ascii_names.py
  pylint/constants.py
  pylint/extensions/typing.py
  requirements_test.txt
  setup.cfg
  tests/functional/d/deprecated/deprecated_method_getmoduleinfo.py
  tests/functional/d/deprecated/deprecated_method_getmoduleinfo.rc
  tests/functional/d/deprecated/deprecated_method_getmoduleinfo.txt
  tests/functional/d/deprecated/deprecated_module_py3.rc
  tests/functional/i/inconsistent/inconsistent_returns_noreturn.rc
  tests/functional/i/inherit_non_class.py
  tests/functional/i/inherit_non_class.txt
  tox.ini
Labels: Blocked 🚧, python 3.7, Maintenance

#6257 Copy all ``OptionsProvideMixIn`` methods to ``ArgumentsProvider``
  pylint/checkers/base_checker.py
  pylint/config/arguments_provider.py
  tests/test_regr.py
Labels: Maintenance

#6258 Set ``pyupgrade`` to ``--py37-plus``
  .pre-commit-config.yaml
  tests/config/unittest_config.py
  tests/test_self.py
Labels: python 3.7

#6264 Added no-else-raise message example
  doc/data/messages/n/no-else-raise/bad.py
  doc/data/messages/n/no-else-raise/good.py
Labels: Documentation 📖

#6265 Added no-else-return message example
  doc/data/messages/n/no-else-return/bad.py
  doc/data/messages/n/no-else-return/good.py
Labels: Documentation 📖

#6261 Use ``namespace`` in two more checkers
  pylint/checkers/base/name_checker/checker.py
  pylint/checkers/variables.py
  pylint/config/utils.py
Labels: Maintenance

#6260 Remove ``OptionsProviderMixIn`` from ``BaseChecker``
  pylint/checkers/base_checker.py
  pylint/config/arguments_manager.py
  pylint/config/arguments_provider.py
  tests/test_regr.py
Labels: Maintenance

#6266 Number of small refactors in ``argparse`` code
  pylint/config/arguments_manager.py
  pylint/config/config_initialization.py
  pylint/lint/pylinter.py
  pylint/typing.py
Labels: Maintenance

#6267 Create ``_OutputFormatAction``
  pylint/config/callback_actions.py
  pylint/lint/pylinter.py
  pylint/testutils/decorator.py
  pylint/typing.py
Labels: Maintenance

#6270 Use ``namespace`` for ``ignore`` and ``ignore_patterns``
  pylint/lint/pylinter.py
  tests/lint/unittest_lint.py
  tests/regrtest_data/dummy_plugin/dummy_conf_plugin.py
Labels: Maintenance

#6268 Remove removed messages from the tests
  pylint/constants.py
  tests/functional/d/disabled_msgid_in_pylintrc.rc
  tests/functional/n/name/name_styles.rc
  tests/functional/o/old_division_floats.py
  tests/functional/o/old_division_floats.rc
  tests/functional/o/old_division_manually.py
  tests/functional/o/old_division_manually.rc
Labels: Maintenance

#6272 Add ``music21`` and remove ``graph-explorer`` from primer
  tests/primer/packages_to_lint_batch_one.json
Labels: primer

#6262 Added no-else-break message example
  doc/data/messages/n/no-else-break/bad.py
  doc/data/messages/n/no-else-break/good.py
Labels: Documentation 📖

#6271 Use ``namespace`` in ``PyLinter`` and the functional config tests
  pylint/config/arguments_manager.py
  pylint/config/callback_actions.py
  pylint/config/config_initialization.py
  pylint/config/option.py
  pylint/config/option_parser.py
  pylint/lint/pylinter.py
  tests/checkers/unittest_format.py
  tests/config/functional/toml/issue_3181/top_level_list_of_disable.2.out
  tests/config/functional/toml/issue_3181/top_level_list_of_disable.result.json
  tests/config/functional/toml/issue_3181/top_level_list_of_disable.toml
  tests/config/functional/toml/issue_4580/correct_basic_name_group.result.json
  tests/config/functional/toml/issue_4580/correct_import_preferred_module.result.json
  tests/config/functional/toml/issue_4580/empty_list.2.out
  tests/config/functional/toml/issue_4580/empty_list.toml
  tests/config/functional/toml/issue_4580/invalid_data_for_basic.2.out
  tests/config/functional/toml/issue_4580/top_level_disable.2.out
  tests/config/functional/toml/issue_4580/top_level_disable.result.json
  tests/config/functional/toml/issue_4580/valid_data_for_basic.result.json
  tests/config/functional/toml/issue_4580/valid_data_for_basic.toml
  tests/config/functional/toml/issue_4580/valid_data_for_import.result.json
  tests/config/functional/toml/issue_4580/valid_data_for_import.toml
  tests/config/test_functional_config_loading.py
  tests/test_self.py
Labels: Maintenance

#6277 Remove last use of ``config`` in ``PyLinter``
  pylint/lint/pylinter.py
  pylint/utils/utils.py
  tests/config/test_config.py
  tests/unittest_reporting.py
Labels: Maintenance

#6278 Deprecate ``BaseChecker.config``
  ChangeLog
  doc/whatsnew/2.14.rst
  pylint/config/arguments_manager.py
  pylint/config/arguments_provider.py
  pylint/lint/pylinter.py
  tests/test_func.py
  tests/test_functional.py
  tests/test_regr.py
Labels: Maintenance

#6283 Do not use ``config`` in ``option_value``
  pylint/config/arguments_provider.py
Labels: Maintenance

#6209 Update optdicts in ``pyreverse``
  pylint/config/options_provider_mixin.py
  pylint/pyreverse/main.py
  tests/pyreverse/test_main.py
Labels: topic-configuration, Maintenance

#6285 Let ``UnittestLinter`` subclass ``PyLinter``
  pylint/testutils/unittest_linter.py
Labels: Maintenance

#6282 Use ``namespace`` in ``--generate-rcfile`` and deprecate it
  doc/Makefile
  pylint/config/arguments_manager.py
  pylint/config/callback_actions.py
  tbump.toml
  tests/test_self.py
Labels: Maintenance

#6286 Update links in documentation
  .github/ISSUE_TEMPLATE/QUESTION.yml
  .github/ISSUE_TEMPLATE/config.yml
  ChangeLog
  doc/backlinks.rst
  doc/conf.py
  doc/development_guide/contribute.rst
  doc/development_guide/testing.rst
  doc/faq.rst
  doc/how_tos/custom_checkers.rst
  doc/intro.rst
  doc/tutorial.rst
  doc/user_guide/ide-integration.rst
  doc/user_guide/options.rst
  doc/whatsnew/1.6.rst
  doc/whatsnew/1.7.rst
  doc/whatsnew/1.8.rst
  doc/whatsnew/2.0.rst
  doc/whatsnew/2.13.rst
  doc/whatsnew/2.6.rst
  doc/whatsnew/2.9.rst
  pylint/checkers/non_ascii_names.py
  pylint/checkers/stdlib.py
  pylint/checkers/unicode.py
  pylint/extensions/docparams.rst
  setup.cfg
Labels: Documentation 📖

#6289 Remove the ``optparse`` section from ``set_config``
  pylint/testutils/decorator.py
Labels: Maintenance

#6291 Move general options to ``PyLinter`` from individual checkers
  pylint/checkers/imports.py
  pylint/checkers/typecheck.py
  pylint/lint/pylinter.py
Labels: Maintenance

#6293 Do not use deprecated methods in ``PyLinter``
  pylint/lint/pylinter.py
  tests/config/functional/toml/unknown_msgid/enable_unknown_msgid.result.json
  tests/config/test_deprecations.py
  tests/test_import_graph.py
Labels: Maintenance

#6297 Remove use of deprecated methods in ``_ArgumentsProvider`` and ``_config_initialization``
  pylint/config/arguments_provider.py
  pylint/config/config_initialization.py
  tests/config/test_deprecations.py
Labels: Maintenance

#6303 Use ``python-typing-update`` on ``pylint/testutils`` directory
  pylint/testutils/checker_test_case.py
  pylint/testutils/configuration_test.py
  pylint/testutils/functional/find_functional_tests.py
  pylint/testutils/functional/lint_module_output_update.py
  pylint/testutils/functional/test_file.py
  pylint/testutils/get_test_info.py
  pylint/testutils/lint_module_test.py
  pylint/testutils/output_line.py
  pylint/testutils/primer.py
  pylint/testutils/pyreverse.py
  pylint/testutils/reporter_for_tests.py
  pylint/testutils/tokenize_str.py
  pylint/testutils/unittest_linter.py
  pylint/testutils/utils.py
Labels: topic-typing, Maintenance

#6304 Use ``python-typing-update`` on ``pylint/utils`` and ``message`` dirs
  pylint/message/message_definition.py
  pylint/message/message_definition_store.py
  pylint/message/message_id_store.py
  pylint/utils/docs.py
  pylint/utils/file_state.py
  pylint/utils/linterstats.py
  pylint/utils/pragma_parser.py
  pylint/utils/utils.py
Labels: topic-typing, Maintenance

#6300 Create ``_ExtendArgument``
  pylint/config/argument.py
  pylint/config/arguments_manager.py
  pylint/config/arguments_provider.py
  pylint/config/callback_actions.py
  pylint/config/utils.py
Labels: Maintenance

#6305 Use ``python-typing-update`` on ``pylint/reporters`` directory
  pylint/reporters/__init__.py
  pylint/reporters/base_reporter.py
  pylint/reporters/collecting_reporter.py
  pylint/reporters/json_reporter.py
  pylint/reporters/multi_reporter.py
  pylint/reporters/reports_handler_mix_in.py
  pylint/reporters/text.py
  pylint/reporters/ureports/base_writer.py
  pylint/reporters/ureports/nodes.py
  pylint/reporters/ureports/text_writer.py
Labels: topic-typing, Maintenance

#6307 Use ``python-typing-update`` on ``pylint/config`` directory
  pylint/config/argument.py
  pylint/config/arguments_manager.py
  pylint/config/arguments_provider.py
  pylint/config/callback_actions.py
  pylint/config/config_file_parser.py
  pylint/config/config_initialization.py
  pylint/config/deprecation_actions.py
  pylint/config/find_default_config_files.py
  pylint/config/help_formatter.py
  pylint/config/option.py
  pylint/config/option_manager_mixin.py
  pylint/config/utils.py
Labels: topic-typing, Maintenance

#6308 Use ``python-typing-update`` on ``pylint/extensions`` directory
  pylint/extensions/__init__.py
  pylint/extensions/_check_docs_utils.py
  pylint/extensions/bad_builtin.py
  pylint/extensions/broad_try_clause.py
  pylint/extensions/check_elif.py
  pylint/extensions/code_style.py
  pylint/extensions/comparetozero.py
  pylint/extensions/comparison_placement.py
  pylint/extensions/confusing_elif.py
  pylint/extensions/consider_ternary_expression.py
  pylint/extensions/docparams.py
  pylint/extensions/docstyle.py
  pylint/extensions/empty_comment.py
  pylint/extensions/emptystring.py
  pylint/extensions/for_any_all.py
  pylint/extensions/mccabe.py
  pylint/extensions/overlapping_exceptions.py
  pylint/extensions/private_import.py
  pylint/extensions/redefined_variable_type.py
  pylint/extensions/set_membership.py
  pylint/extensions/typing.py
  pylint/extensions/while_used.py
Labels: topic-typing, Maintenance

#6309 Use ``python-typing-update`` on ``pylint/pyreverse`` directory
  pylint/message/message.py
  pylint/pyreverse/diadefslib.py
  pylint/pyreverse/dot_printer.py
  pylint/pyreverse/mermaidjs_printer.py
  pylint/pyreverse/plantuml_printer.py
  pylint/pyreverse/printer.py
  pylint/pyreverse/printer_factory.py
  pylint/pyreverse/utils.py
  pylint/pyreverse/vcg_printer.py
Labels: topic-typing, Maintenance

#6310 Use ``python-typing-update`` on ``pylint/lint`` directory
  pylint/lint/expand_modules.py
  pylint/lint/parallel.py
  pylint/lint/pylinter.py
  pylint/lint/report_functions.py
  pylint/lint/run.py
Labels: topic-typing, Maintenance

#6311 Use ``python-typing-update`` on ``pylint/checkers/...`` directories
  pylint/checkers/base/__init__.py
  pylint/checkers/base/basic_checker.py
  pylint/checkers/base/name_checker/checker.py
  pylint/checkers/classes/__init__.py
  pylint/checkers/classes/class_checker.py
  pylint/checkers/refactoring/__init__.py
  pylint/checkers/refactoring/implicit_booleaness_checker.py
  pylint/checkers/refactoring/recommendation_checker.py
  pylint/checkers/refactoring/refactoring_checker.py
Labels: topic-typing, Maintenance
