Repository pylint-dev/pylint, pull requests merged in 2022-12, with the labels that each got.

#7887 add test and expl for line-too-long useless-supp FP
  doc/data/messages/l/line-too-long/details.rst
  doc/whatsnew/fragments/3368.false_positive
  tests/regrtest_data/line_too_long_no_code.py
  tests/test_self.py
Labels: Documentation :green_book:, False Positive 🦟, backport maintenance/2.15.x

#7878 Fix ``missing-param-doc`` FP
  doc/whatsnew/fragments/7827.false_positive
  pylint/extensions/_check_docs_utils.py
  tests/functional/ext/docparams/parameter/missing_param_doc_required_Google.py
Labels: Blocked 🚧, Needs review 🔍, False Positive 🦟, backport maintenance/2.15.x

#7899 Bump pylint to 2.15.8, update changelog
  CONTRIBUTORS.txt
  doc/whatsnew/2/2.15/index.rst
  doc/whatsnew/fragments/3368.false_positive
  doc/whatsnew/fragments/4984.false_positive
  doc/whatsnew/fragments/7209.false_positive
  doc/whatsnew/fragments/7827.false_positive
  doc/whatsnew/fragments/7860.false_positive
  pylint/__pkginfo__.py
  script/.contributors_aliases.json
  tbump.toml
Labels: Maintenance

#7904 [doc] Upgrade generated doc, create example for redundant-typehint-argument
  doc/data/messages/r/redundant-typehint-argument/bad.py
  doc/data/messages/r/redundant-typehint-argument/good.py
  doc/data/messages/r/redundant-typehint-argument/pylintrc
  doc/user_guide/checkers/extensions.rst
  doc/user_guide/checkers/features.rst
  doc/user_guide/messages/messages_overview.rst
Labels: Maintenance, Skip news :mute:

#7802 Add flag `--clear-cache-post-run` to support server-like usage
  doc/whatsnew/fragments/5401.feature
  examples/pylintrc
  examples/pyproject.toml
  pylint/lint/base_options.py
  pylint/lint/run.py
  pylintrc
  tests/config/test_config.py
Labels: Enhancement ✨, topic-configuration

#7908 Fixes ``method-cache-max-size-none`` false positive
  doc/whatsnew/fragments/7857.false_positive
  pylint/checkers/base/name_checker/checker.py
  pylint/checkers/design_analysis.py
  pylint/checkers/stdlib.py
  pylint/checkers/utils.py
  tests/functional/m/method_cache_max_size_none.py
  tests/functional/m/method_cache_max_size_none.txt
Labels: False Positive 🦟, backport maintenance/2.15.x

#7806 Emit `used-before-assignment` for further imports guarded by TYPE_CHECKING
  doc/whatsnew/fragments/7539.false_negative
  pylint/checkers/variables.py
  pylint/constants.py
  tests/functional/u/used/used_before_assignment_typing.py
  tests/functional/u/used/used_before_assignment_typing.txt
Labels: False Negative 🦋, C: used-before-assignment

#7922 Prevent `used-before-assignment` in pattern matching with a guard
  doc/whatsnew/fragments/5327.false_positive
  pylint/checkers/variables.py
  tests/functional/u/used/used_before_assignment_py310.py
  tests/functional/u/used/used_before_assignment_py310.rc
Labels: False Positive 🦟, backport maintenance/2.15.x

#7921 Fix unreleased false positives with `used-before-assignment`
  pylint/checkers/variables.py
  tests/functional/u/undefined/undefined_variable_py38.py
  tests/functional/u/used/used_before_assignment.py
Labels: False Positive 🦟, Unreleased, Skip news :mute:

#7888 7788 no else return False Negative fix
  doc/whatsnew/fragments/7788.false_negative
  pylint/checkers/refactoring/refactoring_checker.py
  pylint/lint/pylinter.py
  tests/functional/n/no/no_else_break.txt
  tests/functional/n/no/no_else_continue.txt
  tests/functional/n/no/no_else_raise.txt
  tests/functional/n/no/no_else_return.py
  tests/functional/n/no/no_else_return.txt
  tests/functional/r/raise_missing_from.py
Labels: False Negative 🦋

#7834 Avoid hanging forever after a parallel job was killed
  doc/whatsnew/fragments/3899.bugfix
  pylint/lint/parallel.py
  pylint/lint/run.py
  tests/test_check_parallel.py
Labels: Bug :beetle:, topic-multiprocessing, backport maintenance/2.15.x

#7936 Add documentation for emitted messages
  doc/data/messages/d/disallowed-name/bad.py
  doc/data/messages/d/disallowed-name/details.rst
  doc/data/messages/d/disallowed-name/good.py
  doc/data/messages/e/else-if-used/bad.py
  doc/data/messages/e/else-if-used/details.rst
  doc/data/messages/e/else-if-used/good.py
  doc/data/messages/e/else-if-used/pylintrc
  doc/data/messages/i/import-error/bad.py
  doc/data/messages/i/import-error/details.rst
  doc/data/messages/i/import-error/good.py
  doc/data/messages/i/import-self/bad.py
  doc/data/messages/i/import-self/details.rst
  doc/data/messages/i/import-self/good.py
Labels: Documentation :green_book:, Skip news :mute:

#7918 fix: bump dill to >= 0.3.6, prevents tests hanging with python3.11
  pyproject.toml
  requirements_test_pre_commit.txt
Labels: Skip news :mute:, backport maintenance/2.15.x

#7940 Fix ModuleNotFoundError when using pylint_django
  doc/whatsnew/fragments/7938.bugfix
  pylint/lint/pylinter.py
Labels: Bug :beetle:, backport maintenance/2.15.x

#7931 Fix inconsistent argument exit code when argparse exit with its own error code
  doc/whatsnew/fragments/7931.bugfix
  pylint/config/arguments_manager.py
  pylint/config/config_initialization.py
  tests/lint/test_run_pylint.py
  tests/lint/unittest_expand_modules.py
Labels: Bug :beetle:, backport maintenance/2.15.x

#7949 [no-member doc] Add generated-members documentation
  doc/data/messages/n/no-member/details.rst
Labels: Documentation :green_book:, Skip news :mute:

#7947 Add test for ModuleNotFoundError fix
  tests/regrtest_data/importing_plugin/importing_plugin.py
  tests/regrtest_data/settings_project/models.py
  tests/regrtest_data/settings_project/settings.py
  tests/test_self.py
Labels: Maintenance, Skip news :mute:

#7948 [testutil] More information in output for functional test fail
  pylint/testutils/lint_module_test.py
Labels: Maintenance, Skip news :mute:

#7952 Release branch 2.15.9
  doc/whatsnew/2/2.15/index.rst
  doc/whatsnew/fragments/3899.bugfix
  doc/whatsnew/fragments/5327.false_positive
  doc/whatsnew/fragments/7931.bugfix
  doc/whatsnew/fragments/7938.bugfix
  pylint/__pkginfo__.py
  tbump.toml
Labels: Maintenance

#7956 Merge maintenance 2.15.9 in main
  doc/whatsnew/2/2.15/index.rst
Labels: Maintenance, Skip news :mute:

#7958 [doc] Upgrade the doc following the addition of clear-cache-post-run
  doc/user_guide/configuration/all-options.rst
Labels: Documentation :green_book:, Skip news :mute:

#7970 Add documentation for ternary operation messages
  doc/data/messages/c/consider-ternary-expression/bad.py
  doc/data/messages/c/consider-ternary-expression/details.rst
  doc/data/messages/c/consider-ternary-expression/good.py
  doc/data/messages/c/consider-ternary-expression/pylintrc
  doc/data/messages/c/consider-using-ternary/bad.py
  doc/data/messages/c/consider-using-ternary/details.rst
  doc/data/messages/c/consider-using-ternary/good.py
Labels: Documentation :green_book:, Skip news :mute:

#7968 ``consider-using-with`` now triggers for ``pathlib.Path.open``
  doc/whatsnew/fragments/7964.false_negative
  pylint/checkers/refactoring/refactoring_checker.py
  tests/functional/c/consider/consider_using_with.py
  tests/functional/c/consider/consider_using_with.txt
Labels: False Negative 🦋

#7974 update while-used doc
  pylint/extensions/while_used.py
Labels: Documentation :green_book:, Skip news :mute:

#7980 Fix `used-before-assignment` if conditional imports guarded again when used
  doc/whatsnew/fragments/7979.false_positive
  pylint/checkers/variables.py
  tests/functional/u/used/used_before_assignment_typing.py
  tests/functional/u/used/used_before_assignment_typing.txt
Labels: False Positive 🦟, backport maintenance/2.15.x

#7975 Fix `use-sequence-for-iteration` when unpacking a set with `*`
  doc/whatsnew/fragments/5788.false_positive
  pylint/checkers/refactoring/recommendation_checker.py
  pylint/checkers/utils.py
  tests/functional/ext/code_style/cs_consider_using_tuple.py
  tests/functional/ext/code_style/cs_consider_using_tuple.txt
  tests/functional/u/use/use_sequence_for_iteration.py
  tests/functional/u/use/use_sequence_for_iteration.txt
Labels: False Positive 🦟, backport maintenance/2.15.x

#7988 Fix `use-sequence-for-iteration` when unpacking a set with `*` (#7975)
  doc/whatsnew/fragments/5788.false_positive
  pylint/checkers/refactoring/recommendation_checker.py
  pylint/checkers/utils.py
  tests/functional/ext/code_style/cs_consider_using_tuple.py
  tests/functional/ext/code_style/cs_consider_using_tuple.txt
  tests/functional/u/use/use_sequence_for_iteration.py
  tests/functional/u/use/use_sequence_for_iteration.txt
Labels: False Positive 🦟

#7965 [pre-commit] Trying out black 23.1a1
  .pre-commit-config.yaml
  examples/custom_raw.py
  pylint/checkers/base/basic_error_checker.py
  pylint/checkers/base_checker.py
  pylint/checkers/classes/class_checker.py
  pylint/checkers/classes/special_methods_checker.py
  pylint/checkers/misc.py
  pylint/checkers/refactoring/recommendation_checker.py
  pylint/checkers/refactoring/refactoring_checker.py
  pylint/checkers/spelling.py
  pylint/checkers/threading_checker.py
  pylint/checkers/unicode.py
  pylint/checkers/variables.py
  pylint/epylint.py
  pylint/extensions/bad_builtin.py
  pylint/extensions/code_style.py
  pylint/extensions/consider_ternary_expression.py
  pylint/extensions/empty_comment.py
  pylint/extensions/eq_without_hash.py
  pylint/extensions/for_any_all.py
  pylint/extensions/no_self_use.py
  pylint/extensions/private_import.py
  pylint/extensions/redefined_loop_name.py
  pylint/extensions/set_membership.py
  pylint/extensions/while_used.py
  pylint/lint/message_state_handler.py
  pylint/pyreverse/diagrams.py
  requirements_test_pre_commit.txt
  tests/checkers/unittest_deprecated.py
  tests/checkers/unittest_design.py
  tests/checkers/unittest_imports.py
  tests/checkers/unittest_variables.py
  tests/lint/unittest_lint.py
  tests/test_deprecation.py
Labels: dependency, Skip news :mute:

#7976 Fixes bug when loading user-provided msg-template.
  doc/whatsnew/fragments/5636.bugfix
  pylint/reporters/text.py
  tests/reporters/unittest_reporting.py
Labels: Bug :beetle:, backport maintenance/2.15.x

#7993 Manual backport of #7976 following cherry-pick conflict
  doc/whatsnew/fragments/5636.bugfix
  pylint/reporters/text.py
  tests/reporters/unittest_reporting.py
Labels: Maintenance

#7992 Use codecov instead of coveralls for coverage reporting
  .github/workflows/tests.yaml
  README.rst
  codecov.yml
  requirements_test.txt
Labels: Maintenance, Skip news :mute:

#7994 Cover missing line in dict-init-mutate test
  tests/functional/ext/dict_init_mutate.py
Labels: Maintenance, Skip news :mute:

#7996 Cover more lines
  pylint/extensions/docparams.py
  tests/functional/ext/code_style/cs_consider_using_namedtuple_or_dataclass.py
  tests/functional/ext/code_style/cs_consider_using_namedtuple_or_dataclass.txt
  tests/functional/ext/consider_ternary_expression/consider_ternary_expression.py
  tests/functional/ext/consider_ternary_expression/consider_ternary_expression.rc
  tests/functional/ext/consider_ternary_expression/consider_ternary_expression.txt
  tests/functional/ext/docparams/docparams.py
  tests/functional/ext/private_import/private_import.py
  tests/functional/ext/private_import/private_import.txt
Labels: Skip news :mute:

#7869 Add `no-header` run option
  doc/whatsnew/fragments/5362.feature
  pylint/reporters/text.py
  tests/test_self.py
Labels: Enhancement ✨

#7987 class attrs should not emit assigning-non-slot msg
  doc/whatsnew/fragments/6001.false_positive
  pylint/checkers/classes/class_checker.py
  pylint/checkers/utils.py
  tests/functional/a/assigning/assigning_non_slot.py
  tests/functional/a/assigning/assigning_non_slot.txt
  tests/functional/a/assigning/assigning_non_slot_4509.txt
Labels: False Positive 🦟, backport maintenance/2.15.x
