Repository pylint-dev/pylint, pull requests merged in 2022-02, with the labels that each got.

#5745 Remove VariableVisitConsumerAction.CONSUME
  pylint/checkers/variables.py
Labels: Maintenance

#5628 Add `iterating-modified-list` checker for modified lists
  ChangeLog
  doc/whatsnew/2.13.rst
  pylint/checkers/base.py
  pylint/checkers/modified_iterating_checker.py
  tests/checkers/unittest_base.py
  tests/functional/c/consider/consider_using_dict_items.py
  tests/functional/m/modified_iterating.py
  tests/functional/m/modified_iterating.txt
Labels: Enhancement ✨

#5687 tests_functional rc file not found overpasses default disables hotfix
  doc/development_guide/testing.rst
Labels: Bug 🪳, Needs Review 🔍

#5748 Fix false positive `used-before-assignment` for named expressions in ternary operators
  ChangeLog
  doc/whatsnew/2.13.rst
  pylint/checkers/variables.py
  tests/functional/u/undefined/undefined_variable_py38.py
Labels: False Positive 🦟

#5664 Remove unnecessary ``try...except`` from ``frame()`` call
  pylint/checkers/classes/class_checker.py
Labels: Maintenance

#5708 False negative - tuple unpacking
  ChangeLog
  doc/whatsnew/2.13.rst
  pylint/checkers/variables.py
  tests/functional/u/unbalanced_tuple_unpacking.py
  tests/functional/u/unbalanced_tuple_unpacking.txt
Labels: False Negative 🦋

#5738 Fix assignment-from-none false negative case using list.sort()
  ChangeLog
  doc/whatsnew/2.13.rst
  pylint/checkers/typecheck.py
  tests/functional/a/assign/assignment_from_no_return_2.py
  tests/functional/a/assign/assignment_from_no_return_2.txt
Labels: False Negative 🦋

#5766 Avoid using get on a defaultdict
  pylint/lint/pylinter.py
Labels: Bug 🪳, Minor 💅

#5682 Lint all files in a directory by expanding arguments
  ChangeLog
  doc/faq.rst
  doc/user_guide/run.rst
  doc/whatsnew/2.13.rst
  pylint/lint/pylinter.py
  tests/regrtest_data/directory/package/__init__.py
  tests/regrtest_data/directory/package/module.py
  tests/regrtest_data/directory/package/subpackage/__init__.py
  tests/regrtest_data/directory/package/subpackage/module.py
  tests/regrtest_data/directory/subdirectory/module.py
  tests/regrtest_data/directory/subdirectory/subsubdirectory/module.py
  tests/test_self.py
Labels: Enhancement ✨, topic-command-line

#5774 wrong-import-position is equivalent to E402
  doc/faq.rst
Labels: Documentation 📖

#5772 Fix crash in `use-maxsplit-arg` checker where `sep` given by keyword
  ChangeLog
  doc/whatsnew/2.13.rst
  pylint/checkers/refactoring/recommendation_checker.py
  tests/functional/u/use/use_maxsplit_arg.py
  tests/functional/u/use/use_maxsplit_arg.txt
Labels: Crash 💥

#5775 Fix unsafe `utils.safe_infer`
  pylint/checkers/utils.py
Labels: Crash 💥

#5744 Fix duplicate names of ``Pylint Messages`` in docs
  doc/exts/pylint_messages.py
  doc/messages/messages_introduction.rst
  doc/messages/messages_list.rst
  doc/release.md
  tbump.toml
Labels: Documentation 📖, High priority

#5781 Add parameter typing to ``PyLinter``
  pylint/lint/pylinter.py
Labels: Maintenance

#5764 Fix false negative for `used-before-assignment` when some except handlers don't define a name
  ChangeLog
  doc/whatsnew/2.13.rst
  pylint/checkers/variables.py
  tests/functional/u/use/used_before_assignment_except_handler_for_try_with_return.py
  tests/functional/u/use/used_before_assignment_except_handler_for_try_with_return.txt
  tests/functional/u/use/used_before_assignment_except_handler_for_try_with_return_py38.py
  tests/functional/u/use/used_before_assignment_except_handler_for_try_with_return_py38.rc
Labels: False Negative 🦋, C: used-before-assignment

#5790 Fix the period added in docstring automatically by mistake
  .pre-commit-config.yaml
  pylint/checkers/format.py
  pylint/lint/run.py
  pylint/pyreverse/diadefslib.py
Labels: Documentation 📖, task

#5792 Update Testing docs to reflect enforced folder structure
  doc/development_guide/testing.rst
Labels: Documentation 📖

#5816 Don't assume test runners have more than 2 cores available
  tests/test_check_parallel.py
Labels: Maintenance

#5820 Add note on how to share the badge for pylint
  CONTRIBUTORS.txt
  README.rst
Labels: Documentation 📖

#5837 Add title in running pylint's documentation
  doc/user_guide/output.rst
  doc/user_guide/run.rst
Labels: Documentation 📖

#5841 Add some flags showing information to the CI pytest runs
  .github/workflows/ci.yaml
Labels: Maintenance

#5842 Add a ``testutil`` extra-require and add ``gitpython`` to it
  ChangeLog
  doc/whatsnew/2.13.rst
  requirements_test_min.txt
  setup.cfg
Labels: Bug 🪳
