Repository pylint-dev/pylint, pull requests merged in 2022-07, with the labels that each got.

#7103 Update docs to explain escape character not valid
  doc/user_guide/configuration/all-options.rst
  pylint/lint/base_options.py
Labels: Documentation :green_book:

#7110 [not-callable] Add a regression test for issue #4660
  tests/functional/r/regression_02/regression_4660.py
  tests/functional/r/regression_02/regression_4660.rc
  tests/functional/r/regression_02/regression_4660.txt
Labels: Maintenance, Skip news :mute:

#7119 Restore `sys.path` in `test_load_plugin_configuration`
  tests/lint/unittest_lint.py
Labels: Skip news :mute:

#6636 [consider-using-in] Suggest set instead of tuple for membership
  pylint/checkers/refactoring/refactoring_checker.py
  tests/functional/c/consider/consider_using_in.txt
Labels: Enhancement ✨, Minor 💅

#7132 Fix crash when using `enumerate` in a ternary expression
  doc/whatsnew/2/2.14/full.rst
  pylint/checkers/variables.py
  tests/functional/u/undefined/undefined_loop_variable.py
  tests/functional/u/undefined/undefined_loop_variable.txt
Labels: Needs backport, Crash 💥

#7102 doc(fail-under): improve description
  doc/user_guide/configuration/all-options.rst
  examples/pylintrc
  examples/pyproject.toml
  pylint/lint/base_options.py
  pylintrc
Labels: Discussion 🤔, Documentation :green_book:

#6996 [empty_comment] fix checker name in code and docs
  doc/user_guide/checkers/extensions.rst
  pylint/extensions/empty_comment.py
  tests/message/unittest_message_id_store.py
Labels: Work in progress, Waiting on author, Maintenance

#7138 [struct.unpack] Add a test for a false positive no-member
  tests/functional/r/regression_02/regression_5801.py
Labels: Maintenance, Skip news :mute:

#7141 Bump or remove some ``TODOs``
  pylint/checkers/exceptions.py
  pylint/config/callback_actions.py
  pylint/testutils/functional/test_file.py
Labels: Maintenance

#7142 Use the default config in the messages documentation tests
  doc/data/messages/b/bad-builtin/pylintrc
  doc/data/messages/c/consider-using-tuple/pylintrc
  doc/data/messages/m/missing-param-doc/pylintrc
  doc/data/messages/m/missing-raises-doc/pylintrc
  doc/data/messages/m/missing-type-doc/pylintrc
  doc/data/messages/o/overlapping-except/pylintrc
  doc/data/messages/r/redefined-variable-type/pylintrc
  doc/data/messages/u/use-set-for-membership/pylintrc
  doc/data/messages/u/using-final-decorator-in-unsupported-version/pylintrc
  doc/test_messages_documentation.py
Labels: Documentation :green_book:, Maintenance

#7088 Add partial typing to ``class_checker``
  pylint/checkers/classes/class_checker.py
  pylint/checkers/utils.py
Labels: topic-typing

#7146 Remove unsupported option from our own ``pylintrc``
  pylintrc
Labels: topic-configuration

#7148 singleton-comparison is equivalent to E711
  doc/faq.rst
Labels: Documentation :green_book:

#7149 Allow lists of default values in parameter documentation for ``Numpy``
  doc/whatsnew/2/2.14/full.rst
  pylint/extensions/_check_docs_utils.py
  tests/functional/ext/docparams/parameter/missing_param_doc_required_Numpy.py
Labels: Needs backport, False Positive 🦟

#7152 Added documentation examples for `consider-using-any-or-all`.
  doc/data/messages/c/consider-using-any-or-all/bad.py
  doc/data/messages/c/consider-using-any-or-all/details.rst
  doc/data/messages/c/consider-using-any-or-all/good.py
  doc/data/messages/c/consider-using-any-or-all/pylintrc
Labels: Documentation :green_book:

#7151 Added documentation examples for `class-variable-slots-conflict`.
  doc/data/messages/c/class-variable-slots-conflict/bad.py
  doc/data/messages/c/class-variable-slots-conflict/details.rst
  doc/data/messages/c/class-variable-slots-conflict/good.py
Labels: Documentation :green_book:

#7154 Prevent appending distinct crash reports together that occur in the same hour
  pylint/lint/pylinter.py
Labels: Maintenance, Skip news :mute:

#7156 Increase new primer timeout to 60m
  .github/workflows/primer_run_main.yaml
Labels: Maintenance, primer, Skip news :mute:

#7158 Add documentation on using a minimal config file
  doc/user_guide/configuration/index.rst
Labels: Documentation :green_book:

#7157 Bump runners to ``3.10``
  .github/workflows/checks.yaml
  .github/workflows/release.yml
  .github/workflows/tests.yaml
  doc/test_messages_documentation.py
Labels: Maintenance

#7162 In "Messages Overview", show the `bad_code` first
  doc/exts/pylint_messages.py
Labels: Enhancement ✨, Documentation :green_book:, Skip news :mute:

#7165 test_run_pylint_config: ignore pytest args
  tests/config/pylint_config/test_run_pylint_config.py
Labels: Skip news :mute:

#7168 Use trace not turtle in import_outside_toplevel test
  tests/functional/i/import_outside_toplevel.py
  tests/functional/i/import_outside_toplevel.txt
Labels: Skip news :mute:

#7177 README.md: Add Discord invite/badge
  README.rst
Labels: Documentation :green_book:

#7153 Update `astroid` to 2.12
  .github/workflows/checks.yaml
  .github/workflows/primer-test.yaml
  .github/workflows/primer_comment.yaml
  .github/workflows/primer_run_main.yaml
  .github/workflows/primer_run_pr.yaml
  .github/workflows/tests.yaml
  .pyenchant_pylint_custom_dict.txt
  doc/user_guide/usage/run.rst
  doc/whatsnew/2/2.15/index.rst
  pylint/checkers/imports.py
  pylint/checkers/variables.py
  pylint/lint/pylinter.py
  pyproject.toml
  requirements_test.txt
  requirements_test_min.txt
  tests/functional/u/unused/unused_import.py
  tests/functional/u/unused/unused_import.txt
  tests/pyreverse/test_diadefs.py
  tests/pyreverse/test_inspector.py
  tests/test_func.py
  tests/test_self.py
Labels: Astroid, Maintenance

#7179 Links in the documentation to help triaging and labelling the backlog
  doc/development_guide/contributor_guide/contribute.rst
  doc/user_guide/configuration/all-options.rst
Labels: Documentation :green_book:, Skip news :mute:

#7180 Fix typing of most inference calls
  pylint/checkers/utils.py
  pylint/checkers/variables.py
  pylint/pyreverse/utils.py
Labels: topic-typing, Skip news :mute:

#7182 [doc] Separate false postives and bug/crashes in contributor doc
  doc/development_guide/contributor_guide/contribute.rst
Labels: Documentation :green_book:, Skip news :mute:

#7184 Add run_pylint, run_epylint, run_symilar, run_pyreverse explicitely in the api
  pylint/__init__.py
Labels: Documentation :green_book:, Skip news :mute:

#7185 [primer] Fix a silent fail when no command were given
  pylint/testutils/_primer/primer.py
  tests/testutils/_primer/test_primer.py
Labels: primer, Skip news :mute:

#7186 Fix config section name in doc
  doc/exts/pylint_options.py
Labels: Documentation :green_book:

#7183 [typing] Add typing to the tests
  tests/checkers/__init__.py
  tests/checkers/base/unittest_multi_naming_style.py
  tests/checkers/unittest_spelling.py
  tests/checkers/unittest_stdlib.py
  tests/checkers/unittest_unicode/__init__.py
  tests/checkers/unittest_unicode/unittest_bad_chars.py
  tests/checkers/unittest_unicode/unittest_bidirectional_unicode.py
  tests/checkers/unittest_unicode/unittest_invalid_encoding.py
  tests/lint/unittest_lint.py
  tests/pyreverse/test_main.py
  tests/pyreverse/test_printer.py
  tests/test_pylint_runners.py
  tests/test_self.py
  tests/testutils/test_functional_testutils.py
  tests/utils/__init__.py
Labels: Maintenance, Skip news :mute:

#7187 [primer] display results early instead of priming all the packages first
  pylint/testutils/_primer/primer_run_command.py
Labels: primer, Skip news :mute:

#7191 [typing] Add typing to the similar checker
  pylint/checkers/similar.py
Labels: Maintenance, Skip news :mute:

#7194 Add typing to ``exceptions`` checker
  pylint/checkers/exceptions.py
  tests/pyreverse/functional/class_diagrams/colorized_output/colorized.puml
Labels: topic-typing, Maintenance, Skip news :mute:

#6798 Add regression test for Enum imported as alias
  doc/whatsnew/fragments/5776.false_positive
  tests/functional/r/regression_02/regression_5776.py
Labels: False Positive 🦟

#7105 Add regression test for #5832
  doc/whatsnew/fragments/5832.false_positive
  tests/functional/n/no/no_member.py
Labels: False Positive 🦟, Needs astroid update

#7113 Add regression test for #1667
  doc/whatsnew/fragments/1667.bugfix
  tests/lint/unittest_lint.py
Labels: Crash 💥, Needs astroid update

#7112 Add regression test for #7109
  doc/whatsnew/fragments/7109.bugfix
  tests/functional/n/not_callable.py
Labels: Crash 💥, Needs astroid update

#7195 Update tox.ini - Add `isolated_build = True`.
  .github/workflows/checks.yaml
  tox.ini
Labels: Maintenance, Unreleased, Skip news :mute:

#7206 [tests cleanup] Move line-too-long and logging functional tests together
  tests/functional/l/line/__init__.py
  tests/functional/l/line/line_endings.py
  tests/functional/l/line/line_endings.rc
  tests/functional/l/line/line_endings.txt
  tests/functional/l/line/line_too_long.py
  tests/functional/l/line/line_too_long.txt
  tests/functional/l/line/line_too_long_end_of_module.py
  tests/functional/l/line/line_too_long_with_utf8.py
  tests/functional/l/line/line_too_long_with_utf8.txt
  tests/functional/l/line/line_too_long_with_utf8_2.py
  tests/functional/l/logging/__init__.py
  tests/functional/l/logging/logging_format_interpolation.py
  tests/functional/l/logging/logging_format_interpolation.txt
  tests/functional/l/logging/logging_format_interpolation_py36.py
  tests/functional/l/logging/logging_format_interpolation_py36.rc
  tests/functional/l/logging/logging_format_interpolation_py36.txt
  tests/functional/l/logging/logging_format_interpolation_style.py
  tests/functional/l/logging/logging_format_interpolation_style.rc
  tests/functional/l/logging/logging_fstring_interpolation_py36.py
  tests/functional/l/logging/logging_fstring_interpolation_py36.rc
  tests/functional/l/logging/logging_fstring_interpolation_py36.txt
  tests/functional/l/logging/logging_fstring_interpolation_py37.py
  tests/functional/l/logging/logging_fstring_interpolation_py37.rc
  tests/functional/l/logging/logging_fstring_interpolation_py37.txt
  tests/functional/l/logging/logging_not_lazy.py
  tests/functional/l/logging/logging_not_lazy.txt
  tests/functional/l/logging/logging_not_lazy_module.py
  tests/functional/l/logging/logging_not_lazy_module.rc
  tests/functional/l/logging/logging_not_lazy_module.txt
  tests/functional/l/logging/logging_not_lazy_with_logger.py
  tests/functional/l/logging/logging_not_lazy_with_logger.rc
  tests/functional/l/logging/logging_not_lazy_with_logger.txt
  tests/functional/l/logging/logging_too_few_args.py
  tests/functional/l/logging/logging_too_few_args.rc
  tests/functional/l/logging/logging_too_few_args.txt
  tests/functional/l/logging/logging_too_many_args.py
  tests/functional/l/logging/logging_too_many_args.rc
  tests/functional/l/logging/logging_too_many_args.txt
Labels: Maintenance, Skip news :mute:

#7211 Add typing to ``logging.py``
  pylint/checkers/logging.py
Labels: Maintenance, Skip news :mute:

#7193 [doc] Add the spelling checker in the install guide
  doc/user_guide/checkers/features.rst
  doc/user_guide/configuration/all-options.rst
  doc/user_guide/installation/command_line_installation.rst
  doc/user_guide/installation/index.rst
  doc/user_guide/installation/with-multiple-interpreters.rst
  doc/user_guide/messages/messages_overview.rst
Labels: Documentation :green_book:, Skip news :mute:

#7216 Add the confidence for 'unreacheable' code
  pylint/checkers/base/basic_checker.py
  tests/functional/ext/docparams/parameter/missing_param_doc_required_Sphinx.txt
  tests/functional/ext/docparams/raise/missing_raises_doc.txt
  tests/functional/ext/docparams/raise/missing_raises_doc_Google.txt
  tests/functional/ext/docparams/raise/missing_raises_doc_Numpy.txt
  tests/functional/ext/docparams/raise/missing_raises_doc_Sphinx.txt
  tests/functional/ext/docparams/return/missing_return_doc_Google.txt
  tests/functional/ext/docparams/return/missing_return_doc_required_Google.txt
  tests/functional/ext/docparams/return/missing_return_doc_required_Numpy.txt
  tests/functional/ext/docparams/return/missing_return_doc_required_Sphinx.txt
  tests/functional/u/unreachable.txt
Labels: Maintenance, Skip news :mute:

#7218 Add some typing to ``spelling.py``
  pylint/checkers/spelling.py
Labels: Maintenance, Skip news :mute:

#7242 Fix raise-missing-from related PEP
  doc/data/messages/r/raise-missing-from/related.rst
Labels: Documentation :green_book:, Skip news :mute:

#7243 [pyreverse test] Silence a deprecation warning for __implements__
  tests/pyreverse/test_diadefs.py
Labels: Maintenance, Skip news :mute:

#7097 [syntax error] Fix a crash when the line and column can't be retrieved
  doc/whatsnew/fragments/3860.bugfix
  pylint/checkers/imports.py
  pylint/lint/pylinter.py
  tests/functional/i/import_error.txt
  tests/functional/s/syntax/syntax_error.txt
  tests/test_self.py
Labels: Needs backport, Crash 💥

#7239 Remove hard-coded default in 'ignored-argument-names' description
  doc/user_guide/configuration/all-options.rst
  examples/pylintrc
  examples/pyproject.toml
  pylint/checkers/variables.py
Labels: Documentation :green_book:, Skip news :mute:

#7196 Release branch 2.15.0 alpha 0
  CONTRIBUTORS.txt
  doc/whatsnew/2/2.15/index.rst
  doc/whatsnew/fragments/6974.internal
  examples/pylintrc
  examples/pyproject.toml
  pylint/__pkginfo__.py
  script/.contributors_aliases.json
  tbump.toml
Labels: Maintenance, Skip news :mute:

#7247 Fix sys.path pollution in parallel mode
  doc/whatsnew/fragments/7246.bugfix
  pylint/lint/pylinter.py
Labels: Bug :beetle:

#7248 [doc consider-using-with] Add the case where the file isn't even closed
  doc/data/messages/c/consider-using-with/bad.py
  doc/data/messages/c/consider-using-with/details.rst
  doc/data/messages/c/consider-using-with/good.py
  doc/data/messages/c/consider-using-with/related.rst
Labels: Documentation :green_book:, Skip news :mute:

#7249 Remove ``setup.py``
  setup.py
Labels: Maintenance, Skip news :mute:

#7228 Fix crash when regex option raises a `re.error` exception.
  doc/whatsnew/fragments/7202.bugfix
  pylint/config/argument.py
  tests/config/test_config.py
Labels: Crash 💥

#7227 Don't emit ``super-init-not-called`` for abstract ``__init__`` methods
  doc/whatsnew/fragments/3975.false_positive
  pylint/checkers/classes/class_checker.py
  tests/functional/i/init_not_called.py
  tests/functional/i/init_not_called.txt
  tests/functional/n/non/non_init_parent_called.py
  tests/functional/n/non/non_init_parent_called.txt
  tests/functional/s/super/super_init_not_called.py
  tests/functional/s/super/super_init_not_called.rc
  tests/functional/s/super/super_init_not_called.txt
Labels: False Positive 🦟
