Repository pylint-dev/pylint, pull requests merged in 2022-05, with the labels that each got.

#6481 Fix false positive for ``unused-variable`` when specifying a metaclass via a call
  ChangeLog
  doc/whatsnew/2.13.rst
  pylint/checkers/variables.py
  tests/functional/b/bugfix_local_scope_metaclass_1177.py
Labels: Bug 🪳, Needs Backport, False Positive 🦟

#6480 Fix false positive for `undefined-loop-variable` when a loop else raises or returns
  ChangeLog
  doc/whatsnew/2.13.rst
  pylint/checkers/variables.py
  tests/functional/u/undefined/undefined_loop_variable.py
Labels: Bug 🪳, Needs Backport, False Positive 🦟

#6479 Fix false positive for `undefined-loop-variable` for lambda in first of two loops
  ChangeLog
  doc/whatsnew/2.13.rst
  pylint/checkers/variables.py
  tests/functional/u/undefined/undefined_loop_variable.py
Labels: Bug 🪳, Needs Backport, False Positive 🦟

#6482 Disable fixme for internal uses before we make it optional in #3512
  pylint/checkers/base_checker.py
  pylint/checkers/classes/special_methods_checker.py
  pylint/checkers/typecheck.py
  pylint/checkers/utils.py
  pylint/checkers/variables.py
  pylint/config/arguments_manager.py
  pylint/config/arguments_provider.py
  pylint/config/callback_actions.py
  pylint/config/configuration_mixin.py
  pylint/config/find_default_config_files.py
  pylint/config/option.py
  pylint/config/option_manager_mixin.py
  pylint/config/option_parser.py
  pylint/config/options_provider_mixin.py
  pylint/constants.py
  pylint/interfaces.py
  pylint/lint/parallel.py
  pylint/lint/pylinter.py
  pylint/reporters/base_reporter.py
  pylint/reporters/text.py
  pylint/testutils/checker_test_case.py
  pylint/testutils/unittest_linter.py
  pylintrc
  tests/pyreverse/test_diadefs.py
  tests/test_regr.py
  tests/test_self.py
Labels: Maintenance

#6483 Add related and details.rst to 'redundant-unittest-assert' doc
  doc/data/messages/a/assert-on-string-literal/bad.py
  doc/data/messages/a/assert-on-string-literal/details.rst
  doc/data/messages/a/assert-on-string-literal/good.py
  doc/data/messages/a/assert-on-string-literal/related.rst
  doc/data/messages/a/assert-on-tuple/details.rst
  doc/data/messages/r/redundant-unittest-assert/details.rst
  doc/data/messages/r/redundant-unittest-assert/related.rst
Labels: Documentation 📖

#5649 [optional ext] Emit `redefined-loop-name` for redefinitions of loop variables in body
  ChangeLog
  doc/data/messages/r/redefined-loop-name/bad.py
  doc/data/messages/r/redefined-loop-name/good.py
  doc/data/messages/r/redefined-loop-name/pylintrc
  doc/whatsnew/2.14.rst
  pylint/checkers/utils.py
  pylint/checkers/variables.py
  pylint/extensions/redefined_loop_name.py
  tests/functional/c/cellvar_escaping_loop.py
  tests/functional/ext/redefined_loop_name/redefined_loop_name.py
  tests/functional/ext/redefined_loop_name/redefined_loop_name.rc
  tests/functional/ext/redefined_loop_name/redefined_loop_name.txt
  tests/functional/ext/redefined_loop_name/reused_outer_loop_variable.py
  tests/functional/ext/redefined_loop_name/reused_outer_loop_variable.rc
  tests/functional/ext/redefined_loop_name/reused_outer_loop_variable.txt
  tests/functional/r/redefine_loop.py
  tests/functional/r/redefine_loop.txt
  tests/functional/r/reused_outer_loop_variable.txt
  tests/functional/r/reused_outer_loop_variable_py3.py
  tests/functional/r/reused_outer_loop_variable_py3.txt
  tests/functional/t/too/too_many_nested_blocks.py
Labels: Enhancement ✨

#6405 Do not append namespace packages to sys.path
  ChangeLog
  doc/whatsnew/2.14.rst
  pylint/lint/utils.py
  tests/lint/test_namespace_packages.py
  tests/lint/unittest_expand_modules.py
  tests/regrtest_data/namespace_import_self/else/__init__.py
  tests/regrtest_data/namespace_import_self/pylint/__init__.py
Labels: Bug 🪳, Beta-Blocker 🙅🩸

#6347 Avoid reporting useless-suppression on wrong-import-position (#5219)
  ChangeLog
  doc/whatsnew/2.14.rst
  pylint/checkers/imports.py
  tests/functional/u/useless/useless_suppression.py
Labels: Bug 🪳, False Positive 🦟

#6494 Create a path type of argument that automatically expand user/var
  ChangeLog
  doc/whatsnew/2.14.rst
  pylint/checkers/imports.py
  pylint/checkers/spelling.py
  pylint/config/argument.py
  pylint/pyreverse/main.py
Labels: Enhancement ✨, Maintenance

#6493 [spelling checker] Use a context manager to access the private dict
  pylint/checkers/spelling.py
Labels: Maintenance

#6422 [refactor] Create a generic '_check_open_call' function for the StdlibChecker
  pylint/checkers/stdlib.py
Labels: Maintenance

#5847 Enum: Add support for self-defined members
  CONTRIBUTORS.txt
  ChangeLog
  doc/whatsnew/2.14.rst
  pylint/checkers/typecheck.py
  tests/functional/e/enum_self_defined_member_5138.py
  tests/functional/e/enum_self_defined_member_5138.txt
Labels: Bug 🪳, False Positive 🦟

#6413 Add `comparison-of-constants` checker
  ChangeLog
  doc/data/messages/c/comparison-of-constants/bad.py
  doc/data/messages/c/comparison-of-constants/good.py
  doc/whatsnew/2.14.rst
  pylint/checkers/base/comparison_checker.py
  tests/functional/a/access/access_to_protected_members.py
  tests/functional/a/assert_on_tuple.py
  tests/functional/c/comparison_of_constants.py
  tests/functional/c/comparison_of_constants.txt
  tests/functional/c/comparison_with_callable.py
  tests/functional/c/consider/consider_using_get.py
  tests/functional/c/consider/consider_using_in.py
  tests/functional/d/deprecated/deprecated_methods_py38.py
  tests/functional/e/excess_escapes.py
  tests/functional/ext/check_elif/check_elif.py
  tests/functional/ext/comparison_placement/misplaced_comparison_constant.py
  tests/functional/ext/comparison_placement/misplaced_comparison_constant.txt
  tests/functional/i/import_outside_toplevel.py
  tests/functional/i/import_outside_toplevel.txt
  tests/functional/l/literal_comparison.py
  tests/functional/l/literal_comparison.txt
  tests/functional/l/logical_tautology.py
  tests/functional/l/logical_tautology.txt
  tests/functional/m/membership_protocol.py
  tests/functional/m/misplaced_bare_raise.py
  tests/functional/m/misplaced_bare_raise.txt
  tests/functional/n/nan_comparison_check.py
  tests/functional/s/singleton_comparison.py
  tests/functional/s/superfluous_parens.py
  tests/functional/t/too/too_many_boolean_expressions.py
  tests/functional/u/unnecessary/unnecessary_ellipsis.py
  tests/functional/u/unnecessary/unnecessary_not.py
  tests/functional/u/use/use_implicit_booleaness_not_len.py
  tests/functional/u/use/use_implicit_booleaness_not_len.txt
  tests/functional/u/useless/useless_else_on_loop.py
  tests/functional/u/using_constant_test.py
  tests/functional/u/using_constant_test.txt
Labels: Enhancement ✨, Checkers

#6445 Fix `AstCallbackMethod` typing
  pylint/checkers/utils.py
  pylint/typing.py
  tests/checkers/unittest_utils.py
  tests/utils/unittest_ast_walker.py
Labels: Maintenance

#6502 Move AstCallback
  .pyenchant_pylint_custom_dict.txt
  pylint/typing.py
  pylint/utils/ast_walker.py
Labels: Maintenance

#6500 Change default values of ``ignore-imports`` and ``ignore-signatures``
  ChangeLog
  doc/whatsnew/2.14.rst
  pylint/checkers/similar.py
  tests/checkers/unittest_similar.py
Labels: topic-configuration

#6504 Do not report useless-suppression on duplicate-code
  pylint/constants.py
  tests/regrtest_data/duplicate_code/useless_suppression/__init__.py
  tests/regrtest_data/duplicate_code/useless_suppression/file_one.py
  tests/regrtest_data/duplicate_code/useless_suppression/file_two.py
  tests/test_similar.py
Labels: Bug 🪳

#6335 Regression tests for setup.cfg's options using the wrong section failing silently
  tests/config/functional/setup_cfg/issue_4272/option_in_wrong_section.cfg
  tests/config/functional/setup_cfg/issue_4272/option_in_wrong_section.result.json
Labels: Bug 🪳, topic-configuration

#6499 Allow not yet published extensions links in ``linkcheck``
  doc/conf.py
Labels: Documentation 📖, Maintenance

#6121 Activate the ``duplicate-code`` checker
  pylint/config/callback_actions.py
  pylint/config/option_manager_mixin.py
  pylint/graph.py
  pylint/pyreverse/mermaidjs_printer.py
  pylint/testutils/unittest_linter.py
  pylintrc
  tests/test_similar.py
Labels: Maintenance

#6356 Fix the loading of unrelated tools options
  pylint/config/config_file_parser.py
  tests/config/functional/setup_cfg/deprecate_master/setup.cfg
  tests/config/functional/setup_cfg/deprecate_master/setup.result.json
  tests/config/functional/setup_cfg/do_not_read_other_tools_configuration/setup.2.out
  tests/config/functional/setup_cfg/do_not_read_other_tools_configuration/setup.cfg
  tests/config/functional/setup_cfg/do_not_read_other_tools_configuration/setup.result.json
  tests/config/functional/setup_cfg/identical_name_in_flake8/setup.cfg
  tests/config/functional/setup_cfg/identical_name_in_flake8/setup.result.json
  tests/config/test_functional_config_loading.py
Labels: Bug 🪳

#6507 Refactor of ``config.__init__.py``
  pylint/config/__init__.py
  pylint/utils/linterstats.py
Labels: Maintenance

#6506 Exit gracefully for unrecognized command line options
  pylint/config/config_initialization.py
  tests/config/test_config.py
Labels: Maintenance

#6510 Disable duplicate-code warnings
  tests/config/test_find_default_config_files.py
Labels: Maintenance

#6511 Fix invalid-enum-extension with IntFlag
  pylint/checkers/classes/class_checker.py
  tests/functional/i/invalid/invalid_enum_extension.py
Labels: False Positive 🦟

#6468 Create ``lint/caching.py``
  pylint/config/__init__.py
  pylint/lint/caching.py
  tests/lint/test_caching.py
  tests/lint/unittest_expand_modules.py
  tests/test_deprecation.py
Labels: Maintenance

#6517 Fix behavior of empty `--confidence` option
  pylint/config/argument.py
  tests/config/test_config.py
Labels: Bug 🪳, Unreleased

#6516 Fix pylint.config's caching deprecation
  pylint/lint/__init__.py
  pylint/lint/pylinter.py
Labels: Maintenance

#5929 spellcheck will skip the rule names of mypy inline directives
  ChangeLog
  doc/whatsnew/2.14.rst
  pylint/checkers/spelling.py
  tests/checkers/unittest_spelling.py
Labels: Enhancement ✨

#6520 Remove never run test
  tests/checkers/unittest_spelling.py
Labels: Maintenance

#6521 Add regression test of invalid-sequence-index false-positive
  tests/functional/r/regression/regression_4083_sequence_index.py
Labels: Bug 🪳

#6524 Change confidence for `no-self-use` to `INFERENCE`
  pylint/extensions/no_self_use.py
  tests/functional/ext/no_self_use/no_self_use.txt
Labels: Maintenance

#6526 Fix saving of persistent data files on different drives
  ChangeLog
  doc/whatsnew/2.14.rst
  pylint/lint/caching.py
  tests/lint/test_caching.py
Labels: Bug 🪳, Windows 🪟

#6534 Correct link to VSCode IDE integration documentation
  doc/user_guide/ide-integration.rst
Labels: Documentation 📖

#6536 Don't emit unsubscriptable-object for string annotations
  ChangeLog
  doc/whatsnew/2.14.rst
  pylint/checkers/utils.py
  tests/functional/g/generic_alias/generic_alias_postponed_evaluation_py37.py
  tests/functional/g/generic_alias/generic_alias_postponed_evaluation_py37.txt
  tests/functional/g/generic_alias/generic_alias_typing.py
  tests/functional/g/generic_alias/generic_alias_typing.txt
  tests/functional/p/postponed_evaluation_pep585.py
  tests/functional/p/postponed_evaluation_pep585.txt
Labels: False Positive 🦟

#6537 Make the scope of ``PyLinter`` messages explicit
  pylint/lint/pylinter.py
Labels: Maintenance

#6541 Added dict-iter-missing-items message example
  doc/data/messages/d/dict-iter-missing-items/bad.py
  doc/data/messages/d/dict-iter-missing-items/good.py
Labels: Documentation 📖

#6532 Add an exception for `IndexError` inside `uninferable_final_decorator`
  ChangeLog
  doc/whatsnew/2.13.rst
  pylint/checkers/utils.py
  tests/functional/r/regression/regression_6531_crash_index_error.py
Labels: Bug 🪳, Needs Backport, Crash 💥

#6547 Add typing to `pylint.pyreverse.diagrams.py`
  pylint/pyreverse/diagrams.py
Labels: topic-pyreverse, topic-typing, Maintenance

#6544 Create ``_MessageStateHandler`` and move all private methods
  pylint/lint/message_state_handler.py
  pylint/lint/pylinter.py
Labels: Maintenance

#6545 Move all public methods to ``_MessageStateHandler``
  pylint/lint/message_state_handler.py
  pylint/lint/pylinter.py
Labels: Maintenance

#6546 Move ``process_tokens`` to ``_MessageStateHandler``
  pylint/lint/message_state_handler.py
  pylint/lint/pylinter.py
Labels: Maintenance

#6548 Revert "Do not append namespace packages to sys.path (#6405)"
  ChangeLog
  doc/whatsnew/2.14.rst
  pylint/lint/utils.py
  tests/lint/test_namespace_packages.py
  tests/lint/unittest_expand_modules.py
  tests/regrtest_data/namespace_import_self/else/__init__.py
  tests/regrtest_data/namespace_import_self/pylint/__init__.py
Labels: Maintenance

#6540 Added try-except-raise message example
  doc/data/messages/t/try-except-raise/bad.py
  doc/data/messages/t/try-except-raise/details.rst
  doc/data/messages/t/try-except-raise/good.py
Labels: Documentation 📖

#6558 Pass ``msg_store`` and ``node`` to ``FileState``
  pylint/lint/parallel.py
  pylint/lint/pylinter.py
  pylint/utils/file_state.py
  tests/lint/unittest_lint.py
  tests/test_deprecation.py
Labels: Maintenance

#6560 Refactor ``_collect_block_lines``
  pylint/utils/file_state.py
Labels: Maintenance

#6553 Add regression test for #6538
  tests/lint/unittest_lint.py
Labels: tests

#6562 Added while-used message example
  doc/data/messages/w/while-used/bad.py
  doc/data/messages/w/while-used/good.py
  doc/data/messages/w/while-used/pylintrc
  doc/data/messages/w/while-used/related.rst
Labels: Documentation 📖

#6498 Add regression test for #6497
  ChangeLog
  doc/whatsnew/2.13.rst
  tests/functional/n/no/no_name_in_module.py
Labels: Needs Backport, Regression, Requires Astroid Update

#6556 Fix disabling of ``bad-option-value``
  ChangeLog
  doc/whatsnew/2.14.rst
  pylint/lint/pylinter.py
  pylint/utils/file_state.py
  tests/functional/b/bad_option_value_disable.py
  tests/functional/b/bad_option_value_disable.txt
  tests/lint/unittest_lint.py
  tests/regrtest_data/long_test_file.py
  tests/test_deprecation.py
Labels: Bug 🪳, Enhancement ✨, topic-configuration, T: Pragma's

#6564 Make sure that --generate-toml-config generates a valid file
  pylint/config/arguments_manager.py
  tests/test_self.py
Labels: Bug 🪳

#6566 Make sure that --generate-rcfile generates a valid file
  pylint/utils/utils.py
  tests/test_self.py
Labels: Bug 🪳

#6529 Upgrade configuration example and add toml example
  examples/pylintrc
  examples/pyproject.toml
  tbump.toml
Labels: Blocker 🙅, Documentation 📖, Maintenance, Beta-Blocker 🙅🩸

#6527 Release branch 2.14 beta
  CONTRIBUTORS.txt
  ChangeLog
  doc/messages/messages_list.rst
  doc/whatsnew/2.14.rst
  examples/pyproject.toml
  pylint/__pkginfo__.py
  requirements_test.txt
  script/.contributors_aliases.json
  tbump.toml
Labels: Maintenance

#6573 Update all ``TODO: 2.14``
  pylint/checkers/classes/special_methods_checker.py
  pylint/checkers/utils.py
  pylint/config/callback_actions.py
Labels: Maintenance

#6572 Use the standard config parser instead a new one in functional tests
  .pyenchant_pylint_custom_dict.txt
  pylint/testutils/functional/test_file.py
  pylint/testutils/lint_module_test.py
Labels: Enhancement ✨, topic-configuration, tests

#6575 Better assert message for documentation tests
  doc/test_messages_documentation.py
Labels: Minor 💅, Maintenance

#6579 Fix a crash in `unnecessary-dict-index-lookup` when subscripting an attribute
  ChangeLog
  doc/whatsnew/2.13.rst
  pylint/checkers/refactoring/refactoring_checker.py
  tests/functional/u/unnecessary/unnecessary_dict_index_lookup.py
Labels: Crash 💥

#6581 [--long-help] Remove redundant default description in message
  pylint/checkers/exceptions.py
Labels: Minor 💅, Documentation 📖

#6549 Finish typing of `pylint.pyreverse.utils`
  pylint/pyreverse/utils.py
Labels: topic-pyreverse, topic-typing, Maintenance

#6584 Add `unnecessary-pass` documentation examples
  doc/data/messages/u/unnecessary-pass/bad.py
  doc/data/messages/u/unnecessary-pass/good.py
Labels: Documentation 📖

#6585 Add `yield-outside-function` documentation examples
  doc/data/messages/y/yield-outside-function/bad.py
  doc/data/messages/y/yield-outside-function/good.py
Labels: Documentation 📖

#6576 [raise-missing-from] Clearer message and example in the documentation
  doc/data/messages/r/raise-missing-from/bad.py
  doc/data/messages/r/raise-missing-from/good.py
  doc/data/messages/r/raise-missing-from/related.rst
  pylint/checkers/exceptions.py
  tests/functional/r/raise_missing_from.py
  tests/functional/r/raise_missing_from.txt
Labels: Documentation 📖

#6588 Replace `pip install -e` with `pip install -r requirements_test_min.txt`
  doc/development_guide/testing.rst
Labels: Documentation 📖

#6583 Add documentation for `using-final-decorator-in-unsupported-version`
  doc/data/messages/u/using-final-decorator-in-unsupported-version/bad.py
  doc/data/messages/u/using-final-decorator-in-unsupported-version/details.rst
  doc/data/messages/u/using-final-decorator-in-unsupported-version/good.py
  doc/data/messages/u/using-final-decorator-in-unsupported-version/related.rst
Labels: Documentation 📖

#6591 Added using-constant-test message example
  doc/data/messages/u/using-constant-test/bad.py
  doc/data/messages/u/using-constant-test/good.py
Labels: Documentation 📖

#6598 Write the exception message to stderr in `ASTWalker.walk`
  ChangeLog
  doc/whatsnew/2.14.rst
  pylint/utils/ast_walker.py
Labels: Bug 🪳

#6595 Raise use_a_generator for `sum()`, `max()`, `min()`
  ChangeLog
  pylint/checkers/refactoring/refactoring_checker.py
  tests/functional/u/use/use_a_generator.py
  tests/functional/u/use/use_a_generator.txt
Labels: Enhancement ✨

#6528 Respect ignore configuration options when --recursive=y.
  ChangeLog
  pylint/lint/expand_modules.py
  pylint/lint/pylinter.py
  tests/lint/unittest_lint.py
  tests/regrtest_data/directory/ignored_subdirectory/failing.py
  tests/test_self.py
Labels: Bug 🪳, Needs Backport

#6590 Added use-a-generator message example
  doc/data/messages/u/use-a-generator/bad.py
  doc/data/messages/u/use-a-generator/details.rst
  doc/data/messages/u/use-a-generator/good.py
  doc/data/messages/u/use-a-generator/related.rst
Labels: Documentation 📖

#6600 Change wording of use a generator message for sum/max/min
  ChangeLog
  doc/data/messages/c/consider-using-generator/bad.py
  doc/data/messages/c/consider-using-generator/details.rst
  doc/data/messages/c/consider-using-generator/good.py
  doc/data/messages/c/consider-using-generator/related.rst
  doc/whatsnew/2.14.rst
  pylint/checkers/refactoring/refactoring_checker.py
  tests/functional/c/consider/consider_using_generator.py
  tests/functional/c/consider/consider_using_generator.txt
  tests/functional/u/use/use_a_generator.py
  tests/functional/u/use/use_a_generator.txt
Labels: Enhancement ✨, Documentation 📖

#6601 Add ``macOS`` to the test environments
  .github/workflows/tests.yaml
Labels: Maintenance

#6604 Fix a crash in `unnecessary-list-index-lookup` when incorrectly using `enumerate()`
  ChangeLog
  doc/whatsnew/2.13.rst
  pylint/checkers/refactoring/refactoring_checker.py
  tests/functional/u/unnecessary/unnecessary_list_index_lookup.py
Labels: Needs Backport, Crash 💥

#6602 Fix false positive for `undefined-loop-variable` with `enumerate()`
  ChangeLog
  doc/whatsnew/2.13.rst
  pylint/checkers/variables.py
  tests/functional/u/undefined/undefined_loop_variable.py
Labels: Bug 🪳, Needs Backport, False Positive 🦟

#6605 Remove release note for unreleased crash fix
  ChangeLog
  doc/whatsnew/2.13.rst
Labels: Maintenance

#6606 Update ranges for error messages
  ChangeLog
  doc/whatsnew/2.14.rst
  pylint/checkers/base/basic_checker.py
  tests/functional/ext/docparams/raise/missing_raises_doc_Google.txt
  tests/functional/m/missing/missing_parentheses_for_call_in_test.txt
  tests/functional/u/using_constant_test.txt
Labels: Enhancement ✨, Error range

#6608 Fix `no-member` in type annotations with future import
  ChangeLog
  doc/whatsnew/2.14.rst
  pylint/checkers/typecheck.py
  tests/functional/g/generated_members.py
  tests/functional/g/generated_members.txt
Labels: False Positive 🦟

#6607 Remove `utils.subscriptable_with_postponed_evaluation_enabled`
  ChangeLog
  doc/whatsnew/2.14.rst
  pylint/checkers/utils.py
Labels: Maintenance

#6614 Add typing to `pylint.pyreverse.inspector`
  pylint/pyreverse/inspector.py
  pylint/pyreverse/writer.py
Labels: topic-pyreverse, topic-typing, Maintenance

#6615 Create constant for default ignore list
  pylint/constants.py
  pylint/lint/base_options.py
  pylint/pyreverse/inspector.py
  pylint/pyreverse/main.py
Labels: Maintenance

#6616 Pin coverage to 6.3.3
  requirements_test.txt
Labels: dependency, python 3.11

#6613 [Doc] Create a contact section and cleanup the introduction
  .github/workflows/checks.yaml
  doc/backlinks.rst
  doc/conf.py
  doc/contact.rst
  doc/development_guide/contribute.rst
  doc/faq.rst
  doc/index.rst
  doc/intro.rst
  doc/requirements.txt
  doc/support.rst
Labels: Documentation 📖

#6611 Suppress useless-super-delegation on __hash__ in classes with __eq__
  ChangeLog
  doc/whatsnew/2.14.rst
  pylint/checkers/classes/class_checker.py
  tests/functional/u/useless/useless_super_delegation.py
  tests/functional/u/useless/useless_super_delegation.txt
Labels: False Positive 🦟

#6618 Added example for invalid-slots-object message
  doc/data/messages/i/invalid-slots-object/bad.py
  doc/data/messages/i/invalid-slots-object/good.py
  doc/data/messages/i/invalid-slots-object/related.rst
Labels: Documentation 📖

#6619 Added logging-not-lazy message example
  doc/data/messages/l/logging-not-lazy/bad.py
  doc/data/messages/l/logging-not-lazy/details.rst
  doc/data/messages/l/logging-not-lazy/good.py
  doc/data/messages/l/logging-not-lazy/related.rst
Labels: Documentation 📖

#6620 Added logging-too-few-args message example
  doc/data/messages/l/logging-too-few-args/bad.py
  doc/data/messages/l/logging-too-few-args/good.py
Labels: Documentation 📖

#6621 Added logging-too-many-args message example
  doc/data/messages/l/logging-too-many-args/bad.py
  doc/data/messages/l/logging-too-many-args/good.py
Labels: Documentation 📖

#6629 Add documentation examples for `consider-using-enumerate`.
  doc/data/messages/c/consider-using-enumerate/bad.py
  doc/data/messages/c/consider-using-enumerate/good.py
Labels: Documentation 📖

#6630 Add documentation examples for `consider-using-get`.
  doc/data/messages/c/consider-using-get/bad.py
  doc/data/messages/c/consider-using-get/good.py
Labels: Documentation 📖

#6626 Refactors in preparation of ``pylint-config``
  .pyenchant_pylint_custom_dict.txt
  pylint/config/arguments_manager.py
  pylint/config/callback_actions.py
  pylint/config/config_initialization.py
  pylint/extensions/comparetozero.py
  pylint/lint/run.py
Labels: Maintenance

#6617 Run linking and diadef handling with patched `sys.path`
  pylint/pyreverse/main.py
  pylint/testutils/pyreverse.py
  tests/testutils/pyreverse_data/_not_a_functest.py
  tests/testutils/pyreverse_data/functest_with_options.py
  tests/testutils/pyreverse_data/functest_with_options.rc
  tests/testutils/pyreverse_data/functest_without_options.py
  tests/testutils/test_pyreverse_testutils.py
Labels: topic-pyreverse, Maintenance

#6635 Add documentation examples for `consider-using-in`.
  doc/data/messages/c/consider-using-in/bad.py
  doc/data/messages/c/consider-using-in/good.py
Labels: Documentation 📖

#6637 Add documentation examples for `consider-using-join`.
  doc/data/messages/c/consider-using-join/bad.py
  doc/data/messages/c/consider-using-join/good.py
Labels: Documentation 📖

#6640 [doc] Fix the short version in the sphinx configuration
  doc/conf.py
Labels: Documentation 📖, Maintenance

#6641 Burst additional command in two files
  doc/conf.py
  doc/index.rst
  doc/pyreverse.rst
  doc/symilar.rst
Labels: Documentation 📖

#6649 Run ``linkcheck`` in quiet mode
  doc/Makefile
  doc/exts/pylint_messages.py
  doc/make.bat
Labels: Documentation 📖, Maintenance

#6647 Change names of documentation files
  doc/exts/pylint_messages.py
  doc/user_guide/index.rst
  doc/user_guide/messages/messages_introduction.rst
  doc/user_guide/messages/messages_list.rst
Labels: Documentation 📖

#6642 [doc] Fix the link to block disable in useless-import-alias related
  doc/data/messages/u/useless-import-alias/related.rst
  doc/user_guide/messages/message_control.rst
Labels: Documentation 📖

#6654 Fix ``unexpected-special-method-signature`` false positive
  ChangeLog
  doc/whatsnew/2.14.rst
  pylint/checkers/utils.py
  tests/functional/u/unexpected_special_method_signature.py
  tests/functional/u/unexpected_special_method_signature.txt
Labels: False Positive 🦟

#6658 Burst run's documentation between user guide and dev guide, merge FAQ's run questions in the user guide
  doc/development_guide/api/epylint.rst
  doc/development_guide/api/index.rst
  doc/development_guide/api/pylint.rst
  doc/development_guide/index.rst
  doc/faq.rst
  doc/user_guide/run.rst
Labels: Documentation 📖

#6659 Move c-extensions to user guides where it belong
  doc/conf.py
  doc/technical_reference/index.rst
  doc/technical_reference/startup.rst
  doc/user_guide/c_extensions.rst
  doc/user_guide/index.rst
Labels: Documentation 📖

#6660 Documentation: `consider-using-max-builtin` & `consider-using-min-builtin`
  doc/data/messages/c/consider-using-max-builtin/bad.py
  doc/data/messages/c/consider-using-max-builtin/good.py
  doc/data/messages/c/consider-using-min-builtin/bad.py
  doc/data/messages/c/consider-using-min-builtin/good.py
  doc/user_guide/index.rst
Labels: Documentation 📖

#6653 Retry user input if it is not correct
  pylint/config/_pylint_config/utils.py
  tests/config/pylint_config/test_pylint_config_generate.py
  tests/config/pylint_config/test_pylint_config_utils.py
Labels: Enhancement ✨, pylint-config

#6662 Allow specifying an output file when generating a configuration file
  pylint/config/_pylint_config/generate_command.py
  pylint/config/_pylint_config/utils.py
  tests/config/pylint_config/test_pylint_config_generate.py
Labels: Enhancement ✨, pylint-config

#6650 [doc] Activate the nitpicky option in sphinx build
  doc/Makefile
  doc/development_guide/contribute.rst
  doc/how_tos/custom_checkers.rst
  doc/make.bat
  doc/technical_reference/checkers.rst
  doc/technical_reference/startup.rst
  doc/whatsnew/2.0.rst
  doc/whatsnew/2.2.rst
Labels: Documentation 📖, Maintenance

#6669 [doc] Move the naming-style documentation to invalid-name doc
  doc/conf.py
  doc/data/messages/i/invalid-name/bad.py
  doc/data/messages/i/invalid-name/details.rst
  doc/data/messages/i/invalid-name/good.py
  doc/user_guide/configuration/.gitkeep
  doc/user_guide/options.rst
Labels: Documentation 📖

#6671 Update ``pydocstringformatter`` to ``0.6.0``
  .pre-commit-config.yaml
  doc/exts/pylint_messages.py
  pylint/checkers/__init__.py
  pylint/checkers/classes/class_checker.py
  pylint/checkers/refactoring/refactoring_checker.py
  pylint/checkers/spelling.py
  pylint/checkers/utils.py
  pylint/epylint.py
  pylint/extensions/_check_docs_utils.py
  pylint/extensions/broad_try_clause.py
  pylint/extensions/no_self_use.py
Labels: Maintenance

#6675 Enable line-wrapping from ``pydocstringformatter``
  .pre-commit-config.yaml
  pylint/checkers/base/name_checker/naming_style.py
  pylint/checkers/refactoring/implicit_booleaness_checker.py
  pylint/checkers/refactoring/refactoring_checker.py
  pylint/checkers/similar.py
  pylint/checkers/variables.py
  pylint/extensions/for_any_all.py
  pylint/extensions/private_import.py
  pylint/graph.py
Labels: Maintenance

#6589 Reorganize the documentation table of content
  .gitignore
  doc/conf.py
  doc/development_guide/contributor_guide/contribute.rst
  doc/development_guide/contributor_guide/index.rst
  doc/development_guide/contributor_guide/profiling.rst
  doc/development_guide/contributor_guide/release.md
  doc/development_guide/contributor_guide/tests/index.rst
  doc/development_guide/contributor_guide/tests/install.rst
  doc/development_guide/contributor_guide/tests/launching_test.rst
  doc/development_guide/contributor_guide/tests/writing_test.rst
  doc/development_guide/how_tos/custom_checkers.rst
  doc/development_guide/how_tos/index.rst
  doc/development_guide/how_tos/plugins.rst
  doc/development_guide/how_tos/transform_plugins.rst
  doc/development_guide/index.rst
  doc/development_guide/technical_reference/checkers.rst
  doc/development_guide/technical_reference/index.rst
  doc/development_guide/technical_reference/startup.rst
  doc/exts/pylint_extensions.py
  doc/exts/pylint_features.py
  doc/exts/pylint_options.py
  doc/faq.rst
  doc/index.rst
  doc/requirements.txt
  doc/user_guide/checkers/index.rst
  doc/user_guide/configuration/index.rst
  doc/user_guide/ide_integration/ide-integration.rst
  doc/user_guide/index.rst
  doc/user_guide/installation/badge.rst
  doc/user_guide/installation/command_line_installation.rst
  doc/user_guide/installation/ide_integration/flymake-emacs.rst
  doc/user_guide/installation/ide_integration/index.rst
  doc/user_guide/installation/ide_integration/textmate.rst
  doc/user_guide/installation/index.rst
  doc/user_guide/installation/pre-commit-integration.rst
  doc/user_guide/options.rst
  doc/user_guide/usage/index.rst
  doc/user_guide/usage/output.rst
  doc/user_guide/usage/run.rst
Labels: Documentation 📖

#6679 Add documentation examples for `consider-using-dict-items`.
  doc/data/messages/c/consider-using-dict-items/bad.py
  doc/data/messages/c/consider-using-dict-items/good.py
Labels: Documentation 📖

#6680 [doc] Fix broken links following toc reorganization
  README.rst
  doc/conf.py
  doc/whatsnew/2.9.rst
Labels: Documentation 📖

#6684 Add typing to ``async`` and ``deprecated`` checkers
  pylint/checkers/async.py
  pylint/checkers/deprecated.py
Labels: topic-typing, Maintenance

#6687 Add typing to ``name_checker``
  pylint/checkers/base/name_checker/checker.py
  pylint/checkers/base/name_checker/naming_style.py
Labels: topic-typing, Maintenance

#6690 Add documentation examples for `line-too-long`.
  doc/data/messages/l/line-too-long/bad.py
  doc/data/messages/l/line-too-long/good.py
Labels: Documentation 📖

#6701 Added documentation examples for `useless-object-inheritance`.
  doc/data/messages/u/useless-object-inheritance/bad.py
  doc/data/messages/u/useless-object-inheritance/good.py
Labels: Documentation 📖

#6694 Add typing to ``comparison_checker``
  pylint/checkers/base/comparison_checker.py
Labels: topic-typing, Maintenance

#6706 Added documentation examples for `unnecessary-comprehension`.
  doc/data/messages/u/unnecessary-comprehension/bad.py
  doc/data/messages/u/unnecessary-comprehension/details.rst
  doc/data/messages/u/unnecessary-comprehension/good.py
Labels: Documentation 📖

#6705 Added documentation examples for `unnecessary-semicolon`
  doc/data/messages/u/unnecessary-semicolon/bad.py
  doc/data/messages/u/unnecessary-semicolon/details.rst
  doc/data/messages/u/unnecessary-semicolon/good.py
Labels: Documentation 📖

#6704 Added documentation examples for `unpacking-non-sequence`
  doc/data/messages/u/unpacking-non-sequence/bad.py
  doc/data/messages/u/unpacking-non-sequence/details.rst
  doc/data/messages/u/unpacking-non-sequence/good.py
Labels: Documentation 📖

#6710 Fix a crash in `unused-private-member` with chained private attributes
  ChangeLog
  doc/whatsnew/2.14.rst
  pylint/checkers/classes/class_checker.py
  tests/functional/u/unused/unused_private_member.py
  tests/functional/u/unused/unused_private_member.txt
Labels: Crash 💥

#6703 Cache and store primer packages via the default branch
  .github/workflows/primer_run_main.yaml
  .github/workflows/primer_run_pr.yaml
  .pylint_primer_tests/.gitkeep
  pylint/testutils/primer.py
  tests/primer/packages_to_prime.json
  tests/primer/primer_tool.py
Labels: primer

#6691 Allow disabling `bad-option-value` and `unrecognized-option` with `--disable=all`
  pylint/config/callback_actions.py
  pylint/config/config_initialization.py
  pylint/lint/message_state_handler.py
  pylint/lint/pylinter.py
Labels: C: Pragma's

#6712 Remove unnecessary base class and dead code in `pylint.pyreverse.utils`
  ChangeLog
  doc/whatsnew/2.14.rst
  pylint/pyreverse/utils.py
Labels: topic-pyreverse, Maintenance

#6715 Added documentation examples for `consider-merging-isinstance`.
  doc/data/messages/c/consider-merging-isinstance/bad.py
  doc/data/messages/c/consider-merging-isinstance/details.rst
  doc/data/messages/c/consider-merging-isinstance/good.py
Labels: Documentation 📖

#6717 Adding documentation examples for `not-an-iterable`.
  doc/data/messages/n/not-an-iterable/bad.py
  doc/data/messages/n/not-an-iterable/details.rst
  doc/data/messages/n/not-an-iterable/good.py
Labels: Documentation 📖

#6713 Refactor and deprecate resolving of interface implementations in `pyreverse`
  ChangeLog
  doc/whatsnew/2.14.rst
  pylint/pyreverse/inspector.py
  tests/pyreverse/test_inspector.py
Labels: topic-pyreverse, Maintenance

#6718 Added documentation examples for pointless statements
  doc/data/messages/p/pointless-statement/bad.py
  doc/data/messages/p/pointless-statement/details.rst
  doc/data/messages/p/pointless-statement/good.py
  doc/data/messages/p/pointless-string-statement/bad.py
  doc/data/messages/p/pointless-string-statement/details.rst
  doc/data/messages/p/pointless-string-statement/good.py
Labels: Documentation 📖

#6716 Added documentation examples for `trailing-comma-tuple`.
  doc/data/messages/t/trailing-comma-tuple/bad.py
  doc/data/messages/t/trailing-comma-tuple/details.rst
  doc/data/messages/t/trailing-comma-tuple/good.py
Labels: Documentation 📖

#6714 Run and upload primer over packages
  .github/workflows/primer_run_main.yaml
  .github/workflows/primer_run_pr.yaml
  tests/primer/packages_to_prime.json
  tests/primer/primer_tool.py
Labels: primer

#6725 Primer tool: remove duplicated directory paths
  tests/primer/primer_tool.py
Labels: Bug 🪳, primer

#6728 Move ``pylint_primer_tests`` into ``tests``
  .github/workflows/primer_run_main.yaml
  .github/workflows/primer_run_pr.yaml
  .gitignore
  pylint/testutils/primer.py
  tests/.pylint_primer_tests/.gitkeep
  tests/primer/primer_tool.py
  tests/primer/test_primer_external.py
Labels: primer

#6724 Use bleeding-edge `astroid` for primer comparisons
  .github/workflows/primer_run_main.yaml
  .github/workflows/primer_run_pr.yaml
Labels: Maintenance, primer

#6726 Clean-up the FAQ and remove out of date questions
  README.rst
  doc/exts/pylint_options.py
  doc/faq.rst
  doc/index.rst
  doc/short_text_contribute.rst
  doc/short_text_installation.rst
  doc/user_guide/configuration/all-options.rst
Labels: Documentation 📖

#6730 Small refactors to primer
  .github/workflows/primer_run_pr.yaml
  tests/primer/primer_tool.py
Labels: primer

#6723 Compare difference between primer runs and post comment
  .github/workflows/primer_comment.yaml
  tests/primer/packages_to_lint_batch_two.json
  tests/primer/primer_tool.py
Labels: Enhancement ✨, primer

#6727 Refactor to be able to document deleted message
  doc/exts/pylint_messages.py
Labels: Documentation 📖, Maintenance

#6731 Add concurrency to primer
  .github/workflows/primer_run_pr.yaml
Labels: primer

#6734 Add more packages to the new primer
  tests/primer/packages_to_lint_batch_one.json
  tests/primer/packages_to_lint_batch_two.json
  tests/primer/packages_to_prime.json
Labels: primer

#6720 Fix `pyreverse` type annotations for attributes using alternative union syntax
  doc/whatsnew/2/2.14/full.rst
  doc/whatsnew/2/2.14/summary.rst
  pylint/pyreverse/diagrams.py
  pylint/pyreverse/dot_printer.py
  pylint/pyreverse/utils.py
  tests/pyreverse/functional/class_diagrams/annotations/attributes_annotation.dot
  tests/pyreverse/functional/class_diagrams/annotations/attributes_annotation.mmd
  tests/pyreverse/functional/class_diagrams/annotations/attributes_annotation.puml
  tests/pyreverse/functional/class_diagrams/annotations/attributes_annotation.py
  tests/pyreverse/functional/class_diagrams/annotations/attributes_annotation.rc
Labels: Bug 🪳, topic-pyreverse

#6743 Added documentation examples for `not-callable`.
  doc/data/messages/n/not-callable/bad.py
  doc/data/messages/n/not-callable/details.rst
  doc/data/messages/n/not-callable/good.py
Labels: Documentation 📖

#6740 Added documentation examples for `no-name-in-module`.
  doc/data/messages/n/no-name-in-module/bad.py
  doc/data/messages/n/no-name-in-module/details.rst
  doc/data/messages/n/no-name-in-module/good.py
Labels: Documentation 📖

#6739 Added documentation examples for `invalid-all-format`.
  doc/data/messages/i/invalid-all-format/bad.py
  doc/data/messages/i/invalid-all-format/details.rst
  doc/data/messages/i/invalid-all-format/good.py
Labels: Documentation 📖

#6741 Added documentation examples for `no-method-argument`.
  doc/data/messages/n/no-method-argument/bad.py
  doc/data/messages/n/no-method-argument/details.rst
  doc/data/messages/n/no-method-argument/good.py
Labels: Documentation 📖

#6742 Added documentation examples for `not-in-loop`.
  doc/data/messages/n/not-in-loop/bad.py
  doc/data/messages/n/not-in-loop/details.rst
  doc/data/messages/n/not-in-loop/good.py
Labels: Documentation 📖

#6744 Put fatal messages at the top in the primer comment
  tests/primer/primer_tool.py
Labels: primer

#6747 Use `node-version` in `setup-node` action
  .github/workflows/primer_comment.yaml
Labels: primer

#6754 Add python version into the file name of output files of primer
  .github/workflows/primer_comment.yaml
  .github/workflows/primer_run_main.yaml
  .github/workflows/primer_run_pr.yaml
  tests/primer/primer_tool.py
Labels: primer

#6753 Move more packages to the new primer
  tests/primer/packages_to_lint_batch_one.json
  tests/primer/packages_to_lint_batch_two.json
  tests/primer/packages_to_prime.json
Labels: primer

#6746 Fail "new primer" runs on fatal errors, like "old primer"
  .github/workflows/primer_run_main.yaml
  .github/workflows/primer_run_pr.yaml
  tests/primer/primer_tool.py
  tests/profile/test_profile_against_externals.py
Labels: primer

#6757 Remove redundant second batch of old primer
  .github/workflows/primer-test.yaml
  doc/development_guide/contributor_guide/tests/launching_test.rst
  setup.cfg
  tests/conftest.py
  tests/primer/packages_to_lint_batch_two.json
  tests/primer/test_primer_external.py
Labels: Maintenance
