Repository pylint-dev/pylint, pull requests merged in 2022-10, with the labels that each got.

#7544 Prevent leaving pip install cache in Docker iamge
  Dockerfile
  doc/whatsnew/fragments/7544.other
Labels: Enhancement ✨

#7549 Check `` py-version`` for async ``unnecessary-dunder-call``
  doc/whatsnew/fragments/7529.false_positive
  pylint/checkers/dunder_methods.py
  tests/functional/u/unnecessary/unnecessary_dunder_call_async_py310.py
  tests/functional/u/unnecessary/unnecessary_dunder_call_async_py310.rc
  tests/functional/u/unnecessary/unnecessary_dunder_call_async_py310.txt
  tests/functional/u/unnecessary/unnecessary_dunder_call_async_py39.py
  tests/functional/u/unnecessary/unnecessary_dunder_call_async_py39.rc
Labels: Needs backport, False Positive 🦟

#7551 Fix handling of ``--`` as separator between positional args and flags
  doc/whatsnew/fragments/7003.bugfix
  pylint/config/config_initialization.py
  tests/config/test_config.py
Labels: Bug :beetle:, topic-command-line, Needs backport

#7554 Resolve deprecation warning in pyreverse test
  tests/pyreverse/test_utils.py
Labels: topic-pyreverse, Maintenance, Skip news :mute:

#7552 Remove xfail from passing tests
  tests/pyreverse/test_diadefs.py
Labels: Maintenance, Skip news :mute:

#7553 Raise ``syntax-error`` correctly on invalid encodings
  doc/whatsnew/fragments/7522.bugfix
  pylint/lint/pylinter.py
  tests/regrtest_data/invalid_encoding.py
  tests/test_self.py
Labels: Bug :beetle:, Needs backport

#7521 fix: test_logger_rcfile: replace only the last .py token in the string
  tests/config/test_argparse_config.py
Labels: Maintenance, Skip news :mute:

#7576 Add documentation examples for invalid-index-returned, invalid-bytes-returned, invalid-bool-returned, invalid-hash-returned
  doc/data/messages/i/invalid-bool-returned/bad.py
  doc/data/messages/i/invalid-bool-returned/details.rst
  doc/data/messages/i/invalid-bool-returned/good.py
  doc/data/messages/i/invalid-bytes-returned/bad.py
  doc/data/messages/i/invalid-bytes-returned/details.rst
  doc/data/messages/i/invalid-bytes-returned/good.py
  doc/data/messages/i/invalid-hash-returned/bad.py
  doc/data/messages/i/invalid-hash-returned/details.rst
  doc/data/messages/i/invalid-hash-returned/good.py
  doc/data/messages/i/invalid-index-returned/bad.py
  doc/data/messages/i/invalid-index-returned/details.rst
  doc/data/messages/i/invalid-index-returned/good.py
Labels: Documentation :green_book:, Skip news :mute:

#7573 Add docs for consider-using-assignment-expr and confusing-with-statement
  doc/data/messages/c/confusing-with-statement/bad.py
  doc/data/messages/c/confusing-with-statement/details.rst
  doc/data/messages/c/confusing-with-statement/good.py
  doc/data/messages/c/consider-using-assignment-expr/bad.py
  doc/data/messages/c/consider-using-assignment-expr/details.rst
  doc/data/messages/c/consider-using-assignment-expr/good.py
  doc/data/messages/c/consider-using-assignment-expr/pylintrc
Labels: Documentation :green_book:, Skip news :mute:

#7588 Add "breaking change" and "user action" fragment types
  .github/PULL_REQUEST_TEMPLATE.md
  doc/development_guide/contributor_guide/contribute.rst
  towncrier.toml
Labels: Documentation :green_book:, Skip news :mute:

#7587 Make primer use ``3.10``
  .github/workflows/primer_comment.yaml
  .github/workflows/primer_run_main.yaml
  .github/workflows/primer_run_pr.yaml
Labels: primer, Skip news :mute:

#7600 Merge maintenance 2.15.x following 2.15.4 release
  .github/workflows/changelog.yml
  .github/workflows/checks.yaml
  .github/workflows/primer-test.yaml
  .github/workflows/primer_comment.yaml
  .github/workflows/primer_run_main.yaml
  .github/workflows/primer_run_pr.yaml
  .github/workflows/tests.yaml
  CONTRIBUTORS.txt
  doc/user_guide/checkers/features.rst
  doc/whatsnew/2/2.15/index.rst
  pyproject.toml
  requirements_test_min.txt
  script/.contributors_aliases.json
Labels: Maintenance, Skip news :mute:

#7606 Add docs for various `invalid-*` messages
  doc/data/messages/i/invalid-class-object/bad.py
  doc/data/messages/i/invalid-class-object/details.rst
  doc/data/messages/i/invalid-class-object/good.py
  doc/data/messages/i/invalid-format-returned/bad.py
  doc/data/messages/i/invalid-format-returned/details.rst
  doc/data/messages/i/invalid-format-returned/good.py
  doc/data/messages/i/invalid-getnewargs-ex-returned/bad.py
  doc/data/messages/i/invalid-getnewargs-ex-returned/details.rst
  doc/data/messages/i/invalid-getnewargs-ex-returned/good.py
  doc/data/messages/i/invalid-getnewargs-returned/bad.py
  doc/data/messages/i/invalid-getnewargs-returned/details.rst
  doc/data/messages/i/invalid-getnewargs-returned/good.py
  doc/data/messages/i/invalid-length-hint-returned/bad.py
  doc/data/messages/i/invalid-length-hint-returned/details.rst
  doc/data/messages/i/invalid-length-hint-returned/good.py
Labels: Documentation :green_book:, Skip news :mute:

#7608 Add docs examples for invalid-* and isinstance-*
  doc/data/messages/i/invalid-metaclass/bad.py
  doc/data/messages/i/invalid-metaclass/details.rst
  doc/data/messages/i/invalid-metaclass/good.py
  doc/data/messages/i/invalid-repr-returned/bad.py
  doc/data/messages/i/invalid-repr-returned/details.rst
  doc/data/messages/i/invalid-repr-returned/good.py
  doc/data/messages/i/invalid-str-returned/bad.py
  doc/data/messages/i/invalid-str-returned/details.rst
  doc/data/messages/i/invalid-str-returned/good.py
  doc/data/messages/i/isinstance-second-argument-not-valid-type/bad.py
  doc/data/messages/i/isinstance-second-argument-not-valid-type/details.rst
  doc/data/messages/i/isinstance-second-argument-not-valid-type/good.py
Labels: Documentation :green_book:, Skip news :mute:

#7618 Replace deprecated set-output commands [ci]
  .github/workflows/changelog.yml
  .github/workflows/checks.yaml
  .github/workflows/primer-test.yaml
  .github/workflows/primer_run_main.yaml
  .github/workflows/primer_run_pr.yaml
  .github/workflows/tests.yaml
Labels: Maintenance, Skip news :mute:

#7627 Fix a false positive for `simplify-boolean-expression` when multiple values inferred
  doc/whatsnew/fragments/7626.false_positive
  doc/whatsnew/fragments/7626.other
  pylint/checkers/refactoring/refactoring_checker.py
  pylint/checkers/utils.py
  tests/functional/t/ternary.py
  tests/functional/t/ternary.txt
Labels: Needs backport, False Positive 🦟

#7628 Move `consider-using-augmented-assign` to `CodeStyle` extension
  doc/data/messages/c/consider-using-augmented-assign/pylintrc
  doc/whatsnew/fragments/3391.extension
  doc/whatsnew/fragments/3391.new_check
  pylint/checkers/refactoring/recommendation_checker.py
  pylint/extensions/code_style.py
  tests/functional/ext/code_style/cs_consider_using_augmented_assign.py
  tests/functional/ext/code_style/cs_consider_using_augmented_assign.rc
  tests/functional/ext/code_style/cs_consider_using_augmented_assign.txt
  tests/functional/ext/code_style/cs_default.py
  tests/functional/ext/code_style/cs_default.rc
  tests/functional/n/no/no_member_augassign.py
  tests/functional/u/undefined/undefined_variable_py38.py
  tests/functional/u/use/use_maxsplit_arg.py
  tests/functional/u/used/used_before_assignment_conditional.py
  tests/functional/u/used/used_before_assignment_conditional.txt
  tests/functional/u/used/used_before_assignment_nonlocal.py
Labels: Blocker 🙅, Skip news :mute:

#7649 Upgrade astroid to 2.12.12
  .github/workflows/changelog.yml
  .github/workflows/checks.yaml
  .github/workflows/primer-test.yaml
  .github/workflows/primer_comment.yaml
  .github/workflows/primer_run_main.yaml
  .github/workflows/primer_run_pr.yaml
  .github/workflows/tests.yaml
  pyproject.toml
  requirements_test_min.txt
Labels: Needs backport, Maintenance, Skip news :mute:

#7652 Fix windows cache key [ci]
  .github/workflows/tests.yaml
Labels: Maintenance, Skip news :mute:

#7640 Swap plugin cache to pickle-able values when done
  doc/whatsnew/fragments/7635.bugfix
  pylint/lint/pylinter.py
  script/.contributors_aliases.json
  tests/test_check_parallel.py
Labels: Needs backport, Crash 💥, topic-multiprocessing, macOS

#7650 Remove __index__ from unnecessary-dunder-call check
  doc/whatsnew/fragments/6795.bugfix
  pylint/checkers/dunder_methods.py
  tests/functional/u/unnecessary/unnecessary_dunder_call.py
Labels: Needs backport, False Positive 🦟

#7656 Use relative paths in `create_contributor_list.py`
  script/create_contributor_list.py
Labels: Needs backport, Maintenance, Skip news :mute:

#7655 Sort `--generate-rcfile` ouput
  doc/whatsnew/fragments/7655.other
  examples/pylintrc
  pylint/config/arguments_manager.py
Labels: Enhancement ✨, Needs backport

#7660 Release 2.15.5
  .github/workflows/changelog.yml
  .github/workflows/checks.yaml
  .github/workflows/primer-test.yaml
  .github/workflows/primer_comment.yaml
  .github/workflows/primer_run_main.yaml
  .github/workflows/primer_run_pr.yaml
  .github/workflows/tests.yaml
  CONTRIBUTORS.txt
  doc/whatsnew/2/2.15/index.rst
  examples/pylintrc
  pylint/__pkginfo__.py
  pylint/checkers/dunder_methods.py
  pylint/checkers/refactoring/refactoring_checker.py
  pylint/checkers/typecheck.py
  pylint/checkers/utils.py
  pylint/config/arguments_manager.py
  pylint/lint/pylinter.py
  pyproject.toml
  requirements_test_min.txt
  script/.contributors_aliases.json
  script/create_contributor_list.py
  tbump.toml
  tests/functional/r/regression_02/regression_no_member_7631.py
  tests/functional/t/ternary.py
  tests/functional/t/ternary.txt
  tests/functional/u/unnecessary/unnecessary_dunder_call.py
  tests/test_check_parallel.py
Labels: Maintenance, Skip news :mute:

#7662 Merge maintenance 2.15.x following the 2.15.5 release
  CONTRIBUTORS.txt
  doc/whatsnew/2/2.15/index.rst
  script/.contributors_aliases.json
Labels: Maintenance, Skip news :mute:

#7659 Add new `feature` category for changelog entries
  .github/PULL_REQUEST_TEMPLATE.md
  doc/development_guide/contributor_guide/contribute.rst
  towncrier.toml
Labels: Maintenance, Skip news :mute:

#7526 add `magic-number` checker for comparison with literals
  doc/data/messages/m/magic-value/bad.py
  doc/data/messages/m/magic-value/good.py
  doc/data/messages/m/magic-value/pylintrc
  doc/whatsnew/fragments/7281.new_check
  pylint/checkers/base/comparison_checker.py
  pylint/checkers/utils.py
  pylint/extensions/magic_value.py
  tests/functional/ext/magic_value_comparison/magic_value_comparison.py
  tests/functional/ext/magic_value_comparison/magic_value_comparison.rc
  tests/functional/ext/magic_value_comparison/magic_value_comparison.txt
  tests/message/unittest_message_id_store.py
Labels: Enhancement ✨

#7664 Add additional stdlib deprecations
  pylint/checkers/imports.py
  pylint/checkers/stdlib.py
Labels: Maintenance, Skip news :mute:

#7665 Fix showing DeprecationWarnings for functional tests
  tests/test_functional.py
Labels: Maintenance, Skip news :mute:

#7666 Confirm changes before tbump commit
  tbump.toml
Labels: Needs backport, Maintenance, Skip news :mute:

#7663 fix astroid-error for parsing module encoding
  doc/whatsnew/fragments/7661.bugfix
  pylint/checkers/unicode.py
  tests/regrtest_data/encoding/bad_missing_num.py
  tests/regrtest_data/encoding/bad_wrong_num.py
  tests/regrtest_data/encoding/good.py
  tests/test_self.py
Labels: Needs backport, Crash 💥

#7602 Make the order of functional tests deterministic
  pylint/testutils/functional/find_functional_tests.py
Labels: Bug :beetle:, Skip news :mute:

#7629 Add `default_enabled` option to optional message dict
  doc/exts/pylint_messages.py
  doc/whatsnew/fragments/7629.other
  pylint/extensions/code_style.py
  pylint/lint/pylinter.py
  pylint/message/message_definition.py
  pylint/typing.py
Labels: Enhancement ✨

#7674 Pin pytest to resolve issue with pytest-benchmark
  requirements_test_min.txt
Labels: Maintenance, Skip news :mute:

#7671 Run tests with Python 3.11.0
  .github/workflows/changelog.yml
  .github/workflows/checks.yaml
  .github/workflows/primer-test.yaml
  .github/workflows/release.yml
  .github/workflows/tests.yaml
Labels: Maintenance, Skip news :mute:

#7673 [github action] Follow the principle of least privileges
  .github/workflows/changelog.yml
  .github/workflows/checks.yaml
  .github/workflows/codeql-analysis.yml
  .github/workflows/primer-test.yaml
  .github/workflows/primer_run_main.yaml
  .github/workflows/primer_run_pr.yaml
  .github/workflows/release.yml
  .github/workflows/tests.yaml
Labels: Maintenance, Skip news :mute:

#7675 Update pytest and pytest-benchmark following the 7.2.0 release
  requirements_test_min.txt
Labels: Needs backport, dependency, Maintenance, Skip news :mute:

#7676 Add PyPI deployment environment [ci]
  .github/workflows/release.yml
Labels: Needs backport, Maintenance, Skip news :mute:

#7683 Add the `coverage` package to the primer suite.
  tests/primer/packages_to_prime.json
Labels: Maintenance, primer, Skip news :mute:

#7687 Replace flake8 mirror with upstream repository
  README.rst
Labels: Documentation :green_book:, Skip news :mute:

#7621 Fix a false negative for ``unused-import``
  doc/whatsnew/fragments/4150.false_negative
  pylint/checkers/variables.py
  tests/regrtest_data/imported_module_in_typehint/module_a.py
  tests/regrtest_data/imported_module_in_typehint/module_b.py
  tests/test_self.py
Labels: Bug :beetle:, Checkers, False Negative 🦋

#7612 `check_newsfragments`: Improve output on Windows machines
  script/check_newsfragments.py
Labels: Blocked 🚧, Maintenance, Skip news :mute:

#7642 Add `bad-dunder-name` checker
  doc/data/messages/b/bad-dunder-name/bad.py
  doc/data/messages/b/bad-dunder-name/good.py
  doc/data/messages/b/bad-dunder-name/pylintrc
  doc/whatsnew/fragments/3038.new_check
  pylint/checkers/dunder_methods.py
  pylint/constants.py
  pylint/extensions/dunder.py
  tests/functional/ext/bad_dunder/bad_dunder_name.py
  tests/functional/ext/bad_dunder/bad_dunder_name.rc
  tests/functional/ext/bad_dunder/bad_dunder_name.txt
Labels: Enhancement ✨

#7692 Add `py` to requirements
  requirements_test_min.txt
Labels: Needs backport, Maintenance, Skip news :mute:

#7620 fix: reporters receive copy of message
  doc/whatsnew/fragments/7214.bugfix
  pylint/reporters/multi_reporter.py
  tests/reporters/unittest_reporting.py
Labels: Bug :beetle:, Needs review 🔍, Needs backport

#7575 @singledispatch and @singledispatchmethod checks for methods and functions
  .pyenchant_pylint_custom_dict.txt
  doc/data/messages/s/singledispatch-method/bad.py
  doc/data/messages/s/singledispatch-method/details.rst
  doc/data/messages/s/singledispatch-method/good.py
  doc/data/messages/s/singledispatchmethod-function/bad.py
  doc/data/messages/s/singledispatchmethod-function/details.rst
  doc/data/messages/s/singledispatchmethod-function/good.py
  doc/user_guide/checkers/features.rst
  doc/user_guide/messages/messages_overview.rst
  doc/whatsnew/fragments/6917.new_check
  pylint/checkers/stdlib.py
  pylint/checkers/utils.py
  tests/functional/s/singledispatch_method.txt
  tests/functional/s/singledispatch_method_py37.py
  tests/functional/s/singledispatch_method_py37.rc
  tests/functional/s/singledispatch_method_py37.txt
  tests/functional/s/singledispatch_method_py38.py
  tests/functional/s/singledispatch_method_py38.rc
  tests/functional/s/singledispatch_method_py38.txt
  tests/functional/s/singledispatchmethod_function_py38.py
  tests/functional/s/singledispatchmethod_function_py38.rc
  tests/functional/s/singledispatchmethod_function_py38.txt
Labels: Enhancement ✨, hacktoberfest-accepted
