Repository pylint-dev/pylint, pull requests merged in 2022-01, with the labels that each got.

#5630 Fix #5370: Emit `redefined-outer-name` when a nested except handler shadows an outer one
  ChangeLog
  doc/whatsnew/2.13.rst
  pylint/checkers/variables.py
  tests/functional/r/redefined_except_handler.py
  tests/functional/r/redefined_except_handler.txt
Labels: Enhancement ✨

#5632 pre-commit colorama error fix with mypy checker on Windows
  setup.cfg
Labels: Maintenance, Windows 🪟

#5634 Update astroid to ``2.9.2``
  requirements_test_min.txt
  setup.cfg
Labels: dependency, Maintenance

#5642 Move ``HUMAN_READABLE_TYPES`` to ``constants``
  pylint/checkers/base.py
  pylint/constants.py
Labels: Maintenance

#5615 Add test for exclusivity of id names
  tests/message/unittest_message_id_store.py
Labels: Maintenance

#5618 Rename CI job names
  .github/workflows/ci.yaml
  .github/workflows/primer-test.yaml
Labels: Discussion 🤔, Maintenance

#5494 Fix crash with slots and annotated assignments
  ChangeLog
  doc/whatsnew/2.13.rst
  pylint/checkers/classes/class_checker.py
  tests/functional/r/regression_02/regression_5479.py
  tests/functional/r/regression_02/regression_5479.rc
  tests/functional/r/regression_02/regression_5479.txt
Labels: Crash 💥

#5660 Fix escaping of some strings in functional tests
  tests/functional/e/.#emacs_file_lock_redefined_conf.txt
  tests/functional/ext/docparams/raise/missing_raises_doc_required_exc_inheritance.txt
Labels: Maintenance

#5582 Don't assume direct parentage when emitting `used-before-assignment`
  ChangeLog
  doc/whatsnew/2.13.rst
  pylint/checkers/utils.py
  pylint/checkers/variables.py
  tests/functional/u/use/used_before_assignment_issue2615.py
  tests/functional/u/use/used_before_assignment_issue2615.txt
Labels: False Negative 🦋

#5656 Fixed false positive for ``global-variable-not-assigned``
  ChangeLog
  doc/whatsnew/2.13.rst
  pylint/checkers/utils.py
  pylint/checkers/variables.py
  tests/functional/g/globals.py
  tests/functional/g/globals.txt
Labels: Bug 🪳, topic-control-flow

#5621 Add ``future=True`` to all ``NodeNG.frame`` calls
  examples/custom.py
  pylint/checkers/base.py
  pylint/checkers/classes/class_checker.py
  pylint/checkers/format.py
  pylint/checkers/imports.py
  pylint/checkers/newstyle.py
  pylint/checkers/refactoring/not_checker.py
  pylint/checkers/refactoring/refactoring_checker.py
  pylint/checkers/utils.py
  pylint/checkers/variables.py
  pylint/extensions/_check_docs_utils.py
  pylint/extensions/bad_builtin.py
  pylint/extensions/docparams.py
  pylint/pyreverse/inspector.py
  pylint/utils/utils.py
Labels: Maintenance

#5651 Fix #5326: Fix false positive for `unused-variable` for a comprehension variable matching a type annotation
  ChangeLog
  doc/whatsnew/2.13.rst
  pylint/checkers/variables.py
  tests/functional/u/undefined/undefined_variable_py38.py
  tests/functional/u/undefined/undefined_variable_py38.txt
Labels: False Positive 🦟

#5665 Make sure to split non-separated csv ``OuputLine's``
  pylint/testutils/output_line.py
  tests/testutils/test_output_line.py
Labels: Maintenance

#5526 Disable bad-docstring-quotes for <= 3.7
  ChangeLog
  doc/whatsnew/2.13.rst
  pylint/extensions/docstyle.py
  tests/functional/ext/docstyle/docstyle.txt
  tests/functional/ext/docstyle/docstyle_first_line_empty.py
  tests/functional/ext/docstyle/docstyle_first_line_empty.rc
  tests/functional/ext/docstyle/docstyle_first_line_empty.txt
  tests/functional/ext/docstyle/docstyle_quotes_py37.py
  tests/functional/ext/docstyle/docstyle_quotes_py37.rc
  tests/functional/ext/docstyle/docstyle_quotes_py38.py
  tests/functional/ext/docstyle/docstyle_quotes_py38.rc
  tests/functional/ext/docstyle/docstyle_quotes_py38.txt
Labels: Maintenance

#5666 Fix #5586: False positive for `used-before-assignment` with homonyms in filtered comprehensions and except blocks
  ChangeLog
  doc/whatsnew/2.13.rst
  pylint/checkers/variables.py
  tests/functional/u/use/used_before_assignment_filtered_comprehension.py
Labels: False Positive 🦟

#5669 Update `pandas-dev` testing primer package branch to `main`
  tests/primer/packages_to_lint_batch_two.json
Labels: Maintenance

#5311 add a checker for misleading unicode
  CONTRIBUTORS.txt
  ChangeLog
  doc/whatsnew/2.13.rst
  pylint/checkers/__init__.py
  pylint/checkers/unicode.py
  tests/checkers/unittest_unicode/__init__.py
  tests/checkers/unittest_unicode/unittest_bad_chars.py
  tests/checkers/unittest_unicode/unittest_bidirectional_unicode.py
  tests/checkers/unittest_unicode/unittest_functions.py
  tests/checkers/unittest_unicode/unittest_invalid_encoding.py
  tests/conftest.py
  tests/functional/b/bad_char/bad_char_backspace.py
  tests/functional/b/bad_char/bad_char_backspace.txt
  tests/functional/b/bad_char/bad_char_carriage_return.py
  tests/functional/b/bad_char/bad_char_carriage_return.rc
  tests/functional/b/bad_char/bad_char_carriage_return.txt
  tests/functional/b/bad_char/bad_char_esc.py
  tests/functional/b/bad_char/bad_char_esc.txt
  tests/functional/b/bad_char/bad_char_sub.py
  tests/functional/b/bad_char/bad_char_sub.txt
  tests/functional/b/bad_char/bad_char_zero_width_space.py
  tests/functional/b/bad_char/bad_char_zero_width_space.txt
  tests/functional/e/.#emacs_file_lock_redefined_conf.rc
  tests/functional/i/implicit/implicit_str_concat_latin1.py
  tests/functional/i/implicit/implicit_str_concat_latin1.txt
  tests/functional/n/non/non_ascii_name.py
  tests/functional/u/unicode/unicode_bidi_commenting_out.py
  tests/functional/u/unicode/unicode_bidi_commenting_out.txt
  tests/functional/u/unicode/unicode_bidi_early_return.py
  tests/functional/u/unicode/unicode_bidi_early_return.txt
  tests/functional/u/unicode/unicode_bidi_pep672.py
  tests/functional/u/unicode/unicode_bidi_pep672.txt
  tests/regrtest_data/unicode/invisible_function.txt
  tests/regrtest_data/unicode/pep_bidirectional_utf_16_bom.txt
  tests/regrtest_data/unicode/pep_bidirectional_utf_16_le_no_bom.txt
  tests/regrtest_data/unicode/pep_bidirectional_utf_32_bom.txt
  tests/regrtest_data/unicode/pep_bidirectional_utf_32_le_no_bom.txt
  tests/test_self.py
Labels: Enhancement ✨, Checkers

#5672 Remove ``lru_cache`` from ``get_active_msgids``
  pylint/message/message_id_store.py
Labels: topic-performance, Maintenance

#5652 Fix crash on properties & inherited methods in ``implicit-booleaness``
  ChangeLog
  doc/whatsnew/2.13.rst
  pylint/checkers/refactoring/implicit_booleaness_checker.py
  tests/checkers/unittest_refactoring.py
  tests/functional/u/use/use_implicit_booleaness_not_comparison.py
  tests/functional/u/use/use_implicit_booleaness_not_comparison.txt
Labels: Crash 💥

#5674 Add ``lru-cache-decorating-method`` checker
  ChangeLog
  doc/whatsnew/2.13.rst
  pylint/checkers/stdlib.py
  pylint/message/message_definition_store.py
  tests/functional/l/lru_cache_decorating_method.py
  tests/functional/l/lru_cache_decorating_method.txt
Labels: Enhancement ✨

#5680 Add typing to `ScopeConsumer`
  pylint/checkers/variables.py
Labels: Maintenance

#5681 Add typing to ``get_next_to_consume`` and ``_check_consumer``
  pylint/checkers/variables.py
Labels: Maintenance

#5675 Fix crashes for accesses to `node.parent.name` on `FunctionDef` nodes
  ChangeLog
  doc/whatsnew/2.13.rst
  pylint/checkers/classes/class_checker.py
  pylint/checkers/typecheck.py
  tests/functional/a/arguments_renamed.py
  tests/functional/a/arguments_renamed.txt
  tests/functional/o/overridden_final_method_py38.py
  tests/functional/o/overridden_final_method_py38.txt
Labels: Crash 💥

#5583 Fix false negative for `used-before-assignment` when an Except intervenes between Try/Finally
  ChangeLog
  doc/whatsnew/2.13.rst
  pylint/checkers/variables.py
  tests/functional/c/consider/consider_using_with_open.py
  tests/functional/c/consider/consider_using_with_open.txt
  tests/functional/u/use/used_before_assignment_issue85.py
  tests/functional/u/use/used_before_assignment_issue85.txt
Labels: False Negative 🦋

#5685 Follow-up to some test changes
  tests/checkers/unittest_unicode/unittest_bad_chars.py
  tests/checkers/unittest_unicode/unittest_bidirectional_unicode.py
  tests/checkers/unittest_unicode/unittest_invalid_encoding.py
  tests/conftest.py
Labels: Maintenance

#5686 Fix typing of `get_node_first_ancestor_of_type()` and related method
  pylint/checkers/utils.py
Labels: Maintenance

#5689 Allow dev version of next minor ``astroid`` version
  setup.cfg
Labels: Maintenance

#5688 Fix #5568: Allow nested classes as return annotations
  ChangeLog
  doc/whatsnew/2.13.rst
  pylint/checkers/variables.py
  tests/functional/u/undefined/undefined_variable.py
Labels: False Positive 🦟

#5640 Add checker `redefined-slots-in-subclass`
  ChangeLog
  doc/whatsnew/2.13.rst
  pylint/checkers/classes/class_checker.py
  tests/functional/r/redefined_slots.py
  tests/functional/r/redefined_slots.txt
Labels: Enhancement ✨, Checkers

#5690 Fixed false positive for ``global-variable-undefined``
  ChangeLog
  doc/whatsnew/2.13.rst
  pylint/checkers/utils.py
  pylint/checkers/variables.py
  tests/functional/g/globals.py
  tests/functional/g/globals.txt
Labels: False Positive 🦟

#5700 ``unused-variable`` when `nonlocal` name in a multiple-assignment
  ChangeLog
  doc/whatsnew/2.13.rst
  pylint/checkers/variables.py
  tests/functional/n/nonlocal_without_binding.py
Labels: Enhancement ✨, False Positive 🦟

#5697 Fix ``super-init-not-called`` if parent or ``self`` is a ``Protocol``
  ChangeLog
  doc/whatsnew/2.13.rst
  pylint/checkers/classes/class_checker.py
  tests/functional/i/init_not_called.txt
  tests/functional/n/non/non_init_parent_called.txt
  tests/functional/s/super/super_init_not_called.py
  tests/functional/s/super/super_init_not_called.txt
  tests/functional/s/super/super_init_not_called_extensions.py
  tests/functional/s/super/super_init_not_called_extensions.rc
  tests/functional/s/super/super_init_not_called_extensions.txt
  tests/functional/s/super/super_init_not_called_extensions_py310.py
  tests/functional/s/super/super_init_not_called_extensions_py310.rc
  tests/functional/s/super/super_init_not_called_extensions_py310.txt
  tests/functional/s/super/super_init_not_called_py38.py
  tests/functional/s/super/super_init_not_called_py38.rc
Labels: False Positive 🦟

#5698 Fix false positive ``super-init-not-called`` for inherited ``init``
  ChangeLog
  doc/whatsnew/2.13.rst
  pylint/checkers/classes/class_checker.py
  pylint/checkers/imports.py
  pylint/checkers/stdlib.py
  tests/functional/s/super/super_init_not_called.py
  tests/functional/s/super/super_init_not_called.txt
Labels: False Positive 🦟

#5721 add Or Bahari copyrite aliases
  .copyrite_aliases
  CONTRIBUTORS.txt
Labels: Maintenance

#5711 Fix #5654: Fix false negative for `undefined-variable` for unused type annotation after the same name appears multiple times in a comprehension
  ChangeLog
  doc/whatsnew/2.13.rst
  pylint/checkers/variables.py
  tests/functional/u/undefined/undefined_variable_py38.py
  tests/functional/u/undefined/undefined_variable_py38.txt
Labels: False Negative 🦋, C: used-before-assignment

#5718 Fix #5713: Emit `used-before-assignment` instead of `undefined-variable` when accessing unused type annotations
  ChangeLog
  doc/whatsnew/2.13.rst
  pylint/checkers/variables.py
  tests/functional/u/undefined/undefined_variable.py
  tests/functional/u/undefined/undefined_variable.txt
  tests/functional/u/use/used_before_assignment_type_annotations.py
  tests/functional/u/use/used_before_assignment_type_annotations.txt
Labels: Enhancement ✨

#5726 Fix test conflicts
  tests/functional/u/undefined/undefined_variable_py38.py
  tests/functional/u/undefined/undefined_variable_py38.txt
Labels: Maintenance

#5709 Add confidence level `CONTROL_FLOW`
  ChangeLog
  doc/whatsnew/2.13.rst
  pylint/checkers/variables.py
  pylint/interfaces.py
  tests/functional/a/assign/assignment_expression.txt
  tests/functional/c/class_scope.txt
  tests/functional/c/consider/consider_using_with_open.txt
  tests/functional/m/module___dict__.txt
  tests/functional/p/postponed_evaluation_not_activated.txt
  tests/functional/r/redefined_except_handler.txt
  tests/functional/u/undefined/undefined_variable.txt
  tests/functional/u/undefined/undefined_variable_py38.txt
  tests/functional/u/use/used_before_assignment.txt
  tests/functional/u/use/used_before_assignment_except_handler_for_try_with_return.txt
  tests/functional/u/use/used_before_assignment_issue1081.txt
  tests/functional/u/use/used_before_assignment_issue2615.txt
  tests/functional/u/use/used_before_assignment_issue4761.txt
  tests/functional/u/use/used_before_assignment_issue626.txt
  tests/functional/u/use/used_before_assignment_issue85.txt
  tests/functional/u/use/used_before_assignment_nonlocal.txt
  tests/functional/u/use/used_before_assignment_py37.txt
  tests/functional/u/use/used_before_assignment_typing.txt
  tests/functional/w/with_used_before_assign.txt
Labels: Enhancement ✨, Maintenance

#5684 Fix #5683: False positive ``used-before-assignment`` in loop `else` where the only non-break exit is through `except`
  ChangeLog
  doc/whatsnew/2.13.rst
  pylint/checkers/variables.py
  tests/functional/u/use/used_before_assignment_issue4761.py
  tests/functional/u/use/used_before_assignment_issue4761.txt
Labels: False Positive 🦟

#5730 Remove the ``check_docs`` extension and remove any references to it
  ChangeLog
  doc/exts/pylint_extensions.py
  doc/whatsnew/2.13.rst
  pylint/extensions/check_docs.py
  pylint/lint/run.py
  tests/extensions/test_check_docs_utils.py
  tests/test_self.py
Labels: Checkers, Maintenance

#5580 Add ``DeprecationWarning`` for non-string ``current_name`` & ``file``
  pylint/checkers/similar.py
  pylint/lint/parallel.py
  pylint/lint/pylinter.py
  tests/lint/unittest_lint.py
  tests/test_check_parallel.py
Labels: Maintenance

#5739 Fix typos in unit test docstrings
  tests/functional/n/no/no_else_break.py
  tests/functional/n/no/no_else_continue.py
  tests/functional/n/no/no_else_raise.py
Labels: Maintenance

#5396 Create separate documentation page for each message
  .gitignore
  doc/Makefile
  doc/conf.py
  doc/exts/pylint_messages.py
  doc/index.rst
  doc/messages/index.rst
  doc/messages/messages_introduction.rst
  doc/messages/messages_list.rst
  pylint/checkers/base.py
  pylint/checkers/non_ascii_names.py
  pylint/checkers/refactoring/refactoring_checker.py
  pylint/checkers/stdlib.py
  pylint/checkers/strings.py
Labels: Needs Review 🔍, Documentation 📖

#5741 Correct reference to `argv` in documentation for `run_pylint()`
  ChangeLog
  doc/user_guide/run.rst
  doc/whatsnew/2.13.rst
Labels: Maintenance

#5743 Emit the crash issue template for more exceptions and crashes
  ChangeLog
  doc/whatsnew/2.13.rst
  pylint/lint/pylinter.py
  tests/lint/test_utils.py
Labels: Bug 🪳, Maintenance

#5727 Fix #5399: Fix false negatives for further variable messages for invalid type annotations or default arguments
  ChangeLog
  doc/whatsnew/2.13.rst
  pylint/checkers/variables.py
  tests/functional/u/undefined/undefined_variable.py
  tests/functional/u/undefined/undefined_variable.txt
  tests/functional/u/use/used_before_assignment_py37.py
  tests/functional/u/use/used_before_assignment_py37.txt
  tests/functional/u/use/used_before_assignment_typing.py
  tests/functional/u/use/used_before_assignment_typing.txt
Labels: False Negative 🦋

#5736 Clearer error message for useless-else-x type messages
  ChangeLog
  doc/whatsnew/2.13.rst
  pylint/checkers/base.py
  pylint/checkers/refactoring/refactoring_checker.py
  pylint/extensions/check_elif.py
  tests/functional/ext/check_elif/check_elif.txt
  tests/functional/n/no/no_else_break.txt
  tests/functional/n/no/no_else_continue.txt
  tests/functional/n/no/no_else_raise.txt
  tests/functional/n/no/no_else_return.txt
  tests/functional/u/useless/useless_else_on_loop.txt
Labels: Enhancement ✨, Documentation 📖

#5752 Add timeouts for CI jobs
  .github/workflows/ci.yaml
  .github/workflows/primer-test.yaml
Labels: Maintenance

#5754 Improve error message arguments formatting [redefined-slots]
  pylint/checkers/classes/class_checker.py
  tests/functional/r/redefined_slots.txt
Labels: Discussion 🤔

#5755 Increase timeouts
  .github/workflows/ci.yaml
  .github/workflows/primer-test.yaml
Labels: Maintenance
