Repository pylint-dev/pylint, pull requests merged in 2022-08, with the labels that each got.

#7251 Add type annotations to `format.py` module.
  pylint/checkers/format.py
Labels: Maintenance, Skip news :mute:

#7234 Fix failing tests in `test_self.py` module
  tests/test_self.py
Labels: Maintenance, macOS, Skip news :mute:

#7267 [open source insight] Add the badge from OpenSSF
  README.rst
  doc/whatsnew/fragments/7267.internal
Labels: Documentation :green_book:

#7277 Check for `<cwd>` before removing first item from `sys.path` in `modify_sys_path`.
  doc/whatsnew/fragments/7231.bugfix
  pylint/__init__.py
  tests/test_self.py
Labels: Bug :beetle:

#7190 [typing] Add typing to the class checkers
  pylint/checkers/base/basic_error_checker.py
  pylint/checkers/classes/class_checker.py
  pylint/checkers/classes/special_methods_checker.py
Labels: Maintenance, Skip news :mute:

#7294 bukzor: Updating my contributor aliases.
  script/.contributors_aliases.json
Labels: Maintenance, Skip news :mute:

#7295 Partial typing of ``refactoring_checker``
  pylint/checkers/refactoring/refactoring_checker.py
Labels: Maintenance

#7299 Update PyPI `Homepage` url via pyproject.toml configuration.
  pyproject.toml
Labels: Documentation :green_book:, Skip news :mute:

#7279 Clean up beyond_top_level tests
  tests/checkers/unittest_imports.py
Labels: tests, Skip news :mute:

#7304 Revert "Fix the failure to lint modules contained under an identically named directory"
  doc/whatsnew/fragments/4444.bugfix
  pylint/lint/expand_modules.py
  tests/checkers/unittest_imports.py
  tests/lint/unittest_lint.py
Labels: Bug :beetle:, Regression, Unreleased, namespace-package, Skip news :mute:

#7301 Fix false positive for `no-self-argument`
  doc/whatsnew/fragments/7300.false_positive
  pylint/checkers/classes/class_checker.py
  tests/functional/n/no/no_self_argument.py
  tests/functional/n/no/no_self_argument.txt
Labels: False Positive 🦟

#7286 Refactors related to separating ast creating and linting
  pylint/lint/pylinter.py
Labels: Maintenance, Skip news :mute:

#7312 Partial typing of ``refactoring_checker``
  pylint/checkers/refactoring/refactoring_checker.py
Labels: Maintenance, Skip news :mute:

#7315 Partial typing of ``refactoring_checker``
  pylint/checkers/refactoring/refactoring_checker.py
Labels: Maintenance, Skip news :mute:

#7313 Some primer fixes
  .github/workflows/primer_comment.yaml
  .github/workflows/primer_run_main.yaml
  .github/workflows/primer_run_pr.yaml
Labels: primer, Skip news :mute:

#7288 Refactor check()
  pylint/lint/pylinter.py
  tests/lint/test_pylinter.py
  tests/test_check_parallel.py
Labels: Maintenance, Skip news :mute:

#7318 fix `undefined-loop-variable` with `break` and `continue` statements in `else` blocks
  doc/whatsnew/fragments/7311.false_positive
  pylint/checkers/variables.py
  script/check_newsfragments.py
  tests/functional/u/undefined/undefined_loop_variable.py
  tests/functional/u/undefined/undefined_loop_variable.txt
Labels: False Positive 🦟

#7321 [doc] Remove dead link to the mail archives prior to 2013
  doc/contact.rst
Labels: Documentation :green_book:, Skip news :mute:

#7322 Improve TypeVar name regex
  doc/data/messages/i/invalid-name/details.rst
  doc/whatsnew/fragments/7322.false-positive
  pylint/checkers/base/name_checker/checker.py
  tests/functional/a/assigning/assigning_non_slot.py
  tests/functional/t/typevar_naming_style_default.py
  tests/functional/t/typevar_naming_style_default.txt
Labels: Enhancement ✨, C: invalid-name

#7323 Add enum regression test
  tests/functional/r/regression_02/regression_enum_1734.py
Labels: Skip news :mute:

#7324 Fix `undefined-loop-variable` from walrus in comprehension test
  doc/whatsnew/fragments/7222.bugfix
  pylint/checkers/variables.py
  tests/functional/u/undefined/undefined_loop_variable_py38.py
  tests/functional/u/undefined/undefined_loop_variable_py38.rc
Labels: False Positive 🦟

#7326 Add a functional test for the `useless-parent-delegation` checker.
  tests/functional/u/useless/useless_parent_delegation.py
  tests/functional/u/useless/useless_parent_delegation.txt
Labels: Skip news :mute:

#7329 Prevent `useless-parent-delegation` for overriding builtins with new args
  doc/whatsnew/fragments/7319.bugfix
  pylint/checkers/classes/class_checker.py
  tests/functional/u/useless/useless_parent_delegation.py
Labels: False Positive 🦟

#7117 Add regression test for #3651
  tests/lint/unittest_lint.py
Labels: topic-import-system, Skip news :mute:

#7331 Fix ``mypy`` issues in primer
  pylint/testutils/_primer/package_to_lint.py
  pylint/testutils/_primer/primer_prepare_command.py
Labels: primer, Skip news :mute:

#7334 Skip ``unnecessary-list-index-lookup`` if we encounter if statements
  doc/whatsnew/fragments/6896.false_positive
  pylint/checkers/refactoring/refactoring_checker.py
  tests/functional/u/unnecessary/unnecessary_list_index_lookup.py
Labels: False Positive 🦟

#7327 Check for ``contextlib.suppress`` in ``node_ignores_exception``
  doc/whatsnew/fragments/7270.false_positive
  pylint/checkers/utils.py
  tests/functional/i/import_error.py
  tests/functional/i/import_error.txt
Labels: False Positive 🦟

#7335 Don't emit ``trailing-whitespace`` twice for multi-line docstrings
  doc/whatsnew/fragments/6936.false_positive
  pylint/checkers/format.py
  tests/functional/t/trailing_whitespaces.py
  tests/functional/t/trailing_whitespaces.txt
Labels: False Positive 🦟

#7332 Use permanent links in the primer comment
  pylint/testutils/_primer/primer_command.py
  pylint/testutils/_primer/primer_compare_command.py
  pylint/testutils/_primer/primer_run_command.py
  tests/testutils/_primer/fixtures/message_changed/expected.txt
  tests/testutils/_primer/fixtures/message_changed/expected_truncated.txt
  tests/testutils/_primer/fixtures/message_changed/main.json
  tests/testutils/_primer/fixtures/message_changed/pr.json
  tests/testutils/_primer/fixtures/no_change/main.json
  tests/testutils/_primer/fixtures/no_change/pr.json
  tests/testutils/_primer/test_primer.py
Labels: primer, Skip news :mute:

#7344 Upgrade astroid version following 2.12.3 release
  .github/workflows/changelog.yml
  .github/workflows/checks.yaml
  .github/workflows/primer-test.yaml
  .github/workflows/primer_comment.yaml
  .github/workflows/primer_run_main.yaml
  .github/workflows/primer_run_pr.yaml
  .github/workflows/tests.yaml
  pyproject.toml
  requirements_test_min.txt
Labels: Maintenance, Skip news :mute:

#7345 Revert "[test] Temporary xfail deprecated methods py36 on pypy"
  tests/functional/d/deprecated/deprecated_methods_py36.rc
  tests/functional/d/deprecated/deprecated_module_redundant.rc
Labels: Maintenance, Skip news :mute:

#7349 Bump TODOs to the next minor version in preparation of release
  pylint/reporters/json_reporter.py
  script/fix_documentation.py
Labels: Maintenance, Skip news :mute:

#7333 Add tests for #5767
  doc/whatsnew/fragments/5767.false_positive
  tests/functional/d/dataclass_parameter.py
  tests/functional/d/dataclass_parameter.rc
Labels: False Positive 🦟, Needs astroid update, Skip news :mute:

#7356 Upgrade astroid version following 2.12.4 release
  .github/workflows/changelog.yml
  .github/workflows/checks.yaml
  .github/workflows/primer-test.yaml
  .github/workflows/primer_comment.yaml
  .github/workflows/primer_run_main.yaml
  .github/workflows/primer_run_pr.yaml
  .github/workflows/tests.yaml
  pyproject.toml
  requirements_test_min.txt
Labels: Maintenance, Skip news :mute:

#7358 Update `tox.ini`
  tox.ini
Labels: Maintenance, Skip news :mute:

#7355 Release branch 2.15.0
  CONTRIBUTORS.txt
  doc/whatsnew/2/2.15/index.rst
  doc/whatsnew/fragments/1667.bugfix
  doc/whatsnew/fragments/3694.other
  doc/whatsnew/fragments/3860.bugfix
  doc/whatsnew/fragments/3975.false_positive
  doc/whatsnew/fragments/4624.false_negative
  doc/whatsnew/fragments/4951.false_positive
  doc/whatsnew/fragments/5237.other
  doc/whatsnew/fragments/5653.false_negative
  doc/whatsnew/fragments/5767.false_positive
  doc/whatsnew/fragments/5776.false_positive
  doc/whatsnew/fragments/5832.false_positive
  doc/whatsnew/fragments/6643.false_negative
  doc/whatsnew/fragments/6648.false_negative
  doc/whatsnew/fragments/6780.new_check
  doc/whatsnew/fragments/6812.false_negative
  doc/whatsnew/fragments/6883.false_negative
  doc/whatsnew/fragments/6891.internal
  doc/whatsnew/fragments/6896.false_positive
  doc/whatsnew/fragments/6905.internal
  doc/whatsnew/fragments/6909.false_negative
  doc/whatsnew/fragments/6936.false_positive
  doc/whatsnew/fragments/6953.other
  doc/whatsnew/fragments/6974.internal
  doc/whatsnew/fragments/6974.other
  doc/whatsnew/fragments/7034.false_negative
  doc/whatsnew/fragments/7109.bugfix
  doc/whatsnew/fragments/7153.other
  doc/whatsnew/fragments/7202.bugfix
  doc/whatsnew/fragments/7222.bugfix
  doc/whatsnew/fragments/7231.bugfix
  doc/whatsnew/fragments/7246.bugfix
  doc/whatsnew/fragments/7267.internal
  doc/whatsnew/fragments/7270.false_positive
  doc/whatsnew/fragments/7280.other
  doc/whatsnew/fragments/7300.false_positive
  doc/whatsnew/fragments/7311.false_positive
  doc/whatsnew/fragments/7319.bugfix
  pylint/__pkginfo__.py
  script/.contributors_aliases.json
  tbump.toml
Labels: Maintenance, Skip news :mute:

#7363 Bump pylint to 2.16.0-dev, update changelog
  doc/whatsnew/2/2.16/index.rst
  doc/whatsnew/2/index.rst
  pylint/__pkginfo__.py
  tbump.toml
  towncrier.toml
Labels: Maintenance, Skip news :mute:

#7364 Add a functional regression test.
  tests/functional/r/regression_02/regression_3976.py
Labels: Skip news :mute:

#7369 Fix 2.15 changelog
  doc/whatsnew/2/2.15/index.rst
  doc/whatsnew/fragments/7322.false-positive
Labels: Needs backport, Skip news :mute:

#7367 nest _test_environ_pythonpath independent of outside PYTHONPATH
  tests/testutils/test_testutils_utils.py
Labels: Maintenance, Skip news :mute:

#7370 Fix `used-before-assignment` for functions/classes defined in type checking guard
  doc/whatsnew/fragments/7368.false_positive
  pylint/checkers/variables.py
  tests/functional/u/undefined/undefined_variable.py
  tests/functional/u/undefined/undefined_variable.txt
Labels: Needs backport, False Positive 🦟

#7372 Replace deprecated `sre_constants.error` with `re.error`
  tests/config/unittest_config.py
Labels: Maintenance, Skip news :mute:

#7373 Added documentation examples for `bad-format-string-key`
  doc/data/messages/b/bad-format-string-key/bad.py
  doc/data/messages/b/bad-format-string-key/details.rst
  doc/data/messages/b/bad-format-string-key/good.py
Labels: Documentation :green_book:, Skip news :mute:

#7374 Added documentation examples for `redefined-outer-name`
  doc/data/messages/r/redefined-outer-name/bad.py
  doc/data/messages/r/redefined-outer-name/details.rst
  doc/data/messages/r/redefined-outer-name/good.py
Labels: Documentation :green_book:, Skip news :mute:

#7342 Don't report ``trailing-whitespaces`` within strings
  .pyenchant_pylint_custom_dict.txt
  doc/whatsnew/fragments/3822.false_positive
  pylint/checkers/format.py
  tests/functional/t/trailing_whitespaces.py
Labels: False Positive 🦟

#7378 Fix following "Bump astroid from 2.12.4 to 2.12.5"
  .github/workflows/changelog.yml
  .github/workflows/checks.yaml
  .github/workflows/primer-test.yaml
  .github/workflows/primer_comment.yaml
  .github/workflows/primer_run_main.yaml
  .github/workflows/primer_run_pr.yaml
  .github/workflows/tests.yaml
Labels: Blocked 🚧, dependency, Skip news :mute:

#7386 Fix crash while iteraring over a class attribute
  doc/whatsnew/fragments/7380.bugfix
  pylint/checkers/modified_iterating_checker.py
  tests/functional/m/modified_iterating.py
  tests/functional/m/modified_iterating.txt
Labels: Needs backport, Crash 💥
