Repository pylint-dev/pylint, pull requests merged in 2023-09, with the labels that each got.

#8988 Fix Pyreverse line break bug
  doc/whatsnew/fragments/8671.bugfix
  pylint/pyreverse/dot_printer.py
  tests/pyreverse/functional/class_diagrams/annotations/line_breaks.dot
  tests/pyreverse/functional/class_diagrams/annotations/line_breaks.mmd
  tests/pyreverse/functional/class_diagrams/annotations/line_breaks.puml
  tests/pyreverse/functional/class_diagrams/annotations/line_breaks.py
Labels: Bug :beetle:, pyreverse

#8994 [mixed-line-endings] Create the initial documentation
  .gitattributes
  doc/data/messages/m/mixed-line-endings/bad.py
  doc/data/messages/m/mixed-line-endings/details.rst
  doc/data/messages/m/mixed-line-endings/good.py
  doc/data/messages/m/mixed-line-endings/good/full_crlf.py
  doc/data/messages/m/mixed-line-endings/good/full_lf.py
  doc/data/messages/m/mixed-line-endings/related.rst
  doc/data/messages/u/unexpected-line-ending-format/bad.py
  doc/data/messages/u/unexpected-line-ending-format/good.py
Labels: Documentation :green_book:, Skip news :mute:

#8892 Fix false positive when testing for-loops for unbalanced unpacking (W0644)
  doc/whatsnew/fragments/8156.false_positive
  pylint/checkers/variables.py
  tests/functional/u/unbalanced/unbalanced_dict_unpacking.py
  tests/functional/u/unbalanced/unbalanced_dict_unpacking.txt
Labels: Needs review 🔍, False Positive 🦟, backport maintenance/2.17.x

#8993 [relative-beyond-top-level] Create the initial documentation
  doc/data/messages/r/relative-beyond-top-level/bad.py
  doc/data/messages/r/relative-beyond-top-level/details.rst
  doc/data/messages/r/relative-beyond-top-level/good.py
  doc/data/messages/r/relative-beyond-top-level/good/absolute_import.py
  doc/data/messages/r/relative-beyond-top-level/good/fix_the_relative_import.py
  doc/data/messages/r/relative-beyond-top-level/related.rst
Labels: Documentation :green_book:, Skip news :mute:

#8992 [doc] Document some internal pylint errors and configuration/option error
  doc/data/messages/b/bad-plugin-value/details.rst
  doc/data/messages/b/bad-plugin-value/good.py
  doc/data/messages/r/raw-checker-failed/details.rst
  doc/data/messages/r/raw-checker-failed/good.py
  doc/data/messages/u/unrecognized-option/details.rst
  doc/data/messages/u/unrecognized-option/good.py
Labels: Documentation :green_book:, Skip news :mute:

#8960 Better example for W0640: cell-var-from-loop
  doc/data/messages/c/cell-var-from-loop/bad.py
  doc/data/messages/c/cell-var-from-loop/good.py
  doc/data/messages/c/cell-var-from-loop/good/functools.partial.py
  doc/data/messages/c/cell-var-from-loop/good/new_function.py
Labels: Documentation :green_book:, Skip news :mute:

#9003 Fixing inconsistent hashing issue in `BaseChecker`
  doc/whatsnew/fragments/9001.bugfix
  pylint/checkers/base_checker.py
  tests/checkers/unittest_base_checker.py
Labels: Maintenance, backport maintenance/2.17.x

#9004 Fix duplicate fields Pyreverse bug
  doc/whatsnew/fragments/8189.bugfix
  pylint/pyreverse/diagrams.py
  tests/pyreverse/functional/class_diagrams/attributes/duplicates.mmd
  tests/pyreverse/functional/class_diagrams/attributes/duplicates.py
Labels: Bug :beetle:, pyreverse, backport maintenance/2.17.x

#8995 [deprecated-argument] Create the initial documentation
  doc/data/messages/d/deprecated-argument/bad.py
  doc/data/messages/d/deprecated-argument/details.rst
  doc/data/messages/d/deprecated-argument/good.py
  doc/data/messages/d/deprecated-argument/pylintrc
Labels: Documentation :green_book:, Skip news :mute:

#9012 Fix Pyreverse duplicate annotations
  doc/whatsnew/fragments/8888.bugfix
  pylint/pyreverse/diagrams.py
  tests/pyreverse/functional/class_diagrams/attributes/duplicates.mmd
  tests/pyreverse/functional/class_diagrams/attributes/duplicates.py
Labels: Bug :beetle:, pyreverse, backport maintenance/2.17.x

#9016 Fix Pyreverse optional annotation bug
  doc/whatsnew/fragments/9014.bugfix
  pylint/pyreverse/utils.py
  tests/pyreverse/functional/class_diagrams/annotations/attributes_annotation.dot
  tests/pyreverse/functional/class_diagrams/annotations/attributes_annotation.mmd
  tests/pyreverse/functional/class_diagrams/annotations/attributes_annotation.puml
  tests/pyreverse/functional/class_diagrams/annotations/attributes_annotation.py
Labels: Bug :beetle:, pyreverse, backport maintenance/2.17.x

#8991 [doc test helper] Better representation of failure for multiple good files
  doc/test_messages_documentation.py
Labels: Maintenance, Skip news :mute:

#9020 [doc test helper] Better representation of failure for multiple bad files
  doc/data/messages/n/non-ascii-file-name/bad/__init__.py
  doc/data/messages/n/non-ascii-file-name/good/__init__.py
  doc/test_messages_documentation.py
Labels: Maintenance, Skip news :mute:

#9035 Fix doc and/or a false negative in ``superfluous-parens``
  .pre-commit-config.yaml
  doc/data/messages/s/superfluous-parens/bad/example_1.py
  doc/data/messages/s/superfluous-parens/bad/example_2.py
  doc/data/messages/s/superfluous-parens/good/example_1.py
  doc/data/messages/s/superfluous-parens/good/example_2.py
Labels: Documentation :green_book:, Skip news :mute:

#9031 fix mermaid dotted arrow
  pylint/pyreverse/mermaidjs_printer.py
  tests/pyreverse/functional/package_diagrams/type_check_imports/packages.mmd
Labels: Bug :beetle:, pyreverse, Unreleased, Skip news :mute:

#9029 Fix Pyreverse duplicate arrows bug
  doc/whatsnew/fragments/8522.bugfix
  pylint/pyreverse/diagrams.py
  tests/pyreverse/functional/class_diagrams/attributes/duplicates.mmd
  tests/pyreverse/functional/class_diagrams/attributes/duplicates.py
Labels: Bug :beetle:, pyreverse, backport maintenance/2.17.x

#9049 Update `BUG-REPORT.yml`
  .github/ISSUE_TEMPLATE/BUG-REPORT.yml
Labels: Skip news :mute:

#9046 Add test for aggregation issue
  tests/pyreverse/functional/class_diagrams/aggregation/fields.mmd
  tests/pyreverse/functional/class_diagrams/aggregation/fields.py
Labels: pyreverse, tests, Skip news :mute:

#9057 Tidy up 3.0 fragments
  doc/whatsnew/fragments/6871.user_action
  doc/whatsnew/fragments/8411.user_action
Labels: Documentation :green_book:, Skip news :mute:

#9034 Fix C2801 special cases in lambda
  doc/whatsnew/fragments/8769.bugfix
  pylint/checkers/dunder_methods.py
  pylint/constants.py
  tests/functional/u/unnecessary/unnecessary_dunder_call.txt
  tests/functional/u/unnecessary/unnecessary_dunder_call_py38.py
  tests/functional/u/unnecessary/unnecessary_dunder_call_py38.rc
  tests/functional/u/unnecessary/unnecessary_dunder_call_py38.txt
  tests/functional/u/unnecessary/unnecessary_dunder_call_py38_pypy.py
  tests/functional/u/unnecessary/unnecessary_dunder_call_py38_pypy.rc
  tests/functional/u/unnecessary/unnecessary_dunder_call_py38_pypy.txt
  tests/functional/u/unnecessary/unnecessary_dunder_call_py39.py
  tests/functional/u/unnecessary/unnecessary_dunder_call_py39.rc
  tests/functional/u/unnecessary/unnecessary_dunder_call_py39.txt
Labels: Bug :beetle:

#9055 Pyreverse: Don't show multiple class association arrows
  doc/whatsnew/fragments/9045.bugfix
  pylint/pyreverse/writer.py
  tests/pyreverse/functional/class_diagrams/aggregation/fields.mmd
Labels: Bug :beetle:, pyreverse

#9064 Bump pylint to 2.17.6, update changelog
  doc/whatsnew/2/2.17/index.rst
  doc/whatsnew/fragments/7229.bugfix
  doc/whatsnew/fragments/7710.bugfix
  doc/whatsnew/fragments/8189.bugfix
  doc/whatsnew/fragments/8522.bugfix
  doc/whatsnew/fragments/8888.bugfix
  doc/whatsnew/fragments/9014.bugfix
  pylint/__pkginfo__.py
  tbump.toml
  towncrier.toml
Labels: Maintenance

#9067 Merge maintenance into main following 2.17.6 release
  CONTRIBUTORS.txt
  README.rst
  doc/data/messages/n/non-ascii-file-name/good/__init__.py
  doc/whatsnew/2/2.17/index.rst
  doc/whatsnew/fragments/8603.bugfix
  doc/whatsnew/fragments/8613.false_positive
  tests/functional/u/unused/unused_import.py
Labels: Maintenance, Skip news :mute:

#9068 Add release note for `PYLINTRC` removal
  doc/whatsnew/fragments/8862.breaking
Labels: Documentation :green_book:

#8905 Check that a name exists inside `enum.Enum` class' `__members__`.
  doc/whatsnew/fragments/7402.false_positive
  pylint/checkers/base/name_checker/checker.py
  pylint/checkers/utils.py
  tests/functional/i/invalid/invalid_name/invalid_name_enum.py
  tests/functional/i/invalid/invalid_name/invalid_name_enum.txt
Labels: False Positive 🦟

#9075 Fix crash in refactoring checker from unaryop with variable
  doc/whatsnew/fragments/9074.bugfix
  pylint/checkers/refactoring/refactoring_checker.py
  tests/functional/r/regression/regression_9074_refactor_loop_with_unary_variable.py
  tests/functional/r/regression/regression_9074_refactor_loop_with_unary_variable.txt
Labels: Crash 💥, backport maintenance/2.17.x

#9083 [skip ci] Remove typo in README
  README.rst
Labels: Maintenance, Skip news :mute:

#9084 Bump pylint to 2.17.7, update changelog
  doc/whatsnew/2/2.17/index.rst
  doc/whatsnew/fragments/9069.false_positive
  doc/whatsnew/fragments/9074.bugfix
  pylint/__pkginfo__.py
  tbump.toml
  towncrier.toml
Labels: Maintenance

#9085 Merge maintenance 2.17.x into main
  doc/whatsnew/2/2.17/index.rst
Labels: Maintenance, Skip news :mute:
