Repository pylint-dev/pylint, pull requests merged in 2023-07, with the labels that each got.

#8809 Emit assignment-from-none for builtin methods like dict.update()
  doc/whatsnew/fragments/8714.false_negative
  pylint/checkers/typecheck.py
  tests/functional/a/assignment/assignment_from_no_return_2.py
  tests/functional/a/assignment/assignment_from_no_return_2.txt
Labels: False Negative 🦋

#8815 Remove Python 2 check in visit_call()
  pylint/checkers/typecheck.py
Labels: performance, Skip news :mute:

#8816 [Backport maintenance/2.17.x] Update typing-extensions requirement from ~=4.5 to ~=4.7
  requirements_test_min.txt
Labels: dependency

#8820 Fix cyclic import edge exclusion with `--jobs`
  pylint/checkers/imports.py
  tests/test_check_parallel.py
Labels: Bug :beetle:, Unreleased, Skip news :mute:

#8834 Exempt parents with only annotations from `invalid-enum-extension`
  doc/whatsnew/fragments/8830.false_positive
  pylint/checkers/classes/class_checker.py
  tests/functional/i/invalid/invalid_enum_extension.py
  tests/functional/i/invalid/invalid_enum_extension.txt
Labels: False Positive 🦟, backport maintenance/2.17.x

#8720 Avoid `consider-using-f-string` on modulos with brackets in template
  doc/whatsnew/fragments/8720.bugfix
  pylint/checkers/refactoring/recommendation_checker.py
  tests/functional/c/consider/consider_using_f_string.py
  tests/functional/c/consider/consider_using_f_string.txt
  tests/functional/r/regression_02/regression_8109.py
  tests/functional/r/regression_02/regression_8109.txt
Labels: False Positive 🦟, backport maintenance/2.17.x

#8836 [Backport maintenance/2.17.x] Avoid `consider-using-f-string` on modulos with brackets in template …
  doc/whatsnew/fragments/8720.bugfix
  pylint/checkers/refactoring/recommendation_checker.py
  tests/functional/c/consider/consider_using_f_string.py
  tests/functional/c/consider/consider_using_f_string.txt
  tests/functional/r/regression_02/regression_8109.py
  tests/functional/r/regression_02/regression_8109.txt
  tests/test_epylint.py
Labels: False Positive 🦟

#8837 [primer] Skip regenerate cache step for cache hits
  .github/workflows/primer_run_main.yaml
Labels: primer, Skip news :mute:

#8838 Optimize parallel runs when `cyclic-import` disabled
  pylint/checkers/imports.py
  tests/test_check_parallel.py
Labels: performance, Unreleased, Skip news :mute:

#7767 Use `Try` node
  doc/whatsnew/fragments/7767.breaking
  doc/whatsnew/fragments/7767.false_positive
  pylint/checkers/base/basic_checker.py
  pylint/checkers/base/basic_error_checker.py
  pylint/checkers/design_analysis.py
  pylint/checkers/exceptions.py
  pylint/checkers/format.py
  pylint/checkers/imports.py
  pylint/checkers/refactoring/refactoring_checker.py
  pylint/checkers/utils.py
  pylint/checkers/variables.py
  pylint/extensions/broad_try_clause.py
  pylint/extensions/mccabe.py
  pylint/extensions/overlapping_exceptions.py
  pyproject.toml
  requirements_test_min.txt
  tests/functional/a/async_functions.py
  tests/functional/a/async_functions.txt
  tests/functional/ext/broad_try_clause/broad_try_clause_extension.txt
  tests/functional/ext/mccabe/mccabe.py
  tests/functional/ext/mccabe/mccabe.txt
  tests/functional/t/too/too_many_branches.py
  tests/functional/u/used/used_before_assignment_issue2615.py
  tests/lint/unittest_lint.py
  tests/pyreverse/functional/class_diagrams/colorized_output/colorized.puml
  tests/pyreverse/functional/class_diagrams/colorized_output/custom_colors.dot
  tests/pyreverse/functional/class_diagrams/colorized_output/custom_colors.puml
Labels: Maintenance

#8840 Avoid blaming formatting commits
  .git-blame-ignore-revs
Labels: Maintenance, Skip news :mute:

#8824 Pyreverse: Use dashed lines for type-checking imports
  doc/whatsnew/fragments/8112.feature
  pylint/pyreverse/diagrams.py
  pylint/pyreverse/dot_printer.py
  pylint/pyreverse/inspector.py
  pylint/pyreverse/mermaidjs_printer.py
  pylint/pyreverse/plantuml_printer.py
  pylint/pyreverse/printer.py
  pylint/pyreverse/writer.py
  tests/pyreverse/data/classes_type_check_imports.dot
  tests/pyreverse/data/packages_type_check_imports.dot
  tests/pyreverse/functional/package_diagrams/__init__.py
  tests/pyreverse/functional/package_diagrams/type_check_imports/__init__.py
  tests/pyreverse/functional/package_diagrams/type_check_imports/mod_a.py
  tests/pyreverse/functional/package_diagrams/type_check_imports/mod_b.py
  tests/pyreverse/functional/package_diagrams/type_check_imports/mod_c.py
  tests/pyreverse/functional/package_diagrams/type_check_imports/mod_d.py
  tests/pyreverse/functional/package_diagrams/type_check_imports/packages.mmd
  tests/pyreverse/test_writer.py
Labels: Enhancement ✨, pyreverse

#8819 Observe specific enables/disables even if followed by "all"
  doc/whatsnew/fragments/3696.breaking
  pylint/config/config_initialization.py
  tests/config/functional/toml/toml_with_mutually_exclusive_disable_enable_all.toml
  tests/config/functional/toml/toml_with_specific_disable_before_enable_all.toml
  tests/config/functional/toml/toml_with_specific_enable_before_disable_all.toml
  tests/config/test_config.py
  tests/config/test_functional_config_loading.py
  tests/regrtest_data/fixme.py
  tests/test_self.py
Labels: Configuration, Breaking changes for 3.0 🦤

#8839 Fix crash from unexpected assignment
  doc/whatsnew/fragments/8754.bugfix
  pylint/checkers/variables.py
  tests/functional/u/used/used_before_assignment.py
Labels: Crash 💥, backport maintenance/2.17.x

#8843 [Backport maintenance/2.17.x] Fix crash from unexpected assignment (#8839)
  doc/whatsnew/fragments/8754.bugfix
  pylint/checkers/variables.py
  tests/functional/u/used/used_before_assignment.py
Labels: Crash 💥

#8847 docs: Fix typo in implicit booleaness checker description.
  doc/user_guide/checkers/features.rst
  pylint/checkers/refactoring/implicit_booleaness_checker.py
Labels: Documentation :green_book:, Skip news :mute:

#8849 Bump astroid to 2.15.6 on maintenance branch
  pyproject.toml
  requirements_test_min.txt
Labels: Skip news :mute:

#8850 Spruce up 3.0 changelog fragments
  doc/whatsnew/fragments/1954.performance
  doc/whatsnew/fragments/6306.breaking
  doc/whatsnew/fragments/6871.user_action
  doc/whatsnew/fragments/8411.user_action
  doc/whatsnew/fragments/8412.internal
  doc/whatsnew/fragments/8433.internal
  doc/whatsnew/fragments/8462.breaking
  doc/whatsnew/fragments/8463.internal
  doc/whatsnew/fragments/8465.user_action
  doc/whatsnew/fragments/8475.internal
Labels: Documentation :green_book:, Skip news :mute:

#8851 Fix type annotation
  pylint/checkers/refactoring/refactoring_checker.py
Labels: typing, Unreleased, Skip news :mute:

#8856 Add stdlib deprecations from 3.12
  pylint/checkers/stdlib.py
  tests/functional/t/try_except_raise_crash.py
Labels: Enhancement ✨, Maintenance, Skip news :mute:

#8861 CI: exclude linting dependencies from the unittest environment.
  .github/workflows/checks.yaml
  .github/workflows/primer_run_pr.yaml
  requirements_test.txt
Labels: performance, Maintenance, Skip news :mute:

#8873 Bump dill to 0.3.7 on Python 3.12
  pyproject.toml
Labels: Maintenance, Skip news :mute:, python 3.12

#8877 Documentation - Update `unnecessary-pass`
  doc/data/messages/u/unnecessary-pass/bad.py
  doc/data/messages/u/unnecessary-pass/good.py
  doc/user_guide/checkers/features.rst
  pylint/checkers/base/pass_checker.py
Labels: Documentation :green_book:, Skip news :mute:

#8884 Remove carriage returns from doc file.
  doc/data/messages/t/too-many-lines/good/__init__.py
Labels: Documentation :green_book:, Skip news :mute:, backport maintenance/2.17.x

#8887 Release branch for 2.17.5
  CONTRIBUTORS.txt
  doc/user_guide/configuration/all-options.rst
  doc/whatsnew/2/2.17/index.rst
  doc/whatsnew/fragments/8554.bugfix
  doc/whatsnew/fragments/8598.bugfix
  doc/whatsnew/fragments/8696.false_positive
  doc/whatsnew/fragments/8698.bugfix
  doc/whatsnew/fragments/8719.false_positive
  doc/whatsnew/fragments/8720.bugfix
  doc/whatsnew/fragments/8735.other
  doc/whatsnew/fragments/8740.bugfix
  doc/whatsnew/fragments/8747.false_positive
  doc/whatsnew/fragments/8754.bugfix
  doc/whatsnew/fragments/8774.bugfix
  doc/whatsnew/fragments/8830.false_positive
  pylint/__pkginfo__.py
  tbump.toml
  towncrier.toml
Labels: Maintenance

#8898 Ignore quantifiers when splitting comma-separated regexes
  doc/whatsnew/fragments/7229.bugfix
  pylint/config/argument.py
  pylint/utils/__init__.py
  pylint/utils/utils.py
  tests/config/test_config.py
Labels: Bug :beetle:, Configuration, backport maintenance/2.17.x

#8878 Avoid editable installs on CI
  .github/workflows/checks.yaml
  .github/workflows/primer-test.yaml
  .github/workflows/primer_run_main.yaml
  .github/workflows/primer_run_pr.yaml
  .github/workflows/tests.yaml
  doc/development_guide/contributor_guide/tests/install.rst
  pyproject.toml
  requirements_test_min.txt
  tests/test_check_parallel.py
Labels: tests, Skip news :mute:

#8902 [coverage] Invoke pytest as `python -m pytest` to restore coverage
  .github/workflows/tests.yaml
  doc/conf.py
Labels: Maintenance, Skip news :mute:
