Repository pylint-dev/pylint, pull requests merged in 2023-03, with the labels that each got.

#8312 Support globbing pattern for input specification
  .pyenchant_pylint_custom_dict.txt
  doc/user_guide/usage/run.rst
  doc/whatsnew/fragments/8310.feature
  pylint/config/config_initialization.py
  tests/lint/unittest_lint.py
  tests/test_self.py
Labels: Enhancement ✨

#8362 Changing flake8 to have max-line-length of 115
  examples/deprecation_checker.py
  pylint/checkers/base/basic_checker.py
  pylint/checkers/utils.py
  pylint/config/arguments_provider.py
  pylint/config/config_initialization.py
  pylint/extensions/confusing_elif.py
  pylint/extensions/typing.py
  pylint/lint/run.py
  pylint/reporters/text.py
  pylint/testutils/_primer/primer_compare_command.py
  pylint/testutils/lint_module_test.py
  setup.cfg
  tests/message/unittest_message_definition_store.py
Labels: Maintenance, Skip news :mute:

#8370 [spelling] Ignore spelling in type/mypy type ignore comments
  doc/whatsnew/fragments/8370.false_positive
  pylint/checkers/spelling.py
  tests/checkers/unittest_spelling.py
Labels: False Positive 🦟, backport maintenance/2.16.x

#8372 [pre-commit] Transition from flake8/autoflake to ruff
  .pre-commit-config.yaml
  doc/data/ruff.toml
  pylint/config/config_initialization.py
  pyproject.toml
  setup.cfg
Labels: Maintenance, Skip news :mute:

#8375 Bump pylint to 2.16.3, update changelog
  doc/whatsnew/2/2.16/index.rst
  doc/whatsnew/fragments/8307.bugfix
  doc/whatsnew/fragments/8370.false_positive
  pylint/__pkginfo__.py
  tbump.toml
  towncrier.toml
Labels: Maintenance

#8364 Accept values of the form ``<class name>.<attribute name>`` for the `exclude-protected` list
  doc/whatsnew/fragments/7343.feature
  pylint/checkers/classes/class_checker.py
  tests/functional/p/protected_access.py
  tests/functional/p/protected_access.rc
  tests/functional/p/protected_access.txt
Labels: Enhancement ✨

#8377 Merge maintenance 2.16.x in main
  doc/whatsnew/2/2.16/index.rst
Labels: Maintenance, Skip news :mute:

#8380 Document ignoring pragmas for calculating line length
  doc/data/messages/l/line-too-long/details.rst
Labels: Documentation :green_book:, Skip news :mute:

#8382 Cancel previous tests when pushing to PRs
  .github/workflows/codeql-analysis.yml
  .github/workflows/tests.yaml
Labels: Maintenance, Skip news :mute:

#8386 [Backport maintenance/2.16.x] Fix invalid type false positive (#8206)
  doc/whatsnew/fragments/8205.false_positive
  pylint/checkers/typecheck.py
  pylint/constants.py
  tests/functional/d/dataclass/dataclass_typecheck.txt
  tests/functional/ext/typing/redundant_typehint_argument.py
  tests/functional/i/isinstance_second_argument.txt
  tests/functional/i/isinstance_second_argument_py310.py
  tests/functional/i/isinstance_second_argument_py310.rc
  tests/functional/i/isinstance_second_argument_py310.txt
Labels: False Positive 🦟

#8389 Bump pylint to 2.16.4, update changelog
  doc/whatsnew/2/2.16/index.rst
  doc/whatsnew/fragments/8205.false_positive
  pylint/__pkginfo__.py
  tbump.toml
  towncrier.toml
Labels: Maintenance

#8387 Upgrade to astroid 2.15.0
  doc/whatsnew/fragments/8387.feature
  pylint/checkers/imports.py
  pylint/checkers/typecheck.py
  pylint/pyreverse/inspector.py
  pylint/pyreverse/writer.py
  pyproject.toml
  requirements_test_min.txt
Labels: Maintenance

#8384 Use ``UninferableBase`` instead of ``Uninferable``
  pylint/checkers/async.py
  pylint/checkers/base/basic_checker.py
  pylint/checkers/classes/class_checker.py
  pylint/checkers/classes/special_methods_checker.py
  pylint/checkers/dunder_methods.py
  pylint/checkers/exceptions.py
  pylint/checkers/refactoring/implicit_booleaness_checker.py
  pylint/checkers/refactoring/refactoring_checker.py
  pylint/checkers/stdlib.py
  pylint/checkers/strings.py
  pylint/checkers/typecheck.py
  pylint/checkers/utils.py
  pylint/checkers/variables.py
  pylint/extensions/_check_docs_utils.py
  pylint/extensions/overlapping_exceptions.py
  pylint/pyreverse/diagrams.py
  pylint/pyreverse/inspector.py
Labels: Needs astroid update, Skip news :mute:

#8385 Add regression test for #5288
  doc/whatsnew/fragments/5288.false_positive
  tests/functional/u/unpacking/unpacking_non_sequence_py310.py
  tests/functional/u/unpacking/unpacking_non_sequence_py310.rc
Labels: Maintenance, Skip news :mute:

#8395 Bump pylint to 2.17.0, update changelog
  CONTRIBUTORS.txt
  doc/user_guide/checkers/features.rst
  doc/user_guide/configuration/all-options.rst
  doc/user_guide/messages/messages_overview.rst
  doc/whatsnew/2/2.17/index.rst
  doc/whatsnew/fragments/5073.other
  doc/whatsnew/fragments/5288.false_positive
  doc/whatsnew/fragments/6559.new_check
  doc/whatsnew/fragments/6738.feature
  doc/whatsnew/fragments/7081.feature
  doc/whatsnew/fragments/7343.feature
  doc/whatsnew/fragments/7574.false_positive
  doc/whatsnew/fragments/7851.feature
  doc/whatsnew/fragments/7957.feature
  doc/whatsnew/fragments/8102.new_check
  doc/whatsnew/fragments/8125.bugfix
  doc/whatsnew/fragments/8148.bugfix
  doc/whatsnew/fragments/8154.feature
  doc/whatsnew/fragments/8161.bugfix
  doc/whatsnew/fragments/8168.bugfix
  doc/whatsnew/fragments/8185.false_negative
  doc/whatsnew/fragments/8205.false_positive
  doc/whatsnew/fragments/8207.bugfix
  doc/whatsnew/fragments/8252.false_positive
  doc/whatsnew/fragments/8280.false_negative
  doc/whatsnew/fragments/8290.feature
  doc/whatsnew/fragments/8307.bugfix
  doc/whatsnew/fragments/8310.feature
  doc/whatsnew/fragments/8329.other
  doc/whatsnew/fragments/8370.false_positive
  doc/whatsnew/fragments/8387.feature
  examples/pylintrc
  examples/pyproject.toml
  pylint/__pkginfo__.py
  pylint/checkers/refactoring/refactoring_checker.py
  pylint/checkers/unicode.py
  script/.contributors_aliases.json
  tbump.toml
Labels: Maintenance, Skip news :mute:

#8399 [release documentation] Upgrade for post release branch deletion
  doc/development_guide/contributor_guide/release.md
  doc/whatsnew/3/index.rst
Labels: Documentation :green_book:, Maintenance, Skip news :mute:

#8400 [deprecation] epylint removal for pylint 3.0.0
  doc/development_guide/api/epylint.rst
  doc/development_guide/api/index.rst
  doc/user_guide/installation/ide_integration/flymake-emacs.rst
  doc/whatsnew/fragments/7737.user_action
  pylint/__init__.py
  pylint/epylint.py
  pyproject.toml
  tests/test_epylint.py
  tests/test_pylint_runners.py
Labels: Breaking changes for 3.0 🦤, Maintenance

#8401 [deprecation] Remove ``get_message_definitions`` from ``BaseChecker``
  doc/whatsnew/fragments/8401.breaking
  pylint/checkers/base_checker.py
  tests/checkers/unittest_base_checker.py
Labels: Breaking changes for 3.0 🦤, Maintenance

#8402 Add and expose ``py.typed``
  doc/whatsnew/fragments/5488.other
  pylint/py.typed
  pyproject.toml
Labels: typing

#8405 Remove all old code related to ``optparse`` config parsing.
  doc/exts/pylint_extensions.py
  doc/whatsnew/fragments/8405.other
  pylint/checkers/base_checker.py
  pylint/config/__init__.py
  pylint/config/_pylint_config/generate_command.py
  pylint/config/arguments_manager.py
  pylint/config/arguments_provider.py
  pylint/config/callback_actions.py
  pylint/config/configuration_mixin.py
  pylint/config/environment_variable.py
  pylint/config/find_default_config_files.py
  pylint/config/option.py
  pylint/config/option_manager_mixin.py
  pylint/config/option_parser.py
  pylint/config/options_provider_mixin.py
  pylint/config/utils.py
  pylint/lint/pylinter.py
  pylint/lint/utils.py
  pylint/utils/docs.py
  script/get_unused_message_id_category.py
  tests/config/test_deprecations.py
  tests/config/test_find_default_config_files.py
  tests/config/unittest_config.py
  tests/lint/test_pylinter.py
  tests/lint/unittest_lint.py
  tests/test_check_parallel.py
  tests/test_deprecation.py
Labels: Breaking changes for 3.0 🦤, Maintenance

#8404 [__implements__] Remove everything related to the rejected PEP245
  doc/symilar.rst
  doc/whatsnew/fragments/8404.breaking
  pylint/checkers/base_checker.py
  pylint/interfaces.py
  pylint/lint/pylinter.py
  pylint/pyreverse/diagrams.py
  pylint/pyreverse/inspector.py
  pylint/reporters/base_reporter.py
  tests/data/clientmodule_test.py
  tests/pyreverse/data/classes_No_Name.dot
  tests/pyreverse/data/classes_No_Name.html
  tests/pyreverse/data/classes_No_Name.mmd
  tests/pyreverse/data/classes_No_Name.puml
  tests/pyreverse/data/classes_No_Name.vcg
  tests/pyreverse/data/classes_colorized.dot
  tests/pyreverse/data/classes_colorized.puml
  tests/pyreverse/test_diadefs.py
  tests/pyreverse/test_inspector.py
  tests/test_deprecation.py
  tests/test_self.py
Labels: Breaking changes for 3.0 🦤, Maintenance

#8409 Remove deprecated functions and classes
  doc/whatsnew/fragments/8409.breaking
  pylint/checkers/__init__.py
  pylint/checkers/mapreduce_checker.py
  pylint/checkers/utils.py
  pylint/lint/__init__.py
  pylint/lint/expand_modules.py
  pylint/lint/utils.py
  pylint/testutils/functional_test_file.py
  pylint/utils/__init__.py
  pylint/utils/utils.py
  tests/checkers/unittest_utils.py
  tests/config/test_deprecations.py
  tests/lint/unittest_lint.py
  tests/test_deprecation.py
Labels: Maintenance

#8414 `pyreverse`: remove remaining code parts related to `__implements__`
  pylint/pyreverse/diagrams.py
  pylint/pyreverse/dot_printer.py
  pylint/pyreverse/inspector.py
  pylint/pyreverse/mermaidjs_printer.py
  pylint/pyreverse/plantuml_printer.py
  pylint/pyreverse/printer.py
  pylint/pyreverse/utils.py
  pylint/pyreverse/vcg_printer.py
  pylint/pyreverse/writer.py
Labels: pyreverse, Maintenance, Skip news :mute:

#8417 Removing files from coveragerc since they have been deleted
  .coveragerc
Labels: Maintenance, Skip news :mute:

#8412 [colorize_ansi] Remove the possibility to use anything else than a MessageStyle
  doc/whatsnew/fragments/8412.breaking
  pylint/reporters/text.py
Labels: Breaking changes for 3.0 🦤, Maintenance

#8422 [release doc] Add a paragraph for label maintenance
  doc/development_guide/contributor_guide/release.md
Labels: Maintenance, Skip news :mute:

#8190 pyreverse: Add show-stdlib option
  doc/whatsnew/fragments/8181.breaking
  pylint/pyreverse/diadefslib.py
  pylint/pyreverse/main.py
  pylint/testutils/pyreverse.py
  tests/pyreverse/test_diadefs.py
  tests/pyreverse/test_main.py
  tests/pyreverse/test_writer.py
Labels: Enhancement ✨, pyreverse

#8420 Clear LRU caches on pylint utilities
  doc/whatsnew/fragments/8361.bugfix
  pylint/checkers/utils.py
  pylint/lint/run.py
Labels: Bug :beetle:, backport maintenance/2.17.x

#8426 `pyreverse`: drop support for `.vcg` format
  doc/pyreverse.rst
  doc/whatsnew/fragments/8416.breaking
  pylint/pyreverse/main.py
  pylint/pyreverse/printer_factory.py
  pylint/pyreverse/vcg_printer.py
  pylint/pyreverse/writer.py
  tests/pyreverse/conftest.py
  tests/pyreverse/data/classes_No_Name.vcg
  tests/pyreverse/data/packages_No_Name.vcg
  tests/pyreverse/test_printer.py
  tests/pyreverse/test_printer_factory.py
  tests/pyreverse/test_writer.py
Labels: pyreverse, Breaking changes for 3.0 🦤

#8415 `pyreverse`: use colorblind friendly default colors
  .pyenchant_pylint_custom_dict.txt
  doc/whatsnew/fragments/8251.breaking
  pylint/pyreverse/main.py
  pylint/pyreverse/plantuml_printer.py
  tests/pyreverse/data/classes_colorized.dot
  tests/pyreverse/data/classes_colorized.puml
  tests/pyreverse/data/packages_colorized.dot
  tests/pyreverse/data/packages_colorized.puml
  tests/pyreverse/functional/class_diagrams/colorized_output/colorized.puml
  tests/pyreverse/functional/class_diagrams/colorized_output/custom_colors.dot
  tests/pyreverse/functional/class_diagrams/colorized_output/custom_colors.puml
  tests/pyreverse/functional/class_diagrams/colorized_output/custom_colors.rc
Labels: pyreverse, Breaking changes for 3.0 🦤

#8435 Fix a crash when `TYPE_CHECKING` is used without importing it
  doc/whatsnew/fragments/8434.bugfix
  pylint/checkers/utils.py
  tests/checkers/unittest_utils.py
Labels: Crash 💥, backport maintenance/2.17.x

#8403 Add Python 3.8+ `asyncSetUp` to "defining-attr-methods" list
  doc/user_guide/configuration/all-options.rst
  doc/whatsnew/fragments/8403.false_positive
  examples/pylintrc
  examples/pyproject.toml
  pylint/checkers/classes/class_checker.py
  tests/functional/a/attribute_defined_outside_init_py38.py
  tests/functional/a/attribute_defined_outside_init_py38.rc
Labels: False Positive 🦟, backport maintenance/2.17.x

#8433 Deprecate redundant type checking guard utils
  doc/whatsnew/fragments/8433.internal
  pylint/checkers/imports.py
  pylint/checkers/utils.py
  pylint/checkers/variables.py
  pylint/extensions/private_import.py
  tests/checkers/unittest_utils.py
Labels: Maintenance, backport maintenance/2.17.x

#8442 Increase new primer timeout to 120m
  .github/workflows/primer_run_main.yaml
Labels: Maintenance, primer, Skip news :mute:

#8448 [cyclic-import] Break cycle between pylint.checkers.util / variables
  pylint/checkers/utils.py
  pylint/checkers/variables.py
Labels: Maintenance, Skip news :mute:

#8449 [pre-commit] Add ruff specific rules in ruff configuration
  pylint/checkers/base/basic_checker.py
  pylint/checkers/stdlib.py
  pylint/checkers/typecheck.py
  pylint/checkers/utils.py
  pylint/checkers/variables.py
  pylint/config/find_default_config_files.py
  pylint/lint/expand_modules.py
  pylint/lint/parallel.py
  pylint/lint/pylinter.py
  pylint/reporters/ureports/nodes.py
  pyproject.toml
  tests/checkers/unittest_format.py
  tests/lint/unittest_lint.py
  tests/primer/test_primer_external.py
  tests/primer/test_primer_stdlib.py
  tests/test_func.py
  tests/test_self.py
  tests/testutils/_primer/test_package_to_lint.py
  tests/testutils/_primer/test_primer.py
Labels: Maintenance, Skip news :mute:

#8447 Add some documentation examples
  doc/data/messages/b/bad-file-encoding/bad.py
  doc/data/messages/b/bad-file-encoding/details.rst
  doc/data/messages/b/bad-file-encoding/good.py
  doc/data/messages/i/invalid-unicode-codec/details.rst
  doc/data/messages/i/invalid-unicode-codec/good.py
  doc/data/messages/r/return-arg-in-generator/details.rst
  doc/data/messages/r/return-arg-in-generator/good.py
Labels: Documentation :green_book:, Skip news :mute:

#8461 [cleanup] Remove the script for checking changelog
  .pre-commit-config.yaml
  script/fix_documentation.py
Labels: Maintenance, Skip news :mute:

#8463 [deprecation] 'Pylinter.check' now takes sequence of str only
  doc/whatsnew/fragments/8463.internal
  pylint/lint/pylinter.py
  tests/lint/test_pylinter.py
Labels: Maintenance

#8464 [deprecation] 'ColorizedTextReporter' only accepts 'ColorMappingDict'
  doc/whatsnew/fragments/8464.internal
  pylint/reporters/text.py
Labels: Maintenance

#8466 [deprecation] end_line and end_col_offset required in functional tests
  doc/whatsnew/fragments/8465.user_action
  doc/whatsnew/fragments/8466.internal
  pylint/testutils/checker_test_case.py
Labels: Maintenance

#8467 Remove some useless assertions in pylint 3.0
  pylint/lint/pylinter.py
Labels: Maintenance, Skip news :mute:

#8468 [test] Remove 'test_pylint_config_attr'
  tests/test_regr.py
Labels: Maintenance, Skip news :mute:

#8470 [test multiprocessing] Add regression test against removing dill for unpickable plugins
  tests/test_check_parallel.py
Labels: Maintenance, Skip news :mute:

#8473 [deprecation] Make 'py_version' required for 'MessageDefinition.may_be_emitted'
  doc/whatsnew/fragments/8473.internal
  pylint/message/message_definition.py
Labels: Maintenance

#8472 [deprecation] Remove 'do_exit' from the 'Run' constructor
  doc/whatsnew/fragments/8472.internal
  pylint/lint/run.py
  pylint/testutils/_run.py
Labels: Maintenance

#8477 [deprecation] Message.location must be a 'MessageLocationTuple'
  doc/whatsnew/fragments/8477.internal
  pylint/message/message.py
Labels: Maintenance

#8454 Fix incorrect preferred-modules matches
  doc/whatsnew/fragments/8453.bugfix
  pylint/checkers/imports.py
  tests/checkers/unittest_imports.py
Labels: Regression, backport maintenance/2.17.x

#8480 Upgrade TODO from pylint 2.x to pylint 3.0
  pylint/checkers/variables.py
  pylint/reporters/json_reporter.py
  pylint/testutils/functional/test_file.py
Labels: Maintenance, Skip news :mute:

#8475 [deprecation] Remove all duplicated typing guard check functions
  doc/whatsnew/fragments/8475.internal
  pylint/checkers/utils.py
  tests/checkers/unittest_utils.py
Labels: Maintenance

#8482 Bump pylint to 2.17.1, update changelog
  doc/whatsnew/2/2.17/index.rst
  doc/whatsnew/fragments/8361.bugfix
  doc/whatsnew/fragments/8403.false_positive
  doc/whatsnew/fragments/8433.internal
  doc/whatsnew/fragments/8434.bugfix
  doc/whatsnew/fragments/8453.bugfix
  pylint/__pkginfo__.py
  tbump.toml
  towncrier.toml
Labels: Maintenance

#8483 Merge maintenance 2.17.x in main following 2.17.1 release
  doc/whatsnew/2/2.17/index.rst
  towncrier.toml
Labels: Maintenance, Skip news :mute:

#8489 Don't consider ``Union`` to always be a type alias
  doc/whatsnew/fragments/8487.false_positive
  pylint/checkers/base/name_checker/checker.py
  tests/functional/t/typealias_naming_style_default.py
Labels: False Positive 🦟, backport maintenance/2.17.x

#8493 Fix typos in README.rst
  README.rst
Labels: Documentation :green_book:, Skip news :mute:

#8498 Fix `unnecessary-lambda` false positive for lambdas using its parameters in their body
  doc/whatsnew/fragments/8496.false_positive
  pylint/checkers/base/basic_checker.py
  tests/functional/u/unnecessary/unnecessary_lambda.py
  tests/functional/u/unnecessary/unnecessary_lambda.txt
Labels: False Positive 🦟, backport maintenance/2.17.x

#8474 [deprecation] Make 'OutputLine' require a fixed number of args
  doc/whatsnew/fragments/8474.internal
  pylint/testutils/output_line.py
  tests/testutils/test_output_line.py
Labels: Maintenance

#8488 Allow integers in TypeAlias names.
  doc/data/messages/i/invalid-name/details.rst
  doc/whatsnew/fragments/8485.false_positive
  pylint/checkers/base/name_checker/checker.py
  tests/functional/t/typealias_naming_style_default.py
  tests/functional/t/typealias_naming_style_default.txt
Labels: False Positive 🦟, backport maintenance/2.17.x

#8508 Fix news fragment after incorrect auto-merge
  doc/whatsnew/fragments/8485.false_positive
Labels: Skip news :mute:

#8519 [doc] Fix missing spaces in 2.13's whatsnew
  doc/whatsnew/2/2.13/summary.rst
Labels: Documentation :green_book:, Skip news :mute:
