Repository pylint-dev/pylint, pull requests merged in 2023-05, with the labels that each got.

#8648 [Doc] Create implicit-str-concat/details.rst
  doc/data/messages/i/implicit-str-concat/details.rst
Labels: Documentation :green_book:, Skip news :mute:

#8649 [Doc] Improving implicit-str-concat/details.rst
  doc/data/messages/i/implicit-str-concat/details.rst
  doc/data/messages/i/implicit-str-concat/related.rst
Labels: Documentation :green_book:, Skip news :mute:

#8653 Upgrade 'tox - docs' to match readthedoc online and for performance
  doc/whatsnew/3/3.0/index.rst
  doc/whatsnew/3/index.rst
  tox.ini
Labels: Documentation :green_book:, Skip news :mute:

#8661 [Doc] Minor fixup in launching_test.rst
  doc/development_guide/contributor_guide/tests/launching_test.rst
Labels: Documentation :green_book:, Skip news :mute:

#8665 Merge maintenance 2.17.x in main
  doc/whatsnew/2/2.17/index.rst
  doc/whatsnew/fragments/8632.bugfix
  tests/pyreverse/data/classes_No_Name.vcg
  tests/pyreverse/data/packages_No_Name.vcg
Labels: Maintenance, Skip news :mute:

#8676 Primer - remove `.git` suffix from github URL.
  tests/primer/packages_to_prime.json
Labels: Maintenance, primer, Skip news :mute:

#8678 Fix crash when deleting from a dict returned from a call
  doc/whatsnew/fragments/8598.bugfix
  pylint/checkers/modified_iterating_checker.py
  tests/functional/m/modified_iterating.py
  tests/functional/m/modified_iterating.txt
Labels: Crash 💥, backport maintenance/2.17.x

#8683 Load custom plugins when linting in parallel
  doc/user_guide/usage/run.rst
  doc/whatsnew/fragments/4874.bugfix
  pylint/lint/parallel.py
  pylint/lint/pylinter.py
  tests/test_check_parallel.py
Labels: multiprocessing

#8684 Regression fix for `unused-variable` false negative
  pylint/checkers/variables.py
  tests/functional/u/unused/unused_variable.py
  tests/functional/u/unused/unused_variable.txt
Labels: False Negative 🦋, Unreleased, Skip news :mute:

#8644 Add new checker `kwarg-superseded-by-positional-arg` and fix a false positive
  doc/data/messages/k/kwarg-superseded-by-positional-arg/bad.py
  doc/data/messages/k/kwarg-superseded-by-positional-arg/good.py
  doc/whatsnew/fragments/8558.feature
  pylint/checkers/typecheck.py
  tests/functional/a/arguments.py
  tests/functional/a/arguments.txt
  tests/functional/a/arguments_positional_only.py
  tests/functional/a/arguments_positional_only.rc
  tests/functional/a/arguments_positional_only.txt
  tests/functional/k/kwarg_superseded_by_positional_arg.py
  tests/functional/k/kwarg_superseded_by_positional_arg.txt
  tests/functional/p/positional_only_arguments_expected.py
Labels: Enhancement ✨, False Positive 🦟

#8699 Fix crash in `invalid-metaclass` check
  doc/whatsnew/fragments/8698.bugfix
  pylint/checkers/typecheck.py
  tests/functional/i/invalid/invalid_metaclass.py
  tests/functional/i/invalid/invalid_metaclass.txt
Labels: Crash 💥, backport maintenance/2.17.x

#8702 Avoid duplicate overgeneral-exceptions warnings with ``--jobs``
  doc/whatsnew/fragments/7774.bugfix
  pylint/checkers/exceptions.py
  pylint/config/config_initialization.py
Labels: Bug :beetle:, multiprocessing

#8697 [primer] Parallelize primer workflow into package batches
  .github/workflows/primer_comment.yaml
  .github/workflows/primer_run_main.yaml
  .github/workflows/primer_run_pr.yaml
  pylint/testutils/_primer/primer.py
  pylint/testutils/_primer/primer_compare_command.py
  pylint/testutils/_primer/primer_run_command.py
  tests/testutils/_primer/fixtures/batched/expected.txt
  tests/testutils/_primer/fixtures/batched/main_batch0.json
  tests/testutils/_primer/fixtures/batched/main_batch1.json
  tests/testutils/_primer/fixtures/batched/pr_batch0.json
  tests/testutils/_primer/fixtures/batched/pr_batch1.json
  tests/testutils/_primer/test_primer.py
Labels: primer, Skip news :mute:

#8126 feat(5159): add new checker `invalid-field-call`
  .pyenchant_pylint_custom_dict.txt
  doc/data/messages/i/invalid-field-call/bad.py
  doc/data/messages/i/invalid-field-call/good.py
  doc/user_guide/checkers/features.rst
  doc/user_guide/messages/messages_overview.rst
  doc/whatsnew/fragments/5159.new_check
  pylint/checkers/dataclass_checker.py
  tests/functional/d/dataclass/dataclass_with_default_factory.py
  tests/functional/d/dataclass/dataclass_with_default_factory.txt
  tests/functional/i/invalid/invalid_field_call.py
  tests/functional/i/invalid/invalid_field_call.rc
  tests/functional/i/invalid/invalid_field_call.txt
  tests/functional/n/no/no_member_dataclasses.py
Labels: Enhancement ✨, Checkers

#8708 Docs: optparse not removed in Python 3.12
  doc/whatsnew/2/2.14/summary.rst
Labels: Documentation :green_book:, Skip news :mute:

#8706 Manage PR/Issues that are stale automatically
  .github/workflows/stale.yml
Labels: Maintenance, Skip news :mute:

#8440 add checker for return in finally
  doc/data/messages/r/return-in-finally/bad.py
  doc/data/messages/r/return-in-finally/good.py
  doc/data/messages/r/return-in-finally/related.rst
  doc/whatsnew/fragments/8260.new_check
  pylint/checkers/base/basic_checker.py
  tests/functional/l/lost_exception.py
  tests/functional/r/return_in_finally.py
  tests/functional/r/return_in_finally.txt
Labels: Enhancement ✨, Control flow

#8710 [stale action] The expected value is a comma separated string
  .github/workflows/stale.yml
Labels: Maintenance, Skip news :mute:

#8707 [config] Make the linter optional during config parsing
  pylint/config/config_file_parser.py
Labels: Maintenance, Skip news :mute:

#8717 CI: Only run stale cron on upstream
  .github/workflows/codeql-analysis.yml
  .github/workflows/stale.yml
Labels: Maintenance, Skip news :mute:

#8721 Extend test cases for 'condition-evals-to-constant'
  tests/functional/c/condition_evals_to_constant.py
  tests/functional/c/condition_evals_to_constant.txt
Labels: Maintenance, Skip news :mute:
