Repository pylint-dev/pylint, pull requests merged in 2023-08, with the labels that each got.

#8915 Remove duplicate fragment
  doc/whatsnew/fragments/8558.feature
Labels: Documentation :green_book:, Skip news :mute:

#8921 Fix news fragment indentation
  doc/whatsnew/fragments/2018.user_action
  towncrier.toml
Labels: Documentation :green_book:, Skip news :mute:

#8904 Add setuptools to test dependencies
  requirements_test_min.txt
Labels: Bug :beetle:, tests, Skip news :mute:

#8872 Add compatibility with astroid inference cache changes
  doc/requirements.txt
  doc/whatsnew/fragments/529.performance
  pylint/checkers/design_analysis.py
  pylint/checkers/typecheck.py
  pyproject.toml
  requirements_test_min.txt
Labels: Skip news :mute:

#8931 Fix invocation of tests on pypy
  .github/workflows/tests.yaml
Labels: tests, Skip news :mute:

#8846 Rename `unneeded-not` to `unnecessary-negation` for clarity
  doc/data/messages/u/unnecessary-negation/bad.py
  doc/data/messages/u/unnecessary-negation/good.py
  doc/data/messages/u/unneeded-not/bad.py
  doc/data/messages/u/unneeded-not/good.py
  doc/whatsnew/fragments/8789.other
  pylint/checkers/refactoring/not_checker.py
  tests/functional/u/unnecessary/unnecessary_negation.py
  tests/functional/u/unnecessary/unnecessary_negation.txt
  tests/functional/u/unnecessary/unnecessary_not.txt
Labels: Enhancement ✨

#8932 Restore editable_mode=compat analogue
  pyproject.toml
Labels: Maintenance, Beta-Blocker 🙅🩸, Skip news :mute:

#8942 Add a tbump step to automatically normalize line ending
  doc/user_guide/checkers/features.rst
  tbump.toml
Labels: Maintenance, Skip news :mute:

#8945 [anomalous-backslash-in-string] More details in documentation
  doc/data/messages/a/anomalous-backslash-in-string/details.rst
  doc/data/messages/a/anomalous-backslash-in-string/good/double_escape.py
  doc/data/messages/a/anomalous-backslash-in-string/good/existing_escape_sequence.py
  doc/data/messages/a/anomalous-backslash-in-string/good/r_prefix.py
  doc/data/messages/a/anomalous-backslash-in-string/related.rst
Labels: Documentation :green_book:, Skip news :mute:

#8927 Fix false positive for ``arguments-differ``
  doc/whatsnew/fragments/8919.false_positive
  pylint/checkers/classes/class_checker.py
  tests/functional/a/arguments_differ.py
Labels: False Positive 🦟

#8949 Add the possible choices in the generated toml doc
  doc/exts/pylint_options.py
  doc/user_guide/configuration/all-options.rst
Labels: Documentation :green_book:, Skip news :mute:

#8956 [base checker] Fix the ordering of checkers for extensions
  pylint/checkers/base_checker.py
  tests/checkers/unittest_base_checker.py
Labels: Maintenance, Skip news :mute:

#6736 [doc] Add a CI check for the doc being properly generated
  .github/workflows/checks.yaml
  .pre-commit-config.yaml
  doc/development_guide/contributor_guide/tests/install.rst
Labels: Documentation :green_book:, Maintenance, Skip news :mute:

#8929 Add new JSON reporter
  .pyenchant_pylint_custom_dict.txt
  doc/user_guide/configuration/all-options.rst
  doc/whatsnew/3/3.0/index.rst
  doc/whatsnew/fragments/4741.feature
  pylint/interfaces.py
  pylint/lint/base_options.py
  pylint/reporters/__init__.py
  pylint/reporters/json_reporter.py
  pylint/testutils/_primer/primer_run_command.py
  tests/reporters/unittest_json_reporter.py
  tests/reporters/unittest_reporting.py
  tests/test_self.py
Labels: Enhancement ✨

#8961 Unpin setuptools build dependency
  pyproject.toml
Labels: Maintenance, Skip news :mute:

#8964 Fix false negative for `consider-using-augmented-assign` on dicts/lists
  doc/whatsnew/fragments/8959.false_negative
  pylint/checkers/utils.py
  tests/functional/ext/code_style/cs_consider_using_augmented_assign.py
  tests/functional/ext/code_style/cs_consider_using_augmented_assign.txt
Labels: False Negative 🦋

#8974 Pyreverse: print package import stats
  doc/whatsnew/fragments/8973.user_action
  pylint/pyreverse/inspector.py
  pylint/pyreverse/main.py
  pylint/pyreverse/writer.py
  tests/pyreverse/conftest.py
  tests/pyreverse/test_main.py
Labels: Enhancement ✨, pyreverse

#8983 Add tests for existing Pyreverse bugs
  pylint/pyreverse/diagrams.py
  tests/pyreverse/functional/class_diagrams/annotations/line_breaks.dot
  tests/pyreverse/functional/class_diagrams/annotations/line_breaks.mmd
  tests/pyreverse/functional/class_diagrams/annotations/line_breaks.puml
  tests/pyreverse/functional/class_diagrams/annotations/line_breaks.py
  tests/pyreverse/functional/class_diagrams/annotations/line_breaks.rc
  tests/pyreverse/functional/class_diagrams/attributes/duplicates.mmd
  tests/pyreverse/functional/class_diagrams/attributes/duplicates.py
Labels: pyreverse, Skip news :mute:
