Repository pylint-dev/pylint, pull requests merged in 2023-10, with the labels that each got.

#9082 Prevent stats loss
  doc/whatsnew/fragments/9059.bugfix
  pylint/lint/pylinter.py
  tests/lint/unittest_lint.py
  tests/test_check_parallel.py
  tests/test_regr.py
  tests/test_self.py
Labels: Bug :beetle:

#9108 Fix false positive for ``inherit-non-class`` for generic Protocols
  doc/whatsnew/fragments/9106.false_positive
  pylint/checkers/classes/class_checker.py
  tests/functional/i/inherit_non_class.py
  tests/functional/i/inherit_non_class.txt
Labels: False Positive 🦟, backport maintenance/3.0.x

#9104 Fix a crash for Enum class decorated with dataclass
  doc/whatsnew/fragments/9100.other
  pylint/checkers/utils.py
  tests/functional/i/invalid/invalid_name/invalid_name_enum.py
  tests/functional/i/invalid/invalid_name/invalid_name_enum.txt
Labels: backport maintenance/3.0.x

#9119 Bump pylint to 3.0.1, update changelog
  doc/exts/pylint_extensions.py
  doc/whatsnew/3/3.0/index.rst
  doc/whatsnew/fragments/9100.other
  doc/whatsnew/fragments/9106.false_positive
  pylint/__pkginfo__.py
  tbump.toml
  towncrier.toml
Labels: Maintenance, Skip news :mute:

#9120 Merge maintenance into main following 3.0.1 release
  doc/exts/pylint_extensions.py
  doc/whatsnew/3/3.0/index.rst
Labels: Maintenance, Skip news :mute:

#9092 Bump CI jobs to 3.12
  .github/workflows/changelog.yml
  .github/workflows/primer-test.yaml
  .github/workflows/primer_comment.yaml
  .github/workflows/primer_run_main.yaml
  .github/workflows/primer_run_pr.yaml
  .github/workflows/release.yml
  .github/workflows/tests.yaml
  .readthedocs.yaml
  tox.ini
Labels: Blocked 🚧, Maintenance, Skip news :mute:

#9140 [readthedoc] Upgrade the ubuntu image, downgrade the python interpreter
  .readthedocs.yaml
Labels: Maintenance, Skip news :mute:

#9131 Fix suggestion for min-max with expressions
  doc/whatsnew/fragments/8524.bugfix
  pylint/checkers/nested_min_max.py
  tests/functional/n/nested_min_max.py
  tests/functional/n/nested_min_max.txt
  tests/functional/n/nested_min_max_py39.py
  tests/functional/n/nested_min_max_py39.rc
  tests/functional/n/nested_min_max_py39.txt
Labels: Bug :beetle:, backport maintenance/3.0.x

#9088 [configuration] Create a data structure to store breaking changes
  pylint/config/_breaking_changes.py
Labels: Documentation :green_book:, Skip news :mute:

#9129 Optionally disable consider-using-join for non-empty separator
  doc/user_guide/configuration/all-options.rst
  doc/whatsnew/fragments/8701.feature
  pylint/checkers/refactoring/refactoring_checker.py
  tests/functional/c/consider/consider_join_for_non_empty_separator.py
  tests/functional/c/consider/consider_join_for_non_empty_separator.rc
Labels: Enhancement ✨

#9150 Fix `used-before-assignment` FP for generic type syntax (Py 3.12)
  doc/whatsnew/fragments/9110.false_positive
  pylint/checkers/variables.py
  pyproject.toml
  requirements_test_min.txt
  tests/functional/u/used/used_before_assignment_py312.py
  tests/functional/u/used/used_before_assignment_py312.rc
Labels: False Positive 🦟, C: used-before-assignment, python 3.12, backport maintenance/3.0.x

#9152 Respect py-version for ``inconsistent-quotes`` inside f-strings
  doc/whatsnew/fragments/9113.bugfix
  pylint/checkers/strings.py
  tests/functional/i/inconsistent/inconsistent_quotes_fstring.py
  tests/functional/i/inconsistent/inconsistent_quotes_fstring.rc
  tests/functional/i/inconsistent/inconsistent_quotes_fstring_py312.py
  tests/functional/i/inconsistent/inconsistent_quotes_fstring_py312.rc
  tests/functional/i/inconsistent/inconsistent_quotes_fstring_py312.txt
  tests/functional/i/inconsistent/inconsistent_quotes_fstring_py312_311.py
  tests/functional/i/inconsistent/inconsistent_quotes_fstring_py312_311.rc
Labels: False Positive 🦟

#9164 Escape special symbols and newlines in messages.
  doc/whatsnew/fragments/7874.bugfix
  pylint/extensions/magic_value.py
  tests/functional/ext/magic_value_comparison/magic_value_comparison.py
  tests/functional/ext/magic_value_comparison/magic_value_comparison.txt
Labels: Bug :beetle:, backport maintenance/3.0.x

#9147 Fixes duplicate-code check with ignore-imports
  doc/whatsnew/fragments/8914.bugfix
  pylint/checkers/similar.py
  tests/checkers/unittest_similar.py
  tests/regrtest_data/duplicate_code/ignore_conditional_imports/__init__.py
  tests/regrtest_data/duplicate_code/ignore_conditional_imports/file_one.py
  tests/regrtest_data/duplicate_code/ignore_conditional_imports/file_two.py
  tests/test_similar.py
Labels: Bug :beetle:, duplicate-code, False Positive 🦟, backport maintenance/3.0.x

#9178 Merge maintenance following 3.0.2 release
  doc/whatsnew/3/3.0/index.rst
  doc/whatsnew/fragments/7874.bugfix
  doc/whatsnew/fragments/8524.bugfix
  doc/whatsnew/fragments/8914.bugfix
  doc/whatsnew/fragments/9110.false_positive
  doc/whatsnew/fragments/9113.bugfix
Labels: Maintenance, Skip news :mute:

#9167 fix: exempt `TypedDict` from `typing_extensions`
  pylint/checkers/design_analysis.py
Labels: Enhancement ✨, Skip news :mute:

#9195 Fix `undefined-variable` etc for Python 3.12 generic type syntax
  doc/whatsnew/fragments/9193.false_positive
  pylint/checkers/variables.py
  tests/functional/u/undefined/undefined_variable_py312.py
  tests/functional/u/undefined/undefined_variable_py312.rc
Labels: False Positive 🦟, C: undefined-variable, python 3.12, backport maintenance/3.0.x

#9149 Fix false positive for ``unnecessary-lambda`` with kwargs in the call but not the lambda
  doc/whatsnew/fragments/9148.false_positive
  pylint/checkers/base/basic_checker.py
  tests/functional/u/unnecessary/unnecessary_lambda.py
Labels: False Positive 🦟, backport maintenance/3.0.x

#9202 [todos] Fix the todos version and the warnings' text
  pylint/checkers/similar.py
  pylint/checkers/variables.py
  pylint/config/callback_actions.py
  pylint/config/config_initialization.py
  pylint/testutils/functional/test_file.py
  pylint/utils/utils.py
  tests/test_check_parallel.py
Labels: Documentation :green_book:, Skip news :mute:, backport maintenance/3.0.x
