Repository pylint-dev/pylint, pull requests merged in 2023-06, with the labels that each got.

#8733 [stale issue CI] Permit to write comment on stale pull requests
  .github/workflows/stale.yml
Labels: Maintenance, Skip news :mute:

#8741 Fix a crash when `__all__` exists but cannot be inferred
  doc/whatsnew/fragments/8740.bugfix
  pylint/checkers/variables.py
  tests/functional/u/undefined/undefined_all_variable_edge_case.py
  tests/functional/u/undefined/undefined_all_variable_edge_case.txt
Labels: Crash 💥, backport maintenance/2.17.x

#8713 Fix a false positive for ``unused-variable``
  doc/whatsnew/fragments/8696.false_positive
  pylint/checkers/variables.py
  tests/functional/u/unused/unused_global_variable2.py
  tests/functional/u/unused/unused_global_variable2.txt
Labels: False Positive 🦟, backport maintenance/2.17.x

#8745 Skip flaky `regression_5408.py` test on PyPy
  tests/functional/r/regression_02/regression_5408.rc
Labels: Maintenance, tests, Skip news :mute:

#8682 Add regression test for #8554
  doc/whatsnew/fragments/8554.bugfix
  tests/functional/i/invalid/invalid_unary_operand_type.py
Labels: Maintenance, backport maintenance/2.17.x

#8757 Support `duplicate-code` message with `--jobs`
  doc/whatsnew/fragments/374.bugfix
  pylint/checkers/similar.py
  pylint/lint/parallel.py
  tests/test_self.py
  tests/test_similar.py
Labels: multiprocessing

#8750 fix(inconsistent-return-statements): Fix false positive due to pylint not seeing that a method returns `NoReturn`
  doc/whatsnew/fragments/8747.false_positive
  pylint/checkers/refactoring/refactoring_checker.py
  tests/functional/i/inconsistent/inconsistent_returns_noreturn.py
  tests/functional/i/inconsistent/inconsistent_returns_noreturn.txt
Labels: False Positive 🦟, backport maintenance/2.17.x

#6288 docparams extension considers type comments as type documentation.
  doc/whatsnew/fragments/6287.bugfix
  pylint/extensions/_check_docs_utils.py
  pylint/extensions/docparams.py
  tests/functional/ext/docparams/missing_param_doc.py
  tests/functional/ext/docparams/missing_param_doc_py38.py
  tests/functional/ext/docparams/missing_param_doc_py38.rc
  tests/functional/ext/docparams/parameter/missing_param_doc_required_Google.py
  tests/functional/ext/docparams/parameter/missing_param_doc_required_Google.txt
  tests/functional/ext/docparams/parameter/missing_param_doc_required_Numpy.py
  tests/functional/ext/docparams/parameter/missing_param_doc_required_Numpy.txt
  tests/functional/ext/docparams/parameter/missing_param_doc_required_Sphinx.py
  tests/functional/ext/docparams/parameter/missing_param_doc_required_Sphinx.txt
Labels: Enhancement ✨

#8770 Upgrade astroid to 3.0.0a5
  pyproject.toml
  requirements_test_min.txt
Labels: Maintenance, Skip news :mute:

#8728 Fix false positive `unspecified-encoding` when using kwargs
  doc/whatsnew/fragments/8719.false_positive
  pylint/checkers/stdlib.py
  pylint/checkers/utils.py
  tests/functional/b/bad_open_mode.txt
  tests/functional/u/unspecified_encoding_py38.py
  tests/functional/u/unspecified_encoding_py38.txt
Labels: False Positive 🦟, backport maintenance/2.17.x

#8777 Add a CITATION.cff containing the necessary metadata to cite Pylint
  CITATION.cff
  doc/whatsnew/fragments/8760.other
Labels: Documentation :green_book:

#8784 Fix a crash when calling `copy.copy()` without args
  doc/user_guide/installation/ide_integration/index.rst
  doc/whatsnew/fragments/8774.bugfix
  pylint/checkers/stdlib.py
  tests/functional/s/shallow_copy_environ.py
  tests/functional/s/shallow_copy_environ.txt
Labels: Crash 💥, backport maintenance/2.17.x

#8590 Allow parenthesized implicitly concatenated strings inside calls, to be more compatible with Black.
  doc/data/messages/i/implicit-str-concat/details.rst
  doc/data/messages/i/implicit-str-concat/related.rst
  doc/whatsnew/fragments/8552.false_positive
  pylint/checkers/strings.py
  tests/functional/i/implicit/implicit_str_concat_multiline.py
  tests/functional/i/implicit/implicit_str_concat_multiline.txt
Labels: Enhancement ✨

#8758 Ignore cached_property in method-hidden check (#8753)
  doc/whatsnew/fragments/8753.bugfix
  pylint/checkers/classes/class_checker.py
  tests/functional/m/method_hidden.py
  tests/functional/m/method_hidden.txt
  tests/functional/m/method_hidden_py39.py
  tests/functional/m/method_hidden_py39.rc
Labels: False Positive 🦟, backport maintenance/2.17.x

#8792 Clean up tests that had min_pyver=3.7 test setting
  doc/data/messages/r/redundant-typehint-argument/pylintrc
  tests/functional/a/access/access_to_protected_members_typing.rc
  tests/functional/a/assigning/assigning_non_slot_4509.rc
  tests/functional/a/await_outside_async.rc
  tests/functional/d/dataclass/dataclass_typecheck.rc
  tests/functional/d/dataclass/dataclass_with_default_factory.rc
  tests/functional/d/dataclass/dataclass_with_field.rc
  tests/functional/ext/typing/redundant_typehint_argument.rc
  tests/functional/ext/typing/typing_broken_callable.rc
  tests/functional/ext/typing/typing_broken_callable_deprecated_alias.rc
  tests/functional/ext/typing/typing_broken_callable_future_import.rc
  tests/functional/ext/typing/typing_broken_noreturn_future_import.rc
  tests/functional/f/forgotten_debug_statement.py
  tests/functional/f/forgotten_debug_statement.txt
  tests/functional/f/forgotten_debug_statement_py37.rc
  tests/functional/f/function_redefined_2540.rc
  tests/functional/g/generic_alias/generic_alias_collections_py37.rc
  tests/functional/g/generic_alias/generic_alias_collections_py37_with_typing.rc
  tests/functional/g/generic_alias/generic_alias_mixed_py37.rc
  tests/functional/g/generic_alias/generic_alias_postponed_evaluation_py37.rc
  tests/functional/g/generic_alias/generic_alias_related.rc
  tests/functional/g/generic_alias/generic_alias_typing.rc
  tests/functional/i/invalid/invalid_field_call.rc
  tests/functional/i/invalid/invalid_name/invalid_name_issue_3405.rc
  tests/functional/l/logging/logging_fstring_interpolation_py37.rc
  tests/functional/m/member/member_checks_async.py
  tests/functional/m/member/member_checks_async.txt
  tests/functional/m/member/member_checks_py37.rc
  tests/functional/n/no/no_member_dataclasses.rc
  tests/functional/n/no/no_member_nested_namedtuple.rc
  tests/functional/n/no/no_member_subclassed_dataclasses.rc
  tests/functional/n/no/no_self_argument.py
  tests/functional/n/no/no_self_argument.txt
  tests/functional/n/no/no_self_argument_py37.py
  tests/functional/n/no/no_self_argument_py37.rc
  tests/functional/n/no/no_self_argument_py37.txt
  tests/functional/n/not_async_context_manager_py37.rc
  tests/functional/p/postponed/postponed_evaluation_activated.rc
  tests/functional/p/postponed/postponed_evaluation_activated_with_alias.rc
  tests/functional/p/postponed/postponed_evaluation_not_activated.rc
  tests/functional/r/redefined/redefined_outer_name_type_checking.rc
  tests/functional/r/regression/regression_3507_typing_alias_isinstance.rc
  tests/functional/r/regression_02/regression_5030.rc
  tests/functional/t/too/too_few_public_methods_37.rc
  tests/functional/t/too/too_many_instance_attributes_py37.rc
  tests/functional/t/try_except_raise_crash.rc
  tests/functional/t/typing_generic.rc
  tests/functional/u/unpacking/unpacking_non_sequence_py37.rc
  tests/functional/u/unsubscriptable_value_py37.rc
  tests/functional/u/used/used_before_assignment_py37.rc
  tests/functional/w/wrong_exception_operation_py37.rc
Labels: Maintenance, Skip news :mute:

#8799 Exit immediately if all messages are disabled
  doc/whatsnew/fragments/8715.performance
  pylint/lint/run.py
  tests/test_self.py
Labels: performance

#8807 Support `cyclic-import` message with `--jobs`
  doc/user_guide/usage/run.rst
  doc/whatsnew/fragments/4171.bugfix
  pylint/checkers/imports.py
  tests/test_check_parallel.py
Labels: multiprocessing
