Repository pylint-dev/pylint, pull requests merged in 2023-04, with the labels that each got.

#8353 security update, bump dockerfile to python:3.10.10-alpine3.17
  examples/Dockerfile
Labels: Maintenance, Skip news :mute:

#8525 Don't use removed function from ``astroid``
  pylint/checkers/imports.py
Labels: Maintenance, Skip news :mute:, backport maintenance/2.17.x

#8520 Add Pyreverse option to exclude standalone nodes
  doc/whatsnew/fragments/8476.feature
  pylint/pyreverse/main.py
  pylint/pyreverse/writer.py
  pylint/testutils/pyreverse.py
  tests/pyreverse/conftest.py
  tests/pyreverse/data/classes_no_standalone.dot
  tests/pyreverse/data/packages_no_standalone.dot
  tests/pyreverse/functional/class_diagrams/inheritance/no_standalone.mmd
  tests/pyreverse/functional/class_diagrams/inheritance/no_standalone.py
  tests/pyreverse/functional/class_diagrams/inheritance/no_standalone.rc
  tests/pyreverse/test_writer.py
Labels: Enhancement ✨, pyreverse

#8517 [pyreverse] Bugfix: strip "/" at the end of the file
  doc/whatsnew/fragments/8504.bugfix
  pylint/pyreverse/writer.py
  tests/pyreverse/test_writer.py
Labels: pyreverse, Crash 💥, backport maintenance/2.17.x

#8529 refactor `pyreverse` tests to use temporary directory
  tests/pyreverse/test_writer.py
Labels: pyreverse, Maintenance, Skip news :mute:

#8432 Add regression test for #7506
  doc/whatsnew/fragments/7506.false_positive
  requirements_test.txt
  tests/functional/u/unused/unused_import.py
  tests/functional/u/unused/unused_import.txt
Labels: Regression, backport maintenance/2.17.x

#8530 Upgrade astroid to 2.15.2
  pyproject.toml
  requirements_test_min.txt
Labels: Maintenance, Skip news :mute:, backport maintenance/2.17.x

#8532 Backport astroid upgrade to maintenance/2.17.x
  pyproject.toml
  requirements_test_min.txt
Labels: Astroid, Maintenance, Skip news :mute:

#8533 Release branch 2.17.2
  doc/whatsnew/2/2.17/index.rst
  doc/whatsnew/fragments/8485.false_positive
  doc/whatsnew/fragments/8487.false_positive
  doc/whatsnew/fragments/8496.false_positive
  doc/whatsnew/fragments/8504.bugfix
  pylint/__pkginfo__.py
  tbump.toml
  towncrier.toml
Labels: Maintenance, Skip news :mute:

#8534 Merge maintenance 2.17.x in main following 2.17.2 release
  doc/whatsnew/2/2.17/index.rst
Labels: Maintenance, Skip news :mute:

#7579 Handle patterns in ignored-modules when checking for no-name-in-module
  doc/whatsnew/fragments/7578.bugfix
  pylint/checkers/imports.py
  pylint/checkers/typecheck.py
  pylint/checkers/utils.py
  pylint/checkers/variables.py
  tests/functional/i/import_error.py
  tests/functional/i/import_error.rc
  tests/functional/i/import_error.txt
Labels: Bug :beetle:

#8542 Fix check unused arguments false positive bug
  doc/whatsnew/fragments/3670.false_positive
  pylint/checkers/variables.py
  tests/functional/u/unused/unused_argument.py
  tests/functional/u/unused/unused_argument.txt
Labels: False Positive 🦟, backport maintenance/2.17.x

#8546 Do not emit `logging-not-lazy` for explicitly concatenated strings.
  doc/whatsnew/fragments/8410.false_positive
  pylint/checkers/logging.py
  tests/functional/l/logging/logging_not_lazy.py
  tests/functional/l/logging/logging_not_lazy.txt
Labels: Enhancement ✨, False Positive 🦟, backport maintenance/2.17.x

#8541 Fix typelias `invalid-name` false positives for Union variables without assignment.
  doc/whatsnew/fragments/8540.false_positive
  pylint/checkers/base/name_checker/checker.py
  tests/functional/t/typealias_naming_style_default.py
  tests/functional/t/typealias_naming_style_rgx.py
Labels: False Positive 🦟, backport maintenance/2.17.x

#8549 Fix isinstance-second-argument-not-valid-type for union types with None
  doc/whatsnew/fragments/8424.false_positive
  pylint/checkers/typecheck.py
  tests/functional/i/isinstance_second_argument_py310.py
  tests/functional/i/isinstance_second_argument_py310.txt
Labels: False Positive 🦟, backport maintenance/2.17.x

#8537 Also check the typealias naming style for TypeAlias variables defined in functions.
  doc/whatsnew/fragments/8536.false_negative
  pylint/checkers/base/name_checker/checker.py
  tests/functional/t/typealias_naming_style_default.py
  tests/functional/t/typealias_naming_style_default.txt
Labels: False Negative 🦋

#8556 Fix false positive for ``positional-only-arguments-expected``
  doc/whatsnew/fragments/8555.false_positive
  pylint/checkers/method_args.py
  tests/functional/p/positional_only_arguments_expected.py
Labels: False Positive 🦟, backport maintenance/2.17.x

#8566 Fix `unused-import` to check`dummy-variables-rgx`
  doc/whatsnew/fragments/8500.false_positive
  pylint/checkers/variables.py
  tests/checkers/unittest_typecheck.py
  tests/functional/i/import_dummy.py
Labels: Bug :beetle:, backport maintenance/2.17.x

#8571 Fix false positive for ``keyword-arg-before-vararg``
  doc/whatsnew/fragments/8570.false_positive
  pylint/checkers/typecheck.py
  tests/functional/k/keyword_arg_before_vararg_positional_only.py
  tests/functional/k/keyword_arg_before_vararg_positional_only.rc
  tests/functional/k/keyword_arg_before_vararg_positional_only.txt
Labels: False Positive 🦟

#8576 Disable Info linters in definition instead of Run class
  pylint/checkers/misc.py
  pylint/lint/pylinter.py
  pylint/lint/run.py
  pylint/testutils/testing_pylintrc
Labels: Documentation :green_book:, Maintenance, Skip news :mute:

#8431 Fix `used-before-assignment` TYPE_CHECKING false negatives
  doc/whatsnew/fragments/8198.bugfix
  pylint/checkers/variables.py
  tests/functional/u/used/used_before_assignment_scoping.py
  tests/functional/u/used/used_before_assignment_scoping.txt
Labels: False Negative 🦋, C: used-before-assignment

#8582 Improve output of `consider-using-generator` message for `min()` calls with `default` keyword
  doc/whatsnew/fragments/8563.bugfix
  pylint/checkers/refactoring/refactoring_checker.py
  tests/functional/c/consider/consider_using_generator.py
  tests/functional/c/consider/consider_using_generator.txt
Labels: Bug :beetle:, backport maintenance/2.17.x

#8581 Fix FP `used-before-assignment` for statements guarded under same test
  doc/whatsnew/fragments/8167.false_positive
  pylint/checkers/variables.py
  tests/functional/u/used/used_before_assignment.py
  tests/functional/u/used/used_before_assignment.txt
Labels: False Positive 🦟, C: used-before-assignment, backport maintenance/2.17.x

#8587 Minor refactor on type annotation
  pylint/checkers/variables.py
Labels: Maintenance, Skip news :mute:

#8608 Clear cache between primer package runs
  pylint/testutils/_primer/primer_run_command.py
Labels: primer, Skip news :mute:

#8606 Optimize `is_trailing_comma()`
  doc/whatsnew/fragments/1954.performance
  pylint/checkers/refactoring/refactoring_checker.py
Labels: performance

#8607 Fix `FunctionDef` isinstance checks
  pylint/checkers/typecheck.py
  pylint/checkers/utils.py
  pylint/checkers/variables.py
Labels: Maintenance, Skip news :mute:

#8611 Use `astroid.Context` enum
  pylint/checkers/typecheck.py
Labels: Astroid, Maintenance, Skip news :mute:

#8620 Bump pylint to 2.17.3, update changelog
  CONTRIBUTORS.txt
  doc/whatsnew/2/2.17/index.rst
  doc/whatsnew/fragments/3670.false_positive
  doc/whatsnew/fragments/7506.false_positive
  doc/whatsnew/fragments/8410.false_positive
  doc/whatsnew/fragments/8424.false_positive
  doc/whatsnew/fragments/8500.false_positive
  doc/whatsnew/fragments/8540.false_positive
  doc/whatsnew/fragments/8555.false_positive
  doc/whatsnew/fragments/8563.bugfix
  doc/whatsnew/fragments/8570.false_positive
  pylint/__pkginfo__.py
  tbump.toml
  towncrier.toml
Labels: Maintenance

#8619 Fix a false positive for ``bad-dunder-name``
  doc/whatsnew/fragments/8613.false_positive
  pylint/constants.py
  tests/functional/ext/bad_dunder/bad_dunder_name.py
Labels: False Positive 🦟, backport maintenance/2.17.x

#8621 Merge maintenance 2.17.x in main
  CONTRIBUTORS.txt
  doc/whatsnew/2/2.17/index.rst
Labels: Maintenance, Skip news :mute:

#8609 Drop support for Python 3.7
  .github/workflows/primer_run_main.yaml
  .github/workflows/primer_run_pr.yaml
  .github/workflows/tests.yaml
  .pre-commit-config.yaml
  README.rst
  doc/exts/pylint_extensions.py
  doc/whatsnew/fragments/6306.breaking
  pylint/checkers/__init__.py
  pylint/checkers/base/basic_checker.py
  pylint/checkers/base/docstring_checker.py
  pylint/checkers/classes/class_checker.py
  pylint/checkers/format.py
  pylint/checkers/imports.py
  pylint/checkers/logging.py
  pylint/checkers/raw_metrics.py
  pylint/checkers/refactoring/refactoring_checker.py
  pylint/checkers/spelling.py
  pylint/checkers/strings.py
  pylint/checkers/typecheck.py
  pylint/checkers/utils.py
  pylint/checkers/variables.py
  pylint/config/_pylint_config/utils.py
  pylint/config/argument.py
  pylint/lint/message_state_handler.py
  pylint/lint/pylinter.py
  pylint/reporters/json_reporter.py
  pylint/testutils/_primer/package_to_lint.py
  pylint/testutils/_primer/primer_command.py
  pylint/testutils/functional/test_file.py
  pylint/testutils/pyreverse.py
  pylint/testutils/unittest_linter.py
  pylint/typing.py
  pylint/utils/file_state.py
  pylint/utils/linterstats.py
  pylint/utils/utils.py
  pylintrc
  pyproject.toml
  tests/functional/b/bad_reversed_sequence_py37.py
  tests/functional/b/bad_reversed_sequence_py37.rc
  tests/functional/b/bad_reversed_sequence_py37.txt
  tests/functional/s/singledispatch/singledispatch_method_py37.rc
  tests/functional/s/star/star_needs_assignment_target_py38.py
  tests/functional/s/star/star_needs_assignment_target_py38.rc
  tests/functional/s/star/star_needs_assignment_target_py38.txt
  tests/functional/u/undefined/undefined_loop_variable.py
  tests/functional/u/undefined/undefined_loop_variable.txt
  tests/test_pylint_runners.py
  tests/test_self.py
  tests/testutils/test_output_line.py
  tox.ini
Labels: Maintenance

#8626 Bump astroid to 3.0.0a1
  pylint/checkers/base/basic_checker.py
  pylint/checkers/nested_min_max.py
  pylint/checkers/typecheck.py
  pylint/pyreverse/diagrams.py
  pyproject.toml
  requirements_test_min.txt
  tests/pyreverse/test_printer.py
Labels: Astroid, Maintenance, Skip news :mute:

#8627 Bump astroid to 3.0.0a2
  pyproject.toml
  requirements_test_min.txt
Labels: Astroid, Maintenance, Skip news :mute:

#8610 Added escaping of vertical bar character in annotation labels
  doc/whatsnew/fragments/8603.bugfix
  pylint/pyreverse/dot_printer.py
  tests/data/nullable_pattern.py
  tests/pyreverse/data/classes_No_Name.dot
  tests/pyreverse/data/classes_No_Name.html
  tests/pyreverse/data/classes_No_Name.mmd
  tests/pyreverse/data/classes_No_Name.puml
  tests/pyreverse/data/classes_colorized.dot
  tests/pyreverse/data/classes_colorized.puml
  tests/pyreverse/data/packages_No_Name.dot
  tests/pyreverse/data/packages_No_Name.html
  tests/pyreverse/data/packages_No_Name.mmd
  tests/pyreverse/data/packages_No_Name.puml
  tests/pyreverse/data/packages_colorized.dot
  tests/pyreverse/data/packages_colorized.puml
  tests/pyreverse/functional/class_diagrams/colorized_output/custom_colors.dot
  tests/pyreverse/test_diadefs.py
  tests/pyreverse/test_inspector.py
Labels: Bug :beetle:, pyreverse, python 3.10, backport maintenance/2.17.x

#8631 [Backport maintenance/2.17.x] Added escaping of vertical bar character in annotation labels
  doc/whatsnew/fragments/8603.bugfix
  pylint/pyreverse/dot_printer.py
  tests/data/nullable_pattern.py
  tests/pyreverse/data/classes_No_Name.dot
  tests/pyreverse/data/classes_No_Name.html
  tests/pyreverse/data/classes_No_Name.mmd
  tests/pyreverse/data/classes_No_Name.puml
  tests/pyreverse/data/classes_No_Name.vcg
  tests/pyreverse/data/classes_colorized.dot
  tests/pyreverse/data/classes_colorized.puml
  tests/pyreverse/data/packages_No_Name.dot
  tests/pyreverse/data/packages_No_Name.html
  tests/pyreverse/data/packages_No_Name.mmd
  tests/pyreverse/data/packages_No_Name.puml
  tests/pyreverse/data/packages_No_Name.vcg
  tests/pyreverse/data/packages_colorized.dot
  tests/pyreverse/data/packages_colorized.puml
  tests/pyreverse/test_diadefs.py
  tests/pyreverse/test_inspector.py
Labels: Bug :beetle:, pyreverse, python 3.10

#8633 [tomlkit] Limit the maximum version of tomlkit
  doc/whatsnew/fragments/8632.bugfix
  pyproject.toml
Labels: Crash 💥, backport maintenance/2.17.x

#8612 Add home-assistant to primer and remove old external primer
  .github/workflows/primer-test.yaml
  pylint/testutils/_primer/primer_prepare_command.py
  pyproject.toml
  tests/conftest.py
  tests/primer/packages_to_lint_batch_one.json
  tests/primer/packages_to_prime.json
  tests/primer/test_primer_external.py
Labels: primer, Skip news :mute:

#8494 Fix false negative for calling module-level function before definition
  doc/whatsnew/fragments/1144.false_negative
  pylint/checkers/variables.py
  tests/functional/u/used/used_before_assignment.py
  tests/functional/u/used/used_before_assignment.txt
  tests/functional/u/used/used_before_assignment_ternary.txt
Labels: False Negative 🦋

#8638 Make sure a ``tool`` table is created in ``toml`` generation
  doc/exts/pylint_options.py
  doc/user_guide/configuration/all-options.rst
  doc/whatsnew/fragments/8632.bugfix
  pylint/config/arguments_manager.py
  pyproject.toml
Labels: dependency, Skip news :mute:, backport maintenance/2.17.x

#8639 [primer] Fix commit string generation
  pylint/testutils/_primer/primer_prepare_command.py
Labels: primer, Skip news :mute:

#7163 Search for pyproject.toml config file in parent dirs
  .pyenchant_pylint_custom_dict.txt
  doc/user_guide/usage/run.rst
  doc/whatsnew/fragments/7163.other
  pylint/config/find_default_config_files.py
  tests/config/test_find_default_config_files.py
Labels: Enhancement ✨, Breaking changes for 3.0 🦤
