Repository pylint-dev/pylint, pull requests merged in 2023-11, with the labels that each got.

#9206 [governance] Upgrade governance for pylint plugin maintainers
  doc/development_guide/contributor_guide/governance.rst
Labels: Documentation :green_book:, Skip news :mute:

#9122 Print statistics how many files were checked in verbose
  doc/whatsnew/fragments/8935.other
  pylint/lint/pylinter.py
  pylint/lint/run.py
  tests/test_self.py
Labels: Usability

#9227 [doc] Add a changelog for #9167
  doc/whatsnew/fragments/9167.false_positive
Labels: Documentation :green_book:, Skip news :mute:

#9230 Support for resolving external toml files
  doc/user_guide/usage/run.rst
  doc/whatsnew/fragments/9228.feature
  pylint/config/find_default_config_files.py
  tests/config/test_find_default_config_files.py
Labels: Configuration

#9172 fix unnecessary-comprehension provides incorrect suggestion
  doc/whatsnew/fragments/9172.false_positive
  pylint/checkers/refactoring/refactoring_checker.py
  tests/functional/u/unnecessary/unnecessary_comprehension.py
  tests/functional/u/unnecessary/unnecessary_comprehension.txt
Labels: False Positive 🦟, backport maintenance/3.0.x

#9264 [not-an-iterable] Add regression test for uninferable instances
  tests/functional/i/iterable_context.py
Labels: tests, Skip news :mute:
