Repository pylint-dev/pylint, pull requests merged in 2023-01, with the labels that each got.

#8007 Correction for doc files line ending
  .gitattributes
  doc/data/messages/c/consider-ternary-expression/bad.py
  doc/data/messages/c/consider-ternary-expression/pylintrc
  doc/data/messages/c/consider-using-ternary/bad.py
  doc/data/messages/d/disallowed-name/bad.py
  doc/data/messages/e/else-if-used/bad.py
  doc/data/messages/e/else-if-used/pylintrc
  doc/data/messages/i/import-error/details.rst
  doc/data/messages/i/import-self/bad.py
  doc/data/messages/l/logging-format-interpolation/details.rst
  doc/data/messages/l/logging-fstring-interpolation/details.rst
  doc/data/messages/u/use-a-generator/details.rst
  doc/data/messages/u/use-dict-literal/details.rst
  doc/data/messages/u/using-final-decorator-in-unsupported-version/bad.py
  doc/data/messages/u/using-final-decorator-in-unsupported-version/good.py
Labels: Maintenance, Skip news :mute:

#8005 Backport (#7987)
  .pre-commit-config.yaml
  doc/whatsnew/fragments/6001.false_positive
  pylint/checkers/classes/class_checker.py
  pylint/checkers/utils.py
  tests/functional/a/assigning/assigning_non_slot.py
  tests/functional/a/assigning/assigning_non_slot.txt
  tests/functional/a/assigning/assigning_non_slot_4509.txt
Labels: Maintenance

#8014 [style] Use default 'dummy-variable-rgx' and 'ignored-argument-names'
  pylint/checkers/typecheck.py
  pylint/extensions/docparams.py
  pylint/testutils/unittest_linter.py
  pylintrc
Labels: Maintenance, Skip news :mute:

#7939 Add new check "pointless-exception-statement"
  doc/data/messages/p/pointless-exception-statement/bad.py
  doc/data/messages/p/pointless-exception-statement/good.py
  doc/user_guide/checkers/features.rst
  doc/user_guide/messages/messages_overview.rst
  doc/whatsnew/fragments/3110.new_check
  pylint/checkers/base/basic_checker.py
  pyproject.toml
  requirements_test_min.txt
  tests/functional/c/ctor_arguments.py
  tests/functional/c/ctor_arguments.txt
  tests/functional/s/statement_without_effect.py
  tests/functional/s/statement_without_effect.txt
Labels: Enhancement ✨

#8032 Prevent `pyreverse` crash when processing attributes assigned via tuple unpacking
  pylint/pyreverse/inspector.py
  tests/pyreverse/functional/class_diagrams/regression/regression_8031.mmd
  tests/pyreverse/functional/class_diagrams/regression/regression_8031.py
Labels: topic-pyreverse, Crash 💥, Skip news :mute:

#8029 Fix `used-before-assignment` false positive
  doc/whatsnew/fragments/7779.false_positive
  pylint/checkers/variables.py
  tests/functional/u/used/used_before_assignment_ternary.py
  tests/functional/u/used/used_before_assignment_ternary.rc
  tests/functional/u/used/used_before_assignment_ternary.txt
Labels: False Positive 🦟, C: used-before-assignment, backport maintenance/2.15.x

#8036 Merge maintenance 2.15.x in main following 2.15.10 release
  doc/whatsnew/2/2.15/index.rst
Labels: Maintenance, Skip news :mute:

#8037 [consider-using-augmented-assign] Do not warn for non-commutative operators
  pylint/checkers/utils.py
  tests/functional/ext/code_style/cs_consider_using_augmented_assign.py
  tests/functional/ext/code_style/cs_consider_using_augmented_assign.txt
Labels: False Positive 🦟, Unreleased, Skip news :mute:

#8044 [codecov] Use our own token to avoid being rate limited
  .github/workflows/tests.yaml
Labels: Maintenance, Skip news :mute:

#7880 Bugfix - extend ``magic-value-comparison`` support for parsing numerical types and `\\` in rcfile configuration
  pylint/extensions/magic_value.py
  tests/functional/ext/magic_value_comparison/magic_value_comparison.py
  tests/functional/ext/magic_value_comparison/magic_value_comparison.rc
Labels: Bug :beetle:, Blocker 🙅, Unreleased, Skip news :mute:

#8052 Fixes false positive for `try-except-raise` with multiple exceptions in one except statement
  doc/whatsnew/fragments/8051.false_positive
  pylint/checkers/exceptions.py
  tests/functional/t/try_except_raise.py
  tests/functional/t/try_except_raise.txt
Labels: False Positive 🦟

#8030 Upgrade astroid to 2.13.2
  pyproject.toml
  requirements_test_min.txt
Labels: Maintenance, Skip news :mute:

#8054 Regression tests for false positive ``no-member`` in decorated manager
  tests/functional/r/regression_02/regression_2567.py
Labels: False Positive 🦟, Skip news :mute:

#8057 [contributors.txt] Fix aliases and name that were actually emails
  CONTRIBUTORS.txt
  script/.contributors_aliases.json
Labels: Maintenance, Skip news :mute:

#8059 [tbump] Fix the regex for semver version to accept '1.2.3a4'
  tbump.toml
Labels: Maintenance, Skip news :mute:

#8064 [style] Limit line length and complexity using flake8
  doc/exts/pylint_messages.py
  pylint/checkers/exceptions.py
  pylint/checkers/similar.py
  pylint/lint/pylinter.py
  pylint/pyreverse/inspector.py
  pylint/pyreverse/main.py
  pylint/pyreverse/plantuml_printer.py
  setup.cfg
  tests/checkers/unittest_spelling.py
  tests/test_func.py
  tests/test_self.py
Labels: Maintenance, Skip news :mute:

#8065 [code owner] Remove areveny from her checkers temporarily
  .github/CODEOWNERS
Labels: Maintenance, Skip news :mute:

#8070 Fixed a crash when inferring a value and using its qname on a slice
  doc/whatsnew/fragments/8067.bugfix
  pylint/checkers/method_args.py
  pylint/checkers/refactoring/refactoring_checker.py
  tests/functional/r/regression_02/regression_8067.py
  tests/functional/r/regression_02/regression_8067.txt
Labels: Crash 💥, topic-qname

#8081 Better regex for private attribute check
  doc/whatsnew/fragments/8081.bugfix
  pylint/checkers/utils.py
Labels: topic-performance

#8085 [ci] Use pre-authenticated context for Primer PR
  .github/workflows/primer_comment.yaml
  .github/workflows/primer_run_pr.yaml
Labels: Maintenance, primer, Skip news :mute:

#8078 pointless-exception-statement: filter call inference to names that begin with an uppercase character
  pylint/checkers/base/basic_checker.py
  tests/functional/s/statement_without_effect.py
  tests/functional/s/statement_without_effect.txt
Labels: Blocker 🙅, topic-performance, Unreleased, Skip news :mute:

#8088 Fix `consider-using-augmented-assign` nested attribute access
  pylint/checkers/utils.py
  tests/functional/ext/code_style/cs_consider_using_augmented_assign.py
  tests/functional/ext/code_style/cs_consider_using_augmented_assign.txt
Labels: False Positive 🦟, Unreleased, Skip news :mute:

#8092 docs: fix typo
  doc/development_guide/how_tos/custom_checkers.rst
Labels: Documentation :green_book:, Skip news :mute:

#8095 Fix FP for `used-before-assignment` when reimporting name used in type annotation
  doc/whatsnew/fragments/7882.false_positive
  pylint/checkers/variables.py
  tests/functional/u/used/used_before_assignment_typing.py
  tests/functional/u/used/used_before_assignment_typing.txt
Labels: False Positive 🦟

#8093 Add test for existing preferred-modules functionality
  doc/whatsnew/fragments/7957.other
  tests/checkers/unittest_imports.py
  tests/regrtest_data/preferred_module/unpreferred_module.py
Labels: Enhancement ✨, Needs review 🔍

#8077 [doc] Add details and related links for bare/broad-except
  doc/data/messages/b/bare-except/bad.py
  doc/data/messages/b/bare-except/details.rst
  doc/data/messages/b/bare-except/good.py
  doc/data/messages/b/bare-except/related.rst
  doc/data/messages/b/broad-exception-caught/bad.py
  doc/data/messages/b/broad-exception-caught/details.rst
  doc/data/messages/b/broad-exception-caught/good.py
  doc/data/messages/b/broad-exception-caught/related.rst
  doc/data/messages/b/broad-exception-raised/related.rst
  doc/user_guide/checkers/features.rst
  pylint/checkers/exceptions.py
Labels: Documentation :green_book:, Skip news :mute:

#8101 Fix `missing-kwoa` FP with With statements
  doc/whatsnew/fragments/8100.false_positive
  pylint/checkers/typecheck.py
  tests/functional/d/dataclass/dataclass_kw_only.txt
  tests/functional/m/missing/missing_kwoa.py
  tests/functional/m/missing/missing_kwoa.txt
Labels: False Positive 🦟

#7808 Update disallowed-name to flag module-level variables
  doc/data/messages/d/disallowed-name/bad.py
  doc/data/messages/d/disallowed-name/good.py
  doc/data/messages/d/disallowed-name/pylintrc
  doc/whatsnew/fragments/3701.bugfix
  pylint/checkers/base/name_checker/checker.py
  tests/functional/a/async_functions.txt
  tests/functional/b/blacklisted_name.py
  tests/functional/b/blacklisted_name.txt
  tests/functional/d/disallowed_name.py
  tests/functional/d/disallowed_name.txt
  tests/functional/n/name/name_good_bad_names_regex.txt
  tests/functional/n/non_ascii_import/non_ascii_import_as_bad.py
  tests/functional/n/non_ascii_import/non_ascii_import_from_as.py
  tests/functional/n/non_ascii_name/non_ascii_name_inline_var.py
  tests/functional/n/non_ascii_name/non_ascii_name_try_except.py
  tests/functional/n/non_ascii_name/non_ascii_name_try_except.txt
  tests/functional/u/unused/unused_private_member.py
  tests/functional/u/use/use_maxsplit_arg.py
  tests/functional/u/use/use_maxsplit_arg.txt
  tests/testutils/test_lint_module_output_update.py
Labels: Enhancement ✨, False Negative 🦋

#8096 Add tests to improve coverage
  pylint/checkers/base_checker.py
  pylint/checkers/classes/special_methods_checker.py
  pylint/checkers/typecheck.py
  tests/checkers/unittest_base_checker.py
  tests/functional/n/non/non_iterator_returned.py
Labels: Maintenance, Skip news :mute:

#8021 feat(8015): `consider-refactoring-into-while-condition` checker
  .pyenchant_pylint_custom_dict.txt
  doc/data/messages/c/consider-refactoring-into-while-condition/bad.py
  doc/data/messages/c/consider-refactoring-into-while-condition/good.py
  doc/data/messages/c/consider-refactoring-into-while-condition/pylintrc
  doc/user_guide/checkers/extensions.rst
  doc/user_guide/messages/messages_overview.rst
  doc/whatsnew/fragments/8015.new_check
  pylint/checkers/base/basic_error_checker.py
  pylint/checkers/utils.py
  pylint/extensions/consider_refactoring_into_while_condition.py
  pylintrc
  tests/functional/ext/consider_refactoring_into_while_condition/consider_refactoring_into_while_condition.py
  tests/functional/ext/consider_refactoring_into_while_condition/consider_refactoring_into_while_condition.rc
  tests/functional/ext/consider_refactoring_into_while_condition/consider_refactoring_into_while_condition.txt
  tests/functional/ext/consider_refactoring_into_while_condition/consider_refactoring_into_while_condition_py38.py
  tests/functional/ext/consider_refactoring_into_while_condition/consider_refactoring_into_while_condition_py38.rc
  tests/functional/ext/consider_refactoring_into_while_condition/consider_refactoring_into_while_condition_py38.txt
Labels: Enhancement ✨, Checkers, Needs review 🔍

#8123 Fix a false positive for ``redefined-variable-type`` when ``async`` methods are present.
  doc/whatsnew/fragments/8120.false_positive
  pylint/extensions/redefined_variable_type.py
  tests/functional/ext/redefined_variable_type/redefined_variable_type.py
Labels: Bug :beetle:, False Positive 🦟

#8121 feat(6489): implement `positional-only-arguments-expected` checker
  doc/data/messages/p/positional-only-arguments-expected/bad.py
  doc/data/messages/p/positional-only-arguments-expected/good.py
  doc/data/messages/p/positional-only-arguments-expected/related.rst
  doc/user_guide/checkers/features.rst
  doc/user_guide/messages/messages_overview.rst
  doc/whatsnew/fragments/6489.new_check
  pylint/checkers/method_args.py
  tests/functional/p/positional_only_arguments_expected.py
  tests/functional/p/positional_only_arguments_expected.rc
  tests/functional/p/positional_only_arguments_expected.txt
Labels: Enhancement ✨, Checkers

#8115 Tighten design constraints
  pylint/checkers/base/basic_checker.py
  pylint/checkers/classes/class_checker.py
  pylint/checkers/format.py
  pylint/checkers/imports.py
  pylint/checkers/refactoring/refactoring_checker.py
  pylint/checkers/similar.py
  pylint/checkers/spelling.py
  pylint/checkers/stdlib.py
  pylint/checkers/strings.py
  pylint/checkers/typecheck.py
  pylint/checkers/utils.py
  pylint/checkers/variables.py
  pylint/lint/expand_modules.py
  pylint/lint/run.py
  pylint/testutils/output_line.py
  pylint/utils/ast_walker.py
  pylintrc
  tests/checkers/unittest_deprecated.py
  tests/checkers/unittest_format.py
  tests/lint/unittest_lint.py
  tests/test_self.py
Labels: Maintenance, Skip news :mute:

#8130 Update isort to 5.12.0
  .pre-commit-config.yaml
  requirements_test_pre_commit.txt
Labels: Blocker 🙅, dependency, Skip news :mute:

#8114 fix(4857): fix false positive for `use-maxsplit-arg` with custom spli…
  doc/whatsnew/fragments/4857.false_positive
  pylint/checkers/refactoring/recommendation_checker.py
  tests/functional/u/use/use_maxsplit_arg.py
Labels: False Positive 🦟

#8135 [doc] Make sure that doc examples are of a reasonable length
  .pre-commit-config.yaml
  doc/data/.flake8
  doc/data/messages/b/bad-exception-cause/bad.py
  doc/data/messages/c/class-variable-slots-conflict/bad.py
  doc/data/messages/c/consider-using-dict-comprehension/bad.py
  doc/data/messages/c/consider-using-dict-comprehension/details.rst
  doc/data/messages/c/consider-using-f-string/bad.py
  doc/data/messages/c/consider-using-set-comprehension/bad.py
  doc/data/messages/c/consider-using-set-comprehension/details.rst
  doc/data/messages/l/line-too-long/bad.py
  doc/data/messages/l/line-too-long/pylintrc
  doc/data/messages/n/no-self-use/details.rst
  doc/data/messages/n/no-self-use/good.py
  doc/data/messages/t/too-many-boolean-expressions/bad.py
  doc/data/messages/t/too-many-format-args/bad.py
Labels: Documentation :green_book:, Skip news :mute:

#8140 Fix dev requirements
  .github/workflows/changelog.yml
  .github/workflows/checks.yaml
  .github/workflows/primer-test.yaml
  .github/workflows/primer_run_main.yaml
  .github/workflows/primer_run_pr.yaml
  .github/workflows/tests.yaml
  requirements_test_pre_commit.txt
Labels: dependency, Maintenance, Skip news :mute:

#8142 Print this error to stderr instead of stdout.
  pylint/lint/utils.py
Labels: Maintenance, Skip news :mute:

#8149 Fix primer comment job [ci]
  .github/workflows/primer_comment.yaml
Labels: Maintenance, primer, Skip news :mute:
