Repository pylint-dev/pylint, pull requests merged in 2023-02, with the labels that each got.

#8151 Update docs for `global-variable-not-assigned`
  doc/user_guide/checkers/features.rst
  doc/whatsnew/fragments/5073.other
  pylint/checkers/variables.py
  tests/functional/g/globals.py
  tests/functional/g/globals.txt
  tests/functional/r/regression/regression___file___global.txt
  tests/functional/u/unused/unused_variable.txt
Labels: Documentation :green_book:

#8159 improving test_pragma_parser
  tests/test_pragma_parser.py
Labels: Maintenance, Skip news :mute:

#8163 [crash] Fix crashes on python interpreter < 3.9
  doc/whatsnew/fragments/8161.bugfix
  pylint/checkers/imports.py
Labels: Crash 💥, backport maintenance/2.16.x

#8108 docs: fix grammatical error
  doc/user_guide/checkers/features.rst
  pylint/checkers/variables.py
Labels: Documentation :green_book:, Skip news :mute:

#8166 Bump pylint to 2.16.1, update changelog
  doc/whatsnew/2/2.16/index.rst
  doc/whatsnew/fragments/8161.bugfix
  pylint/__pkginfo__.py
  tbump.toml
  towncrier.toml
Labels: Maintenance

#8144 Add examples in doc for ``too-complex`` for ``pylint.extensions.mccabe``
  doc/data/messages/t/too-complex/bad.py
  doc/data/messages/t/too-complex/details.rst
  doc/data/messages/t/too-complex/good.py
  doc/data/messages/t/too-complex/pylintrc
Labels: Documentation :green_book:, Skip news :mute:

#8180 Small documentation update for `using-f-string-in-unsupported-version`.
  doc/data/messages/u/using-f-string-in-unsupported-version/details.rst
Labels: Documentation :green_book:, Skip news :mute:

#8172 Merge maintenance 2.16.x in main
  doc/whatsnew/2/2.16/index.rst
Labels: Maintenance, Skip news :mute:

#8193 Add poetry-core as a repository to prime
  tests/primer/packages_to_prime.json
Labels: Maintenance, primer, Skip news :mute:

#8195 add doc for message missing-final-newline / C0304
  .pre-commit-config.yaml
  doc/data/messages/m/missing-final-newline/bad.py
  doc/data/messages/m/missing-final-newline/details.rst
  doc/data/messages/m/missing-final-newline/good.py
  doc/data/messages/m/missing-final-newline/related.rst
Labels: Documentation :green_book:, Skip news :mute:

#8218 add doc for message unused-format-string-key
  doc/data/messages/u/unused-format-string-key/bad.py
  doc/data/messages/u/unused-format-string-key/details.rst
  doc/data/messages/u/unused-format-string-key/good.py
Labels: Documentation :green_book:, Skip news :mute:

#8209 Fix crash when an attribute node was used inside an unary op
  doc/whatsnew/fragments/8207.bugfix
  pylint/checkers/refactoring/refactoring_checker.py
  tests/functional/r/regression_02/regression_8207.py
Labels: Crash 💥, backport maintenance/2.16.x

#8169 fix no-name-in-module when variable is same as module name
  doc/whatsnew/fragments/8148.bugfix
  pylint/checkers/variables.py
  tests/regrtest_data/pkg_mod_imports/__init__.py
  tests/regrtest_data/pkg_mod_imports/base/__init__.py
  tests/regrtest_data/pkg_mod_imports/base/errors.py
  tests/regrtest_data/test_no_name_in_module.py
  tests/test_self.py
Labels: False Positive 🦟, backport maintenance/2.16.x

#8222 Add docs for inconsistent-quotes
  doc/data/messages/i/inconsistent-quotes/bad.py
  doc/data/messages/i/inconsistent-quotes/details.rst
  doc/data/messages/i/inconsistent-quotes/good.py
  doc/data/messages/i/inconsistent-quotes/pylintrc
Labels: Documentation :green_book:, Skip news :mute:

#8071 Fix `used-before-assignment` false positive for TYPE_CHECKING if/elif/else usage
  doc/whatsnew/fragments/7574.false_positive
  pylint/checkers/utils.py
  pylint/checkers/variables.py
  tests/functional/u/undefined/undefined_variable_py38.py
  tests/functional/u/undefined/undefined_variable_py38.txt
  tests/functional/u/used/used_before_assignment_typing.py
  tests/functional/u/used/used_before_assignment_typing.txt
Labels: False Positive 🦟, backport maintenance/2.16.x

#8228 Add missing import to example test
  doc/development_guide/how_tos/custom_checkers.rst
Labels: Documentation :green_book:, Skip news :mute:

#8227 Don't use ``self.config`` since it's deprecated
  examples/custom.py
Labels: Documentation :green_book:, Skip news :mute:

#8231 Don't use deprecated attribute in example test
  doc/development_guide/how_tos/custom_checkers.rst
Labels: Documentation :green_book:, Skip news :mute:

#8233 add doc for message use-sequence-for-iteration
  doc/data/messages/u/use-sequence-for-iteration/bad.py
  doc/data/messages/u/use-sequence-for-iteration/details.rst
  doc/data/messages/u/use-sequence-for-iteration/good.py
Labels: Documentation :green_book:, Skip news :mute:

#8239 doc for inline message suppression
  doc/data/messages/u/use-symbolic-message-instead/bad.py
  doc/data/messages/u/use-symbolic-message-instead/details.rst
  doc/data/messages/u/use-symbolic-message-instead/good.py
  doc/data/messages/u/useless-suppression/bad.py
  doc/data/messages/u/useless-suppression/details.rst
  doc/data/messages/u/useless-suppression/good.py
Labels: Documentation :green_book:, Skip news :mute:

#8243 Minor refactor to util function
  pylint/checkers/utils.py
Labels: Skip news :mute:, backport maintenance/2.16.x

#8242 Adding documentation for invalid-character-sub and invalid-character-zero-width-space
  doc/data/messages/i/invalid-character-sub/bad.py
  doc/data/messages/i/invalid-character-sub/details.rst
  doc/data/messages/i/invalid-character-sub/good.py
  doc/data/messages/i/invalid-character-zero-width-space/bad.py
  doc/data/messages/i/invalid-character-zero-width-space/details.rst
  doc/data/messages/i/invalid-character-zero-width-space/good.py
Labels: Documentation :green_book:, Skip news :mute:

#8234 Fix `nested-min-max` output msg
  doc/whatsnew/fragments/8168.bugfix
  pylint/checkers/nested_min_max.py
  tests/functional/n/nested_min_max.py
  tests/functional/n/nested_min_max.txt
Labels: Bug :beetle:, backport maintenance/2.16.x

#8153 Support Implicit Namespace Packages (PEP 420)
  doc/user_guide/configuration/all-options.rst
  doc/user_guide/usage/run.rst
  doc/whatsnew/fragments/8154.feature
  examples/pylintrc
  pylint/config/argument.py
  pylint/config/option.py
  pylint/lint/__init__.py
  pylint/lint/base_options.py
  pylint/lint/expand_modules.py
  pylint/lint/parallel.py
  pylint/lint/pylinter.py
  pylint/lint/utils.py
  pylint/pyreverse/main.py
  pylint/testutils/pyreverse.py
  tests/lint/unittest_expand_modules.py
  tests/lint/unittest_lint.py
  tests/primer/packages_to_prime.json
  tests/pyreverse/conftest.py
  tests/pyreverse/functional/class_diagrams/namespaces/pep420/pep420.dot
  tests/pyreverse/functional/class_diagrams/namespaces/pep420/pep420.mmd
  tests/pyreverse/functional/class_diagrams/namespaces/pep420/pep420.puml
  tests/pyreverse/functional/class_diagrams/namespaces/pep420/pep420.py
  tests/pyreverse/functional/class_diagrams/namespaces/pep420/pep420.rc
  tests/pyreverse/test_main.py
  tests/pyreverse/test_pyreverse_functional.py
  tests/regrtest_data/pep420/basic/project/namespace/package/__init__.py
  tests/regrtest_data/pep420/wrapper/project/namespace/package/logging/__init__.py
  tests/regrtest_data/pep420/wrapper/project/namespace/package/logging/wrapper/__init__.py
  tests/test_check_parallel.py
  tests/test_deprecation.py
Labels: Enhancement ✨

#8223 Add `--color-palette` option to `pyreverse`
  .pyenchant_pylint_custom_dict.txt
  doc/whatsnew/fragments/6738.feature
  pylint/pyreverse/main.py
  pylint/pyreverse/writer.py
  pylint/testutils/pyreverse.py
  tests/pyreverse/functional/class_diagrams/colorized_output/custom_colors.puml
  tests/pyreverse/functional/class_diagrams/colorized_output/custom_colors.py
  tests/pyreverse/functional/class_diagrams/colorized_output/custom_colors.rc
Labels: Enhancement ✨, topic-pyreverse

#8247 Add example for deprecated-module
  doc/data/messages/d/deprecated-module/bad.py
  doc/data/messages/d/deprecated-module/details.rst
  doc/data/messages/d/deprecated-module/good.py
  doc/data/messages/d/deprecated-module/pylintrc
Labels: Documentation :green_book:, Skip news :mute:

#8176 Fix `used-before-assignment` false positive for walrus operator in dictionary
  doc/whatsnew/fragments/8125.bugfix
  pylint/checkers/variables.py
  tests/functional/u/used/used_before_assignment_ternary.py
Labels: False Positive 🦟, backport maintenance/2.16.x

#8257 Add version option to `pyreverse`
  doc/whatsnew/fragments/7851.feature
  pylint/pyreverse/main.py
  tests/pyreverse/test_main.py
Labels: topic-pyreverse, Crash 💥, backport maintenance/2.16.x

#8253 Fix FP for used-before-assignment with assignment expressions in containers
  doc/whatsnew/fragments/8252.false_positive
  pylint/checkers/variables.py
  tests/functional/u/undefined/undefined_variable_py38.py
  tests/functional/u/undefined/undefined_variable_py38.txt
Labels: False Positive 🦟, C: used-before-assignment, backport maintenance/2.16.x

#8264 [typing] Use __future__ annotations where possible
  doc/exts/pylint_messages.py
  doc/test_messages_documentation.py
  examples/custom.py
  examples/custom_raw.py
  pylint/checkers/classes/class_checker.py
Labels: Maintenance, Skip news :mute:

#8255 doc unexpected-line-ending-format
  .gitattributes
  doc/data/messages/u/unexpected-line-ending-format/bad.py
  doc/data/messages/u/unexpected-line-ending-format/details.rst
  doc/data/messages/u/unexpected-line-ending-format/good.py
  doc/data/messages/u/unexpected-line-ending-format/pylintrc
  doc/data/messages/u/unexpected-line-ending-format/related.rst
Labels: Documentation :green_book:, Skip news :mute:

#8269 Add documentation for duplicate-string-formatting-argument and bidirectional-unicode
  doc/data/messages/b/bidirectional-unicode/bad.py
  doc/data/messages/b/bidirectional-unicode/details.rst
  doc/data/messages/b/bidirectional-unicode/good.py
  doc/data/messages/d/duplicate-string-formatting-argument/bad.py
  doc/data/messages/d/duplicate-string-formatting-argument/details.rst
  doc/data/messages/d/duplicate-string-formatting-argument/good.py
Labels: Documentation :green_book:, Skip news :mute:

#8270 Fix ``duplicate-string-formatting-argument`` comment mistakenly left in good.py
  doc/data/messages/d/duplicate-string-formatting-argument/good.py
Labels: Documentation :green_book:, Skip news :mute:

#8276 Bump pylint to 2.16.2, update changelog
  doc/whatsnew/2/2.16/index.rst
  doc/whatsnew/fragments/7574.false_positive
  doc/whatsnew/fragments/7851.feature
  doc/whatsnew/fragments/8125.bugfix
  doc/whatsnew/fragments/8148.bugfix
  doc/whatsnew/fragments/8168.bugfix
  doc/whatsnew/fragments/8207.bugfix
  doc/whatsnew/fragments/8252.false_positive
  pylint/__pkginfo__.py
  tbump.toml
  towncrier.toml
Labels: Maintenance

#8271 Create documentation for consier-alternative-union-syntax, consider-using-alias and consider-using-namedtuple-or-dataclass
  doc/data/messages/c/consider-alternative-union-syntax/bad.py
  doc/data/messages/c/consider-alternative-union-syntax/details.rst
  doc/data/messages/c/consider-alternative-union-syntax/good.py
  doc/data/messages/c/consider-alternative-union-syntax/pylintrc
  doc/data/messages/c/consider-using-alias/bad.py
  doc/data/messages/c/consider-using-alias/details.rst
  doc/data/messages/c/consider-using-alias/good.py
  doc/data/messages/c/consider-using-alias/pylintrc
  doc/data/messages/c/consider-using-namedtuple-or-dataclass/bad.py
  doc/data/messages/c/consider-using-namedtuple-or-dataclass/details.rst
  doc/data/messages/c/consider-using-namedtuple-or-dataclass/good.py
  doc/data/messages/c/consider-using-namedtuple-or-dataclass/pylintrc
Labels: Documentation :green_book:, Skip news :mute:

#8286 [doc] Do not use real code for 'self-import'
  doc/data/messages/i/import-self/bad.py
  doc/data/messages/i/import-self/details.rst
  doc/data/messages/i/import-self/good.py
Labels: Documentation :green_book:, Skip news :mute:

#8283 Merge maintenance 2.16.x in main
  doc/whatsnew/2/2.16/index.rst
Labels: Maintenance, Skip news :mute:

#8294 Add documentation for adding Pylint configuration to ``tox.ini``.
  doc/user_guide/usage/run.rst
Labels: Documentation :green_book:, Skip news :mute:

#8206 Fix invalid type false positive
  doc/whatsnew/fragments/8205.false_positive
  pylint/checkers/typecheck.py
  pylint/constants.py
  tests/functional/d/dataclass/dataclass_typecheck.txt
  tests/functional/ext/typing/redundant_typehint_argument.py
  tests/functional/ext/typing/redundant_typehint_argument_py310.py
  tests/functional/i/isinstance_second_argument.txt
  tests/functional/i/isinstance_second_argument_py310.py
  tests/functional/i/isinstance_second_argument_py310.rc
  tests/functional/i/isinstance_second_argument_py310.txt
Labels: typing, False Positive 🦟, backport maintenance/2.16.x

#8295 Add documentation for truncated-format-string and logging-unsupported-format
  doc/data/messages/l/logging-unsupported-format/bad.py
  doc/data/messages/l/logging-unsupported-format/details.rst
  doc/data/messages/l/logging-unsupported-format/good.py
  doc/data/messages/t/truncated-format-string/bad.py
  doc/data/messages/t/truncated-format-string/details.rst
  doc/data/messages/t/truncated-format-string/good.py
Labels: Documentation :green_book:, Skip news :mute:

#8304 Add documentation for file-ignored and import-private-name
  doc/data/messages/f/file-ignored/bad.py
  doc/data/messages/f/file-ignored/details.rst
  doc/data/messages/f/file-ignored/good.py
  doc/data/messages/i/import-private-name/bad.py
  doc/data/messages/i/import-private-name/details.rst
  doc/data/messages/i/import-private-name/good.py
  doc/data/messages/i/import-private-name/pylintrc
Labels: Documentation :green_book:, Skip news :mute:

#8306 [doc] Add an example for 'too-many-locals'
  doc/data/messages/t/too-many-locals/bad.py
  doc/data/messages/t/too-many-locals/details.rst
  doc/data/messages/t/too-many-locals/good.py
  doc/data/messages/t/too-many-locals/pylintrc
  tests/functional/t/too/too_many_locals.py
Labels: Documentation :green_book:, Skip news :mute:

#8281 Support globbing patterns for source-roots
  doc/whatsnew/fragments/8290.feature
  pylint/config/argument.py
  pylint/config/option.py
  pylint/lint/base_options.py
  pylint/pyreverse/main.py
  tests/lint/unittest_lint.py
Labels: Enhancement ✨

#8323 Add documentation for too-many-lines
  doc/data/messages/t/too-many-lines/bad.py
  doc/data/messages/t/too-many-lines/details.rst
  doc/data/messages/t/too-many-lines/good.py
  doc/data/messages/t/too-many-lines/good/__init__.py
  doc/data/messages/t/too-many-lines/good/is_palindrome.py
  doc/data/messages/t/too-many-lines/good/main.py
  doc/data/messages/t/too-many-lines/pylintrc
Labels: Documentation :green_book:, Skip news :mute:

#8328 [doc] Add an example for suppressed-message
  doc/data/messages/s/suppressed-message/bad.py
  doc/data/messages/s/suppressed-message/details.rst
  doc/data/messages/s/suppressed-message/good.py
Labels: Documentation :green_book:, Skip news :mute:

#8292 Only count obviously non-terminating while-loops as return-ended
  doc/whatsnew/fragments/8280.false_negative
  pylint/checkers/refactoring/refactoring_checker.py
  tests/functional/i/inconsistent/inconsistent_returns.py
  tests/functional/i/inconsistent/inconsistent_returns.txt
Labels: Needs review 🔍, False Negative 🦋

#8330 [PR documentation] Add advice to keep the pull requests small
  .github/PULL_REQUEST_TEMPLATE.md
  doc/development_guide/contributor_guide/contribute.rst
Labels: Documentation :green_book:, Maintenance, Skip news :mute:

#8329 Document the governance model and the path to maintainership
  doc/development_guide/contributor_guide/governance.rst
  doc/development_guide/contributor_guide/index.rst
  doc/whatsnew/fragments/8329.other
Labels: Documentation :green_book:

#8340 [doc] Add an example for 'non-ascii-file-name'
  doc/data/messages/n/non-ascii-file-name/bad/bàd.py
  doc/data/messages/n/non-ascii-file-name/bad/not_bétter.py
  doc/data/messages/n/non-ascii-file-name/details.rst
  doc/data/messages/n/non-ascii-file-name/good.py
  doc/data/messages/n/non-ascii-file-name/good/bad.py
  doc/data/messages/n/non-ascii-file-name/good/not_better.py
  doc/data/messages/n/non-ascii-file-name/related.rst
  doc/user_guide/checkers/features.rst
  doc/user_guide/configuration/all-options.rst
  pylint/checkers/non_ascii_names.py
  tests/functional/n/non_ascii_name/non_ascii_name_loł.txt
Labels: Documentation :green_book:, Skip news :mute:

#8339 Fixing some too long lines
  pylint/checkers/base/name_checker/naming_style.py
  pylint/checkers/classes/class_checker.py
  pylint/checkers/refactoring/refactoring_checker.py
  pylint/checkers/similar.py
  pylint/checkers/unicode.py
  pylint/config/config_file_parser.py
  pylint/extensions/confusing_elif.py
  pylint/extensions/private_import.py
  pylint/lint/pylinter.py
  pylint/reporters/text.py
  script/check_newsfragments.py
  setup.cfg
  tests/checkers/unittest_utils.py
  tests/config/test_config.py
  tests/config/test_functional_config_loading.py
  tests/test_self.py
  tests/test_similar.py
Labels: Maintenance, Skip news :mute:

#8344 Update self in .contributors_aliases.json
  script/.contributors_aliases.json
Labels: Maintenance, Skip news :mute:

#8345 Add new check "implicit-flag-alias"
  doc/data/messages/i/implicit-flag-alias/bad.py
  doc/data/messages/i/implicit-flag-alias/good.py
  doc/whatsnew/fragments/8102.new_check
  pylint/checkers/classes/class_checker.py
  tests/functional/i/implicit/implicit_flag_alias.py
  tests/functional/i/implicit/implicit_flag_alias.txt
Labels: Enhancement ✨

#8347 [test] Permits to debug more easily 'test_allow_reexport_package'
  tests/checkers/unittest_imports.py
Labels: Maintenance, Skip news :mute:, backport maintenance/2.16.x

#7990 Add new checker `bad-chained-comparison`
  doc/data/messages/b/bad-chained-comparison/bad.py
  doc/data/messages/b/bad-chained-comparison/good.py
  doc/data/messages/b/bad-chained-comparison/related.rst
  doc/user_guide/checkers/features.rst
  doc/user_guide/messages/messages_overview.rst
  doc/whatsnew/fragments/6559.new_check
  pylint/checkers/bad_chained_comparison.py
  tests/functional/b/bad_chained_comparison.py
  tests/functional/b/bad_chained_comparison.txt
  tests/functional/c/consider/consider_iterating_dictionary.py
  tests/functional/ext/set_membership/use_set_membership.py
Labels: Enhancement ✨, Needs review 🔍

#7116 Add ``invalid-name`` check for ``TypeAlias`` names
  doc/data/messages/i/invalid-name/details.rst
  doc/user_guide/checkers/features.rst
  doc/whatsnew/fragments/7081.feature
  pylint/checkers/bad_chained_comparison.py
  pylint/checkers/base/name_checker/checker.py
  pylint/checkers/base/name_checker/naming_style.py
  pylint/constants.py
  pylint/utils/linterstats.py
  tests/functional/ext/typing/typing_broken_callable.py
  tests/functional/ext/typing/typing_broken_callable_deprecated_alias.py
  tests/functional/ext/typing/typing_broken_callable_future_import.py
  tests/functional/ext/typing/typing_broken_noreturn.py
  tests/functional/ext/typing/typing_broken_noreturn.txt
  tests/functional/ext/typing/typing_broken_noreturn_future_import.py
  tests/functional/ext/typing/typing_broken_noreturn_future_import.txt
  tests/functional/ext/typing/typing_broken_noreturn_py372.py
  tests/functional/r/regression_02/regression_3979.py
  tests/functional/t/typealias_naming_style_default.py
  tests/functional/t/typealias_naming_style_default.rc
  tests/functional/t/typealias_naming_style_default.txt
  tests/functional/t/typealias_naming_style_rgx.py
  tests/functional/t/typealias_naming_style_rgx.rc
  tests/functional/t/typealias_naming_style_rgx.txt
  tests/lint/test_caching.py
Labels: Enhancement ✨, C: invalid-name

#8350 [test] Use an empty pylintrc so tests to not depend on system's conf
  tests/checkers/unittest_imports.py
  tests/config/pylint_config/test_pylint_config_generate.py
  tests/config/test_per_directory_config.py
  tests/test_pylint_runners.py
Labels: Maintenance, Skip news :mute:, backport maintenance/2.16.x

#8337 Prevent emitting ``invalid-name``
  doc/whatsnew/fragments/8307.bugfix
  pylint/checkers/base/name_checker/checker.py
  tests/functional/g/globals.py
  tests/functional/g/globals.txt
  tests/functional/n/name/name_styles.py
  tests/functional/n/name/name_styles.txt
Labels: Bug :beetle:, backport maintenance/2.16.x

#8354 Manually cherry pick invalid name on global fix
  doc/whatsnew/fragments/8307.bugfix
  pylint/checkers/base/name_checker/checker.py
  tests/functional/g/globals.py
  tests/functional/g/globals.txt
  tests/functional/n/name/name_styles.py
  tests/functional/n/name/name_styles.txt
Labels: Bug :beetle:

#8338 [spelling checker] Better help message and code organization
  pylint/checkers/spelling.py
  tests/checkers/unittest_spelling.py
Labels: Maintenance, Skip news :mute:
