Repository pylint-dev/pylint, pull requests merged in 2024-11, with the labels that each got.

#10064 Update building docs
  doc/development_guide/contributor_guide/contribute.rst
  doc/make.bat
Labels: Maintenance, Skip news :mute:

#10060 Rename checkers/async.py to async_checker.py to import from another module
  doc/whatsnew/fragments/10071.breaking
  pylint/checkers/async_checker.py
Labels: Maintenance, Breaking changes for 4.0 🦤

#10072 Try to fix make.bat for Windows 11
  doc/make.bat
Labels: Maintenance, Skip news :mute:

#10075 Fix `used-before-assignment` false negative for nonlocals
  pylint/checkers/variables.py
  tests/functional/u/used/used_before_assignment_nonlocal.py
  tests/functional/u/used/used_before_assignment_nonlocal.txt
Labels: Unreleased, Skip news :mute:

#10063 Improve pyreverse documentation
  doc/additional_tools/pyreverse/configuration.rst
  doc/additional_tools/pyreverse/index.rst
  doc/additional_tools/pyreverse/output_examples.rst
  doc/exts/pyreverse_configuration.py
  doc/index.rst
Labels: Documentation :green_book:, Skip news :mute:

#10079 Fix RTD links to additional tools in the README
  README.rst
  doc/conf.py
Labels: Documentation :green_book:, Skip news :mute:

#10097 Fix `potential-index-error` false positive when iterable contains starred element
  doc/whatsnew/fragments/10076.false_positive
  pylint/checkers/variables.py
  tests/functional/p/potential_index_error.py
  tests/functional/p/potential_index_error.txt
Labels: False Positive 🦟, backport maintenance/3.3.x
