Repository pylint-dev/pylint, pull requests merged in 2024-05, with the labels that each got.

#9589 [syntax-error] Detail the reason why pylint can't analyse the file after a syntax error
  doc/data/messages/s/syntax-error/details.rst
  doc/data/messages/s/syntax-error/related.rst
Labels: Documentation :green_book:, Skip news :mute:

#9592 Fix false negative for ``property-with-parameters``
  doc/whatsnew/fragments/9584.false_negative
  pylint/checkers/classes/class_checker.py
  tests/functional/p/property_with_parameters.py
  tests/functional/p/property_with_parameters.txt
Labels: False Negative 🦋

#9346 Recognize new-style attrs decorators in too-few-public-methods check
  doc/whatsnew/fragments/9345.false_positive
  pylint/checkers/design_analysis.py
  tests/functional/t/too/too_few_public_methods_37.py
Labels: False Positive 🦟, backport maintenance/3.1.x

#9594 Fix a false positive for ``consider-using-dict-items``
  doc/whatsnew/fragments/9554.false_positive
  pylint/checkers/refactoring/recommendation_checker.py
  tests/functional/c/consider/consider_using_dict_items.py
  tests/functional/c/consider/consider_using_dict_items.txt
Labels: False Positive 🦟, backport maintenance/3.1.x

#9595 Avoid search paths for ImportChecker when possible
  doc/whatsnew/fragments/9310.performance
  pylint/checkers/imports.py
Labels: performance

#9600 replace deprecated m*ster_doc with root_doc
  doc/conf.py
Labels: Documentation :green_book:, Skip news :mute:

#9602 [ruff] Add 'flake8-pathlib' disable the messages that need fixing later
  pylint/config/config_initialization.py
  pyproject.toml
  script/create_contributor_list.py
Labels: Maintenance, Skip news :mute:

#9599 Fix a false positive with ``singledispatchmethod-function``
  doc/data/messages/s/singledispatch-method/bad.py
  doc/data/messages/s/singledispatch-method/good.py
  doc/data/messages/s/singledispatchmethod-function/bad.py
  doc/whatsnew/fragments/9531.false_positive
  pylint/checkers/stdlib.py
  tests/functional/s/singledispatch/singledispatch_method.py
  tests/functional/s/singledispatch/singledispatch_method.txt
  tests/functional/s/singledispatch/singledispatch_method_py37.py
  tests/functional/s/singledispatch/singledispatch_method_py37.rc
  tests/functional/s/singledispatch/singledispatch_method_py37.txt
  tests/functional/s/singledispatch/singledispatch_method_py38.py
  tests/functional/s/singledispatch/singledispatch_method_py38.txt
  tests/functional/s/singledispatch/singledispatchmethod_function.py
  tests/functional/s/singledispatch/singledispatchmethod_function.txt
  tests/functional/s/singledispatch/singledispatchmethod_function_py38.py
  tests/functional/s/singledispatch/singledispatchmethod_function_py38.txt
Labels: False Positive 🦟, backport maintenance/3.1.x

#9606 Bump astroid to 3.2.0
  doc/whatsnew/fragments/9606.internal
  pyproject.toml
  requirements_test_min.txt
  tests/functional/r/regression_02/regression_4660.py
  tests/functional/r/regression_02/regression_4660.txt
Labels: Maintenance

#9133 [contextmanager-generator-missing-cleanup][new feature] Warn about @contextlib.contextmanager without try/finally in generator functions
  doc/data/messages/c/contextmanager-generator-missing-cleanup/bad.py
  doc/data/messages/c/contextmanager-generator-missing-cleanup/details.rst
  doc/data/messages/c/contextmanager-generator-missing-cleanup/good.py
  doc/data/messages/c/contextmanager-generator-missing-cleanup/related.rst
  doc/user_guide/checkers/features.rst
  doc/user_guide/messages/messages_overview.rst
  doc/whatsnew/fragments/2832.new_check
  pylint/checkers/base/__init__.py
  pylint/checkers/base/function_checker.py
  tests/functional/c/consider/consider_using_with.py
  tests/functional/c/consider/consider_using_with.txt
  tests/functional/c/consider/consider_using_with_open.py
  tests/functional/c/consider/consider_using_with_open.txt
  tests/functional/c/contextmanager_generator_missing_cleanup.py
  tests/functional/c/contextmanager_generator_missing_cleanup.txt
  tests/functional/m/missing/missing_kwoa.py
  tests/functional/m/missing/missing_kwoa.txt
Labels: Enhancement ✨

#9504 Add ignored modules to Astroid module deny list
  .pyenchant_pylint_custom_dict.txt
  doc/user_guide/configuration/all-options.rst
  doc/whatsnew/fragments/9442.other
  examples/pylintrc
  examples/pyproject.toml
  pylint/lint/base_options.py
  pylint/lint/pylinter.py
  pylintrc
  tests/lint/test_pylinter.py
  tests/test_functional.py
Labels: Enhancement ✨

#9618 Merge maintenance/3.1.x into main following 3.1.1 release
  doc/whatsnew/3/3.1/index.rst
  doc/whatsnew/fragments/9345.false_positive
  doc/whatsnew/fragments/9531.false_positive
  doc/whatsnew/fragments/9554.false_positive
Labels: Maintenance, Skip news :mute:

#9620 [performance] Check that 'trailing-comma-tuple' is enabled only once
  doc/data/messages/t/trailing-comma-tuple/details.rst
  doc/whatsnew/fragments/9608.performance
  pylint/checkers/refactoring/refactoring_checker.py
Labels: performance

#9630 Fix a false negative for ``--ignore-patterns``
  doc/whatsnew/fragments/9273.false_negative
  pylint/lint/expand_modules.py
  tests/regrtest_data/ignore_pattern/.hidden/module.py
  tests/regrtest_data/ignore_pattern/module.py
  tests/test_self.py
Labels: Bug :beetle:, backport maintenance/3.2.x

#9638 Don't emit incorrect-variance for type parameters (PEP 695)
  doc/whatsnew/fragments/9638.false_positive
  pylint/checkers/base/name_checker/checker.py
  tests/functional/t/type/typevar_naming_style_py312.py
  tests/functional/t/type/typevar_naming_style_py312.txt
Labels: python 3.12, backport maintenance/3.2.x

#9645 Fix FP for `possibly-used-before-assignment` with `assert_never()`
  doc/whatsnew/fragments/9643.false_positive
  pylint/checkers/variables.py
  pylint/constants.py
  tests/functional/u/used/used_before_assignment_py311.py
  tests/functional/u/used/used_before_assignment_py311.rc
Labels: False Positive 🦟, backport maintenance/3.2.x

#9146 Fix linterstats.get_module_message_count()
  doc/whatsnew/fragments/9145.bugfix
  pylint/lint/report_functions.py
  pylint/utils/linterstats.py
  tests/test_self.py
Labels: backport maintenance/3.2.x

#9609 [trailing-comma-tuple] Fix enabling with message control locally when disabled for the file
  .pyenchant_pylint_custom_dict.txt
  doc/data/messages/t/trailing-comma-tuple/details.rst
  doc/whatsnew/fragments/9608.bugfix
  pylint/checkers/refactoring/refactoring_checker.py
  pylint/lint/message_state_handler.py
  tests/functional/t/trailing_comma_tuple.py
  tests/functional/t/trailing_comma_tuple.txt
  tests/functional/t/trailing_comma_tuple_9608.py
  tests/functional/t/trailing_comma_tuple_9608.rc
  tests/functional/t/trailing_comma_tuple_9608.txt
Labels: Bug :beetle:, backport maintenance/3.2.x

#9651 Post 3.2.1
  doc/whatsnew/3/3.2/index.rst
Labels: Maintenance, Skip news :mute:

#9655 Update astroid to 3.2.2
  doc/whatsnew/fragments/9406.false_positive
  pyproject.toml
  requirements_test_min.txt
  tests/functional/g/generic_class_syntax.py
  tests/functional/g/generic_class_syntax_py312.py
  tests/functional/g/generic_class_syntax_py312.rc
  tests/functional/g/generic_class_syntax_py312.txt
Labels: False Positive 🦟, python 3.12, backport maintenance/3.2.x

#9653 Also check Lambda for await-outside-async
  doc/whatsnew/fragments/9653.false_negative
  pylint/checkers/typecheck.py
  tests/functional/a/await_outside_async.py
  tests/functional/a/await_outside_async.txt
Labels: False Negative 🦋

#9654 Fix false-positive with contextmanager missing cleanup
  doc/data/messages/c/contextmanager-generator-missing-cleanup/bad.py
  doc/data/messages/c/contextmanager-generator-missing-cleanup/details.rst
  doc/data/messages/c/contextmanager-generator-missing-cleanup/good.py
  doc/whatsnew/fragments/9625.false_positive
  pylint/checkers/base/function_checker.py
  tests/functional/c/contextmanager_generator_missing_cleanup.py
  tests/functional/c/contextmanager_generator_missing_cleanup.txt
Labels: False Positive 🦟, backport maintenance/3.2.x

#9658 Bump pylint to 3.2.2, update changelog
  doc/whatsnew/3/3.2/index.rst
  doc/whatsnew/fragments/9406.false_positive
  doc/whatsnew/fragments/9625.false_positive
  pylint/__pkginfo__.py
  tbump.toml
  towncrier.toml
Labels: Maintenance

#9659 Post 3.2.2
  doc/whatsnew/3/3.2/index.rst
Labels: Maintenance, Skip news :mute:

#9660 Fix changelog
  doc/whatsnew/fragments/9653.false_negative
Labels: Maintenance, Skip news :mute:
