Repository pylint-dev/pylint, pull requests merged in 2024-06, with the labels that each got.

#9670 Fix a false negative for ``duplicate-argument-name``
  doc/user_guide/checkers/features.rst
  doc/whatsnew/fragments/9669.false_negative
  pylint/checkers/base/basic_error_checker.py
  tests/functional/a/async_functions.txt
  tests/functional/d/duplicate/duplicate_argument_name.py
  tests/functional/d/duplicate/duplicate_argument_name.txt
  tests/functional/d/duplicate/duplicate_argument_name_py3.py
  tests/functional/d/duplicate/duplicate_argument_name_py3.txt
Labels: False Negative 🦋

#9678 Fix a false positive for ``redefined-outer-name``
  doc/whatsnew/fragments/9671.false_positive
  pylint/checkers/variables.py
  tests/functional/r/redefined/redefined_except_handler.py
Labels: False Positive 🦟, backport maintenance/3.2.x

#7107 [pypy] Add a regression test for 'import array' false positive
  tests/functional/r/regression_02/regression_4126.py
  tests/functional/r/regression_02/regression_4126.rc
Labels: False Positive 🦟, Skip news :mute:

#9697 [multiple-statements] Make pylint compatible with black's 2024 style
  doc/whatsnew/fragments/9398.false_positive
  pylint/checkers/format.py
  tests/functional/m/multiple_statements.py
  tests/functional/m/multiple_statements.txt
  tests/functional/m/multiple_statements_single_line.py
  tests/functional/m/multiple_statements_single_line.txt
Labels: False Positive 🦟, backport maintenance/3.2.x

#9564 Add a new ``declare-non-slot`` error code
  doc/data/messages/d/declare-non-slot/bad.py
  doc/data/messages/d/declare-non-slot/good.py
  doc/user_guide/checkers/features.rst
  doc/user_guide/messages/messages_overview.rst
  doc/whatsnew/fragments/9499.feature
  pylint/checkers/classes/class_checker.py
  tests/functional/r/regression_02/regression_5479.py
  tests/functional/s/slots_checks.py
  tests/functional/s/slots_checks.txt
Labels: Enhancement ✨

#9700 Fix false positive in `use-yield-from` when using `yield` return
  doc/whatsnew/fragments/9696.false_positive
  pylint/checkers/refactoring/refactoring_checker.py
  tests/functional/u/use/use_yield_from.py
Labels: False Positive 🦟, backport maintenance/3.2.x

#9702 Release branch 3.2.3
  doc/whatsnew/3/3.2/index.rst
  doc/whatsnew/fragments/9398.false_positive
  doc/whatsnew/fragments/9671.false_positive
  doc/whatsnew/fragments/9696.false_positive
  examples/pylintrc
  examples/pyproject.toml
  pylint/__pkginfo__.py
  tbump.toml
  towncrier.toml
Labels: Maintenance, Skip news :mute:

#9703 Merge maintenance into main following 3.2.3 release
  doc/whatsnew/3/3.2/index.rst
  examples/pylintrc
  examples/pyproject.toml
Labels: Maintenance, Skip news :mute:

#9705 [undefined-variable] Fix a crash for undefined lineno in annotations
  doc/whatsnew/fragments/8866.bugfix
  pylint/checkers/variables.py
  tests/functional/u/undefined/undefined_variable.py
  tests/functional/u/undefined/undefined_variable.txt
Labels: Crash 💥, backport maintenance/3.2.x

#9704 [unnecessary-list-index-lookup] Fix crashes for uninferrable 'start' value in 'enumerate'
  doc/whatsnew/fragments/9078.bugfix
  pylint/checkers/refactoring/refactoring_checker.py
  tests/functional/u/unnecessary/unnecessary_list_index_lookup.py
Labels: Crash 💥, backport maintenance/3.2.x

#9716 [possibly-used-before-assignment] Model using assert_never
  doc/data/messages/p/possibly-used-before-assignment/details.rst
Labels: Documentation :green_book:, Skip news :mute:

#9734 Correct ``similar`` to ``symilar`` when talking about the standalone script
  doc/symilar.rst
  doc/whatsnew/fragments/9734.internal
  pylint/__init__.py
  pylint/checkers/symilar.py
  tests/checkers/unittest_symilar.py
  tests/test_similar.py
Labels: Documentation :green_book:, Maintenance

#9733 Documentation - Update `class-const` definition.
  doc/data/messages/i/invalid-name/details.rst
Labels: Documentation :green_book:, Skip news :mute:

#9728 Add `tox.ini` to the default discovered config files (right after setup.cfg)
  doc/whatsnew/fragments/9727.bugfix
  pylint/config/find_default_config_files.py
  tests/config/test_find_default_config_files.py
Labels: Enhancement ✨

#9714 [possibly-used-before-assignment] Avoid FP for typing.NoReturn
  doc/data/messages/p/possibly-used-before-assignment/details.rst
  doc/whatsnew/fragments/9674.false_positive
  pylint/checkers/utils.py
  pylint/checkers/variables.py
  tests/functional/u/used/used_before_assignment.py
  tests/functional/u/used/used_before_assignment.txt
Labels: Bug :beetle:, backport maintenance/3.2.x

#9742 Backport [possibly-used-before-assignment] Avoid FP for typing.NoReturn & Never
  doc/data/messages/p/possibly-used-before-assignment/details.rst
  doc/whatsnew/fragments/9674.false_positive
  pylint/checkers/utils.py
  pylint/checkers/variables.py
  tests/functional/u/used/used_before_assignment.py
  tests/functional/u/used/used_before_assignment.txt
Labels: False Positive 🦟, Maintenance

#9746 Bump pylint to 3.2.4, update changelog
  doc/whatsnew/3/3.2/index.rst
  doc/whatsnew/fragments/8866.bugfix
  doc/whatsnew/fragments/9078.bugfix
  doc/whatsnew/fragments/9343.bugfix
  doc/whatsnew/fragments/9674.false_positive
  pylint/__pkginfo__.py
  tbump.toml
  towncrier.toml
Labels: Maintenance, Skip news :mute:

#9748 Merge maintenance into main following 3.2.4 release
  doc/whatsnew/3/3.2/index.rst
Labels: Maintenance, Skip news :mute:

#9749 [release] Fix 3.2.4's release date following twine 5.1.0's issues
  doc/whatsnew/3/3.2/index.rst
Labels: Maintenance, Skip news :mute:, backport maintenance/3.2.x

#9753 False positive ``unreachable-code`` when using ``typing.Any`` as return in python 3.8
  doc/whatsnew/fragments/9751.bugfix
  pylint/checkers/utils.py
  tests/functional/r/regression_02/regression_9751.py
  tests/functional/u/used/used_before_assignment.py
  tests/functional/u/used/used_before_assignment_py38.py
  tests/functional/u/used/used_before_assignment_py38.rc
Labels: Regression, backport maintenance/3.2.x

#9756 Bump pylint to 3.2.5, update changelog
  doc/whatsnew/3/3.2/index.rst
  doc/whatsnew/fragments/9751.bugfix
  pylint/__pkginfo__.py
  tbump.toml
  towncrier.toml
Labels: Maintenance, Skip news :mute:
