Repository pylint-dev/pylint, pull requests merged in 2024-07, with the labels that each got.

#9768 Improve file discovery for directories that are not packages
  doc/user_guide/usage/run.rst
  doc/whatsnew/fragments/9764.bugfix
  pylint/lint/expand_modules.py
  tests/lint/unittest_expand_modules.py
Labels: Bug :beetle:

#9769 Merge maintenance into main following pylint 3.2.5
  doc/whatsnew/3/3.2/index.rst
  doc/whatsnew/fragments/8866.bugfix
  doc/whatsnew/fragments/9078.bugfix
  doc/whatsnew/fragments/9139.internal
  doc/whatsnew/fragments/9145.bugfix
  doc/whatsnew/fragments/9273.false_negative
  doc/whatsnew/fragments/9343.bugfix
  doc/whatsnew/fragments/9398.false_positive
  doc/whatsnew/fragments/9406.false_positive
  doc/whatsnew/fragments/9608.bugfix
  doc/whatsnew/fragments/9625.false_positive
  doc/whatsnew/fragments/9626.bugfix
  doc/whatsnew/fragments/9627.false_positive
  doc/whatsnew/fragments/9638.false_positive
  doc/whatsnew/fragments/9643.false_positive
  doc/whatsnew/fragments/9671.false_positive
  doc/whatsnew/fragments/9674.false_positive
  doc/whatsnew/fragments/9696.false_positive
  doc/whatsnew/fragments/9751.bugfix
Labels: Maintenance, Skip news :mute:

#9772 Fix `invalid-name` regression for class attributes in subclasses
  doc/whatsnew/fragments/9765.false_positive
  pylint/checkers/base/name_checker/checker.py
  tests/functional/i/invalid/invalid_name.py
  tests/functional/i/invalid/invalid_name.rc
  tests/functional/i/invalid/invalid_name.txt
Labels: False Positive 🦟, C: invalid-name, backport maintenance/3.2.x

#9773 Cleanup test skips
  tests/checkers/unittest_non_ascii_name.py
  tests/functional/d/deprecated/deprecated_methods_py3.py
  tests/functional/d/deprecated/deprecated_methods_py3.rc
  tests/functional/d/deprecated/deprecated_methods_py3.txt
  tests/functional/u/unnecessary/unnecessary_dunder_call_py38.rc
  tests/functional/u/unnecessary/unnecessary_dunder_call_py38_pypy.rc
  tests/pyreverse/test_diadefs.py
Labels: Maintenance, Skip news :mute:

#9777 Add PyPy 3.10 to CI
  .github/workflows/tests.yaml
Labels: Maintenance, Skip news :mute:

#9784 Revert "Remove `--min_pyver_end_position`"
  doc/development_guide/contributor_guide/tests/writing_test.rst
  doc/whatsnew/fragments/9774.other
  pylint/testutils/functional/test_file.py
  pylint/testutils/lint_module_test.py
  pylint/testutils/output_line.py
  tests/testutils/test_output_line.py
Labels: Maintenance, Skip news :mute:

#9786 Bump astroid to 3.2.3
  doc/whatsnew/fragments/9214.bugfix
  pyproject.toml
  requirements_test_min.txt
Labels: backport maintenance/3.2.x

#9782 Handle assert_never() when imported from typing_extensions
  doc/whatsnew/fragments/9780.false_positive
  pylint/checkers/variables.py
  tests/functional/u/used/used_before_assignment_py311.py
  tests/functional/u/used/used_before_assignment_py311.rc
Labels: False Positive 🦟, backport maintenance/3.2.x

#9790 Handle assert_never() when imported from typing_extensions (#9782)
  doc/whatsnew/fragments/9780.false_positive
  pylint/checkers/variables.py
  tests/functional/u/used/used_before_assignment_py311.py
  tests/functional/u/used/used_before_assignment_py311.rc
Labels: False Positive 🦟

#9740 Fix a false positive for ``missing-param-doc``
  doc/whatsnew/fragments/9739.false_positive
  pylint/extensions/docparams.py
  tests/functional/ext/docparams/missing_param_doc.py
  tests/functional/ext/docparams/missing_param_doc.txt
Labels: False Positive 🦟, backport maintenance/3.2.x

#9591 Give preference to `--never-returning-functions` in `inconsistent-return-statements` check
  doc/whatsnew/fragments/7565.false_negative
  pylint/checkers/refactoring/refactoring_checker.py
  pylint/checkers/variables.py
  tests/functional/i/inconsistent/inconsistent_returns_noreturn.py
  tests/functional/i/inconsistent/inconsistent_returns_noreturn.rc
  tests/functional/i/inconsistent/inconsistent_returns_noreturn.txt
Labels: Enhancement ✨, python 3.11

#9792 Add unsupported version checks for major 3.11 and 3.12 features
  .github/workflows/checks.yaml
  doc/data/messages/a/anomalous-backslash-in-string/bad.py
  doc/data/messages/a/anomalous-backslash-in-string/details.rst
  doc/data/messages/a/anomalous-unicode-escape-in-string/bad.py
  doc/data/messages/u/using-exception-groups-in-unsupported-version/bad.py
  doc/data/messages/u/using-exception-groups-in-unsupported-version/details.rst
  doc/data/messages/u/using-exception-groups-in-unsupported-version/good.py
  doc/data/messages/u/using-exception-groups-in-unsupported-version/pylintrc
  doc/data/messages/u/using-generic-type-syntax-in-unsupported-version/bad.py
  doc/data/messages/u/using-generic-type-syntax-in-unsupported-version/details.rst
  doc/data/messages/u/using-generic-type-syntax-in-unsupported-version/good.py
  doc/data/messages/u/using-generic-type-syntax-in-unsupported-version/pylintrc
  doc/user_guide/checkers/features.rst
  doc/user_guide/messages/messages_overview.rst
  doc/whatsnew/fragments/9791.new_check
  pylint/checkers/unsupported_version.py
  tests/functional/u/unsupported/unsupported_version_for_exception_group.py
  tests/functional/u/unsupported/unsupported_version_for_exception_group.rc
  tests/functional/u/unsupported/unsupported_version_for_exception_group.txt
  tests/functional/u/unsupported/unsupported_version_for_generic_type_syntax.py
  tests/functional/u/unsupported/unsupported_version_for_generic_type_syntax.rc
  tests/functional/u/unsupported/unsupported_version_for_generic_type_syntax.txt
Labels: Enhancement ✨, py-version

#9802 Fix consider-using-min-max-builtin
  doc/whatsnew/fragments/9800.false_negative
  pylint/checkers/refactoring/refactoring_checker.py
  tests/functional/c/consider/consider_using_min_max_builtin.txt
Labels: False Positive 🦟, backport maintenance/3.2.x

#9816 Bump astroid to 3.2.4
  pyproject.toml
  requirements_test_min.txt
Labels: Skip news :mute:, backport maintenance/3.2.x

#9817 Fix a crash when a subclass extends `__slots__`
  doc/whatsnew/fragments/9814.bugfix
  pylint/checkers/classes/class_checker.py
  tests/functional/s/slots_checks.py
Labels: Crash 💥, backport maintenance/3.2.x

#9812 Update setuptools to >=71.0.4
  pyproject.toml
  requirements_test_min.txt
  tests/functional/r/recursion/recursion_error_3159.py
Labels: Skip news :mute:, backport maintenance/3.2.x

#9821 [Backport maintenance/3.2.x] Bump astroid to 3.2.4 (#9816)
  pyproject.toml
  requirements_test_min.txt
Labels: Skip news :mute:

#9822 [Backport maintenance/3.2.x] Fix a crash when a subclass extends `__slots__` (#9817)
  doc/whatsnew/fragments/9814.bugfix
  pylint/checkers/classes/class_checker.py
  tests/functional/s/slots_checks.py
Labels: Crash 💥

#9826 Sync Sphinx version in pre-commit config
  .pre-commit-config.yaml
Labels: Maintenance, Skip news :mute:

#9825 Bump pylint to 3.2.6, update changelog
  doc/whatsnew/3/3.2/index.rst
  doc/whatsnew/fragments/9214.bugfix
  doc/whatsnew/fragments/9672.false_positive
  doc/whatsnew/fragments/9739.false_positive
  doc/whatsnew/fragments/9765.false_positive
  doc/whatsnew/fragments/9780.false_positive
  doc/whatsnew/fragments/9800.false_negative
  doc/whatsnew/fragments/9814.bugfix
  pylint/__pkginfo__.py
  tbump.toml
  towncrier.toml
Labels: Skip news :mute:

#9827 Post 3.2.6
  doc/whatsnew/3/3.2/index.rst
  doc/whatsnew/fragments/9214.bugfix
  doc/whatsnew/fragments/9672.false_positive
  doc/whatsnew/fragments/9739.false_positive
  doc/whatsnew/fragments/9765.false_positive
  doc/whatsnew/fragments/9780.false_positive
  doc/whatsnew/fragments/9800.false_negative
  doc/whatsnew/fragments/9814.bugfix
Labels: Maintenance, Skip news :mute:

#9837 Update repo for pylint-sonarjson
  README.rst
Labels: Maintenance, Skip news :mute:

#9838 Add unsupported version checks for Python 3.8+ syntax
  doc/data/messages/u/using-assignment-expression-in-unsupported-version/bad.py
  doc/data/messages/u/using-assignment-expression-in-unsupported-version/details.rst
  doc/data/messages/u/using-assignment-expression-in-unsupported-version/good.py
  doc/data/messages/u/using-assignment-expression-in-unsupported-version/pylintrc
  doc/data/messages/u/using-positional-only-args-in-unsupported-version/bad.py
  doc/data/messages/u/using-positional-only-args-in-unsupported-version/details.rst
  doc/data/messages/u/using-positional-only-args-in-unsupported-version/good.py
  doc/data/messages/u/using-positional-only-args-in-unsupported-version/pylintrc
  doc/user_guide/checkers/features.rst
  doc/user_guide/messages/messages_overview.rst
  doc/whatsnew/fragments/9820.new_check
  doc/whatsnew/fragments/9823.new_check
  pylint/checkers/unsupported_version.py
  tests/functional/b/broad_exception/broad_exception_caught.txt
  tests/functional/b/broad_exception/broad_exception_caught_trystar.txt
  tests/functional/b/broad_exception/broad_exception_raised.txt
  tests/functional/b/broad_exception/broad_exception_raised_trystar.txt
  tests/functional/u/unsupported/unsupported_version_for_assignment_expression.py
  tests/functional/u/unsupported/unsupported_version_for_assignment_expression.rc
  tests/functional/u/unsupported/unsupported_version_for_assignment_expression.txt
  tests/functional/u/unsupported/unsupported_version_for_exception_group.txt
  tests/functional/u/unsupported/unsupported_version_for_f_string.txt
  tests/functional/u/unsupported/unsupported_version_for_final.txt
  tests/functional/u/unsupported/unsupported_version_for_generic_type_syntax.txt
  tests/functional/u/unsupported/unsupported_version_for_posonly_args.py
  tests/functional/u/unsupported/unsupported_version_for_posonly_args.rc
  tests/functional/u/unsupported/unsupported_version_for_posonly_args.txt
Labels: Enhancement ✨, py-version

#9491 Fix: [unknown-option-value] False negative after --disable=all
  doc/whatsnew/fragments/9403.bugfix
  pylint/lint/message_state_handler.py
  pylint/lint/run.py
  tests/test_self.py
Labels: False Negative 🦋

#9844 Fix a false positive `unreachable` for `NoReturn` coroutine functions
  doc/whatsnew/fragments/9840.false_positive
  pylint/checkers/utils.py
  tests/functional/u/unreachable.py
  tests/functional/u/unreachable.txt
Labels: False Positive 🦟, backport maintenance/3.2.x
