Repository pylint-dev/pylint, pull requests merged in 2024-12, with the labels that each got.

#10088 Bump pylint to 3.3.2, update changelog
  doc/whatsnew/3/3.3/index.rst
  doc/whatsnew/fragments/10026.bugfix
  doc/whatsnew/fragments/10076.false_positive
  examples/pylintrc
  examples/pyproject.toml
  pylint/__pkginfo__.py
  tbump.toml
  towncrier.toml
Labels: Maintenance, Skip news :mute:

#10102 Merge maintenance into main following 3.3.2
  doc/whatsnew/3/3.3/index.rst
  doc/whatsnew/fragments/10026.bugfix
  doc/whatsnew/fragments/10076.false_positive
  examples/pylintrc
  examples/pyproject.toml
Labels: Maintenance, Skip news :mute:

#10107 (bugfix) Issue 10100: [C1802] should not be emitted for generators.
  doc/whatsnew/fragments/10100.false_positive
  pylint/checkers/refactoring/implicit_booleaness_checker.py
  tests/functional/u/use/use_implicit_booleaness_not_len.py
  tests/functional/u/use/use_implicit_booleaness_not_len.txt
Labels: False Positive 🦟, backport maintenance/3.3.x

#10119 [mypy] Use type-setuptools instead of types-pkg-resources
  .pre-commit-config.yaml
  requirements_test.txt
Labels: Maintenance, Skip news :mute:, backport maintenance/3.3.x

#10121 [skip ci] Add python 3.13 to tox configuration
  doc/development_guide/contributor_guide/tests/launching_test.rst
  tox.ini
Labels: Maintenance, Skip news :mute:

#10135 Fix `undefined-variable` for Python 3.12 generic type syntax
  doc/whatsnew/fragments/9335.false_positive
  pylint/checkers/variables.py
  tests/functional/g/generic_class_syntax_py312.py
  tests/functional/g/generic_class_syntax_py312.txt
  tests/functional/u/undefined/undefined_variable_py312.py
Labels: False Positive 🦟, backport maintenance/3.3.x

#10154 [Backport maintenance/3.3.x] Bump actions/cache from 4.1.2 to 4.2.0 (#10123)
  .github/workflows/changelog.yml
  .github/workflows/checks.yaml
  .github/workflows/primer-test.yaml
  .github/workflows/primer_comment.yaml
  .github/workflows/primer_run_main.yaml
  .github/workflows/primer_run_pr.yaml
  .github/workflows/tests.yaml
Labels: Skip news :mute:

#10157 Post 3.3.3
  doc/whatsnew/3/3.3/index.rst
  doc/whatsnew/fragments/10100.false_positive
  doc/whatsnew/fragments/10112.bugfix
  doc/whatsnew/fragments/9335.false_positive
Labels: Maintenance, Skip news :mute:
