Repository pylint-dev/pylint, pull requests merged in 2024-02, with the labels that each got.

#9427 [primer] Allow primer comment job to recreate venv
  .github/workflows/primer_comment.yaml
Labels: primer, Skip news :mute:

#9428 Avoid some inference in `no-name-from-module`
  pylint/checkers/variables.py
Labels: performance, primer, Skip news :mute:

#9419 New message `use-yield-from`
  doc/data/messages/u/use-yield-from/bad.py
  doc/data/messages/u/use-yield-from/details.rst
  doc/data/messages/u/use-yield-from/good.py
  doc/data/messages/u/use-yield-from/related.rst
  doc/user_guide/checkers/features.rst
  doc/user_guide/messages/messages_overview.rst
  doc/whatsnew/fragments/9229.feature
  pylint/checkers/refactoring/refactoring_checker.py
  tests/functional/b/bad_reversed_sequence.py
  tests/functional/c/consider/consider_using_enumerate.py
  tests/functional/ext/docparams/return/missing_return_doc_Sphinx.py
  tests/functional/i/iterable_context_py36.py
  tests/functional/n/non/non_iterator_returned.py
  tests/functional/s/stop_iteration_inside_generator.py
  tests/functional/u/undefined/undefined_variable.py
  tests/functional/u/unpacking/unpacking_non_sequence.py
  tests/functional/u/use/use_implicit_booleaness_not_len.py
  tests/functional/u/use/use_yield_from.py
  tests/functional/u/use/use_yield_from.txt
  tests/functional/y/yield_assign.py
Labels: Enhancement ✨

#9430 Include tests, docs with sdist
  MANIFEST.in
Labels: Maintenance, Skip news :mute:

#9452 [used-before-assignment] Fix FP under finally block
  doc/whatsnew/fragments/9451.false_positive
  pylint/checkers/variables.py
  tests/functional/u/used/used_before_assignment_issue85.py
  tests/functional/u/used/used_before_assignment_issue85.txt
Labels: False Positive 🦟, C: used-before-assignment, backport maintenance/3.0.x

#9454 Catch ValueError - generator already executing
  .pyenchant_pylint_custom_dict.txt
  doc/whatsnew/fragments/9138.bugfix
  pylint/__init__.py
Labels: Upstream Bug 🪲, python 3.12, backport maintenance/3.0.x

#9457 Update astroid version to 3.1.0
  doc/whatsnew/fragments/9196.feature
  doc/whatsnew/fragments/9457.internal
  pylint/checkers/base/name_checker/checker.py
  pyproject.toml
  requirements_test_min.txt
  tests/functional/i/import_error.txt
  tests/functional/s/syntax/syntax_error.txt
  tests/functional/t/type/__init__.py
  tests/functional/t/type/typealias_naming_style_default.py
  tests/functional/t/type/typealias_naming_style_default.rc
  tests/functional/t/type/typealias_naming_style_default.txt
  tests/functional/t/type/typealias_naming_style_py312.py
  tests/functional/t/type/typealias_naming_style_py312.rc
  tests/functional/t/type/typealias_naming_style_py312.txt
  tests/functional/t/type/typealias_naming_style_rgx.py
  tests/functional/t/type/typealias_naming_style_rgx.rc
  tests/functional/t/type/typealias_naming_style_rgx.txt
  tests/functional/t/type/typedDict.py
  tests/functional/t/type/typevar_double_variance.py
  tests/functional/t/type/typevar_double_variance.txt
  tests/functional/t/type/typevar_name_incorrect_variance.py
  tests/functional/t/type/typevar_name_incorrect_variance.txt
  tests/functional/t/type/typevar_name_mismatch.py
  tests/functional/t/type/typevar_name_mismatch.txt
  tests/functional/t/type/typevar_naming_style_default.py
  tests/functional/t/type/typevar_naming_style_default.txt
  tests/functional/t/type/typevar_naming_style_py312.py
  tests/functional/t/type/typevar_naming_style_py312.rc
  tests/functional/t/type/typevar_naming_style_py312.txt
  tests/functional/t/type/typevar_naming_style_rgx.py
  tests/functional/t/type/typevar_naming_style_rgx.rc
  tests/functional/t/type/typevar_naming_style_rgx.txt
  tests/functional/u/used/used_before_assignment.py
  tests/test_self.py
Labels: Astroid, dependency

#9127 [false-negative] Fix 8947 for consider-using-min/max-builtin
  doc/whatsnew/fragments/8947.false_negative
  pylint/checkers/refactoring/refactoring_checker.py
  tests/functional/a/access/access_attr_before_def_false_positive.py
  tests/functional/c/consider/consider_using_min_max_builtin.py
  tests/functional/c/consider/consider_using_min_max_builtin.txt
Labels: False Negative 🦋

#9458 Bump pylint to 3.0.4, update changelog
  doc/whatsnew/3/3.0/index.rst
  doc/whatsnew/fragments/6804.false_positive
  doc/whatsnew/fragments/9138.bugfix
  doc/whatsnew/fragments/9246.false_positive
  doc/whatsnew/fragments/9307.false_positive
  doc/whatsnew/fragments/9451.false_positive
  pylint/__pkginfo__.py
  tbump.toml
  towncrier.toml
Labels: Maintenance

#9459 Merge maintenance 3.0.x into main following 3.0.4 release
  doc/whatsnew/3/3.0/index.rst
  doc/whatsnew/fragments/6804.false_positive
  doc/whatsnew/fragments/9138.bugfix
  doc/whatsnew/fragments/9246.false_positive
  doc/whatsnew/fragments/9307.false_positive
  doc/whatsnew/fragments/9451.false_positive
Labels: Maintenance, Skip news :mute:

#9241 Discover `.pyi` files
  .pyenchant_pylint_custom_dict.txt
  doc/whatsnew/fragments/9097.feature
  pylint/lint/pylinter.py
  tests/lint/unittest_lint.py
  tests/regrtest_data/pyi/foo.pyi
Labels: Enhancement ✨

#9462 [primer] Only prime pandas.core
  tests/primer/packages_to_prime.json
Labels: Maintenance, primer, Skip news :mute:

#9466 fix a docs typo
  doc/user_guide/checkers/extensions.rst
  pylint/extensions/confusing_elif.py
Labels: Skip news :mute:
