Repository pylint-dev/pylint, pull requests merged in 2024-10, with the labels that each got.

#9981 Add tests
  tests/functional/u/unnecessary/unnecessary_lambda.py
  tests/functional/u/unnecessary/unnecessary_lambda.txt
  tests/functional/u/used/used_before_assignment.py
  tests/functional/u/used/used_before_assignment.txt
  tests/functional/u/used/used_before_assignment_postponed_evaluation.py
  tests/functional/u/used/used_before_assignment_postponed_evaluation.txt
  tests/functional/u/used/used_before_assignment_py310.py
  tests/functional/u/used/used_before_assignment_py310.txt
  tests/functional/u/used/used_before_assignment_py312.py
  tests/functional/u/used/used_before_assignment_py312.txt
Labels: Maintenance, Skip news :mute:

#9995 Cut ScopeConsumer
  pylint/checkers/variables.py
Labels: Maintenance, Skip news :mute:

#9992 Add breaking fragment for fixme docstring support
  doc/whatsnew/fragments/9255.breaking
Labels: Documentation :green_book:, Skip news :mute:

#10002 Clarify no-else-raise and no-else-return also apply to try/except
  doc/user_guide/checkers/features.rst
  pylint/checkers/refactoring/refactoring_checker.py
Labels: Documentation :green_book:, Skip news :mute:

#10004 Bump astroid to 3.3.5
  pyproject.toml
  requirements_test_min.txt
Labels: Maintenance, Skip news :mute:, backport maintenance/3.3.x

#10011 Bump CI jobs to python 3.13
  .github/workflows/changelog.yml
  .github/workflows/checks.yaml
  .github/workflows/primer-test.yaml
  .github/workflows/primer_comment.yaml
  .github/workflows/primer_run_main.yaml
  .github/workflows/primer_run_pr.yaml
  .github/workflows/release.yml
  .github/workflows/tests.yaml
Labels: Maintenance, Skip news :mute:

#10015 [bare-except doc] Add PEP760 and discussion around it in related links
  doc/data/messages/b/bare-except/related.rst
Labels: Documentation :green_book:, Skip news :mute:

#9990 Resolve false negative for `used-before-assignment` with TYPE_CHECKING guard
  doc/whatsnew/fragments/8893.false_negative
  pylint/checkers/variables.py
  tests/functional/u/used/used_before_assignment_postponed_evaluation.py
  tests/functional/u/used/used_before_assignment_postponed_evaluation.txt
  tests/functional/u/used/used_before_assignment_typing.py
  tests/functional/u/used/used_before_assignment_typing.txt
Labels: False Negative 🦋, C: used-before-assignment

#9966 remove metaclass check for protected access in properties
  pylint/checkers/classes/class_checker.py
  tests/functional/p/protected_access.py
  tests/functional/p/protected_access.txt
Labels: Maintenance, Skip news :mute:

#10044 Improve documentation for consider-alternative-union-syntax / R6003
  doc/data/messages/c/consider-alternative-union-syntax/bad.py
  doc/data/messages/c/consider-alternative-union-syntax/details.rst
  doc/data/messages/c/consider-alternative-union-syntax/good.py
  doc/user_guide/checkers/extensions.rst
  pylint/extensions/typing.py
  tests/functional/ext/typing/typing_consider_using_union.txt
  tests/functional/ext/typing/typing_consider_using_union_py310.txt
  tests/functional/ext/typing/typing_consider_using_union_without_future.txt
Labels: Documentation :green_book:, Skip news :mute:

#10036 Fix source root not recognized
  doc/whatsnew/fragments/10026.bugfix
  pylint/lint/expand_modules.py
  tests/pyreverse/test_main.py
Labels: Bug :beetle:, pyreverse

#10045 Add detailed documentation for Pyreverse command-line options
  doc/additional_tools/pyreverse/configuration.rst
  doc/additional_tools/pyreverse/index.rst
  doc/additional_tools/symilar/index.rst
  doc/conf.py
  doc/exts/pyreverse_configuration.py
  doc/index.rst
  doc/whatsnew/fragments/9689.breaking
  pylint/__init__.py
  pylint/pyreverse/inspector.py
  pylint/pyreverse/main.py
  tests/pyreverse/test_main.py
  tests/pyreverse/test_pyreverse_functional.py
Labels: Documentation :green_book:
