Repository pylint-dev/pylint, pull requests merged in 2024-03, with the labels that each got.

#9478 Include test requirements with sdist
  MANIFEST.in
Labels: Maintenance, Skip news :mute:

#9486 Fixing typos in too-many-branches example
  doc/data/messages/t/too-many-branches/good.py
Labels: Documentation :green_book:, Skip news :mute:

#9484 Add GitHub reporter
  .pre-commit-config.yaml
  doc/whatsnew/fragments/9443.feature
  pylint/reporters/text.py
  tests/test_self.py
Labels: Enhancement ✨
