Repository pylint-dev/pylint, pull requests merged in 2024-08, with the labels that each got.

#9842 Implement `too-many-positional-arguments`
  doc/data/messages/t/too-many-positional-arguments/bad.py
  doc/data/messages/t/too-many-positional-arguments/details.rst
  doc/data/messages/t/too-many-positional-arguments/good.py
  doc/data/messages/t/too-many-positional-arguments/pylintrc
  doc/data/messages/t/too-many-positional-arguments/related.rst
  doc/data/messages/t/too-many-positional/details.rst
  doc/user_guide/checkers/features.rst
  doc/user_guide/configuration/all-options.rst
  doc/user_guide/messages/messages_overview.rst
  doc/whatsnew/fragments/9099.new_check
  examples/pylintrc
  examples/pyproject.toml
  pylint/checkers/design_analysis.py
  pylint/testutils/pyreverse.py
  pylintrc
  tests/functional/a/async_functions.py
  tests/functional/a/async_functions.txt
  tests/functional/ext/docparams/parameter/missing_param_doc_required_Google.py
  tests/functional/ext/docparams/parameter/missing_param_doc_required_Numpy.py
  tests/functional/t/too/too_many_arguments.py
  tests/functional/t/too/too_many_arguments.txt
  tests/functional/t/too/too_many_locals.py
  tests/functional/t/too/too_many_locals.txt
  tests/functional/t/too/too_many_positional_arguments.py
  tests/functional/t/too/too_many_positional_arguments.txt
  tests/functional/u/unexpected_special_method_signature.py
  tests/functional/w/wrong_import_order.txt
Labels: Enhancement ✨

#9854 Remove pytest-profiling to unblock 3.13 testing
  requirements_test.txt
  tests/profile/test_profile_against_externals.py
  tox.ini
Labels: Maintenance, Skip news :mute:, python 3.13

#9851 Bump astroid to 3.3.1
  README.rst
  pyproject.toml
  requirements_test_min.txt
  tests/functional/i/inconsistent/inconsistent_quotes_fstring.py
  tests/functional/i/inconsistent/inconsistent_quotes_fstring_py312.py
  tests/functional/i/inconsistent/inconsistent_quotes_fstring_py312_311.py
Labels: Maintenance, Skip news :mute:

#9866 Fix crash in refactoring checker when calling bound lambda
  doc/whatsnew/fragments/9865.bugfix
  pylint/checkers/refactoring/refactoring_checker.py
  tests/functional/r/regression/regression_9865_calling_bound_lambda.py
Labels: Crash 💥, backport maintenance/3.2.x

#9876 Fix a crash in `undefined-loop-variable` with `enumerate()`
  doc/whatsnew/fragments/9875.bugfix
  pylint/checkers/variables.py
  tests/functional/r/regression/regression_9875_enumerate.py
  tests/functional/r/regression/regression_9875_enumerate.txt
Labels: Regression, Crash 💥, backport maintenance/3.2.x

#9868 fix false negative when `isinstance` is provided too many or too few arguments
  doc/data/messages/t/too-few-function-args/bad.py
  doc/data/messages/t/too-few-function-args/details.rst
  doc/data/messages/t/too-few-function-args/good.py
  doc/user_guide/checkers/features.rst
  doc/user_guide/messages/messages_overview.rst
  doc/whatsnew/fragments/9847.false_negative
  doc/whatsnew/fragments/9847.new_check
  pylint/checkers/typecheck.py
  tests/functional/c/consider/consider_merging_isinstance.py
  tests/functional/c/consider/consider_merging_isinstance.txt
  tests/functional/t/too/too_few_function_args.py
  tests/functional/t/too/too_few_function_args.txt
  tests/functional/t/too/too_many_function_args.py
  tests/functional/t/too/too_many_function_args.txt
Labels: False Negative 🦋

#9882 `too-few-function-args` redundant with `no-value-for-parameter`
  doc/data/messages/t/too-few-function-args/bad.py
  doc/data/messages/t/too-few-function-args/details.rst
  doc/data/messages/t/too-few-function-args/good.py
  doc/user_guide/checkers/features.rst
  doc/user_guide/messages/messages_overview.rst
  doc/whatsnew/fragments/9847.false_negative
  doc/whatsnew/fragments/9847.new_check
  pylint/checkers/typecheck.py
  tests/functional/a/arguments.py
  tests/functional/a/arguments.txt
  tests/functional/c/consider/consider_merging_isinstance.py
  tests/functional/c/consider/consider_merging_isinstance.txt
  tests/functional/t/too/too_few_function_args.py
  tests/functional/t/too/too_few_function_args.txt
Labels: Maintenance, Beta-Blocker 🙅🩸, Skip news :mute:

#9892 Fixed typo in W0212
  doc/user_guide/checkers/features.rst
  pylint/checkers/classes/class_checker.py
Labels: Skip news :mute:

#9731 [symilar] Migrate from getopt to argparse
  doc/whatsnew/fragments/9731.user_action
  pylint/checkers/symilar.py
  tests/checkers/unittest_symilar.py
Labels: Enhancement ✨, Needs review 🔍, duplicate-code, Maintenance

#9896 Add docs for OSS-Fuzz integration
  doc/development_guide/contributor_guide/index.rst
  doc/development_guide/contributor_guide/oss_fuzz.rst
Labels: Documentation :green_book:, Skip news :mute:

#9887 Fix to maintain order of package paths
  doc/whatsnew/fragments/9883.bugfix
  pylint/lint/pylinter.py
Labels: Bug :beetle:, backport maintenance/3.2.x

#9900 Updating minor error in the changelog
  doc/whatsnew/3/3.0/index.rst
Labels: Documentation :green_book:, Skip news :mute:

#9903 Merge maintenance/3.2.x into main following 3.2.7 release
  doc/whatsnew/3/3.2/index.rst
  doc/whatsnew/fragments/9840.false_positive
  doc/whatsnew/fragments/9865.bugfix
  doc/whatsnew/fragments/9875.bugfix
  doc/whatsnew/fragments/9883.bugfix
Labels: Maintenance, Skip news :mute:
