Repository pylint-dev/pylint, pull requests merged in 2024-09, with the labels that each got.

#9914 Fix max-positional-arguments comments in example config files
  examples/pylintrc
  examples/pyproject.toml
Labels: Documentation :green_book:, Skip news :mute:

#9916 Remove obsolete comment from ASTWalker.walk
  pylint/utils/ast_walker.py
Labels: Maintenance, Skip news :mute:

#9918 Don't use .get() with defaultdicts
  pylint/utils/ast_walker.py
Labels: performance, Skip news :mute:

#9919 Fix coverage uploads
  .github/workflows/tests.yaml
Labels: Maintenance, Skip news :mute:

#9927 Move most ruff exclusions out of .pre-commit-config.yaml
  .pre-commit-config.yaml
  doc/data/ruff.toml
  pyproject.toml
Labels: Maintenance, Skip news :mute:

#9853 Add additional stdlib deprecations (mostly 3.13)
  pylint/checkers/imports.py
  pylint/checkers/stdlib.py
Labels: Skip news :mute:, python 3.13

#9932 Explicitly save cache in primer jobs
  .github/workflows/primer_run_main.yaml
  .github/workflows/primer_run_pr.yaml
Labels: Maintenance, primer, Skip news :mute:

#9933 Add details.rst for c-extension-no-member
  doc/data/messages/c/c-extension-no-member/details.rst
  doc/data/messages/t/typevar-name-incorrect-variance/details.rst
Labels: Documentation :green_book:, Skip news :mute:

#9912 [pre-commit] Add codespell, and fix some existing typos
  .pre-commit-config.yaml
  custom_dict.txt
  doc/development_guide/contributor_guide/profiling.rst
  doc/development_guide/contributor_guide/tests/writing_test.rst
  doc/user_guide/checkers/features.rst
  doc/whatsnew/0/0.x.rst
  doc/whatsnew/1/1.5.rst
  doc/whatsnew/2/2.0/summary.rst
  doc/whatsnew/2/2.13/summary.rst
  doc/whatsnew/2/2.4/full.rst
  doc/whatsnew/2/2.6/full.rst
  doc/whatsnew/2/2.6/summary.rst
  doc/whatsnew/3/3.1/index.rst
  pylint/checkers/base/function_checker.py
  pylint/checkers/refactoring/implicit_booleaness_checker.py
  pylintrc
  pyproject.toml
  tests/checkers/unittest_misc.py
  tests/config/functional/toml/unknown_msgid/enable_unknown_msgid.toml
  tests/data/a_script
  tests/functional/a/arguments_differ.py
  tests/functional/c/consider/consider_using_get.py
  tests/functional/i/inconsistent/inconsistent_quotes_fstring_py312.py
  tests/functional/i/inconsistent/inconsistent_quotes_fstring_py312_311.py
  tests/functional/m/misplaced_format_function.py
  tests/functional/n/names_in__all__.py
  tests/functional/n/names_in__all__.txt
  tests/functional/n/no/no_name_in_module.py
  tests/functional/n/no/no_name_in_module.txt
  tests/functional/n/non/non_init_parent_called.py
  tests/functional/n/non/non_init_parent_called.txt
  tests/functional/n/non_ascii_name/non_ascii_name_assignment_expressions.py
  tests/functional/n/non_ascii_name_class/non_ascii_name_class.py
  tests/functional/n/not_async_context_manager_py37.py
  tests/functional/u/uninferable_all_object.py
  tests/functional/u/use/use_implicit_booleaness_not_comparison_to_string.txt
  tests/lint/unittest_lint.py
  tests/test_self.py
  tests/test_similar.py
Labels: Maintenance, Skip news :mute:

#9936 [doc framework] Assert that the good and bad example exists in the doc
  doc/data/messages/u/unrecognize-option/details.rst
  doc/data/messages/u/unrecognized-option/details.rst
  doc/exts/pylint_messages.py
Labels: Documentation :green_book:, Maintenance, Skip news :mute:

#9938 Add check for `unnecessary-default-type-args`
  doc/data/messages/u/unnecessary-default-type-args/bad.py
  doc/data/messages/u/unnecessary-default-type-args/details.rst
  doc/data/messages/u/unnecessary-default-type-args/good.py
  doc/data/messages/u/unnecessary-default-type-args/pylintrc
  doc/data/messages/u/unnecessary-default-type-args/related.rst
  doc/user_guide/checkers/extensions.rst
  doc/user_guide/messages/messages_overview.rst
  doc/whatsnew/fragments/9938.new_check
  pylint/checkers/exceptions.py
  pylint/checkers/symilar.py
  pylint/checkers/variables.py
  pylint/extensions/typing.py
  pylint/pyreverse/diadefslib.py
  pylint/testutils/checker_test_case.py
  pylint/testutils/utils.py
  pylint/utils/pragma_parser.py
  tests/functional/ext/typing/unnecessary_default_type_args.py
  tests/functional/ext/typing/unnecessary_default_type_args.rc
  tests/functional/ext/typing/unnecessary_default_type_args.txt
  tests/functional/ext/typing/unnecessary_default_type_args_py313.py
  tests/functional/ext/typing/unnecessary_default_type_args_py313.rc
  tests/functional/ext/typing/unnecessary_default_type_args_py313.txt
  tests/pyreverse/test_inspector.py
Labels: Enhancement ✨, typing, Optional Checkers, python 3.13

#9939 Bump astroid to 3.3.3
  pyproject.toml
  requirements_test_min.txt
Labels: Maintenance, Skip news :mute:

#9911 Fix two incorrect/broken tests in `tests/checkers/unittest_imports.py`
  tests/checkers/unittest_imports.py
  tests/regrtest_data/dummy_wildcard.py
Labels: Maintenance, Skip news :mute:

#9944 Update OSS-Fuzz issue tracker links in contributor docs
  doc/development_guide/contributor_guide/oss_fuzz.rst
Labels: Documentation :green_book:, Skip news :mute:

#9948 Bump pylint to 4.0.0-dev0, update changelog
  doc/whatsnew/3/index.rst
  doc/whatsnew/4/4.0/index.rst
  doc/whatsnew/4/index.rst
  doc/whatsnew/index.rst
  pylint/__pkginfo__.py
  tbump.toml
  towncrier.toml
Labels: Maintenance, Skip news :mute:

#9951 Bump astroid to 3.3.4
  doc/whatsnew/fragments/9947.false_positive
  pyproject.toml
  requirements_test_min.txt
Labels: backport maintenance/3.3.x

#9958 Post 3.3.1
  doc/whatsnew/3/3.3/index.rst
  doc/whatsnew/fragments/9947.false_positive
Labels: Maintenance, Skip news :mute:

#9957 [too-many-positional-arguments doc] Add the main option to use, real example
  doc/data/messages/t/too-many-positional-arguments/bad.py
  doc/data/messages/t/too-many-positional-arguments/good.py
  doc/data/messages/t/too-many-positional-arguments/pylintrc
Labels: Documentation :green_book:, Skip news :mute:

#9969 Fix release note typo
  doc/whatsnew/3/3.3/index.rst
Labels: Documentation :green_book:, Skip news :mute:, backport maintenance/3.3.x

#9975 Fix the VS Code extension link syntax @ FAQ
  doc/faq.rst
Labels: Documentation :green_book:, Skip news :mute:

#9978 Cleanup variables checker
  pylint/checkers/variables.py
Labels: Skip news :mute:

#9744 Support fixme's in docstrings
  doc/user_guide/configuration/all-options.rst
  doc/whatsnew/fragments/9255.feature
  pylint/checkers/misc.py
  tests/functional/f/fixme.py
  tests/functional/f/fixme.txt
  tests/functional/f/fixme_docstring.py
  tests/functional/f/fixme_docstring.rc
  tests/functional/f/fixme_docstring.txt
Labels: Enhancement ✨
