Repository pylint-dev/pylint, pull requests merged in 2024-01, with the labels that each got.

#9308 Fix FP for `no-member`: function attributes from decorator
  doc/whatsnew/fragments/9246.false_positive
  pylint/checkers/typecheck.py
  tests/functional/n/no/no_member_decorator.py
Labels: False Positive 🦟, backport maintenance/3.0.x

#9374 [used-before-assignment] Fix FP for try/else/continue
  doc/whatsnew/fragments/6804.false_positive
  pylint/checkers/variables.py
  tests/functional/u/used/used_before_assignment_else_continue.py
  tests/functional/u/used/used_before_assignment_else_continue.txt
Labels: False Positive 🦟, C: used-before-assignment, backport maintenance/3.0.x

#9384 feat(FAQ): Update duplicated messages in pycodestyle
  doc/faq.rst
Labels: Documentation :green_book:, Skip news :mute:

#9371 Catch ParentMissingError in variables checker
  pylint/checkers/variables.py
Labels: Maintenance, Skip news :mute:

#9400 Fix the whitespacing in the optional checker note
  doc/exts/pylint_messages.py
Labels: Documentation :green_book:, Skip news :mute:

#9402 [doc] Add an article about performance related to ``use-dict-literal``
  doc/data/messages/u/use-dict-literal/related.rst
Labels: Documentation :green_book:, Skip news :mute:

#9394 Fix astroid base_nodes imports
  pylint/checkers/typecheck.py
  pylint/checkers/utils.py
  pylint/checkers/variables.py
Labels: Skip news :mute:, backport maintenance/3.0.x
