Repository pylint-dev/pylint, pull requests merged in 2025-01, with the labels that each got.

#10167 Extend documentation for `redefined-builtin`
  doc/data/messages/r/redefined-builtin/details.rst
  tests/functional/r/redefined/redefined_builtin_allowed.py
  tests/functional/r/redefined/redefined_builtin_allowed.rc
  tests/functional/r/redefined/redefined_builtin_allowed.txt
Labels: Documentation :green_book:, Skip news :mute:

#10141 fix "skipped files" count calculation
  doc/whatsnew/fragments/10073.bugfix
  pylint/lint/expand_modules.py
  pylint/lint/pylinter.py
  pylint/typing.py
  pylint/utils/linterstats.py
  tests/lint/unittest_expand_modules.py
  tests/test_self.py
Labels: Bug :beetle:, backport maintenance/3.3.x

#10179 Mention that unused-import skips __init__.py files
  doc/data/messages/u/unused-import/details.rst
  doc/data/messages/u/unused-import/related.rst
Labels: Documentation :green_book:, Skip news :mute:

#10177 Add docs FAQ entry on domain name distinctions (`pylint dot org` vs pylint.readthedocs.io)
  doc/faq.rst
Labels: Documentation :green_book:, Skip news :mute:

#10077 Add --max-depth option to control diagram complexity
  doc/additional_tools/pyreverse/configuration.rst
  doc/whatsnew/fragments/10077.feature
  pylint/pyreverse/main.py
  pylint/pyreverse/writer.py
  pylint/testutils/pyreverse.py
  pylintrc
  tests/pyreverse/conftest.py
  tests/pyreverse/data/classes_depth_limited_0.dot
  tests/pyreverse/data/classes_depth_limited_1.dot
  tests/pyreverse/data/packages_depth_limited_0.dot
  tests/pyreverse/data/packages_depth_limited_1.dot
  tests/pyreverse/test_writer.py
Labels: Enhancement ✨, pyreverse

#10204 [isort] Permit to use isort 6
  doc/whatsnew/fragments/10203.bugfix
  pyproject.toml
Labels: Bug :beetle:, backport maintenance/3.3.x

#10205 Release branch 3.3.4
  .pre-commit-config.yaml
  CONTRIBUTORS.txt
  doc/whatsnew/3/3.3/index.rst
  doc/whatsnew/fragments/10073.bugfix
  doc/whatsnew/fragments/10103.bugfix
  doc/whatsnew/fragments/10203.bugfix
  examples/pylintrc
  examples/pyproject.toml
  pylint/__pkginfo__.py
  tbump.toml
  towncrier.toml
Labels: Maintenance, Skip news :mute:

#10206 Merge back maintenance following 3.3.4 release
  CONTRIBUTORS.txt
  doc/whatsnew/3/3.3/index.rst
  examples/pylintrc
  examples/pyproject.toml
Labels: Maintenance, Skip news :mute:

#10209 Fix a false positive for ``invalid-getnewargs-ex-returned``
  doc/whatsnew/fragments/10208.false_positive
  pylint/checkers/classes/special_methods_checker.py
  tests/functional/i/invalid/invalid_getnewargs/invalid_getnewargs_ex_returned.py
  tests/functional/i/invalid/invalid_getnewargs/invalid_getnewargs_ex_returned.txt
Labels: False Positive 🦟, backport maintenance/3.3.x
