Repository pylint-dev/pylint, pull requests merged in 2025-09, with the labels that each got.

#10535 [primer] Use a dataclasse for PackageToLint
  pylint/testutils/_primer/package_to_lint.py
Labels: Maintenance, Skip news :mute:

#10528 Use match statement in checkers (2)
  pylint/checkers/async_checker.py
  pylint/checkers/exceptions.py
  pylint/checkers/format.py
  pylint/checkers/imports.py
  pylint/checkers/lambda_expressions.py
  pylint/checkers/logging.py
  pylint/checkers/modified_iterating_checker.py
  pylint/checkers/non_ascii_names.py
  pylint/checkers/stdlib.py
  pylint/checkers/strings.py
  pylint/checkers/typecheck.py
  pylint/checkers/utils.py
  pylint/checkers/variables.py
  tests/functional/u/unnecessary/unnecessary_lambda_assignment.py
  tests/functional/u/unnecessary/unnecessary_lambda_assignment.txt
Labels: Maintenance, Skip news :mute:

#10542 Count match cases for too-many-branches
  doc/whatsnew/fragments/10542.false_negative
  pylint/checkers/design_analysis.py
  pylint/checkers/format.py
  tests/functional/t/too/too_many_branches.py
Labels: False Negative 🦋, Match case

#10529 Use match statement in checkers (3)
  pylint/checkers/base/basic_checker.py
  pylint/checkers/base/basic_error_checker.py
  pylint/checkers/base/docstring_checker.py
  pylint/checkers/base/name_checker/checker.py
  pylint/checkers/classes/class_checker.py
  pylint/checkers/classes/special_methods_checker.py
  pylint/checkers/refactoring/implicit_booleaness_checker.py
  pylint/checkers/refactoring/refactoring_checker.py
Labels: Maintenance, Skip news :mute:

#10531 Use match statement in checkers (4)
  pylint/checkers/base/basic_checker.py
  pylint/checkers/base/comparison_checker.py
  pylint/checkers/classes/class_checker.py
  pylint/checkers/deprecated.py
  pylint/checkers/exceptions.py
  pylint/checkers/lambda_expressions.py
  pylint/checkers/newstyle.py
  pylint/checkers/refactoring/recommendation_checker.py
  pylint/checkers/refactoring/refactoring_checker.py
  pylint/checkers/typecheck.py
  pylint/checkers/utils.py
  pylint/checkers/variables.py
  pylint/extensions/_check_docs_utils.py
  pylint/extensions/code_style.py
  pylint/extensions/dict_init_mutate.py
  pylint/extensions/no_self_use.py
Labels: Maintenance, Skip news :mute:

#10561 [docs] Update the message sort order
  doc/user_guide/checkers/extensions.rst
  doc/user_guide/checkers/features.rst
  pylint/checkers/base_checker.py
Labels: Documentation :green_book:, Skip news :mute:

#10564 Add sphinx reference for whatsnew 3.3
  doc/whatsnew/3/3.3/index.rst
Labels: Documentation :green_book:, Skip news :mute:, backport maintenance/3.3.x

#10557 [ci] Allow Python prerelease versions
  .github/workflows/tests.yaml
Labels: Maintenance, Skip news :mute:

#10569 fix: handle for-loop variable shadowing correctly
  doc/whatsnew/fragments/10562.bugfix
  pylint/checkers/variables.py
  tests/functional/f/for_loop_variable_shadowing.py
  tests/functional/f/for_loop_variable_shadowing.txt
Labels: False Positive 🦟, backport maintenance/3.3.x

#10574 Use yaml anchors for workflows
  .github/workflows/changelog.yml
  .github/workflows/checks.yaml
  .github/workflows/primer-test.yaml
  .github/workflows/primer_run_main.yaml
  .github/workflows/primer_run_pr.yaml
  .github/workflows/tests.yaml
Labels: Maintenance, Skip news :mute:

#10567 [mccabe] Add more functional tests to allow for easier refactor
  tests/functional/ext/mccabe/mccabe.py
  tests/functional/ext/mccabe/mccabe.txt
  tests/functional/ext/mccabe/not_too_complex.py
  tests/functional/ext/mccabe/not_too_complex.rc
  tests/functional/ext/mccabe/not_too_complex.txt
Labels: Documentation :green_book:, Maintenance, Skip news :mute:

#10552 Use match statement in checkers (6)
  pylint/checkers/classes/class_checker.py
  pylint/checkers/deprecated.py
  pylint/checkers/design_analysis.py
  pylint/checkers/newstyle.py
  pylint/checkers/refactoring/recommendation_checker.py
  pylint/checkers/refactoring/refactoring_checker.py
  pylint/checkers/typecheck.py
  pylint/checkers/utils.py
  pylint/extensions/code_style.py
  pylint/extensions/consider_ternary_expression.py
  pylint/extensions/dict_init_mutate.py
  pylint/extensions/private_import.py
  pylint/extensions/typing.py
Labels: Maintenance, Skip news :mute:

#10575 feat: add check for async context managers used with regular `with`
  doc/data/messages/a/async-context-manager-with-regular-with/bad.py
  doc/data/messages/a/async-context-manager-with-regular-with/good.py
  doc/data/messages/a/async-context-manager-with-regular-with/related.rst
  doc/user_guide/checkers/features.rst
  doc/user_guide/messages/messages_overview.rst
  doc/whatsnew/fragments/10999.new_check
  pylint/checkers/typecheck.py
  tests/functional/a/async_context_manager_with_regular_with.py
  tests/functional/a/async_context_manager_with_regular_with.txt
Labels: Enhancement ✨

#10576 Use match statement in checkers (7)
  pylint/checkers/base/basic_error_checker.py
  pylint/checkers/base/docstring_checker.py
  pylint/checkers/classes/class_checker.py
  pylint/checkers/refactoring/refactoring_checker.py
  pylint/checkers/variables.py
Labels: Maintenance, Skip news :mute:

#10577 Add support for Python 3.14
  pyproject.toml
  tox.ini
Labels: Skip news :mute:

#10578 Fix invalid refs in 3.3 whatsnew
  doc/whatsnew/3/3.3/index.rst
Labels: Documentation :green_book:, Skip news :mute:, backport maintenance/3.3.x

#10592 Update astroid nodes import
  pylint/checkers/base/basic_error_checker.py
  pylint/checkers/base/name_checker/checker.py
  pylint/checkers/classes/class_checker.py
  pylint/checkers/classes/special_methods_checker.py
  pylint/checkers/deprecated.py
  pylint/checkers/design_analysis.py
  pylint/checkers/refactoring/implicit_booleaness_checker.py
  pylint/checkers/refactoring/recommendation_checker.py
  pylint/checkers/refactoring/refactoring_checker.py
  pylint/checkers/typecheck.py
  pylint/checkers/utils.py
  pylint/checkers/variables.py
  pylint/extensions/_check_docs_utils.py
  pylint/extensions/docparams.py
  pylint/extensions/mccabe.py
  pylint/extensions/overlapping_exceptions.py
  pylint/pyreverse/diadefslib.py
  pylint/pyreverse/diagrams.py
  pylint/pyreverse/inspector.py
  pylint/utils/utils.py
  tests/checkers/unittest_variables.py
Labels: Maintenance, Skip news :mute:

#10594 Update additional astroid imports
  pylint/checkers/async_checker.py
  pylint/checkers/base/basic_checker.py
  pylint/checkers/base/name_checker/checker.py
  pylint/checkers/classes/class_checker.py
  pylint/checkers/imports.py
  pylint/checkers/nested_min_max.py
  pylint/checkers/refactoring/refactoring_checker.py
  pylint/checkers/strings.py
  pylint/checkers/typecheck.py
  pylint/checkers/utils.py
  pylint/checkers/variables.py
  pylint/extensions/docparams.py
  pylint/extensions/typing.py
  pylint/lint/pylinter.py
  pylint/pyreverse/diagrams.py
  pylint/pyreverse/inspector.py
Labels: Maintenance, Skip news :mute:
