Repository pylint-dev/pylint, pull requests merged in 2025-07, with the labels that each got.

#10454 Fix false negative for `deprecated-module` when a `__import__` method is used instead of `import` sentence
  CONTRIBUTORS.txt
  doc/whatsnew/fragments/10453.false_negative
  pylint/checkers/deprecated.py
  script/.contributors_aliases.json
  tests/functional/d/deprecated/deprecated_module__import__.py
  tests/functional/d/deprecated/deprecated_module__import__.rc
  tests/functional/d/deprecated/deprecated_module__import__.txt
Labels: False Negative 🦋

#10444 Colorize "fail-on" messages/categories in ColorizedTextReporter red inverse
  doc/whatsnew/fragments/9898.feature
  pylint/config/config_initialization.py
  pylint/lint/pylinter.py
  pylint/reporters/text.py
Labels: Enhancement ✨

#10466 Bump astroid to 4.0.0b0
  pyproject.toml
  requirements_test_min.txt
Labels: Maintenance, Skip news :mute:
