Repository pylint-dev/pylint, pull requests merged in 2025-10, with the labels that each got.

#10603 Use `sorted()` instead of in-place sorting
  pylint/checkers/symilar.py
  pylint/message/message_id_store.py
Labels: Skip news :mute:

#10614 Bump astroid to 4.0.0
  doc/whatsnew/4/4.0/index.rst
  pyproject.toml
  requirements_test_min.txt
Labels: Maintenance, Skip news :mute:

#10620 Deprecate PyLinter pylintrc argument
  doc/whatsnew/fragments/6052.breaking
  pylint/lint/pylinter.py
  pylint/lint/run.py
Labels: Maintenance
