Repository pylint-dev/pylint, pull requests merged in 2025-02, with the labels that each got.

#10213 Undeprecate getopt
  doc/whatsnew/fragments/10211.false_positive
  pylint/checkers/imports.py
Labels: False Positive 🦟, backport maintenance/3.3.x

#10215 Also undeprecate optparse
  doc/whatsnew/fragments/10211.false_positive
  pylint/checkers/imports.py
  tests/functional/d/deprecated/deprecated_module_py3.py
  tests/functional/d/deprecated/deprecated_module_py3.txt
  tests/functional/d/deprecated/deprecated_module_py36.py
  tests/functional/d/deprecated/deprecated_module_py36.txt
  tests/functional/d/deprecated/deprecated_relative_import/dot_relative_import.py
  tests/functional/d/deprecated/deprecated_relative_import/dot_relative_import.txt
  tests/functional/d/deprecated/deprecated_relative_import/subpackage/dot_dot_relative_import.py
  tests/functional/d/deprecated/deprecated_relative_import/subpackage/dot_dot_relative_import.txt
  tests/functional/n/no/no_member_imports.py
  tests/functional/n/no/no_member_imports.txt
Labels: False Positive 🦟, backport maintenance/3.3.x

#10220 Add pyproject.fmt to the pre-commit tooling
  .pre-commit-config.yaml
  examples/pyproject.toml
  pyproject.toml
Labels: Documentation :green_book:, Skip news :mute:

#10225 unidiomatic-typecheck to check right-hand side too
  doc/whatsnew/fragments/10217.bugfix
  pylint/checkers/base/comparison_checker.py
  tests/functional/u/unidiomatic_typecheck.py
  tests/functional/u/unidiomatic_typecheck.txt
Labels: False Negative 🦋

#10228 Ignore leading underscores in private methods for camelCase style
  doc/whatsnew/fragments/10189.bugfix
  pylint/checkers/base/name_checker/naming_style.py
  tests/functional/n/namePresetCamelCase.py
  tests/functional/n/namePresetCamelCase.txt
Labels: False Positive 🦟, backport maintenance/3.3.x

#10233 Rename init_with_litteral.py to init_with_literal.py
  doc/data/messages/u/use-dict-literal/good/init_with_literal.py
Labels: Skip news :mute:

#10232 Fix crash in `catching-non-exception` when something besides a class in `except`
  doc/whatsnew/fragments/10106.bugfix
  pylint/checkers/exceptions.py
  tests/functional/i/invalid/invalid_exceptions/invalid_exceptions_caught.py
  tests/functional/i/invalid/invalid_exceptions/invalid_exceptions_caught.txt
Labels: Crash 💥, backport maintenance/3.3.x

#10240 Fixed conditional import x.y causing possibly-used-before-assignment
  doc/whatsnew/fragments/10081.bugfix
  pylint/checkers/variables.py
  tests/functional/u/used/used_before_assignment.py
Labels: backport maintenance/3.3.x

#10246 Fix false positives for `use-implicit-booleaness-not-comparison` checks
  doc/whatsnew/fragments/10065.false_positive
  pylint/checkers/refactoring/implicit_booleaness_checker.py
  tests/functional/u/use/use_implicit_booleaness_not_comparison.py
  tests/functional/u/use/use_implicit_booleaness_not_comparison.txt
  tests/functional/u/use/use_implicit_booleaness_not_comparison_to_string.py
  tests/functional/u/use/use_implicit_booleaness_not_comparison_to_zero.py
Labels: False Positive 🦟, backport maintenance/3.3.x
