Repository pylint-dev/pylint, pull requests merged in 2025-08, with the labels that each got.

#10381 Handle deferred evaluation of annotations in Python 3.14
  doc/whatsnew/fragments/10149.feature
  pylint/checkers/typecheck.py
  pylint/checkers/variables.py
  pylint/extensions/typing.py
  tests/functional/p/postponed/postponed_evaluation_not_activated.314.txt
  tests/functional/p/postponed/postponed_evaluation_not_activated.py
  tests/functional/u/undefined/undefined_variable.314.txt
  tests/functional/u/undefined/undefined_variable.py
  tests/functional/u/undefined/undefined_variable_py30.314.txt
  tests/functional/u/undefined/undefined_variable_py30.py
  tests/functional/u/used/used_before_assignment_nonlocal.314.txt
  tests/functional/u/used/used_before_assignment_nonlocal.py
  tests/functional/u/used/used_before_assignment_typing.314.txt
  tests/functional/u/used/used_before_assignment_typing.py
Labels: typing, C: used-before-assignment, C: undefined-variable, python 3.14

#10436 Fix `unused-variable` false positive when using same name for multiple exceptions
  doc/whatsnew/fragments/10426.false_positive
  pylint/checkers/variables.py
  tests/functional/u/unused/unused_global_variable2.py
  tests/functional/u/unused/unused_variable.py
  tests/functional/u/unused/unused_variable.txt
Labels: False Positive 🦟, backport maintenance/3.3.x

#10482 Fix false-negative for used-before-assignment with postponed evaluation in function defs
  doc/whatsnew/fragments/10482.false_negative
  pylint/checkers/variables.py
Labels: False Positive 🦟, C: used-before-assignment, backport maintenance/3.3.x

#10467 Add support for Python 3.14
  .github/workflows/primer-test.yaml
  .github/workflows/tests.yaml
  doc/whatsnew/fragments/10467.feature
  pylint/checkers/base/basic_error_checker.py
  pyproject.toml
  requirements_test_min.txt
  tests/functional/c/consider/consider_using_with.py
  tests/functional/c/consider/consider_using_with.txt
  tests/functional/g/generic_alias/generic_alias_mixed_py39.py
  tests/functional/g/generic_alias/generic_alias_mixed_py39.txt
Labels: Enhancement ✨, python 3.14

#10485 Add a related link for ``unnecessary-dunder-call``
  doc/data/messages/u/unnecessary-dunder-call/related.rst
Labels: Documentation :green_book:, Skip news :mute:

#10486 Bump pylint to 3.3.8, update changelog
  doc/whatsnew/3/3.3/index.rst
  doc/whatsnew/fragments/10104.false_positive
  doc/whatsnew/fragments/10373.bugfix
  doc/whatsnew/fragments/10402.bugfix
  doc/whatsnew/fragments/10426.false_positive
  doc/whatsnew/fragments/10482.false_negative
  doc/whatsnew/fragments/9668.false_positive
  pylint/__pkginfo__.py
  script/.contributors_aliases.json
  tbump.toml
  towncrier.toml
Labels: Skip news :mute:

#10487 Merge branch 'maintenance/3.3.x' into main following 3.3.8 release
  doc/whatsnew/3/3.3/index.rst
  script/.contributors_aliases.json
Labels: Skip news :mute:

#10488 Fix used-before-assignment for PEP 695 type aliases + parameters
  doc/whatsnew/fragments/9815.false_positive
  pylint/checkers/utils.py
  pylint/checkers/variables.py
  pylint/testutils/functional/find_functional_tests.py
  tests/functional/u/used/used_before_assignment_py312.py
  tests/functional/u/used/used_before_assignment_py312.txt
  tests/functional/u/used_02/used_before_assignment_py313.py
  tests/functional/u/used_02/used_before_assignment_py313.rc
  tests/functional/u/used_02/used_before_assignment_py313.txt
Labels: typing, False Positive 🦟, C: used-before-assignment, python 3.12, backport maintenance/3.3.x, python 3.13

#10502 Additional tests for undefined-variable with PEP 695 syntax
  tests/functional/u/undefined/undefined_variable_py312.py
  tests/functional/u/undefined/undefined_variable_py312.txt
Labels: C: undefined-variable, tests, Skip news :mute:, python 3.12

#10501 Switch back to upstream setup-python with PyPy fix [ci]
  .github/workflows/tests.yaml
Labels: Maintenance, Skip news :mute:

#10500 Fix pre-commit checks on Python 3.14
  .pre-commit-config.yaml
  tests/test_check_parallel.py
Labels: Maintenance, Skip news :mute:, python 3.14

#10490 [functional tests] Only count python files for the reasonably displayable limit
  pylint/testutils/functional/find_functional_tests.py
  tests/functional/u/used/used_before_assignment_py313.py
  tests/functional/u/used/used_before_assignment_py313.rc
  tests/functional/u/used/used_before_assignment_py313.txt
  tests/testutils/data/m/max_overflow/max_overflow_3.py
  tests/testutils/test_functional_testutils.py
Labels: Maintenance, Skip news :mute:

#10503 Fix cache keys [ci]
  .github/workflows/checks.yaml
  .github/workflows/primer-test.yaml
  .github/workflows/tests.yaml
Labels: Maintenance, Skip news :mute:

#10509 Fix unreachable assertions in test_errors_only and test_verbose test method #10450
  tests/test_self.py
Labels: Maintenance, Skip news :mute:

#10512 Better approach in 'unnecessary-list-index-lookup' to avoid crashes
  doc/whatsnew/fragments/10510.bugfix
  pylint/checkers/refactoring/refactoring_checker.py
  tests/functional/u/unnecessary/unnecessary_list_index_lookup.py
Labels: Maintenance, Skip news :mute:

#10523 Re-apply "Add dependency groups to pyproject.toml file"
  pyproject.toml
Labels: Maintenance, Skip news :mute:

#10526 Sync requirements
  pyproject.toml
Labels: Maintenance, Skip news :mute:

#10527 Switch to mypy-dev 1.18.0a6
  .pre-commit-config.yaml
  tests/test_self.py
Labels: Maintenance, Skip news :mute:
