Repository pylint-dev/pylint, pull requests merged in 2025-03, with the labels that each got.

#10200 Refactor depth filtering logic
  pylint/pyreverse/diadefslib.py
  pylint/pyreverse/main.py
  pylint/pyreverse/writer.py
  pylint/typing.py
  tests/pyreverse/conftest.py
  tests/pyreverse/test_diadefs.py
  tests/pyreverse/test_diagrams.py
  tests/pyreverse/test_writer.py
Labels: pyreverse, Skip news :mute:

#10251 Update pyreverse documentation
  doc/additional_tools/pyreverse/configuration.rst
  pylint/pyreverse/main.py
Labels: pyreverse, Documentation :green_book:, Skip news :mute:

#10250 feat(pyreverse): add support for colorized output for `mmd` and `html`
  doc/whatsnew/fragments/10242.feature
  pylint/pyreverse/mermaidjs_printer.py
  tests/pyreverse/functional/class_diagrams/colorized_output/colorized.mmd
  tests/pyreverse/functional/class_diagrams/colorized_output/colorized.rc
Labels: Enhancement ✨, pyreverse

#9771 Fix FN for `invalid-name` for type-annotated module constants
  doc/whatsnew/fragments/9770.false_negative
  pylint/checkers/base/name_checker/checker.py
  tests/functional/ext/private_import/private_import.py
  tests/functional/ext/private_import/private_import.rc
  tests/functional/g/generic_alias/generic_alias_collections.py
  tests/functional/g/generic_alias/generic_alias_mixed_py39.py
  tests/functional/i/invalid/invalid_name.py
  tests/functional/i/invalid/invalid_name.txt
  tests/functional/n/namePresetCamelCase.txt
  tests/functional/r/regression_02/regression_3979.py
  tests/functional/t/type/typealias_naming_style_default.py
  tests/functional/u/unused/unused_import.py
  tests/functional/u/unused/unused_name_in_string_literal_type_annotation_py38.py
Labels: False Negative 🦋, C: invalid-name, Breaking changes for 4.0 🦤

#10258 Fix the caching following upgrade of the github action
  .github/workflows/checks.yaml
Labels: Maintenance, Skip news :mute:

#10263 Update release workflow to use Trusted Publishing
  .github/workflows/release.yml
  doc/whatsnew/fragments/10256.other
Labels: Maintenance, backport maintenance/3.3.x

#10266 Bump pylint to 3.3.5, update changelog
  doc/whatsnew/3/3.3/index.rst
  doc/whatsnew/fragments/10065.false_positive
  doc/whatsnew/fragments/10081.bugfix
  doc/whatsnew/fragments/10106.bugfix
  doc/whatsnew/fragments/10189.bugfix
  doc/whatsnew/fragments/10208.false_positive
  doc/whatsnew/fragments/10211.false_positive
  doc/whatsnew/fragments/10256.other
  pylint/__pkginfo__.py
  tbump.toml
Labels: Maintenance

#10267 Minor improvements to release workflow
  .github/workflows/release.yml
Labels: Maintenance, Skip news :mute:, backport maintenance/3.3.x

#10268 Merge maintenance in main following 3.3.5 release
  .pre-commit-config.yaml
  CONTRIBUTORS.txt
  doc/whatsnew/3/3.3/index.rst
  examples/pylintrc
  examples/pyproject.toml
  towncrier.toml
Labels: Maintenance, Skip news :mute:

#10269 Add additional permissions for backport workflow
  .github/workflows/backport.yml
Labels: Maintenance, Skip news :mute:, backport maintenance/3.3.x

#10272 Ref #10260 -- Add documentation for the github output format
  doc/user_guide/configuration/all-options.rst
  doc/user_guide/usage/output.rst
  pylint/lint/base_options.py
Labels: Skip news :mute:, backport maintenance/3.3.x

#10057 Enhanced support for @Property decorator in pyreverse
  doc/whatsnew/fragments/10057.feature
  pylint/pyreverse/diagrams.py
  tests/pyreverse/functional/class_diagrams/property_decorator/property_decorator.mmd
  tests/pyreverse/functional/class_diagrams/property_decorator/property_decorator.py
Labels: Enhancement ✨, pyreverse, Needs decision :lock:

#10275 [used-before-assignment] Fix FP for inner function return type
  doc/whatsnew/fragments/9391.false_positive
  pylint/checkers/variables.py
  tests/functional/u/used/used_before_assignment_typing.py
Labels: False Positive 🦟, C: used-before-assignment, backport maintenance/3.3.x

#10289 Move deprecated 'tool.setuptools.license-files', remove license classifier
  .pre-commit-config.yaml
  pyproject.toml
  setup.cfg
Labels: Maintenance, Skip news :mute:, backport maintenance/3.3.x

#10291 GitHub Actions: Make pip commands more self-documenting
  .github/workflows/changelog.yml
  .github/workflows/checks.yaml
  .github/workflows/primer-test.yaml
  .github/workflows/primer_run_main.yaml
  .github/workflows/primer_run_pr.yaml
  .github/workflows/tests.yaml
Labels: Maintenance, Skip news :mute:

#10297 Post 3.3.6
  CONTRIBUTORS.txt
  doc/whatsnew/3/3.3/index.rst
  doc/whatsnew/fragments/9391.false_positive
Labels: Maintenance, Skip news :mute:

#10296 pre-commit: Add validate-pyproject
  .pre-commit-config.yaml
Labels: Skip news :mute:

#10299 GitHub Actions: Simplify tests using matrix.os
  .github/workflows/tests.yaml
Labels: Maintenance, Skip news :mute:

#10300 Fix crash caused by invalid format strings in `.format` context
  doc/whatsnew/fragments/10282.bugfix
  pylint/checkers/refactoring/recommendation_checker.py
  tests/functional/c/consider/consider_using_f_string.py
Labels: Crash 💥, backport maintenance/3.3.x

#10303 added black's github link in tutorial
  doc/tutorial.rst
Labels: Skip news :mute:

#10310 [ci] Remove the ediatable install from the doc requirements
  .readthedocs.yaml
  doc/readthedoc_requirements.txt
  doc/requirements.txt
Labels: Maintenance, Skip news :mute:

#10287 GH Actions: Add pypy3.11 to testing matrix
  .github/workflows/tests.yaml
  doc/whatsnew/fragments/10287.feature
Labels: Maintenance

#10277 Speed up the generation of no-member suggestions
  doc/whatsnew/fragments/10277.other
  pylint/checkers/typecheck.py
  tests/checkers/unittest_typecheck.py
Labels: performance, backport maintenance/3.3.x

#10313 [setuptools] Force the upgrade of setuptools > 77
  pyproject.toml
Labels: Maintenance, Skip news :mute:

#10314 Fix typo in missing-member-hint-distance documentation
  examples/pylintrc
  examples/pyproject.toml
  pylint/checkers/typecheck.py
  pylintrc
Labels: Documentation :green_book:, Skip news :mute:, backport maintenance/3.3.x

#10274 Update OSS-Fuzz docs to use uv instead of pyenv
  doc/development_guide/contributor_guide/oss_fuzz.rst
Labels: Documentation :green_book:, Skip news :mute:

#10321 [logging-too-few-args] Raise for format strings with no interpolation at all
  doc/whatsnew/fragments/9999.false_negative
  pylint/checkers/logging.py
  tests/config/data/logging_format_interpolation_style.py
  tests/functional/l/logging/logging_format_interpolation_style.py
  tests/functional/l/logging/logging_too_few_args.txt
  tests/functional/l/logging/logging_too_few_args_new_style.py
  tests/functional/l/logging/logging_too_few_args_new_style.rc
  tests/functional/l/logging/logging_too_few_args_new_style.txt
  tests/functional/l/logging/logging_too_few_args_old_style.py
  tests/functional/l/logging/logging_too_few_args_old_style.rc
  tests/functional/l/logging/logging_too_few_args_old_style.txt
  tests/functional/s/string/string_log_formatting.py
  tests/functional/s/string/string_log_formatting.txt
Labels: False Negative 🦋

#9375 [Feature] Add filepaths checked to verbose msg
  doc/whatsnew/fragments/9357.feature
  pylint/lint/pylinter.py
  pylint/utils/linterstats.py
  tests/test_self.py
Labels: Enhancement ✨

#10320 Fix caching issue that led to incorrect all-options.rst being merged on main
  .github/workflows/checks.yaml
  .pre-commit-config.yaml
  doc/development_guide/contributor_guide/contribute.rst
  doc/development_guide/contributor_guide/tests/install.rst
  doc/user_guide/configuration/all-options.rst
Labels: Documentation :green_book:, Maintenance, Skip news :mute:

#10322 Fix `FUNDING.yml`
  .github/FUNDING.yml
  .pre-commit-config.yaml
Labels: Maintenance, Skip news :mute:

#9962 Always use the suggestion mode for ``no-member`` / ``c-extension-no-member``
  .github/workflows/tests.yaml
  doc/user_guide/configuration/all-options.rst
  doc/whatsnew/fragments/9962.breaking
  examples/pylintrc
  examples/pyproject.toml
  pylint/checkers/clear_lru_cache.py
  pylint/checkers/typecheck.py
  pylint/checkers/utils.py
  pylint/lint/base_options.py
  pylint/lint/run.py
  pylint/utils/utils.py
  pylintrc
  tests/checkers/unittest_typecheck.py
Labels: Breaking changes for 4.0 🦤
