Repository pylint-dev/pylint, pull requests merged in 2025-06, with the labels that each got.

#10414 [ci] Disable the benchmarks everywhere except the benchmark job
  .github/workflows/checks.yaml
  .github/workflows/primer-test.yaml
  .github/workflows/tests.yaml
Labels: Maintenance, Skip news :mute:

#10428 [doc]Update custom_checkers.rst to specify the safe range that a custom checker may use
  doc/development_guide/how_tos/custom_checkers.rst
Labels: Documentation :green_book:, Skip news :mute:

#10104 Respect docstring-min-length in docparams extension
  doc/whatsnew/fragments/10104.false_positive
  pylint/extensions/docparams.py
  tests/functional/ext/docparams/raise/missing_raises_doc_required_min_length.py
  tests/functional/ext/docparams/raise/missing_raises_doc_required_min_length.rc
  tests/functional/ext/docparams/yield/missing_yield_doc_required_min_length.py
  tests/functional/ext/docparams/yield/missing_yield_doc_required_min_length.rc
Labels: False Positive 🦟, backport maintenance/3.3.x
