Repository pylint-dev/pylint, pull requests merged in 2025-04, with the labels that each got.

#9913 [doc] exec-used, add a full example writing in an intermediary file
  doc/data/messages/e/exec-used/details.rst
  doc/data/messages/e/exec-used/good.py
  doc/data/messages/e/exec-used/related.rst
Labels: Documentation :green_book:, Skip news :mute:

#10328 Improve code suggestion for `use-implicit-booleaness-not-x` checks
  doc/whatsnew/fragments/9353.feature
  pylint/checkers/refactoring/implicit_booleaness_checker.py
  tests/functional/u/use/use_implicit_booleaness_not_comparison.py
  tests/functional/u/use/use_implicit_booleaness_not_comparison.txt
  tests/functional/u/use/use_implicit_booleaness_not_comparison_to_string.py
  tests/functional/u/use/use_implicit_booleaness_not_comparison_to_string.txt
  tests/functional/u/use/use_implicit_booleaness_not_comparison_to_zero.py
  tests/functional/u/use/use_implicit_booleaness_not_comparison_to_zero.txt
Labels: Enhancement ✨

#10332 Add dependency groups to pyproject.toml file
  pyproject.toml
Labels: Maintenance, Skip news :mute:

#10340 Refactor to align docstring style
  pylint/checkers/refactoring/implicit_booleaness_checker.py
  tests/functional/u/use/use_implicit_booleaness_not_comparison.py
  tests/functional/u/use/use_implicit_booleaness_not_comparison.txt
  tests/functional/u/use/use_implicit_booleaness_not_comparison_to_string.py
  tests/functional/u/use/use_implicit_booleaness_not_comparison_to_string.txt
  tests/functional/u/use/use_implicit_booleaness_not_comparison_to_zero.py
  tests/functional/u/use/use_implicit_booleaness_not_comparison_to_zero.txt
Labels: Skip news :mute:

#10342 Revert "Add dependency groups to pyproject.toml file"
  pyproject.toml
Labels: Maintenance, Skip news :mute:

#10344 Improve handling of aggregations for comprehensions in Pyreverse
  doc/whatsnew/fragments/10236.feature
  pylint/pyreverse/inspector.py
  tests/pyreverse/functional/class_diagrams/aggregation/comprehensions.mmd
  tests/pyreverse/functional/class_diagrams/aggregation/comprehensions.py
Labels: Enhancement ✨, pyreverse

#10354 Fix ambiguous docstring example for docstring-first-line-empty warning
  doc/data/messages/d/docstring-first-line-empty/bad.py
Labels: Skip news :mute:
