Repository pylint-dev/pylint, pull requests merged in 2025-05, with the labels that each got.

#10350 [fix] AttributeError crash when a slice is used as a class decorator
  doc/whatsnew/fragments/10334.bugfix
  pylint/checkers/deprecated.py
  pylint/checkers/utils.py
  tests/functional/r/regression_02/regression_10334.py
  tests/functional/r/regression_02/regression_10334.txt
Labels: Crash 💥, backport maintenance/3.3.x

#10361 Backport: Manual cherry pick for decorator slice crash fix
  doc/whatsnew/fragments/10334.bugfix
  pylint/checkers/deprecated.py
  pylint/checkers/utils.py
  tests/functional/r/regression_02/regression_10334.py
  tests/functional/r/regression_02/regression_10334.txt
Labels: Maintenance

#10362 [fix] Fix a crash for class decorators mistaken for class attributes
  doc/whatsnew/fragments/10105.bugfix
  pylint/checkers/variables.py
  tests/functional/r/regression_02/regression_10105.py
Labels: Crash 💥, backport maintenance/3.3.x

#10170 Consistency between ``is``/``is not`` and ``==``/``!=`` when comparing types for ``unidiomatic-typecheck``
  doc/whatsnew/fragments/10161.false_positive
  pylint/checkers/base/comparison_checker.py
  tests/functional/u/unidiomatic_typecheck.py
  tests/functional/u/unidiomatic_typecheck.txt
Labels: False Positive 🦟, backport maintenance/3.3.x

#10366 [Backport maintenance/3.3.x] Consistency between ``is``/``is not`` and ``==``/``!=`` when comparing types for ``unidiomatic-typecheck`` (#10170)
  doc/whatsnew/fragments/10161.false_positive
  pylint/checkers/base/comparison_checker.py
  tests/functional/u/unidiomatic_typecheck.py
  tests/functional/u/unidiomatic_typecheck.txt
Labels: False Positive 🦟

#10367 Bump pylint to 3.3.7, update changelog
  doc/whatsnew/3/3.3/index.rst
  doc/whatsnew/fragments/10105.bugfix
  doc/whatsnew/fragments/10161.false_positive
  doc/whatsnew/fragments/10277.other
  doc/whatsnew/fragments/10282.bugfix
  doc/whatsnew/fragments/10334.bugfix
  examples/pylintrc
  examples/pyproject.toml
  pylint/__pkginfo__.py
  tbump.toml
  towncrier.toml
Labels: Maintenance

#10368 Merge maintenance into main following 3.3.7's release
  CONTRIBUTORS.txt
  doc/whatsnew/3/3.3/index.rst
Labels: Maintenance, Skip news :mute:

#10380 Remove types-setuptools test dependency
  .pre-commit-config.yaml
  requirements_test.txt
Labels: Maintenance, Skip news :mute:

#10384 Initial fixes for Python 3.14
  pylint/checkers/base/name_checker/checker.py
  pylint/extensions/typing.py
  tests/functional/g/generic_alias/generic_alias_collections.py
  tests/functional/g/generic_alias/generic_alias_collections.txt
  tests/functional/g/generic_alias/generic_alias_typing.py
  tests/functional/g/generic_alias/generic_alias_typing.txt
Labels: Skip news :mute:, python 3.14

#10385 Replace codecs.open with open
  pylint/graph.py
  tests/pyreverse/test_writer.py
Labels: Maintenance, Skip news :mute:, python 3.14

#10386 Fix pylint-config help output test for Python 3.14
  pylint/constants.py
  tests/config/pylint_config/test_pylint_config_help.py
Labels: Maintenance, Skip news :mute:, python 3.14

#10388 [ci] Install pylint before every test
  .github/workflows/checks.yaml
  .github/workflows/primer-test.yaml
  .github/workflows/primer_run_main.yaml
  .github/workflows/primer_run_pr.yaml
  .github/workflows/tests.yaml
Labels: Maintenance, Skip news :mute:, backport maintenance/3.3.x

#10389 [ci] Install pylint before every test (#10388)
  .github/workflows/checks.yaml
  .github/workflows/primer-test.yaml
  .github/workflows/primer_run_main.yaml
  .github/workflows/primer_run_pr.yaml
  .github/workflows/tests.yaml
Labels: Maintenance, Skip news :mute:

#10390 Improve backport job permissions
  .github/workflows/backport.yml
Labels: Maintenance, Skip news :mute:, backport maintenance/3.3.x

#10395 [Backport maintenance/3.3.x] Resolve possibly-used-before-assignment false positives from `match` block assignments (#10393)
  doc/whatsnew/fragments/9668.false_positive
  pylint/checkers/variables.py
  tests/functional/u/used/used_before_assignment_py310.py
  tests/functional/u/used/used_before_assignment_py310.txt
Labels: False Positive 🦟

#10392 [ci] Fix PyPy venv caching issue
  .github/workflows/tests.yaml
Labels: Maintenance, Skip news :mute:, backport maintenance/3.3.x

#10394 Use custom Github App to authenticate backport job
  .github/workflows/backport.yml
Labels: Maintenance, Skip news :mute:, backport maintenance/3.3.x

#10379 Fix Pyreverse: Aggregations aren't filtered according to filter mode (PUB_ONLY, etc.)
  doc/whatsnew/fragments/10373.bugfix
  pylint/pyreverse/diagrams.py
  tests/pyreverse/functional/class_diagrams/aggregation_filtering/all.mmd
  tests/pyreverse/functional/class_diagrams/aggregation_filtering/all.py
  tests/pyreverse/functional/class_diagrams/aggregation_filtering/all.rc
  tests/pyreverse/functional/class_diagrams/aggregation_filtering/other.mmd
  tests/pyreverse/functional/class_diagrams/aggregation_filtering/other.py
  tests/pyreverse/functional/class_diagrams/aggregation_filtering/other.rc
  tests/pyreverse/functional/class_diagrams/aggregation_filtering/pub_only.mmd
  tests/pyreverse/functional/class_diagrams/aggregation_filtering/pub_only.py
  tests/pyreverse/functional/class_diagrams/aggregation_filtering/pub_only.rc
  tests/pyreverse/functional/class_diagrams/aggregation_filtering/special.mmd
  tests/pyreverse/functional/class_diagrams/aggregation_filtering/special.py
  tests/pyreverse/functional/class_diagrams/aggregation_filtering/special.rc
Labels: Bug :beetle:, pyreverse, backport maintenance/3.3.x

#10382 Allow different test output for different Python versions
  doc/development_guide/contributor_guide/tests/writing_test.rst
  doc/whatsnew/fragments/10382.internal
  pylint/testutils/functional/test_file.py
  tests/functional/ext/typing/unnecessary_default_type_args.313.txt
  tests/functional/ext/typing/unnecessary_default_type_args.py
  tests/functional/ext/typing/unnecessary_default_type_args.rc
  tests/functional/ext/typing/unnecessary_default_type_args_py313.py
  tests/functional/ext/typing/unnecessary_default_type_args_py313.rc
  tests/testutils/test_functional_testutils.py
Labels: Maintenance, tests

#10403 Fix Mermaid printer rendering double underscores as bold formatting
  doc/whatsnew/fragments/10402.bugfix
  pylint/pyreverse/mermaidjs_printer.py
  tests/pyreverse/functional/class_diagrams/aggregation_filtering/all.mmd
  tests/pyreverse/functional/class_diagrams/aggregation_filtering/other.mmd
  tests/pyreverse/functional/class_diagrams/aggregation_filtering/special.mmd
Labels: Bug :beetle:, pyreverse, backport maintenance/3.3.x
